// Copyright 2026-present the xvec project
// Licensed under the Apache License, Version 2.0.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: xvec/v1/xvec.proto

package xvecv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	XvecService_CreateCollection_FullMethodName = "/xvec.v1.XvecService/CreateCollection"
	XvecService_DropCollection_FullMethodName   = "/xvec.v1.XvecService/DropCollection"
	XvecService_ListCollections_FullMethodName  = "/xvec.v1.XvecService/ListCollections"
	XvecService_GetSchema_FullMethodName        = "/xvec.v1.XvecService/GetSchema"
	XvecService_GetStats_FullMethodName         = "/xvec.v1.XvecService/GetStats"
	XvecService_Flush_FullMethodName            = "/xvec.v1.XvecService/Flush"
	XvecService_Optimize_FullMethodName         = "/xvec.v1.XvecService/Optimize"
	XvecService_AddColumn_FullMethodName        = "/xvec.v1.XvecService/AddColumn"
	XvecService_AlterColumn_FullMethodName      = "/xvec.v1.XvecService/AlterColumn"
	XvecService_DropColumn_FullMethodName       = "/xvec.v1.XvecService/DropColumn"
	XvecService_CreateIndex_FullMethodName      = "/xvec.v1.XvecService/CreateIndex"
	XvecService_DropIndex_FullMethodName        = "/xvec.v1.XvecService/DropIndex"
	XvecService_Write_FullMethodName            = "/xvec.v1.XvecService/Write"
	XvecService_Delete_FullMethodName           = "/xvec.v1.XvecService/Delete"
	XvecService_DeleteByFilter_FullMethodName   = "/xvec.v1.XvecService/DeleteByFilter"
	XvecService_Fetch_FullMethodName            = "/xvec.v1.XvecService/Fetch"
	XvecService_Query_FullMethodName            = "/xvec.v1.XvecService/Query"
	XvecService_MultiQuery_FullMethodName       = "/xvec.v1.XvecService/MultiQuery"
	XvecService_GroupByQuery_FullMethodName     = "/xvec.v1.XvecService/GroupByQuery"
	XvecService_Iterate_FullMethodName          = "/xvec.v1.XvecService/Iterate"
)

// XvecServiceClient is the client API for XvecService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type XvecServiceClient interface {
	CreateCollection(ctx context.Context, in *CreateCollectionRequest, opts ...grpc.CallOption) (*CollectionSchema, error)
	DropCollection(ctx context.Context, in *CollectionRef, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListCollections(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListCollectionsResponse, error)
	GetSchema(ctx context.Context, in *CollectionRef, opts ...grpc.CallOption) (*CollectionSchema, error)
	GetStats(ctx context.Context, in *CollectionRef, opts ...grpc.CallOption) (*CollectionStats, error)
	Flush(ctx context.Context, in *CollectionRef, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Optimize(ctx context.Context, in *OptimizeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	AddColumn(ctx context.Context, in *AddColumnRequest, opts ...grpc.CallOption) (*CollectionSchema, error)
	AlterColumn(ctx context.Context, in *AlterColumnRequest, opts ...grpc.CallOption) (*CollectionSchema, error)
	DropColumn(ctx context.Context, in *DropColumnRequest, opts ...grpc.CallOption) (*CollectionSchema, error)
	CreateIndex(ctx context.Context, in *CreateIndexRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DropIndex(ctx context.Context, in *DropIndexRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Write(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*WriteResponse, error)
	DeleteByFilter(ctx context.Context, in *DeleteByFilterRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FetchResult], error)
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryResponse], error)
	MultiQuery(ctx context.Context, in *MultiQueryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryResponse], error)
	GroupByQuery(ctx context.Context, in *GroupByQueryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GroupByQueryResponse], error)
	Iterate(ctx context.Context, in *IterateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryResponse], error)
}

type xvecServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewXvecServiceClient(cc grpc.ClientConnInterface) XvecServiceClient {
	return &xvecServiceClient{cc}
}

func (c *xvecServiceClient) CreateCollection(ctx context.Context, in *CreateCollectionRequest, opts ...grpc.CallOption) (*CollectionSchema, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CollectionSchema)
	err := c.cc.Invoke(ctx, XvecService_CreateCollection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xvecServiceClient) DropCollection(ctx context.Context, in *CollectionRef, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, XvecService_DropCollection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xvecServiceClient) ListCollections(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListCollectionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCollectionsResponse)
	err := c.cc.Invoke(ctx, XvecService_ListCollections_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xvecServiceClient) GetSchema(ctx context.Context, in *CollectionRef, opts ...grpc.CallOption) (*CollectionSchema, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CollectionSchema)
	err := c.cc.Invoke(ctx, XvecService_GetSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xvecServiceClient) GetStats(ctx context.Context, in *CollectionRef, opts ...grpc.CallOption) (*CollectionStats, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CollectionStats)
	err := c.cc.Invoke(ctx, XvecService_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xvecServiceClient) Flush(ctx context.Context, in *CollectionRef, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, XvecService_Flush_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xvecServiceClient) Optimize(ctx context.Context, in *OptimizeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, XvecService_Optimize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xvecServiceClient) AddColumn(ctx context.Context, in *AddColumnRequest, opts ...grpc.CallOption) (*CollectionSchema, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CollectionSchema)
	err := c.cc.Invoke(ctx, XvecService_AddColumn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xvecServiceClient) AlterColumn(ctx context.Context, in *AlterColumnRequest, opts ...grpc.CallOption) (*CollectionSchema, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CollectionSchema)
	err := c.cc.Invoke(ctx, XvecService_AlterColumn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xvecServiceClient) DropColumn(ctx context.Context, in *DropColumnRequest, opts ...grpc.CallOption) (*CollectionSchema, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CollectionSchema)
	err := c.cc.Invoke(ctx, XvecService_DropColumn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xvecServiceClient) CreateIndex(ctx context.Context, in *CreateIndexRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, XvecService_CreateIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xvecServiceClient) DropIndex(ctx context.Context, in *DropIndexRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, XvecService_DropIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xvecServiceClient) Write(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteResponse)
	err := c.cc.Invoke(ctx, XvecService_Write_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xvecServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*WriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteResponse)
	err := c.cc.Invoke(ctx, XvecService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xvecServiceClient) DeleteByFilter(ctx context.Context, in *DeleteByFilterRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, XvecService_DeleteByFilter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xvecServiceClient) Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FetchResult], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &XvecService_ServiceDesc.Streams[0], XvecService_Fetch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FetchRequest, FetchResult]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type XvecService_FetchClient = grpc.ServerStreamingClient[FetchResult]

func (c *xvecServiceClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &XvecService_ServiceDesc.Streams[1], XvecService_Query_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[QueryRequest, QueryResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type XvecService_QueryClient = grpc.ServerStreamingClient[QueryResponse]

func (c *xvecServiceClient) MultiQuery(ctx context.Context, in *MultiQueryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &XvecService_ServiceDesc.Streams[2], XvecService_MultiQuery_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MultiQueryRequest, QueryResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type XvecService_MultiQueryClient = grpc.ServerStreamingClient[QueryResponse]

func (c *xvecServiceClient) GroupByQuery(ctx context.Context, in *GroupByQueryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GroupByQueryResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &XvecService_ServiceDesc.Streams[3], XvecService_GroupByQuery_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GroupByQueryRequest, GroupByQueryResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type XvecService_GroupByQueryClient = grpc.ServerStreamingClient[GroupByQueryResponse]

func (c *xvecServiceClient) Iterate(ctx context.Context, in *IterateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &XvecService_ServiceDesc.Streams[4], XvecService_Iterate_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[IterateRequest, QueryResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type XvecService_IterateClient = grpc.ServerStreamingClient[QueryResponse]

// XvecServiceServer is the server API for XvecService service.
// All implementations must embed UnimplementedXvecServiceServer
// for forward compatibility.
type XvecServiceServer interface {
	CreateCollection(context.Context, *CreateCollectionRequest) (*CollectionSchema, error)
	DropCollection(context.Context, *CollectionRef) (*emptypb.Empty, error)
	ListCollections(context.Context, *emptypb.Empty) (*ListCollectionsResponse, error)
	GetSchema(context.Context, *CollectionRef) (*CollectionSchema, error)
	GetStats(context.Context, *CollectionRef) (*CollectionStats, error)
	Flush(context.Context, *CollectionRef) (*emptypb.Empty, error)
	Optimize(context.Context, *OptimizeRequest) (*emptypb.Empty, error)
	AddColumn(context.Context, *AddColumnRequest) (*CollectionSchema, error)
	AlterColumn(context.Context, *AlterColumnRequest) (*CollectionSchema, error)
	DropColumn(context.Context, *DropColumnRequest) (*CollectionSchema, error)
	CreateIndex(context.Context, *CreateIndexRequest) (*emptypb.Empty, error)
	DropIndex(context.Context, *DropIndexRequest) (*emptypb.Empty, error)
	Write(context.Context, *WriteRequest) (*WriteResponse, error)
	Delete(context.Context, *DeleteRequest) (*WriteResponse, error)
	DeleteByFilter(context.Context, *DeleteByFilterRequest) (*emptypb.Empty, error)
	Fetch(*FetchRequest, grpc.ServerStreamingServer[FetchResult]) error
	Query(*QueryRequest, grpc.ServerStreamingServer[QueryResponse]) error
	MultiQuery(*MultiQueryRequest, grpc.ServerStreamingServer[QueryResponse]) error
	GroupByQuery(*GroupByQueryRequest, grpc.ServerStreamingServer[GroupByQueryResponse]) error
	Iterate(*IterateRequest, grpc.ServerStreamingServer[QueryResponse]) error
	mustEmbedUnimplementedXvecServiceServer()
}

// UnimplementedXvecServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedXvecServiceServer struct{}

func (UnimplementedXvecServiceServer) CreateCollection(context.Context, *CreateCollectionRequest) (*CollectionSchema, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCollection not implemented")
}
func (UnimplementedXvecServiceServer) DropCollection(context.Context, *CollectionRef) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DropCollection not implemented")
}
func (UnimplementedXvecServiceServer) ListCollections(context.Context, *emptypb.Empty) (*ListCollectionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCollections not implemented")
}
func (UnimplementedXvecServiceServer) GetSchema(context.Context, *CollectionRef) (*CollectionSchema, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSchema not implemented")
}
func (UnimplementedXvecServiceServer) GetStats(context.Context, *CollectionRef) (*CollectionStats, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedXvecServiceServer) Flush(context.Context, *CollectionRef) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Flush not implemented")
}
func (UnimplementedXvecServiceServer) Optimize(context.Context, *OptimizeRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Optimize not implemented")
}
func (UnimplementedXvecServiceServer) AddColumn(context.Context, *AddColumnRequest) (*CollectionSchema, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddColumn not implemented")
}
func (UnimplementedXvecServiceServer) AlterColumn(context.Context, *AlterColumnRequest) (*CollectionSchema, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AlterColumn not implemented")
}
func (UnimplementedXvecServiceServer) DropColumn(context.Context, *DropColumnRequest) (*CollectionSchema, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DropColumn not implemented")
}
func (UnimplementedXvecServiceServer) CreateIndex(context.Context, *CreateIndexRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateIndex not implemented")
}
func (UnimplementedXvecServiceServer) DropIndex(context.Context, *DropIndexRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DropIndex not implemented")
}
func (UnimplementedXvecServiceServer) Write(context.Context, *WriteRequest) (*WriteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Write not implemented")
}
func (UnimplementedXvecServiceServer) Delete(context.Context, *DeleteRequest) (*WriteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedXvecServiceServer) DeleteByFilter(context.Context, *DeleteByFilterRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteByFilter not implemented")
}
func (UnimplementedXvecServiceServer) Fetch(*FetchRequest, grpc.ServerStreamingServer[FetchResult]) error {
	return status.Errorf(codes.Unimplemented, "method Fetch not implemented")
}
func (UnimplementedXvecServiceServer) Query(*QueryRequest, grpc.ServerStreamingServer[QueryResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedXvecServiceServer) MultiQuery(*MultiQueryRequest, grpc.ServerStreamingServer[QueryResponse]) error {
	return status.Errorf(codes.Unimplemented, "method MultiQuery not implemented")
}
func (UnimplementedXvecServiceServer) GroupByQuery(*GroupByQueryRequest, grpc.ServerStreamingServer[GroupByQueryResponse]) error {
	return status.Errorf(codes.Unimplemented, "method GroupByQuery not implemented")
}
func (UnimplementedXvecServiceServer) Iterate(*IterateRequest, grpc.ServerStreamingServer[QueryResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Iterate not implemented")
}
func (UnimplementedXvecServiceServer) mustEmbedUnimplementedXvecServiceServer() {}
func (UnimplementedXvecServiceServer) testEmbeddedByValue()                     {}

// UnsafeXvecServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to XvecServiceServer will
// result in compilation errors.
type UnsafeXvecServiceServer interface {
	mustEmbedUnimplementedXvecServiceServer()
}

func RegisterXvecServiceServer(s grpc.ServiceRegistrar, srv XvecServiceServer) {
	// If the following call pancis, it indicates UnimplementedXvecServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&XvecService_ServiceDesc, srv)
}

func _XvecService_CreateCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCollectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XvecServiceServer).CreateCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: XvecService_CreateCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XvecServiceServer).CreateCollection(ctx, req.(*CreateCollectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _XvecService_DropCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectionRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XvecServiceServer).DropCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: XvecService_DropCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XvecServiceServer).DropCollection(ctx, req.(*CollectionRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _XvecService_ListCollections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XvecServiceServer).ListCollections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: XvecService_ListCollections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XvecServiceServer).ListCollections(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _XvecService_GetSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectionRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XvecServiceServer).GetSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: XvecService_GetSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XvecServiceServer).GetSchema(ctx, req.(*CollectionRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _XvecService_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectionRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XvecServiceServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: XvecService_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XvecServiceServer).GetStats(ctx, req.(*CollectionRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _XvecService_Flush_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectionRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XvecServiceServer).Flush(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: XvecService_Flush_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XvecServiceServer).Flush(ctx, req.(*CollectionRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _XvecService_Optimize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OptimizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XvecServiceServer).Optimize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: XvecService_Optimize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XvecServiceServer).Optimize(ctx, req.(*OptimizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _XvecService_AddColumn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddColumnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XvecServiceServer).AddColumn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: XvecService_AddColumn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XvecServiceServer).AddColumn(ctx, req.(*AddColumnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _XvecService_AlterColumn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlterColumnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XvecServiceServer).AlterColumn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: XvecService_AlterColumn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XvecServiceServer).AlterColumn(ctx, req.(*AlterColumnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _XvecService_DropColumn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DropColumnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XvecServiceServer).DropColumn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: XvecService_DropColumn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XvecServiceServer).DropColumn(ctx, req.(*DropColumnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _XvecService_CreateIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XvecServiceServer).CreateIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: XvecService_CreateIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XvecServiceServer).CreateIndex(ctx, req.(*CreateIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _XvecService_DropIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DropIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XvecServiceServer).DropIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: XvecService_DropIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XvecServiceServer).DropIndex(ctx, req.(*DropIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _XvecService_Write_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XvecServiceServer).Write(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: XvecService_Write_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XvecServiceServer).Write(ctx, req.(*WriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _XvecService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XvecServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: XvecService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XvecServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _XvecService_DeleteByFilter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteByFilterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XvecServiceServer).DeleteByFilter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: XvecService_DeleteByFilter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XvecServiceServer).DeleteByFilter(ctx, req.(*DeleteByFilterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _XvecService_Fetch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FetchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(XvecServiceServer).Fetch(m, &grpc.GenericServerStream[FetchRequest, FetchResult]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type XvecService_FetchServer = grpc.ServerStreamingServer[FetchResult]

func _XvecService_Query_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(QueryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(XvecServiceServer).Query(m, &grpc.GenericServerStream[QueryRequest, QueryResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type XvecService_QueryServer = grpc.ServerStreamingServer[QueryResponse]

func _XvecService_MultiQuery_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MultiQueryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(XvecServiceServer).MultiQuery(m, &grpc.GenericServerStream[MultiQueryRequest, QueryResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type XvecService_MultiQueryServer = grpc.ServerStreamingServer[QueryResponse]

func _XvecService_GroupByQuery_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GroupByQueryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(XvecServiceServer).GroupByQuery(m, &grpc.GenericServerStream[GroupByQueryRequest, GroupByQueryResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type XvecService_GroupByQueryServer = grpc.ServerStreamingServer[GroupByQueryResponse]

func _XvecService_Iterate_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(IterateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(XvecServiceServer).Iterate(m, &grpc.GenericServerStream[IterateRequest, QueryResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type XvecService_IterateServer = grpc.ServerStreamingServer[QueryResponse]

// XvecService_ServiceDesc is the grpc.ServiceDesc for XvecService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var XvecService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xvec.v1.XvecService",
	HandlerType: (*XvecServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCollection",
			Handler:    _XvecService_CreateCollection_Handler,
		},
		{
			MethodName: "DropCollection",
			Handler:    _XvecService_DropCollection_Handler,
		},
		{
			MethodName: "ListCollections",
			Handler:    _XvecService_ListCollections_Handler,
		},
		{
			MethodName: "GetSchema",
			Handler:    _XvecService_GetSchema_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _XvecService_GetStats_Handler,
		},
		{
			MethodName: "Flush",
			Handler:    _XvecService_Flush_Handler,
		},
		{
			MethodName: "Optimize",
			Handler:    _XvecService_Optimize_Handler,
		},
		{
			MethodName: "AddColumn",
			Handler:    _XvecService_AddColumn_Handler,
		},
		{
			MethodName: "AlterColumn",
			Handler:    _XvecService_AlterColumn_Handler,
		},
		{
			MethodName: "DropColumn",
			Handler:    _XvecService_DropColumn_Handler,
		},
		{
			MethodName: "CreateIndex",
			Handler:    _XvecService_CreateIndex_Handler,
		},
		{
			MethodName: "DropIndex",
			Handler:    _XvecService_DropIndex_Handler,
		},
		{
			MethodName: "Write",
			Handler:    _XvecService_Write_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _XvecService_Delete_Handler,
		},
		{
			MethodName: "DeleteByFilter",
			Handler:    _XvecService_DeleteByFilter_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Fetch",
			Handler:       _XvecService_Fetch_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Query",
			Handler:       _XvecService_Query_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "MultiQuery",
			Handler:       _XvecService_MultiQuery_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GroupByQuery",
			Handler:       _XvecService_GroupByQuery_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Iterate",
			Handler:       _XvecService_Iterate_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "xvec/v1/xvec.proto",
}
