//go:build !noasm && arm64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8 (6ubuntu1)
// 	objdump 2.46
// flags: -O3
// source: src/fastscan_neon.c

package simd

import "unsafe"

//go:noescape
func accumulate_neon(codes, lp_table, result unsafe.Pointer, dim int64)

//go:noescape
func transfer_lut_hacc_neon(lut unsafe.Pointer, dim int64, hc_lut unsafe.Pointer)

//go:noescape
func accumulate_hacc_neon(codes, hc_lut, result unsafe.Pointer, dim int64)
