//go:build !noasm && amd64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8 (6ubuntu1)
// 	objdump 2.46
// flags: -mavx2 -O3
// source: src/fastscan_avx2.c

TEXT ·accumulate_avx2(SB), $0-32
	MOVQ codes+0(FP), DI
	MOVQ lp_table+8(FP), SI
	MOVQ result+16(FP), DX
	MOVQ dim+24(FP), CX
	BYTE $0x55                                 // pushq	%rbp
	WORD $0x8948; BYTE $0xe5                   // movq	%rsp, %rbp
	LONG $0xf8e48348                           // andq	$-8, %rsp
	LONG $0x10ec8348                           // subq	$16, %rsp
	LONG $0x02e1c148                           // shlq	$2, %rcx
	LONG $0x0f2444c6; BYTE $0x0f               // movb	$15, 15(%rsp)
	LONG $0x787de2c4; WORD $0x2444; BYTE $0x0f // vpbroadcastb	15(%rsp), %ymm0
	WORD $0x8548; BYTE $0xc9                   // testq	%rcx, %rcx
	JLE  LBB0_1
	LONG $0xdbefe1c5                           // vpxor	%xmm3, %xmm3, %xmm3
	WORD $0xc031                               // xorl	%eax, %eax
	LONG $0xe4efd9c5                           // vpxor	%xmm4, %xmm4, %xmm4
	LONG $0xd2efe9c5                           // vpxor	%xmm2, %xmm2, %xmm2
	LONG $0xc9eff1c5                           // vpxor	%xmm1, %xmm1, %xmm1

LBB0_4:
	LONG $0x2c6ffec5; BYTE $0x07   // vmovdqu	(%rdi,%rax), %ymm5
	LONG $0x746ffec5; WORD $0x2007 // vmovdqu	32(%rdi,%rax), %ymm6
	LONG $0xf8dbd5c5               // vpand	%ymm0, %ymm5, %ymm7
	LONG $0xd571d5c5; BYTE $0x04   // vpsrlw	$4, %ymm5, %ymm5
	LONG $0xe8dbd5c5               // vpand	%ymm0, %ymm5, %ymm5
	LONG $0x046f7ec5; BYTE $0x06   // vmovdqu	(%rsi,%rax), %ymm8
	LONG $0x4c6f7ec5; WORD $0x2006 // vmovdqu	32(%rsi,%rax), %ymm9
	LONG $0x003de2c4; BYTE $0xff   // vpshufb	%ymm7, %ymm8, %ymm7
	LONG $0x003de2c4; BYTE $0xed   // vpshufb	%ymm5, %ymm8, %ymm5
	LONG $0xdffde5c5               // vpaddw	%ymm7, %ymm3, %ymm3
	LONG $0xd771c5c5; BYTE $0x08   // vpsrlw	$8, %ymm7, %ymm7
	LONG $0xe4fdc5c5               // vpaddw	%ymm4, %ymm7, %ymm4
	LONG $0xd5fdedc5               // vpaddw	%ymm5, %ymm2, %ymm2
	LONG $0xd571d5c5; BYTE $0x08   // vpsrlw	$8, %ymm5, %ymm5
	LONG $0xc9fdd5c5               // vpaddw	%ymm1, %ymm5, %ymm1
	LONG $0xe8dbcdc5               // vpand	%ymm0, %ymm6, %ymm5
	LONG $0xd671cdc5; BYTE $0x04   // vpsrlw	$4, %ymm6, %ymm6
	LONG $0xf0dbcdc5               // vpand	%ymm0, %ymm6, %ymm6
	LONG $0x0035e2c4; BYTE $0xed   // vpshufb	%ymm5, %ymm9, %ymm5
	LONG $0x0035e2c4; BYTE $0xf6   // vpshufb	%ymm6, %ymm9, %ymm6
	LONG $0xddfde5c5               // vpaddw	%ymm5, %ymm3, %ymm3
	LONG $0xd571d5c5; BYTE $0x08   // vpsrlw	$8, %ymm5, %ymm5
	LONG $0xe5fdddc5               // vpaddw	%ymm5, %ymm4, %ymm4
	LONG $0xd6fdedc5               // vpaddw	%ymm6, %ymm2, %ymm2
	LONG $0xd671d5c5; BYTE $0x08   // vpsrlw	$8, %ymm6, %ymm5
	LONG $0xcdfdf5c5               // vpaddw	%ymm5, %ymm1, %ymm1
	LONG $0x40c08348               // addq	$64, %rax
	WORD $0x3948; BYTE $0xc8       // cmpq	%rcx, %rax
	JL   LBB0_4
	JMP  LBB0_2

LBB0_1:
	LONG $0xc9eff1c5 // vpxor	%xmm1, %xmm1, %xmm1
	LONG $0xd2efe9c5 // vpxor	%xmm2, %xmm2, %xmm2
	LONG $0xe4efd9c5 // vpxor	%xmm4, %xmm4, %xmm4
	LONG $0xdbefe1c5 // vpxor	%xmm3, %xmm3, %xmm3

LBB0_2:
	LONG $0xf471fdc5; BYTE $0x08   // vpsllw	$8, %ymm4, %ymm0
	LONG $0xc0f9e5c5               // vpsubw	%ymm0, %ymm3, %ymm0
	LONG $0x467de3c4; WORD $0x21dc // vperm2i128	$33, %ymm4, %ymm0, %ymm3 # ymm3 = ymm0[2,3],ymm4[0,1]
	LONG $0x027de3c4; WORD $0xf0c4 // vpblendd	$240, %ymm4, %ymm0, %ymm0       # ymm0 = ymm0[0,1,2,3],ymm4[4,5,6,7]
	LONG $0xc0fde5c5               // vpaddw	%ymm0, %ymm3, %ymm0
	LONG $0x027ffec5               // vmovdqu	%ymm0, (%rdx)
	LONG $0xf171fdc5; BYTE $0x08   // vpsllw	$8, %ymm1, %ymm0
	LONG $0xc0f9edc5               // vpsubw	%ymm0, %ymm2, %ymm0
	LONG $0x467de3c4; WORD $0x21d1 // vperm2i128	$33, %ymm1, %ymm0, %ymm2 # ymm2 = ymm0[2,3],ymm1[0,1]
	LONG $0x027de3c4; WORD $0xf0c1 // vpblendd	$240, %ymm1, %ymm0, %ymm0       # ymm0 = ymm0[0,1,2,3],ymm1[4,5,6,7]
	LONG $0xc0fdedc5               // vpaddw	%ymm0, %ymm2, %ymm0
	LONG $0x427ffec5; BYTE $0x20   // vmovdqu	%ymm0, 32(%rdx)
	WORD $0x8948; BYTE $0xec       // movq	%rbp, %rsp
	BYTE $0x5d                     // popq	%rbp
	WORD $0xf8c5; BYTE $0x77       // vzeroupper
	RET

TEXT ·transfer_lut_hacc_avx2(SB), $0-24
	MOVQ lut+0(FP), DI
	MOVQ dim+8(FP), SI
	MOVQ hc_lut+16(FP), DX
	LONG $0x02fec148                       // sarq	$2, %rsi
	WORD $0x8548; BYTE $0xf6               // testq	%rsi, %rsi
	JLE  LBB1_4
	BYTE $0x55                             // pushq	%rbp
	WORD $0x8948; BYTE $0xe5               // movq	%rsp, %rbp
	BYTE $0x53                             // pushq	%rbx
	LONG $0xf8e48348                       // andq	$-8, %rsp
	WORD $0x3145; BYTE $0xc9               // xorl	%r9d, %r9d
	QUAD $0xffffffffffc0ba49; WORD $0x7fff // movabsq	$9223372036854775744, %r10      # imm = 0x7FFFFFFFFFFFFFC0
	WORD $0x3145; BYTE $0xc0               // xorl	%r8d, %r8d

LBB1_2:
	WORD $0x894c; BYTE $0xc3       // movq	%r8, %rbx
	WORD $0x214c; BYTE $0xd3       // andq	%r10, %rbx
	WORD $0x0148; BYTE $0xd3       // addq	%rdx, %rbx
	WORD $0x8944; BYTE $0xc8       // movl	%r9d, %eax
	WORD $0xe083; BYTE $0x10       // andl	$16, %eax
	LONG $0x0cb70f42; BYTE $0x07   // movzwl	(%rdi,%r8), %ecx
	WORD $0x0c88; BYTE $0x18       // movb	%cl, (%rax,%rbx)
	LONG $0x20186c88               // movb	%ch, 32(%rax,%rbx)
	LONG $0x4cb70f42; WORD $0x0207 // movzwl	2(%rdi,%r8), %ecx
	LONG $0x01184c88               // movb	%cl, 1(%rax,%rbx)
	LONG $0x21186c88               // movb	%ch, 33(%rax,%rbx)
	LONG $0x4cb70f42; WORD $0x0407 // movzwl	4(%rdi,%r8), %ecx
	LONG $0x02184c88               // movb	%cl, 2(%rax,%rbx)
	LONG $0x22186c88               // movb	%ch, 34(%rax,%rbx)
	LONG $0x4cb70f42; WORD $0x0607 // movzwl	6(%rdi,%r8), %ecx
	LONG $0x03184c88               // movb	%cl, 3(%rax,%rbx)
	LONG $0x23186c88               // movb	%ch, 35(%rax,%rbx)
	LONG $0x4cb70f42; WORD $0x0807 // movzwl	8(%rdi,%r8), %ecx
	LONG $0x04184c88               // movb	%cl, 4(%rax,%rbx)
	LONG $0x24186c88               // movb	%ch, 36(%rax,%rbx)
	LONG $0x4cb70f42; WORD $0x0a07 // movzwl	10(%rdi,%r8), %ecx
	LONG $0x05184c88               // movb	%cl, 5(%rax,%rbx)
	LONG $0x25186c88               // movb	%ch, 37(%rax,%rbx)
	LONG $0x4cb70f42; WORD $0x0c07 // movzwl	12(%rdi,%r8), %ecx
	LONG $0x06184c88               // movb	%cl, 6(%rax,%rbx)
	LONG $0x26186c88               // movb	%ch, 38(%rax,%rbx)
	LONG $0x4cb70f42; WORD $0x0e07 // movzwl	14(%rdi,%r8), %ecx
	LONG $0x07184c88               // movb	%cl, 7(%rax,%rbx)
	LONG $0x27186c88               // movb	%ch, 39(%rax,%rbx)
	LONG $0x4cb70f42; WORD $0x1007 // movzwl	16(%rdi,%r8), %ecx
	LONG $0x08184c88               // movb	%cl, 8(%rax,%rbx)
	LONG $0x28186c88               // movb	%ch, 40(%rax,%rbx)
	LONG $0x4cb70f42; WORD $0x1207 // movzwl	18(%rdi,%r8), %ecx
	LONG $0x09184c88               // movb	%cl, 9(%rax,%rbx)
	LONG $0x29186c88               // movb	%ch, 41(%rax,%rbx)
	LONG $0x4cb70f42; WORD $0x1407 // movzwl	20(%rdi,%r8), %ecx
	LONG $0x0a184c88               // movb	%cl, 10(%rax,%rbx)
	LONG $0x2a186c88               // movb	%ch, 42(%rax,%rbx)
	LONG $0x4cb70f42; WORD $0x1607 // movzwl	22(%rdi,%r8), %ecx
	LONG $0x0b184c88               // movb	%cl, 11(%rax,%rbx)
	LONG $0x2b186c88               // movb	%ch, 43(%rax,%rbx)
	LONG $0x4cb70f42; WORD $0x1807 // movzwl	24(%rdi,%r8), %ecx
	LONG $0x0c184c88               // movb	%cl, 12(%rax,%rbx)
	LONG $0x2c186c88               // movb	%ch, 44(%rax,%rbx)
	LONG $0x4cb70f42; WORD $0x1a07 // movzwl	26(%rdi,%r8), %ecx
	LONG $0x0d184c88               // movb	%cl, 13(%rax,%rbx)
	LONG $0x2d186c88               // movb	%ch, 45(%rax,%rbx)
	LONG $0x4cb70f42; WORD $0x1c07 // movzwl	28(%rdi,%r8), %ecx
	LONG $0x0e184c88               // movb	%cl, 14(%rax,%rbx)
	LONG $0x2e186c88               // movb	%ch, 46(%rax,%rbx)
	LONG $0x4cb70f42; WORD $0x1e07 // movzwl	30(%rdi,%r8), %ecx
	LONG $0x0f184c88               // movb	%cl, 15(%rax,%rbx)
	LONG $0x2f186c88               // movb	%ch, 47(%rax,%rbx)
	LONG $0x20c08349               // addq	$32, %r8
	LONG $0x10c18349               // addq	$16, %r9
	WORD $0xff48; BYTE $0xce       // decq	%rsi
	JNE  LBB1_2
	LONG $0xf8658d48               // leaq	-8(%rbp), %rsp
	BYTE $0x5b                     // popq	%rbx
	BYTE $0x5d                     // popq	%rbp

LBB1_4:
	RET

TEXT ·accumulate_hacc_avx2(SB), $0-32
	MOVQ codes+0(FP), DI
	MOVQ hc_lut+8(FP), SI
	MOVQ result+16(FP), DX
	MOVQ dim+24(FP), CX
	BYTE $0x55                                 // pushq	%rbp
	WORD $0x8948; BYTE $0xe5                   // movq	%rsp, %rbp
	LONG $0xf8e48348                           // andq	$-8, %rsp
	LONG $0x10ec8348                           // subq	$16, %rsp
	LONG $0x0f2444c6; BYTE $0x0f               // movb	$15, 15(%rsp)
	LONG $0x787de2c4; WORD $0x2474; BYTE $0x0f // vpbroadcastb	15(%rsp), %ymm6
	LONG $0x02f9c148                           // sarq	$2, %rcx
	LONG $0xc0eff9c5                           // vpxor	%xmm0, %xmm0, %xmm0
	WORD $0x8548; BYTE $0xc9                   // testq	%rcx, %rcx
	JLE  LBB2_1
	WORD $0xc031                               // xorl	%eax, %eax
	LONG $0xc9eff1c5                           // vpxor	%xmm1, %xmm1, %xmm1
	LONG $0xd2efe9c5                           // vpxor	%xmm2, %xmm2, %xmm2
	LONG $0xdbefe1c5                           // vpxor	%xmm3, %xmm3, %xmm3
	LONG $0xe4efd9c5                           // vpxor	%xmm4, %xmm4, %xmm4
	LONG $0xedefd1c5                           // vpxor	%xmm5, %xmm5, %xmm5
	LONG $0xffefc1c5                           // vpxor	%xmm7, %xmm7, %xmm7
	LONG $0xef3941c4; BYTE $0xc0               // vpxor	%xmm8, %xmm8, %xmm8
	WORD $0x3145; BYTE $0xc0                   // xorl	%r8d, %r8d

LBB2_4:
	LONG $0x0c6f7ec5; BYTE $0x07   // vmovdqu	(%rdi,%rax), %ymm9
	LONG $0xd6db35c5               // vpand	%ymm6, %ymm9, %ymm10
	LONG $0x7135c1c4; WORD $0x04d1 // vpsrlw	$4, %ymm9, %ymm9
	LONG $0xcedb35c5               // vpand	%ymm6, %ymm9, %ymm9
	LONG $0x1c6f7ec5; BYTE $0x46   // vmovdqu	(%rsi,%rax,2), %ymm11
	LONG $0x646f7ec5; WORD $0x2046 // vmovdqu	32(%rsi,%rax,2), %ymm12
	LONG $0x002542c4; BYTE $0xea   // vpshufb	%ymm10, %ymm11, %ymm13
	LONG $0x002542c4; BYTE $0xd9   // vpshufb	%ymm9, %ymm11, %ymm11
	LONG $0xfd3d41c4; BYTE $0xc5   // vpaddw	%ymm13, %ymm8, %ymm8
	LONG $0x7115c1c4; WORD $0x08d5 // vpsrlw	$8, %ymm13, %ymm13
	LONG $0xfffd95c5               // vpaddw	%ymm7, %ymm13, %ymm7
	LONG $0xedfda5c5               // vpaddw	%ymm5, %ymm11, %ymm5
	LONG $0x7125c1c4; WORD $0x08d3 // vpsrlw	$8, %ymm11, %ymm11
	LONG $0xe4fda5c5               // vpaddw	%ymm4, %ymm11, %ymm4
	LONG $0x001d42c4; BYTE $0xd2   // vpshufb	%ymm10, %ymm12, %ymm10
	LONG $0x001d42c4; BYTE $0xc9   // vpshufb	%ymm9, %ymm12, %ymm9
	LONG $0xdbfdadc5               // vpaddw	%ymm3, %ymm10, %ymm3
	LONG $0x712dc1c4; WORD $0x08d2 // vpsrlw	$8, %ymm10, %ymm10
	LONG $0xd2fdadc5               // vpaddw	%ymm2, %ymm10, %ymm2
	LONG $0xc9fdb5c5               // vpaddw	%ymm1, %ymm9, %ymm1
	LONG $0x7135c1c4; WORD $0x08d1 // vpsrlw	$8, %ymm9, %ymm9
	LONG $0xc0fdb5c5               // vpaddw	%ymm0, %ymm9, %ymm0
	LONG $0x02c08349               // addq	$2, %r8
	LONG $0x20c08348               // addq	$32, %rax
	WORD $0x3949; BYTE $0xc8       // cmpq	%rcx, %r8
	JL   LBB2_4
	JMP  LBB2_2

LBB2_1:
	LONG $0xc9eff1c5             // vpxor	%xmm1, %xmm1, %xmm1
	LONG $0xd2efe9c5             // vpxor	%xmm2, %xmm2, %xmm2
	LONG $0xdbefe1c5             // vpxor	%xmm3, %xmm3, %xmm3
	LONG $0xe4efd9c5             // vpxor	%xmm4, %xmm4, %xmm4
	LONG $0xedefd1c5             // vpxor	%xmm5, %xmm5, %xmm5
	LONG $0xffefc1c5             // vpxor	%xmm7, %xmm7, %xmm7
	LONG $0xef3941c4; BYTE $0xc0 // vpxor	%xmm8, %xmm8, %xmm8

LBB2_2:
	LONG $0xf771cdc5; BYTE $0x08   // vpsllw	$8, %ymm7, %ymm6
	LONG $0xf6f9bdc5               // vpsubw	%ymm6, %ymm8, %ymm6
	LONG $0x464d63c4; WORD $0x21c7 // vperm2i128	$33, %ymm7, %ymm6, %ymm8 # ymm8 = ymm6[2,3],ymm7[0,1]
	LONG $0x024de3c4; WORD $0xf0f7 // vpblendd	$240, %ymm7, %ymm6, %ymm6       # ymm6 = ymm6[0,1,2,3],ymm7[4,5,6,7]
	LONG $0xf6fdbdc5               // vpaddw	%ymm6, %ymm8, %ymm6
	LONG $0xf471c5c5; BYTE $0x08   // vpsllw	$8, %ymm4, %ymm7
	LONG $0xeff9d5c5               // vpsubw	%ymm7, %ymm5, %ymm5
	LONG $0x4655e3c4; WORD $0x21fc // vperm2i128	$33, %ymm4, %ymm5, %ymm7 # ymm7 = ymm5[2,3],ymm4[0,1]
	LONG $0x0255e3c4; WORD $0xf0e4 // vpblendd	$240, %ymm4, %ymm5, %ymm4       # ymm4 = ymm5[0,1,2,3],ymm4[4,5,6,7]
	LONG $0xe4fdc5c5               // vpaddw	%ymm4, %ymm7, %ymm4
	LONG $0xf271d5c5; BYTE $0x08   // vpsllw	$8, %ymm2, %ymm5
	LONG $0xddf9e5c5               // vpsubw	%ymm5, %ymm3, %ymm3
	LONG $0x4665e3c4; WORD $0x21ea // vperm2i128	$33, %ymm2, %ymm3, %ymm5 # ymm5 = ymm3[2,3],ymm2[0,1]
	LONG $0x0265e3c4; WORD $0xf0d2 // vpblendd	$240, %ymm2, %ymm3, %ymm2       # ymm2 = ymm3[0,1,2,3],ymm2[4,5,6,7]
	LONG $0xd2fdd5c5               // vpaddw	%ymm2, %ymm5, %ymm2
	LONG $0xf071e5c5; BYTE $0x08   // vpsllw	$8, %ymm0, %ymm3
	LONG $0xcbf9f5c5               // vpsubw	%ymm3, %ymm1, %ymm1
	LONG $0x4675e3c4; WORD $0x21d8 // vperm2i128	$33, %ymm0, %ymm1, %ymm3 # ymm3 = ymm1[2,3],ymm0[0,1]
	LONG $0x0275e3c4; WORD $0xf0c0 // vpblendd	$240, %ymm0, %ymm1, %ymm0       # ymm0 = ymm1[0,1,2,3],ymm0[4,5,6,7]
	LONG $0xc0fde5c5               // vpaddw	%ymm0, %ymm3, %ymm0
	LONG $0x337de2c4; BYTE $0xce   // vpmovzxwd	%xmm6, %ymm1            # ymm1 = xmm6[0],zero,xmm6[1],zero,xmm6[2],zero,xmm6[3],zero,xmm6[4],zero,xmm6[5],zero,xmm6[6],zero,xmm6[7],zero
	LONG $0x397de3c4; WORD $0x01f3 // vextracti128	$1, %ymm6, %xmm3
	LONG $0x337de2c4; BYTE $0xdb   // vpmovzxwd	%xmm3, %ymm3            # ymm3 = xmm3[0],zero,xmm3[1],zero,xmm3[2],zero,xmm3[3],zero,xmm3[4],zero,xmm3[5],zero,xmm3[6],zero,xmm3[7],zero
	LONG $0x337de2c4; BYTE $0xea   // vpmovzxwd	%xmm2, %ymm5            # ymm5 = xmm2[0],zero,xmm2[1],zero,xmm2[2],zero,xmm2[3],zero,xmm2[4],zero,xmm2[5],zero,xmm2[6],zero,xmm2[7],zero
	LONG $0x397de3c4; WORD $0x01d2 // vextracti128	$1, %ymm2, %xmm2
	LONG $0x337de2c4; BYTE $0xd2   // vpmovzxwd	%xmm2, %ymm2            # ymm2 = xmm2[0],zero,xmm2[1],zero,xmm2[2],zero,xmm2[3],zero,xmm2[4],zero,xmm2[5],zero,xmm2[6],zero,xmm2[7],zero
	LONG $0x337de2c4; BYTE $0xf4   // vpmovzxwd	%xmm4, %ymm6            # ymm6 = xmm4[0],zero,xmm4[1],zero,xmm4[2],zero,xmm4[3],zero,xmm4[4],zero,xmm4[5],zero,xmm4[6],zero,xmm4[7],zero
	LONG $0x397de3c4; WORD $0x01e4 // vextracti128	$1, %ymm4, %xmm4
	LONG $0x337de2c4; BYTE $0xe4   // vpmovzxwd	%xmm4, %ymm4            # ymm4 = xmm4[0],zero,xmm4[1],zero,xmm4[2],zero,xmm4[3],zero,xmm4[4],zero,xmm4[5],zero,xmm4[6],zero,xmm4[7],zero
	LONG $0x337de2c4; BYTE $0xf8   // vpmovzxwd	%xmm0, %ymm7            # ymm7 = xmm0[0],zero,xmm0[1],zero,xmm0[2],zero,xmm0[3],zero,xmm0[4],zero,xmm0[5],zero,xmm0[6],zero,xmm0[7],zero
	LONG $0x397de3c4; WORD $0x01c0 // vextracti128	$1, %ymm0, %xmm0
	LONG $0x337de2c4; BYTE $0xc0   // vpmovzxwd	%xmm0, %ymm0            # ymm0 = xmm0[0],zero,xmm0[1],zero,xmm0[2],zero,xmm0[3],zero,xmm0[4],zero,xmm0[5],zero,xmm0[6],zero,xmm0[7],zero
	LONG $0xf572d5c5; BYTE $0x08   // vpslld	$8, %ymm5, %ymm5
	LONG $0xc9fed5c5               // vpaddd	%ymm1, %ymm5, %ymm1
	LONG $0x0a7ffec5               // vmovdqu	%ymm1, (%rdx)
	LONG $0xf272f5c5; BYTE $0x08   // vpslld	$8, %ymm2, %ymm1
	LONG $0xcbfef5c5               // vpaddd	%ymm3, %ymm1, %ymm1
	LONG $0x4a7ffec5; BYTE $0x20   // vmovdqu	%ymm1, 32(%rdx)
	LONG $0xf772f5c5; BYTE $0x08   // vpslld	$8, %ymm7, %ymm1
	LONG $0xcefef5c5               // vpaddd	%ymm6, %ymm1, %ymm1
	LONG $0x4a7ffec5; BYTE $0x40   // vmovdqu	%ymm1, 64(%rdx)
	LONG $0xf072fdc5; BYTE $0x08   // vpslld	$8, %ymm0, %ymm0
	LONG $0xc4fefdc5               // vpaddd	%ymm4, %ymm0, %ymm0
	LONG $0x427ffec5; BYTE $0x60   // vmovdqu	%ymm0, 96(%rdx)
	WORD $0x8948; BYTE $0xec       // movq	%rbp, %rsp
	BYTE $0x5d                     // popq	%rbp
	WORD $0xf8c5; BYTE $0x77       // vzeroupper
	RET
