//go:build !noasm && riscv64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8 (6ubuntu1)
// 	objdump 2.46
// flags: -march=rv64imafdv -O3
// source: src/rotator_rvv.c

package simd

import "unsafe"

//go:noescape
func flip_sign_rvv(flip, data unsafe.Pointer, dim int64)

//go:noescape
func kacs_walk_rvv(data unsafe.Pointer, len int64)
