//go:build !noasm && riscv64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8 (6ubuntu1)
// 	objdump 2.46
// flags: -march=rv64imafdv -O3
// source: src/rotator_rvv.c

TEXT ·flip_sign_rvv(SB), $0-24
	MOV  flip+0(FP), A0
	MOV  data+8(FP), A1
	MOV  dim+16(FP), A2
	BLEZ A2, LBB0_12
	WORD $0xfd010113    // addi	sp, sp, -48
	WORD $0x02113423    // sd	ra, 40(sp)                      # 8-byte Folded Spill
	WORD $0x02813023    // sd	s0, 32(sp)                      # 8-byte Folded Spill
	WORD $0x00913c23    // sd	s1, 24(sp)                      # 8-byte Folded Spill
	WORD $0x01213823    // sd	s2, 16(sp)                      # 8-byte Folded Spill
	WORD $0x01313423    // sd	s3, 8(sp)                       # 8-byte Folded Spill
	WORD $0x03010413    // addi	s0, sp, 48
	WORD $0x00000693    // li	a3, 0
	WORD $0xc2202873    // csrr	a6, vlenb
	WORD $0x00385713    // srli	a4, a6, 3
	WORD $0x00185793    // srli	a5, a6, 1
	WORD $0x00181813    // slli	a6, a6, 1
	WORD $0x40f008b3    // neg	a7, a5
	WORD $0x0da072d7    // vsetvli	t0, zero, e64, m4, ta, ma
	WORD $0x5208a457    // vid.v	v8
	JMP  LBB0_3

LBB0_2:
	WORD $0x00038113     // mv	sp, t2
	WORD $0x00269393     // slli	t2, a3, 2
	WORD $0x0d037057     // vsetvli	zero, t1, e32, m1, ta, ma
	WORD $0x020e6607     // vle32.v	v12, (t3)
	WORD $0x007583b3     // add	t2, a1, t2
	WORD $0x0203e687     // vle32.v	v13, (t2)
	WORD $0x2ed60657     // vxor.vv	v12, v13, v12
	WORD $0x00d286b3     // add	a3, t0, a3
	WORD $0x0203e627     // vse32.v	v12, (t2)
	BGE  A3, A2, LBB0_11

LBB0_3:
	WORD $0x00010393    // mv	t2, sp
	WORD $0x40d60333    // sub	t1, a2, a3
	WORD $0x0d0372d7    // vsetvli	t0, t1, e32, m1, ta, ma
	WORD $0x00229e93    // slli	t4, t0, 2
	WORD $0x00fe8e13    // addi	t3, t4, 15
	WORD $0xff0e7e13    // andi	t3, t3, -16
	WORD $0x41c10e33    // sub	t3, sp, t3
	WORD $0x000e0113    // mv	sp, t3
	BEQZ T0, LBB0_2
	BGEU T0, A5, LBB0_6
	WORD $0x00000f13    // li	t5, 0
	JMP  LBB0_9

LBB0_6:
	WORD $0x0112ff33 // and	t5, t0, a7
	WORD $0x01e88fb3 // add	t6, a7, t5
	WORD $0x02ffdfb3 // divu	t6, t6, a5
	WORD $0x004f9f93 // slli	t6, t6, 4
	WORD $0x010f8f93 // addi	t6, t6, 16
	WORD $0x03f70fb3 // mul	t6, a4, t6
	WORD $0x01fe0fb3 // add	t6, t3, t6
	WORD $0x000e0493 // mv	s1, t3
	WORD $0x9e81b657 // vmv4r.v	v12, v8

LBB0_7:
	WORD $0x0da07957    // vsetvli	s2, zero, e64, m4, ta, ma
	WORD $0x02c6c857    // vadd.vx	v16, v12, a3
	WORD $0xa301ba57    // vsrl.vi	v20, v16, 3
	WORD $0x0c707057    // vsetvli	zero, zero, e8, mf2, ta, ma
	WORD $0x07457c07    // vluxei64.v	v24, (a0), v20
	WORD $0x0d107057    // vsetvli	zero, zero, e32, m2, ta, ma
	WORD $0xb3003a57    // vnsrl.wi	v20, v16, 0
	WORD $0x2743b857    // vand.vi	v16, v20, 7
	WORD $0x4b822957    // vzext.vf4	v18, v24
	WORD $0xa3280857    // vsrl.vv	v16, v18, v16
	WORD $0x970fb857    // vsll.vi	v16, v16, 31
	WORD $0x22848827    // vs2r.v	v16, (s1)
	WORD $0x010484b3    // add	s1, s1, a6
	WORD $0x0da07057    // vsetvli	zero, zero, e64, m4, ta, ma
	WORD $0x02c7c657    // vadd.vx	v12, v12, a5
	BNE  S1, T6, LBB0_7
	BEQ  T0, T5, LBB0_2

LBB0_9:
	WORD $0x002f1f93 // slli	t6, t5, 2
	WORD $0x01e68f33 // add	t5, a3, t5
	WORD $0x01fe0fb3 // add	t6, t3, t6
	WORD $0x01de0eb3 // add	t4, t3, t4
	WORD $0x000f0493 // mv	s1, t5

LBB0_10:
	WORD $0x003f5913     // srli	s2, t5, 3
	WORD $0x01250933     // add	s2, a0, s2
	WORD $0x00094903     // lbu	s2, 0(s2)
	WORD $0x0074f993     // andi	s3, s1, 7
	WORD $0x0139593b     // srlw	s2, s2, s3
	WORD $0x01f91913     // slli	s2, s2, 31
	WORD $0x012fa023     // sw	s2, 0(t6)
	WORD $0x004f8f93     // addi	t6, t6, 4
	WORD $0x00148493     // addi	s1, s1, 1
	WORD $0x001f0f13     // addi	t5, t5, 1
	BNE  T6, T4, LBB0_10
	JMP  LBB0_2

LBB0_11:
	WORD $0xfd040113 // addi	sp, s0, -48
	WORD $0x02813083 // ld	ra, 40(sp)                      # 8-byte Folded Reload
	WORD $0x02013403 // ld	s0, 32(sp)                      # 8-byte Folded Reload
	WORD $0x01813483 // ld	s1, 24(sp)                      # 8-byte Folded Reload
	WORD $0x01013903 // ld	s2, 16(sp)                      # 8-byte Folded Reload
	WORD $0x00813983 // ld	s3, 8(sp)                       # 8-byte Folded Reload
	WORD $0x03010113 // addi	sp, sp, 48

LBB0_12:
	RET

TEXT ·kacs_walk_rvv(SB), $0-16
	MOV  data+0(FP), A0
	MOV  len+8(FP), A1
	WORD $0x00200613    // li	a2, 2
	BLT  A1, A2, LBB1_3
	WORD $0x00000613    // li	a2, 0
	WORD $0x03f5d693    // srli	a3, a1, 63
	WORD $0x00d585b3    // add	a1, a1, a3
	WORD $0x4015d593    // srai	a1, a1, 1
	WORD $0x00259693    // slli	a3, a1, 2
	WORD $0x00d506b3    // add	a3, a0, a3

LBB1_2:
	WORD $0x40c58733    // sub	a4, a1, a2
	WORD $0x00261793    // slli	a5, a2, 2
	WORD $0x0d077757    // vsetvli	a4, a4, e32, m1, ta, ma
	WORD $0x00f50833    // add	a6, a0, a5
	WORD $0x00f687b3    // add	a5, a3, a5
	WORD $0x02086407    // vle32.v	v8, (a6)
	WORD $0x0207e487    // vle32.v	v9, (a5)
	WORD $0x00c70633    // add	a2, a4, a2
	WORD $0x02849557    // vfadd.vv	v10, v8, v9
	WORD $0x0a849457    // vfsub.vv	v8, v8, v9
	WORD $0x02086527    // vse32.v	v10, (a6)
	WORD $0x0207e427    // vse32.v	v8, (a5)
	BLT  A2, A1, LBB1_2

LBB1_3:
	RET
