//go:build !noasm && amd64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8 (6ubuntu1)
// 	objdump 2.46
// flags: -mavx512f -mavx512dq -O3
// source: src/rotator_avx512.c

TEXT ·flip_sign_avx512(SB), $0-24
	MOVQ flip+0(FP), DI
	MOVQ data+8(FP), SI
	MOVQ dim+16(FP), DX
	BYTE $0x55                     // pushq	%rbp
	WORD $0x8948; BYTE $0xe5       // movq	%rsp, %rbp
	LONG $0xf8e48348               // andq	$-8, %rsp
	LONG $0x10ec8348               // subq	$16, %rsp
	QUAD $0x800000000c2444c7       // movl	$-2147483648, 12(%rsp)          # imm = 0x80000000
	LONG $0x0c24448b               // movl	12(%rsp), %eax
	WORD $0x8548; BYTE $0xd2       // testq	%rdx, %rdx
	JLE  LBB0_3
	LONG $0x487df262; WORD $0xc07c // vpbroadcastd	%eax, %zmm0
	WORD $0xc031                   // xorl	%eax, %eax

LBB0_2:
	WORD $0x8b48; BYTE $0x0f                   // movq	(%rdi), %rcx
	LONG $0xc992f8c5                           // kmovw	%ecx, %k1
	LONG $0x48fef162; WORD $0x0c6f; BYTE $0x86 // vmovdqu64	(%rsi,%rax,4), %zmm1
	QUAD $0x0186546f48fef162                   // vmovdqu64	64(%rsi,%rax,4), %zmm2
	QUAD $0x02865c6f48fef162                   // vmovdqu64	128(%rsi,%rax,4), %zmm3
	QUAD $0x0386646f48fef162                   // vmovdqu64	192(%rsi,%rax,4), %zmm4
	LONG $0x497df162; WORD $0xc9ef             // vpxord	%zmm1, %zmm0, %zmm1 {%k1}
	LONG $0x48fef162; WORD $0x0c7f; BYTE $0x86 // vmovdqu64	%zmm1, (%rsi,%rax,4)
	WORD $0x8941; BYTE $0xc8                   // movl	%ecx, %r8d
	LONG $0x10e8c141                           // shrl	$16, %r8d
	LONG $0x9278c1c4; BYTE $0xc8               // kmovw	%r8d, %k1
	LONG $0x497df162; WORD $0xd2ef             // vpxord	%zmm2, %zmm0, %zmm2 {%k1}
	QUAD $0x0186547f48fef162                   // vmovdqu64	%zmm2, 64(%rsi,%rax,4)
	WORD $0x8949; BYTE $0xc8                   // movq	%rcx, %r8
	LONG $0x20e8c149                           // shrq	$32, %r8
	LONG $0x9278c1c4; BYTE $0xc8               // kmovw	%r8d, %k1
	LONG $0x497df162; WORD $0xdbef             // vpxord	%zmm3, %zmm0, %zmm3 {%k1}
	QUAD $0x02865c7f48fef162                   // vmovdqu64	%zmm3, 128(%rsi,%rax,4)
	LONG $0x30e9c148                           // shrq	$48, %rcx
	LONG $0xc992f8c5                           // kmovw	%ecx, %k1
	LONG $0x497df162; WORD $0xe4ef             // vpxord	%zmm4, %zmm0, %zmm4 {%k1}
	QUAD $0x0386647f48fef162                   // vmovdqu64	%zmm4, 192(%rsi,%rax,4)
	LONG $0x40c08348                           // addq	$64, %rax
	LONG $0x08c78348                           // addq	$8, %rdi
	WORD $0x3948; BYTE $0xd0                   // cmpq	%rdx, %rax
	JL   LBB0_2

LBB0_3:
	WORD $0x8948; BYTE $0xec // movq	%rbp, %rsp
	BYTE $0x5d               // popq	%rbp
	WORD $0xf8c5; BYTE $0x77 // vzeroupper
	RET

TEXT ·kacs_walk_avx512(SB), $0-16
	MOVQ data+0(FP), DI
	MOVQ len+8(FP), SI
	BYTE $0x55               // pushq	%rbp
	WORD $0x8948; BYTE $0xe5 // movq	%rsp, %rbp
	LONG $0xf8e48348         // andq	$-8, %rsp
	LONG $0x02fe8348         // cmpq	$2, %rsi
	JL   LBB1_5
	WORD $0x8948; BYTE $0xf0 // movq	%rsi, %rax
	LONG $0x3fe8c148         // shrq	$63, %rax
	WORD $0x0148; BYTE $0xf0 // addq	%rsi, %rax
	WORD $0xd148; BYTE $0xf8 // sarq	%rax
	LONG $0xff488d48         // leaq	-1(%rax), %rcx
	LONG $0x10f98348         // cmpq	$16, %rcx
	JAE  LBB1_6
	WORD $0xd231             // xorl	%edx, %edx
	JMP  LBB1_3

LBB1_6:
	WORD $0x8948; BYTE $0xce // movq	%rcx, %rsi
	LONG $0x04eec148         // shrq	$4, %rsi
	WORD $0xff48; BYTE $0xc6 // incq	%rsi
	LONG $0xfee68348         // andq	$-2, %rsi
	LONG $0x40478d4c         // leaq	64(%rdi), %r8
	LONG $0x870c8d4c         // leaq	(%rdi,%rax,4), %r9
	LONG $0x40c18349         // addq	$64, %r9
	WORD $0xd231             // xorl	%edx, %edx

LBB1_7:
	QUAD $0xff904410487cd162                   // vmovups	-64(%r8,%rdx,4), %zmm0
	QUAD $0xff914c10487cd162                   // vmovups	-64(%r9,%rdx,4), %zmm1
	LONG $0x487cf162; WORD $0xd158             // vaddps	%zmm1, %zmm0, %zmm2
	QUAD $0xff905411487cd162                   // vmovups	%zmm2, -64(%r8,%rdx,4)
	LONG $0x487cf162; WORD $0xc15c             // vsubps	%zmm1, %zmm0, %zmm0
	QUAD $0xff914411487cd162                   // vmovups	%zmm0, -64(%r9,%rdx,4)
	LONG $0x487cd162; WORD $0x0410; BYTE $0x90 // vmovups	(%r8,%rdx,4), %zmm0
	LONG $0x487cd162; WORD $0x0c10; BYTE $0x91 // vmovups	(%r9,%rdx,4), %zmm1
	LONG $0x487cf162; WORD $0xd158             // vaddps	%zmm1, %zmm0, %zmm2
	LONG $0x487cd162; WORD $0x1411; BYTE $0x90 // vmovups	%zmm2, (%r8,%rdx,4)
	LONG $0x487cf162; WORD $0xc15c             // vsubps	%zmm1, %zmm0, %zmm0
	LONG $0x487cd162; WORD $0x0411; BYTE $0x91 // vmovups	%zmm0, (%r9,%rdx,4)
	LONG $0x20c28348                           // addq	$32, %rdx
	LONG $0xfec68348                           // addq	$-2, %rsi
	JNE  LBB1_7

LBB1_3:
	WORD $0xc1f6; BYTE $0x10                   // testb	$16, %cl
	JNE  LBB1_5
	LONG $0x970c8d48                           // leaq	(%rdi,%rdx,4), %rcx
	LONG $0x487cf162; WORD $0x0410; BYTE $0x97 // vmovups	(%rdi,%rdx,4), %zmm0
	LONG $0x487cf162; WORD $0x0c10; BYTE $0x81 // vmovups	(%rcx,%rax,4), %zmm1
	LONG $0x487cf162; WORD $0xd158             // vaddps	%zmm1, %zmm0, %zmm2
	LONG $0x487cf162; WORD $0x1411; BYTE $0x97 // vmovups	%zmm2, (%rdi,%rdx,4)
	LONG $0x487cf162; WORD $0xc15c             // vsubps	%zmm1, %zmm0, %zmm0
	LONG $0x487cf162; WORD $0x0411; BYTE $0x81 // vmovups	%zmm0, (%rcx,%rax,4)

LBB1_5:
	WORD $0x8948; BYTE $0xec // movq	%rbp, %rsp
	BYTE $0x5d               // popq	%rbp
	WORD $0xf8c5; BYTE $0x77 // vzeroupper
	RET
