//go:build !noasm && arm64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8 (6ubuntu1)
// 	objdump 2.46
// flags: -O3
// source: src/space_excode_neon.c

package simd

import "unsafe"

//go:noescape
func ip16_fxu1_neon(query, compact_code unsafe.Pointer, dim int64) (result float32)

//go:noescape
func ip64_fxu2_neon(query, compact_code unsafe.Pointer, dim int64) (result float32)

//go:noescape
func ip64_fxu3_neon(query, compact_code unsafe.Pointer, dim int64) (result float32)

//go:noescape
func ip16_fxu4_neon(query, compact_code unsafe.Pointer, dim int64) (result float32)

//go:noescape
func ip64_fxu5_neon(query, compact_code unsafe.Pointer, dim int64) (result float32)

//go:noescape
func ip64_fxu6_neon(query, compact_code unsafe.Pointer, dim int64) (result float32)

//go:noescape
func ip64_fxu7_neon(query, compact_code unsafe.Pointer, dim int64) (result float32)

//go:noescape
func ip16_fxu8_neon(query, code unsafe.Pointer, dim int64) (result float32)
