//go:build !noasm && amd64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8 (6ubuntu1)
// 	objdump 2.46
// flags: -mavx512f -mavx512dq -mavx512bw -O3
// source: src/space_excode_avx512.c

TEXT ·ip16_fxu1_avx512(SB), $8-28
	MOVQ query+0(FP), DI
	MOVQ compact_code+8(FP), SI
	MOVQ dim+16(FP), DX
	WORD $0x8548; BYTE $0xd2    // testq	%rdx, %rdx
	JLE  LBB0_1
	BYTE $0x55                  // pushq	%rbp
	WORD $0x8948; BYTE $0xe5    // movq	%rsp, %rbp
	LONG $0xf8e48348            // andq	$-8, %rsp
	LONG $0xff4a8d48            // leaq	-1(%rdx), %rcx
	LONG $0x04e9c148            // shrq	$4, %rcx
	WORD $0xff48; BYTE $0xc1    // incq	%rcx
	WORD $0xc889                // movl	%ecx, %eax
	WORD $0xe083; BYTE $0x03    // andl	$3, %eax
	LONG $0x31fa8348            // cmpq	$49, %rdx
	JAE  LBB0_9
	LONG $0xc057f8c5            // vxorps	%xmm0, %xmm0, %xmm0
	JMP  LBB0_5

LBB0_1:
	LONG $0xc057f8c5 // vxorps	%xmm0, %xmm0, %xmm0
	JMP  LBB0_2

LBB0_9:
	LONG $0xfce18348 // andq	$-4, %rcx
	LONG $0xc057f8c5 // vxorps	%xmm0, %xmm0, %xmm0

LBB0_10:
	LONG $0x0e90f8c5                           // kmovw	(%rsi), %k1
	LONG $0x5690f8c5; BYTE $0x02               // kmovw	2(%rsi), %k2
	LONG $0x5e90f8c5; BYTE $0x04               // kmovw	4(%rsi), %k3
	LONG $0x6690f8c5; BYTE $0x06               // kmovw	6(%rsi), %k4
	LONG $0xc97cf162; WORD $0x0f10             // vmovups	(%rdi), %zmm1 {%k1} {z}
	LONG $0x487cf162; WORD $0xc158             // vaddps	%zmm1, %zmm0, %zmm0
	LONG $0xca7cf162; WORD $0x4f10; BYTE $0x01 // vmovups	64(%rdi), %zmm1 {%k2} {z}
	LONG $0x487cf162; WORD $0xc158             // vaddps	%zmm1, %zmm0, %zmm0
	LONG $0xcb7cf162; WORD $0x4f10; BYTE $0x02 // vmovups	128(%rdi), %zmm1 {%k3} {z}
	LONG $0x487cf162; WORD $0xc158             // vaddps	%zmm1, %zmm0, %zmm0
	LONG $0xcc7cf162; WORD $0x4f10; BYTE $0x03 // vmovups	192(%rdi), %zmm1 {%k4} {z}
	LONG $0x487cf162; WORD $0xc158             // vaddps	%zmm1, %zmm0, %zmm0
	LONG $0x08c68348                           // addq	$8, %rsi
	LONG $0x00c78148; WORD $0x0001; BYTE $0x00 // addq	$256, %rdi                      # imm = 0x100
	LONG $0xfcc18348                           // addq	$-4, %rcx
	JNE  LBB0_10

LBB0_5:
	WORD $0x8548; BYTE $0xc0 // testq	%rax, %rax
	JE   LBB0_8
	WORD $0xc931             // xorl	%ecx, %ecx

LBB0_7:
	LONG $0x0c90f8c5; BYTE $0x4e   // kmovw	(%rsi,%rcx,2), %k1
	LONG $0xc97cf162; WORD $0x0f10 // vmovups	(%rdi), %zmm1 {%k1} {z}
	LONG $0x487cf162; WORD $0xc158 // vaddps	%zmm1, %zmm0, %zmm0
	LONG $0x40c78348               // addq	$64, %rdi
	WORD $0xff48; BYTE $0xc1       // incq	%rcx
	WORD $0x3948; BYTE $0xc8       // cmpq	%rcx, %rax
	JNE  LBB0_7

LBB0_8:
	WORD $0x8948; BYTE $0xec // movq	%rbp, %rsp
	BYTE $0x5d               // popq	%rbp

LBB0_2:
	LONG  $0x48fdf362; WORD $0xc11b; BYTE $0x01 // vextractf64x4	$1, %zmm0, %ymm1
	LONG  $0x487cf162; WORD $0xc158             // vaddps	%zmm1, %zmm0, %zmm0
	LONG  $0x197de3c4; WORD $0x01c1             // vextractf128	$1, %ymm0, %xmm1
	LONG  $0xc158f8c5                           // vaddps	%xmm1, %xmm0, %xmm0
	LONG  $0xc8c6f9c5; BYTE $0x01               // vshufpd	$1, %xmm0, %xmm0, %xmm1         # xmm1 = xmm0[1,0]
	LONG  $0xc158f8c5                           // vaddps	%xmm1, %xmm0, %xmm0
	LONG  $0xc816fac5                           // vmovshdup	%xmm0, %xmm1            # xmm1 = xmm0[1,1,3,3]
	LONG  $0xc158fac5                           // vaddss	%xmm1, %xmm0, %xmm0
	WORD  $0xf8c5; BYTE $0x77                   // vzeroupper
	MOVSS X0, result+24(FP)
	RET

TEXT ·ip64_fxu2_avx512(SB), $8-28
	MOVQ query+0(FP), DI
	MOVQ compact_code+8(FP), SI
	MOVQ dim+16(FP), DX
	BYTE $0x55                                 // pushq	%rbp
	WORD $0x8948; BYTE $0xe5                   // movq	%rsp, %rbp
	LONG $0xf8e48348                           // andq	$-8, %rsp
	LONG $0x10ec8348                           // subq	$16, %rsp
	LONG $0x0f2444c6; BYTE $0x03               // movb	$3, 15(%rsp)
	LONG $0x7879e2c4; WORD $0x2444; BYTE $0x0f // vpbroadcastb	15(%rsp), %xmm0
	LONG $0xc957f0c5                           // vxorps	%xmm1, %xmm1, %xmm1
	WORD $0x8548; BYTE $0xd2                   // testq	%rdx, %rdx
	JLE  LBB1_3
	WORD $0xc031                               // xorl	%eax, %eax

LBB1_2:
	LONG $0x166ffac5                           // vmovdqu	(%rsi), %xmm2
	LONG $0xd8dbe9c5                           // vpand	%xmm0, %xmm2, %xmm3
	LONG $0xd271d9c5; BYTE $0x02               // vpsrlw	$2, %xmm2, %xmm4
	LONG $0xe0dbd9c5                           // vpand	%xmm0, %xmm4, %xmm4
	LONG $0xd271d1c5; BYTE $0x04               // vpsrlw	$4, %xmm2, %xmm5
	LONG $0xe8dbd1c5                           // vpand	%xmm0, %xmm5, %xmm5
	LONG $0xd271e9c5; BYTE $0x06               // vpsrlw	$6, %xmm2, %xmm2
	LONG $0x487df262; WORD $0xdb31             // vpmovzxbd	%xmm3, %zmm3            # zmm3 = xmm3[0],zero,zero,zero,xmm3[1],zero,zero,zero,xmm3[2],zero,zero,zero,xmm3[3],zero,zero,zero,xmm3[4],zero,zero,zero,xmm3[5],zero,zero,zero,xmm3[6],zero,zero,zero,xmm3[7],zero,zero,zero,xmm3[8],zero,zero,zero,xmm3[9],zero,zero,zero,xmm3[10],zero,zero,zero,xmm3[11],zero,zero,zero,xmm3[12],zero,zero,zero,xmm3[13],zero,zero,zero,xmm3[14],zero,zero,zero,xmm3[15],zero,zero,zero
	LONG $0x487cf162; WORD $0xdb5b             // vcvtdq2ps	%zmm3, %zmm3
	LONG $0x4864f162; WORD $0x1c59; BYTE $0x87 // vmulps	(%rdi,%rax,4), %zmm3, %zmm3
	LONG $0xd0dbe9c5                           // vpand	%xmm0, %xmm2, %xmm2
	LONG $0x4874f162; WORD $0xcb58             // vaddps	%zmm3, %zmm1, %zmm1
	LONG $0x487df262; WORD $0xdc31             // vpmovzxbd	%xmm4, %zmm3            # zmm3 = xmm4[0],zero,zero,zero,xmm4[1],zero,zero,zero,xmm4[2],zero,zero,zero,xmm4[3],zero,zero,zero,xmm4[4],zero,zero,zero,xmm4[5],zero,zero,zero,xmm4[6],zero,zero,zero,xmm4[7],zero,zero,zero,xmm4[8],zero,zero,zero,xmm4[9],zero,zero,zero,xmm4[10],zero,zero,zero,xmm4[11],zero,zero,zero,xmm4[12],zero,zero,zero,xmm4[13],zero,zero,zero,xmm4[14],zero,zero,zero,xmm4[15],zero,zero,zero
	LONG $0x487cf162; WORD $0xdb5b             // vcvtdq2ps	%zmm3, %zmm3
	QUAD $0x01875c594864f162                   // vmulps	64(%rdi,%rax,4), %zmm3, %zmm3
	LONG $0x4874f162; WORD $0xcb58             // vaddps	%zmm3, %zmm1, %zmm1
	LONG $0x487df262; WORD $0xdd31             // vpmovzxbd	%xmm5, %zmm3            # zmm3 = xmm5[0],zero,zero,zero,xmm5[1],zero,zero,zero,xmm5[2],zero,zero,zero,xmm5[3],zero,zero,zero,xmm5[4],zero,zero,zero,xmm5[5],zero,zero,zero,xmm5[6],zero,zero,zero,xmm5[7],zero,zero,zero,xmm5[8],zero,zero,zero,xmm5[9],zero,zero,zero,xmm5[10],zero,zero,zero,xmm5[11],zero,zero,zero,xmm5[12],zero,zero,zero,xmm5[13],zero,zero,zero,xmm5[14],zero,zero,zero,xmm5[15],zero,zero,zero
	LONG $0x487cf162; WORD $0xdb5b             // vcvtdq2ps	%zmm3, %zmm3
	QUAD $0x02875c594864f162                   // vmulps	128(%rdi,%rax,4), %zmm3, %zmm3
	LONG $0x4864f162; WORD $0xc958             // vaddps	%zmm1, %zmm3, %zmm1
	LONG $0x487df262; WORD $0xd231             // vpmovzxbd	%xmm2, %zmm2            # zmm2 = xmm2[0],zero,zero,zero,xmm2[1],zero,zero,zero,xmm2[2],zero,zero,zero,xmm2[3],zero,zero,zero,xmm2[4],zero,zero,zero,xmm2[5],zero,zero,zero,xmm2[6],zero,zero,zero,xmm2[7],zero,zero,zero,xmm2[8],zero,zero,zero,xmm2[9],zero,zero,zero,xmm2[10],zero,zero,zero,xmm2[11],zero,zero,zero,xmm2[12],zero,zero,zero,xmm2[13],zero,zero,zero,xmm2[14],zero,zero,zero,xmm2[15],zero,zero,zero
	LONG $0x487cf162; WORD $0xd25b             // vcvtdq2ps	%zmm2, %zmm2
	QUAD $0x03875459486cf162                   // vmulps	192(%rdi,%rax,4), %zmm2, %zmm2
	LONG $0x486cf162; WORD $0xc958             // vaddps	%zmm1, %zmm2, %zmm1
	LONG $0x10c68348                           // addq	$16, %rsi
	LONG $0x40c08348                           // addq	$64, %rax
	WORD $0x3948; BYTE $0xd0                   // cmpq	%rdx, %rax
	JL   LBB1_2

LBB1_3:
	LONG  $0x48fdf362; WORD $0xc81b; BYTE $0x01 // vextractf64x4	$1, %zmm1, %ymm0
	LONG  $0x4874f162; WORD $0xc058             // vaddps	%zmm0, %zmm1, %zmm0
	LONG  $0x197de3c4; WORD $0x01c1             // vextractf128	$1, %ymm0, %xmm1
	LONG  $0xc158f8c5                           // vaddps	%xmm1, %xmm0, %xmm0
	LONG  $0xc8c6f9c5; BYTE $0x01               // vshufpd	$1, %xmm0, %xmm0, %xmm1         # xmm1 = xmm0[1,0]
	LONG  $0xc158f8c5                           // vaddps	%xmm1, %xmm0, %xmm0
	LONG  $0xc816fac5                           // vmovshdup	%xmm0, %xmm1            # xmm1 = xmm0[1,1,3,3]
	LONG  $0xc158fac5                           // vaddss	%xmm1, %xmm0, %xmm0
	WORD  $0x8948; BYTE $0xec                   // movq	%rbp, %rsp
	BYTE  $0x5d                                 // popq	%rbp
	WORD  $0xf8c5; BYTE $0x77                   // vzeroupper
	MOVSS X0, result+24(FP)
	RET

TEXT ·ip64_fxu3_avx512(SB), $8-28
	MOVQ query+0(FP), DI
	MOVQ compact_code+8(FP), SI
	MOVQ dim+16(FP), DX
	BYTE $0x55                                 // pushq	%rbp
	WORD $0x8948; BYTE $0xe5                   // movq	%rsp, %rbp
	LONG $0xf8e48348                           // andq	$-8, %rsp
	LONG $0x10ec8348                           // subq	$16, %rsp
	LONG $0x0b2444c6; BYTE $0x03               // movb	$3, 11(%rsp)
	LONG $0x7879e2c4; WORD $0x2444; BYTE $0x0b // vpbroadcastb	11(%rsp), %xmm0
	WORD $0x8548; BYTE $0xd2                   // testq	%rdx, %rdx
	JLE  LBB2_1
	LONG $0xc0c78148; WORD $0x0000; BYTE $0x00 // addq	$192, %rdi
	LONG $0xc957f0c5                           // vxorps	%xmm1, %xmm1, %xmm1
	WORD $0xc031                               // xorl	%eax, %eax

LBB2_4:
	LONG $0x166ffac5                           // vmovdqu	(%rsi), %xmm2
	LONG $0x90f8e1c4; WORD $0x104e             // kmovq	16(%rsi), %k1
	LONG $0xd8dbe9c5                           // vpand	%xmm0, %xmm2, %xmm3
	LONG $0xd271d9c5; BYTE $0x02               // vpsrlw	$2, %xmm2, %xmm4
	LONG $0xe0dbd9c5                           // vpand	%xmm0, %xmm4, %xmm4
	LONG $0xd271d1c5; BYTE $0x04               // vpsrlw	$4, %xmm2, %xmm5
	LONG $0xe8dbd1c5                           // vpand	%xmm0, %xmm5, %xmm5
	LONG $0xd271e9c5; BYTE $0x06               // vpsrlw	$6, %xmm2, %xmm2
	LONG $0xd0dbe9c5                           // vpand	%xmm0, %xmm2, %xmm2
	LONG $0x487df262; WORD $0xdb31             // vpmovzxbd	%xmm3, %zmm3            # zmm3 = xmm3[0],zero,zero,zero,xmm3[1],zero,zero,zero,xmm3[2],zero,zero,zero,xmm3[3],zero,zero,zero,xmm3[4],zero,zero,zero,xmm3[5],zero,zero,zero,xmm3[6],zero,zero,zero,xmm3[7],zero,zero,zero,xmm3[8],zero,zero,zero,xmm3[9],zero,zero,zero,xmm3[10],zero,zero,zero,xmm3[11],zero,zero,zero,xmm3[12],zero,zero,zero,xmm3[13],zero,zero,zero,xmm3[14],zero,zero,zero,xmm3[15],zero,zero,zero
	LONG $0x487cf162; WORD $0xdb5b             // vcvtdq2ps	%zmm3, %zmm3
	QUAD $0xfd875c594864f162                   // vmulps	-192(%rdi,%rax,4), %zmm3, %zmm3
	LONG $0x4874f162; WORD $0xcb58             // vaddps	%zmm3, %zmm1, %zmm1
	LONG $0x487df262; WORD $0xdc31             // vpmovzxbd	%xmm4, %zmm3            # zmm3 = xmm4[0],zero,zero,zero,xmm4[1],zero,zero,zero,xmm4[2],zero,zero,zero,xmm4[3],zero,zero,zero,xmm4[4],zero,zero,zero,xmm4[5],zero,zero,zero,xmm4[6],zero,zero,zero,xmm4[7],zero,zero,zero,xmm4[8],zero,zero,zero,xmm4[9],zero,zero,zero,xmm4[10],zero,zero,zero,xmm4[11],zero,zero,zero,xmm4[12],zero,zero,zero,xmm4[13],zero,zero,zero,xmm4[14],zero,zero,zero,xmm4[15],zero,zero,zero
	LONG $0x487cf162; WORD $0xdb5b             // vcvtdq2ps	%zmm3, %zmm3
	QUAD $0xfe875c594864f162                   // vmulps	-128(%rdi,%rax,4), %zmm3, %zmm3
	LONG $0x487df262; WORD $0xe531             // vpmovzxbd	%xmm5, %zmm4            # zmm4 = xmm5[0],zero,zero,zero,xmm5[1],zero,zero,zero,xmm5[2],zero,zero,zero,xmm5[3],zero,zero,zero,xmm5[4],zero,zero,zero,xmm5[5],zero,zero,zero,xmm5[6],zero,zero,zero,xmm5[7],zero,zero,zero,xmm5[8],zero,zero,zero,xmm5[9],zero,zero,zero,xmm5[10],zero,zero,zero,xmm5[11],zero,zero,zero,xmm5[12],zero,zero,zero,xmm5[13],zero,zero,zero,xmm5[14],zero,zero,zero,xmm5[15],zero,zero,zero
	LONG $0x487cf162; WORD $0xe45b             // vcvtdq2ps	%zmm4, %zmm4
	QUAD $0xff876459485cf162                   // vmulps	-64(%rdi,%rax,4), %zmm4, %zmm4
	LONG $0x4874f162; WORD $0xcb58             // vaddps	%zmm3, %zmm1, %zmm1
	LONG $0x485cf162; WORD $0xc958             // vaddps	%zmm1, %zmm4, %zmm1
	LONG $0x487df262; WORD $0xd231             // vpmovzxbd	%xmm2, %zmm2            # zmm2 = xmm2[0],zero,zero,zero,xmm2[1],zero,zero,zero,xmm2[2],zero,zero,zero,xmm2[3],zero,zero,zero,xmm2[4],zero,zero,zero,xmm2[5],zero,zero,zero,xmm2[6],zero,zero,zero,xmm2[7],zero,zero,zero,xmm2[8],zero,zero,zero,xmm2[9],zero,zero,zero,xmm2[10],zero,zero,zero,xmm2[11],zero,zero,zero,xmm2[12],zero,zero,zero,xmm2[13],zero,zero,zero,xmm2[14],zero,zero,zero,xmm2[15],zero,zero,zero
	LONG $0x487cf162; WORD $0xd25b             // vcvtdq2ps	%zmm2, %zmm2
	LONG $0x486cf162; WORD $0x1459; BYTE $0x87 // vmulps	(%rdi,%rax,4), %zmm2, %zmm2
	LONG $0x486cf162; WORD $0xc958             // vaddps	%zmm1, %zmm2, %zmm1
	QUAD $0x408000000c2444c7                   // movl	$1082130432, 12(%rsp)           # imm = 0x40800000
	QUAD $0x03245418487df262                   // vbroadcastss	12(%rsp), %zmm2
	QUAD $0xfd875c10c97cf162                   // vmovups	-192(%rdi,%rax,4), %zmm3 {%k1} {z}
	LONG $0x4864f162; WORD $0xda59             // vmulps	%zmm2, %zmm3, %zmm3
	LONG $0x4874f162; WORD $0xcb58             // vaddps	%zmm3, %zmm1, %zmm1
	LONG $0x3179e3c4; WORD $0x10d1             // kshiftrd	$16, %k1, %k2
	QUAD $0xfe875c10ca7cf162                   // vmovups	-128(%rdi,%rax,4), %zmm3 {%k2} {z}
	LONG $0x486cf162; WORD $0xdb59             // vmulps	%zmm3, %zmm2, %zmm3
	LONG $0x4864f162; WORD $0xc958             // vaddps	%zmm1, %zmm3, %zmm1
	LONG $0x31f9e3c4; WORD $0x20d1             // kshiftrq	$32, %k1, %k2
	QUAD $0xff875c10ca7cf162                   // vmovups	-64(%rdi,%rax,4), %zmm3 {%k2} {z}
	LONG $0x486cf162; WORD $0xdb59             // vmulps	%zmm3, %zmm2, %zmm3
	LONG $0x4864f162; WORD $0xc958             // vaddps	%zmm1, %zmm3, %zmm1
	LONG $0x31f9e3c4; WORD $0x30c9             // kshiftrq	$48, %k1, %k1
	LONG $0xc97cf162; WORD $0x1c10; BYTE $0x87 // vmovups	(%rdi,%rax,4), %zmm3 {%k1} {z}
	LONG $0x486cf162; WORD $0xd359             // vmulps	%zmm3, %zmm2, %zmm2
	LONG $0x486cf162; WORD $0xc958             // vaddps	%zmm1, %zmm2, %zmm1
	LONG $0x40c08348                           // addq	$64, %rax
	LONG $0x18c68348                           // addq	$24, %rsi
	WORD $0x3948; BYTE $0xd0                   // cmpq	%rdx, %rax
	JL   LBB2_4
	JMP  LBB2_2

LBB2_1:
	LONG $0xc957f0c5 // vxorps	%xmm1, %xmm1, %xmm1

LBB2_2:
	LONG  $0x48fdf362; WORD $0xc81b; BYTE $0x01 // vextractf64x4	$1, %zmm1, %ymm0
	LONG  $0x4874f162; WORD $0xc058             // vaddps	%zmm0, %zmm1, %zmm0
	LONG  $0x197de3c4; WORD $0x01c1             // vextractf128	$1, %ymm0, %xmm1
	LONG  $0xc158f8c5                           // vaddps	%xmm1, %xmm0, %xmm0
	LONG  $0xc8c6f9c5; BYTE $0x01               // vshufpd	$1, %xmm0, %xmm0, %xmm1         # xmm1 = xmm0[1,0]
	LONG  $0xc158f8c5                           // vaddps	%xmm1, %xmm0, %xmm0
	LONG  $0xc816fac5                           // vmovshdup	%xmm0, %xmm1            # xmm1 = xmm0[1,1,3,3]
	LONG  $0xc158fac5                           // vaddss	%xmm1, %xmm0, %xmm0
	WORD  $0x8948; BYTE $0xec                   // movq	%rbp, %rsp
	BYTE  $0x5d                                 // popq	%rbp
	WORD  $0xf8c5; BYTE $0x77                   // vzeroupper
	MOVSS X0, result+24(FP)
	RET

TEXT ·ip16_fxu4_avx512(SB), $8-28
	MOVQ query+0(FP), DI
	MOVQ compact_code+8(FP), SI
	MOVQ dim+16(FP), DX
	BYTE $0x55                             // pushq	%rbp
	WORD $0x8948; BYTE $0xe5               // movq	%rsp, %rbp
	LONG $0xf0e48348                       // andq	$-16, %rsp
	LONG $0x20ec8348                       // subq	$32, %rsp
	QUAD $0x0f0f0f0f0f0fb848; WORD $0x0f0f // movabsq	$1085102592571150095, %rax      # imm = 0xF0F0F0F0F0F0F0F
	LONG $0x24448948; BYTE $0x08           // movq	%rax, 8(%rsp)
	LONG $0xc057f8c5                       // vxorps	%xmm0, %xmm0, %xmm0
	WORD $0x8548; BYTE $0xd2               // testq	%rdx, %rdx
	JLE  LBB3_3
	WORD $0xc031                           // xorl	%eax, %eax

LBB3_2:
	WORD $0x8b48; BYTE $0x0e                   // movq	(%rsi), %rcx
	LONG $0x24448b4c; BYTE $0x08               // movq	8(%rsp), %r8
	WORD $0x2149; BYTE $0xc8                   // andq	%rcx, %r8
	LONG $0x04f9c148                           // sarq	$4, %rcx
	LONG $0x244c2348; BYTE $0x08               // andq	8(%rsp), %rcx
	LONG $0x2444894c; BYTE $0x10               // movq	%r8, 16(%rsp)
	LONG $0x244c8948; BYTE $0x18               // movq	%rcx, 24(%rsp)
	QUAD $0x01244c21487df262                   // vpmovsxbd	16(%rsp), %zmm1
	LONG $0x487cf162; WORD $0xc95b             // vcvtdq2ps	%zmm1, %zmm1
	LONG $0x4874f162; WORD $0x0c59; BYTE $0x87 // vmulps	(%rdi,%rax,4), %zmm1, %zmm1
	LONG $0x487cf162; WORD $0xc158             // vaddps	%zmm1, %zmm0, %zmm0
	LONG $0x08c68348                           // addq	$8, %rsi
	LONG $0x10c08348                           // addq	$16, %rax
	WORD $0x3948; BYTE $0xd0                   // cmpq	%rdx, %rax
	JL   LBB3_2

LBB3_3:
	LONG  $0x48fdf362; WORD $0xc11b; BYTE $0x01 // vextractf64x4	$1, %zmm0, %ymm1
	LONG  $0x487cf162; WORD $0xc158             // vaddps	%zmm1, %zmm0, %zmm0
	LONG  $0x197de3c4; WORD $0x01c1             // vextractf128	$1, %ymm0, %xmm1
	LONG  $0xc158f8c5                           // vaddps	%xmm1, %xmm0, %xmm0
	LONG  $0xc8c6f9c5; BYTE $0x01               // vshufpd	$1, %xmm0, %xmm0, %xmm1         # xmm1 = xmm0[1,0]
	LONG  $0xc158f8c5                           // vaddps	%xmm1, %xmm0, %xmm0
	LONG  $0xc816fac5                           // vmovshdup	%xmm0, %xmm1            # xmm1 = xmm0[1,1,3,3]
	LONG  $0xc158fac5                           // vaddss	%xmm1, %xmm0, %xmm0
	WORD  $0x8948; BYTE $0xec                   // movq	%rbp, %rsp
	BYTE  $0x5d                                 // popq	%rbp
	WORD  $0xf8c5; BYTE $0x77                   // vzeroupper
	MOVSS X0, result+24(FP)
	RET

TEXT ·ip64_fxu5_avx512(SB), $8-28
	MOVQ query+0(FP), DI
	MOVQ compact_code+8(FP), SI
	MOVQ dim+16(FP), DX
	BYTE $0x55                                 // pushq	%rbp
	WORD $0x8948; BYTE $0xe5                   // movq	%rsp, %rbp
	LONG $0xf8e48348                           // andq	$-8, %rsp
	LONG $0x10ec8348                           // subq	$16, %rsp
	LONG $0x0b2444c6; BYTE $0x0f               // movb	$15, 11(%rsp)
	LONG $0x7879e2c4; WORD $0x2444; BYTE $0x0b // vpbroadcastb	11(%rsp), %xmm0
	WORD $0x8548; BYTE $0xd2                   // testq	%rdx, %rdx
	JLE  LBB4_1
	LONG $0xc0c78148; WORD $0x0000; BYTE $0x00 // addq	$192, %rdi
	LONG $0xc957f0c5                           // vxorps	%xmm1, %xmm1, %xmm1
	WORD $0xc031                               // xorl	%eax, %eax

LBB4_4:
	LONG $0x166ffac5                           // vmovdqu	(%rsi), %xmm2
	LONG $0x5e6ffac5; BYTE $0x10               // vmovdqu	16(%rsi), %xmm3
	LONG $0x90f8e1c4; WORD $0x204e             // kmovq	32(%rsi), %k1
	LONG $0xe0dbe9c5                           // vpand	%xmm0, %xmm2, %xmm4
	LONG $0xd271e9c5; BYTE $0x04               // vpsrlw	$4, %xmm2, %xmm2
	LONG $0xd0dbe9c5                           // vpand	%xmm0, %xmm2, %xmm2
	LONG $0xe8dbe1c5                           // vpand	%xmm0, %xmm3, %xmm5
	LONG $0xd371e1c5; BYTE $0x04               // vpsrlw	$4, %xmm3, %xmm3
	LONG $0xd8dbe1c5                           // vpand	%xmm0, %xmm3, %xmm3
	LONG $0x487df262; WORD $0xe431             // vpmovzxbd	%xmm4, %zmm4            # zmm4 = xmm4[0],zero,zero,zero,xmm4[1],zero,zero,zero,xmm4[2],zero,zero,zero,xmm4[3],zero,zero,zero,xmm4[4],zero,zero,zero,xmm4[5],zero,zero,zero,xmm4[6],zero,zero,zero,xmm4[7],zero,zero,zero,xmm4[8],zero,zero,zero,xmm4[9],zero,zero,zero,xmm4[10],zero,zero,zero,xmm4[11],zero,zero,zero,xmm4[12],zero,zero,zero,xmm4[13],zero,zero,zero,xmm4[14],zero,zero,zero,xmm4[15],zero,zero,zero
	LONG $0x487cf162; WORD $0xe45b             // vcvtdq2ps	%zmm4, %zmm4
	QUAD $0xfd876459485cf162                   // vmulps	-192(%rdi,%rax,4), %zmm4, %zmm4
	LONG $0x4874f162; WORD $0xcc58             // vaddps	%zmm4, %zmm1, %zmm1
	LONG $0x487df262; WORD $0xd231             // vpmovzxbd	%xmm2, %zmm2            # zmm2 = xmm2[0],zero,zero,zero,xmm2[1],zero,zero,zero,xmm2[2],zero,zero,zero,xmm2[3],zero,zero,zero,xmm2[4],zero,zero,zero,xmm2[5],zero,zero,zero,xmm2[6],zero,zero,zero,xmm2[7],zero,zero,zero,xmm2[8],zero,zero,zero,xmm2[9],zero,zero,zero,xmm2[10],zero,zero,zero,xmm2[11],zero,zero,zero,xmm2[12],zero,zero,zero,xmm2[13],zero,zero,zero,xmm2[14],zero,zero,zero,xmm2[15],zero,zero,zero
	LONG $0x487cf162; WORD $0xd25b             // vcvtdq2ps	%zmm2, %zmm2
	QUAD $0xfe875459486cf162                   // vmulps	-128(%rdi,%rax,4), %zmm2, %zmm2
	LONG $0x487df262; WORD $0xe531             // vpmovzxbd	%xmm5, %zmm4            # zmm4 = xmm5[0],zero,zero,zero,xmm5[1],zero,zero,zero,xmm5[2],zero,zero,zero,xmm5[3],zero,zero,zero,xmm5[4],zero,zero,zero,xmm5[5],zero,zero,zero,xmm5[6],zero,zero,zero,xmm5[7],zero,zero,zero,xmm5[8],zero,zero,zero,xmm5[9],zero,zero,zero,xmm5[10],zero,zero,zero,xmm5[11],zero,zero,zero,xmm5[12],zero,zero,zero,xmm5[13],zero,zero,zero,xmm5[14],zero,zero,zero,xmm5[15],zero,zero,zero
	LONG $0x487cf162; WORD $0xe45b             // vcvtdq2ps	%zmm4, %zmm4
	QUAD $0xff876459485cf162                   // vmulps	-64(%rdi,%rax,4), %zmm4, %zmm4
	LONG $0x4874f162; WORD $0xca58             // vaddps	%zmm2, %zmm1, %zmm1
	LONG $0x485cf162; WORD $0xc958             // vaddps	%zmm1, %zmm4, %zmm1
	LONG $0x487df262; WORD $0xd331             // vpmovzxbd	%xmm3, %zmm2            # zmm2 = xmm3[0],zero,zero,zero,xmm3[1],zero,zero,zero,xmm3[2],zero,zero,zero,xmm3[3],zero,zero,zero,xmm3[4],zero,zero,zero,xmm3[5],zero,zero,zero,xmm3[6],zero,zero,zero,xmm3[7],zero,zero,zero,xmm3[8],zero,zero,zero,xmm3[9],zero,zero,zero,xmm3[10],zero,zero,zero,xmm3[11],zero,zero,zero,xmm3[12],zero,zero,zero,xmm3[13],zero,zero,zero,xmm3[14],zero,zero,zero,xmm3[15],zero,zero,zero
	LONG $0x487cf162; WORD $0xd25b             // vcvtdq2ps	%zmm2, %zmm2
	LONG $0x486cf162; WORD $0x1459; BYTE $0x87 // vmulps	(%rdi,%rax,4), %zmm2, %zmm2
	LONG $0x486cf162; WORD $0xc958             // vaddps	%zmm1, %zmm2, %zmm1
	QUAD $0x418000000c2444c7                   // movl	$1098907648, 12(%rsp)           # imm = 0x41800000
	QUAD $0x03245418487df262                   // vbroadcastss	12(%rsp), %zmm2
	QUAD $0xfd875c10c97cf162                   // vmovups	-192(%rdi,%rax,4), %zmm3 {%k1} {z}
	LONG $0x4864f162; WORD $0xda59             // vmulps	%zmm2, %zmm3, %zmm3
	LONG $0x4874f162; WORD $0xcb58             // vaddps	%zmm3, %zmm1, %zmm1
	LONG $0x3179e3c4; WORD $0x10d1             // kshiftrd	$16, %k1, %k2
	QUAD $0xfe875c10ca7cf162                   // vmovups	-128(%rdi,%rax,4), %zmm3 {%k2} {z}
	LONG $0x486cf162; WORD $0xdb59             // vmulps	%zmm3, %zmm2, %zmm3
	LONG $0x4864f162; WORD $0xc958             // vaddps	%zmm1, %zmm3, %zmm1
	LONG $0x31f9e3c4; WORD $0x20d1             // kshiftrq	$32, %k1, %k2
	QUAD $0xff875c10ca7cf162                   // vmovups	-64(%rdi,%rax,4), %zmm3 {%k2} {z}
	LONG $0x486cf162; WORD $0xdb59             // vmulps	%zmm3, %zmm2, %zmm3
	LONG $0x4864f162; WORD $0xc958             // vaddps	%zmm1, %zmm3, %zmm1
	LONG $0x31f9e3c4; WORD $0x30c9             // kshiftrq	$48, %k1, %k1
	LONG $0xc97cf162; WORD $0x1c10; BYTE $0x87 // vmovups	(%rdi,%rax,4), %zmm3 {%k1} {z}
	LONG $0x486cf162; WORD $0xd359             // vmulps	%zmm3, %zmm2, %zmm2
	LONG $0x486cf162; WORD $0xc958             // vaddps	%zmm1, %zmm2, %zmm1
	LONG $0x40c08348                           // addq	$64, %rax
	LONG $0x28c68348                           // addq	$40, %rsi
	WORD $0x3948; BYTE $0xd0                   // cmpq	%rdx, %rax
	JL   LBB4_4
	JMP  LBB4_2

LBB4_1:
	LONG $0xc957f0c5 // vxorps	%xmm1, %xmm1, %xmm1

LBB4_2:
	LONG  $0x48fdf362; WORD $0xc81b; BYTE $0x01 // vextractf64x4	$1, %zmm1, %ymm0
	LONG  $0x4874f162; WORD $0xc058             // vaddps	%zmm0, %zmm1, %zmm0
	LONG  $0x197de3c4; WORD $0x01c1             // vextractf128	$1, %ymm0, %xmm1
	LONG  $0xc158f8c5                           // vaddps	%xmm1, %xmm0, %xmm0
	LONG  $0xc8c6f9c5; BYTE $0x01               // vshufpd	$1, %xmm0, %xmm0, %xmm1         # xmm1 = xmm0[1,0]
	LONG  $0xc158f8c5                           // vaddps	%xmm1, %xmm0, %xmm0
	LONG  $0xc816fac5                           // vmovshdup	%xmm0, %xmm1            # xmm1 = xmm0[1,1,3,3]
	LONG  $0xc158fac5                           // vaddss	%xmm1, %xmm0, %xmm0
	WORD  $0x8948; BYTE $0xec                   // movq	%rbp, %rsp
	BYTE  $0x5d                                 // popq	%rbp
	WORD  $0xf8c5; BYTE $0x77                   // vzeroupper
	MOVSS X0, result+24(FP)
	RET

TEXT ·ip64_fxu6_avx512(SB), $8-28
	MOVQ query+0(FP), DI
	MOVQ compact_code+8(FP), SI
	MOVQ dim+16(FP), DX
	BYTE $0x55                                 // pushq	%rbp
	WORD $0x8948; BYTE $0xe5                   // movq	%rsp, %rbp
	LONG $0xf8e48348                           // andq	$-8, %rsp
	LONG $0x10ec8348                           // subq	$16, %rsp
	LONG $0x0f2444c6; BYTE $0x3f               // movb	$63, 15(%rsp)
	LONG $0x0e2444c6; BYTE $0xc0               // movb	$-64, 14(%rsp)
	LONG $0x7879e2c4; WORD $0x2444; BYTE $0x0f // vpbroadcastb	15(%rsp), %xmm0
	LONG $0x7879e2c4; WORD $0x244c; BYTE $0x0e // vpbroadcastb	14(%rsp), %xmm1
	LONG $0xd257e8c5                           // vxorps	%xmm2, %xmm2, %xmm2
	WORD $0x8548; BYTE $0xd2                   // testq	%rdx, %rdx
	JLE  LBB5_3
	WORD $0xc031                               // xorl	%eax, %eax

LBB5_2:
	LONG $0x1e6ffac5                           // vmovdqu	(%rsi), %xmm3
	LONG $0x666ffac5; BYTE $0x10               // vmovdqu	16(%rsi), %xmm4
	LONG $0x6e6ffac5; BYTE $0x20               // vmovdqu	32(%rsi), %xmm5
	LONG $0xf0dbe1c5                           // vpand	%xmm0, %xmm3, %xmm6
	LONG $0xf8dbd9c5                           // vpand	%xmm0, %xmm4, %xmm7
	LONG $0xc0db51c5                           // vpand	%xmm0, %xmm5, %xmm8
	LONG $0xd9dbe1c5                           // vpand	%xmm1, %xmm3, %xmm3
	LONG $0xd371e1c5; BYTE $0x06               // vpsrlw	$6, %xmm3, %xmm3
	LONG $0xe1dbd9c5                           // vpand	%xmm1, %xmm4, %xmm4
	LONG $0xd471d9c5; BYTE $0x04               // vpsrlw	$4, %xmm4, %xmm4
	LONG $0xdbebd9c5                           // vpor	%xmm3, %xmm4, %xmm3
	LONG $0xe1dbd1c5                           // vpand	%xmm1, %xmm5, %xmm4
	LONG $0xd471d9c5; BYTE $0x02               // vpsrlw	$2, %xmm4, %xmm4
	LONG $0x487df262; WORD $0xee31             // vpmovzxbd	%xmm6, %zmm5            # zmm5 = xmm6[0],zero,zero,zero,xmm6[1],zero,zero,zero,xmm6[2],zero,zero,zero,xmm6[3],zero,zero,zero,xmm6[4],zero,zero,zero,xmm6[5],zero,zero,zero,xmm6[6],zero,zero,zero,xmm6[7],zero,zero,zero,xmm6[8],zero,zero,zero,xmm6[9],zero,zero,zero,xmm6[10],zero,zero,zero,xmm6[11],zero,zero,zero,xmm6[12],zero,zero,zero,xmm6[13],zero,zero,zero,xmm6[14],zero,zero,zero,xmm6[15],zero,zero,zero
	LONG $0x487cf162; WORD $0xed5b             // vcvtdq2ps	%zmm5, %zmm5
	LONG $0x4854f162; WORD $0x2c59; BYTE $0x87 // vmulps	(%rdi,%rax,4), %zmm5, %zmm5
	LONG $0xdcebe1c5                           // vpor	%xmm4, %xmm3, %xmm3
	LONG $0x486cf162; WORD $0xd558             // vaddps	%zmm5, %zmm2, %zmm2
	LONG $0x487df262; WORD $0xe731             // vpmovzxbd	%xmm7, %zmm4            # zmm4 = xmm7[0],zero,zero,zero,xmm7[1],zero,zero,zero,xmm7[2],zero,zero,zero,xmm7[3],zero,zero,zero,xmm7[4],zero,zero,zero,xmm7[5],zero,zero,zero,xmm7[6],zero,zero,zero,xmm7[7],zero,zero,zero,xmm7[8],zero,zero,zero,xmm7[9],zero,zero,zero,xmm7[10],zero,zero,zero,xmm7[11],zero,zero,zero,xmm7[12],zero,zero,zero,xmm7[13],zero,zero,zero,xmm7[14],zero,zero,zero,xmm7[15],zero,zero,zero
	LONG $0x487cf162; WORD $0xe45b             // vcvtdq2ps	%zmm4, %zmm4
	QUAD $0x01876459485cf162                   // vmulps	64(%rdi,%rax,4), %zmm4, %zmm4
	LONG $0x486cf162; WORD $0xd458             // vaddps	%zmm4, %zmm2, %zmm2
	LONG $0x487dd262; WORD $0xe031             // vpmovzxbd	%xmm8, %zmm4            # zmm4 = xmm8[0],zero,zero,zero,xmm8[1],zero,zero,zero,xmm8[2],zero,zero,zero,xmm8[3],zero,zero,zero,xmm8[4],zero,zero,zero,xmm8[5],zero,zero,zero,xmm8[6],zero,zero,zero,xmm8[7],zero,zero,zero,xmm8[8],zero,zero,zero,xmm8[9],zero,zero,zero,xmm8[10],zero,zero,zero,xmm8[11],zero,zero,zero,xmm8[12],zero,zero,zero,xmm8[13],zero,zero,zero,xmm8[14],zero,zero,zero,xmm8[15],zero,zero,zero
	LONG $0x487cf162; WORD $0xe45b             // vcvtdq2ps	%zmm4, %zmm4
	QUAD $0x02876459485cf162                   // vmulps	128(%rdi,%rax,4), %zmm4, %zmm4
	LONG $0x486cf162; WORD $0xd458             // vaddps	%zmm4, %zmm2, %zmm2
	LONG $0x487df262; WORD $0xdb31             // vpmovzxbd	%xmm3, %zmm3            # zmm3 = xmm3[0],zero,zero,zero,xmm3[1],zero,zero,zero,xmm3[2],zero,zero,zero,xmm3[3],zero,zero,zero,xmm3[4],zero,zero,zero,xmm3[5],zero,zero,zero,xmm3[6],zero,zero,zero,xmm3[7],zero,zero,zero,xmm3[8],zero,zero,zero,xmm3[9],zero,zero,zero,xmm3[10],zero,zero,zero,xmm3[11],zero,zero,zero,xmm3[12],zero,zero,zero,xmm3[13],zero,zero,zero,xmm3[14],zero,zero,zero,xmm3[15],zero,zero,zero
	LONG $0x487cf162; WORD $0xdb5b             // vcvtdq2ps	%zmm3, %zmm3
	QUAD $0x03875c594864f162                   // vmulps	192(%rdi,%rax,4), %zmm3, %zmm3
	LONG $0x486cf162; WORD $0xd358             // vaddps	%zmm3, %zmm2, %zmm2
	LONG $0x40c08348                           // addq	$64, %rax
	LONG $0x30c68348                           // addq	$48, %rsi
	WORD $0x3948; BYTE $0xd0                   // cmpq	%rdx, %rax
	JL   LBB5_2

LBB5_3:
	LONG  $0x48fdf362; WORD $0xd01b; BYTE $0x01 // vextractf64x4	$1, %zmm2, %ymm0
	LONG  $0x486cf162; WORD $0xc058             // vaddps	%zmm0, %zmm2, %zmm0
	LONG  $0x197de3c4; WORD $0x01c1             // vextractf128	$1, %ymm0, %xmm1
	LONG  $0xc158f8c5                           // vaddps	%xmm1, %xmm0, %xmm0
	LONG  $0xc8c6f9c5; BYTE $0x01               // vshufpd	$1, %xmm0, %xmm0, %xmm1         # xmm1 = xmm0[1,0]
	LONG  $0xc158f8c5                           // vaddps	%xmm1, %xmm0, %xmm0
	LONG  $0xc816fac5                           // vmovshdup	%xmm0, %xmm1            # xmm1 = xmm0[1,1,3,3]
	LONG  $0xc158fac5                           // vaddss	%xmm1, %xmm0, %xmm0
	WORD  $0x8948; BYTE $0xec                   // movq	%rbp, %rsp
	BYTE  $0x5d                                 // popq	%rbp
	WORD  $0xf8c5; BYTE $0x77                   // vzeroupper
	MOVSS X0, result+24(FP)
	RET

TEXT ·ip64_fxu7_avx512(SB), $8-28
	MOVQ query+0(FP), DI
	MOVQ compact_code+8(FP), SI
	MOVQ dim+16(FP), DX
	BYTE $0x55                                 // pushq	%rbp
	WORD $0x8948; BYTE $0xe5                   // movq	%rsp, %rbp
	LONG $0xf8e48348                           // andq	$-8, %rsp
	LONG $0x10ec8348                           // subq	$16, %rsp
	LONG $0x0b2444c6; BYTE $0x3f               // movb	$63, 11(%rsp)
	LONG $0x0a2444c6; BYTE $0xc0               // movb	$-64, 10(%rsp)
	LONG $0x7879e2c4; WORD $0x2444; BYTE $0x0b // vpbroadcastb	11(%rsp), %xmm0
	LONG $0x7879e2c4; WORD $0x244c; BYTE $0x0a // vpbroadcastb	10(%rsp), %xmm1
	WORD $0x8548; BYTE $0xd2                   // testq	%rdx, %rdx
	JLE  LBB6_1
	LONG $0xc0c78148; WORD $0x0000; BYTE $0x00 // addq	$192, %rdi
	LONG $0xd257e8c5                           // vxorps	%xmm2, %xmm2, %xmm2
	WORD $0xc031                               // xorl	%eax, %eax

LBB6_4:
	LONG $0x1e6ffac5                           // vmovdqu	(%rsi), %xmm3
	LONG $0x666ffac5; BYTE $0x10               // vmovdqu	16(%rsi), %xmm4
	LONG $0x6e6ffac5; BYTE $0x20               // vmovdqu	32(%rsi), %xmm5
	LONG $0xf0dbe1c5                           // vpand	%xmm0, %xmm3, %xmm6
	LONG $0xf8dbd9c5                           // vpand	%xmm0, %xmm4, %xmm7
	LONG $0xc0db51c5                           // vpand	%xmm0, %xmm5, %xmm8
	LONG $0xd9dbe1c5                           // vpand	%xmm1, %xmm3, %xmm3
	LONG $0xd371e1c5; BYTE $0x06               // vpsrlw	$6, %xmm3, %xmm3
	LONG $0xe1dbd9c5                           // vpand	%xmm1, %xmm4, %xmm4
	LONG $0xd471d9c5; BYTE $0x04               // vpsrlw	$4, %xmm4, %xmm4
	LONG $0xdbebd9c5                           // vpor	%xmm3, %xmm4, %xmm3
	LONG $0xe1dbd1c5                           // vpand	%xmm1, %xmm5, %xmm4
	LONG $0xd471d9c5; BYTE $0x02               // vpsrlw	$2, %xmm4, %xmm4
	LONG $0xdcebe1c5                           // vpor	%xmm4, %xmm3, %xmm3
	LONG $0x90f8e1c4; WORD $0x304e             // kmovq	48(%rsi), %k1
	LONG $0x487df262; WORD $0xe631             // vpmovzxbd	%xmm6, %zmm4            # zmm4 = xmm6[0],zero,zero,zero,xmm6[1],zero,zero,zero,xmm6[2],zero,zero,zero,xmm6[3],zero,zero,zero,xmm6[4],zero,zero,zero,xmm6[5],zero,zero,zero,xmm6[6],zero,zero,zero,xmm6[7],zero,zero,zero,xmm6[8],zero,zero,zero,xmm6[9],zero,zero,zero,xmm6[10],zero,zero,zero,xmm6[11],zero,zero,zero,xmm6[12],zero,zero,zero,xmm6[13],zero,zero,zero,xmm6[14],zero,zero,zero,xmm6[15],zero,zero,zero
	LONG $0x487cf162; WORD $0xe45b             // vcvtdq2ps	%zmm4, %zmm4
	QUAD $0xfd876459485cf162                   // vmulps	-192(%rdi,%rax,4), %zmm4, %zmm4
	LONG $0x486cf162; WORD $0xd458             // vaddps	%zmm4, %zmm2, %zmm2
	LONG $0x487df262; WORD $0xe731             // vpmovzxbd	%xmm7, %zmm4            # zmm4 = xmm7[0],zero,zero,zero,xmm7[1],zero,zero,zero,xmm7[2],zero,zero,zero,xmm7[3],zero,zero,zero,xmm7[4],zero,zero,zero,xmm7[5],zero,zero,zero,xmm7[6],zero,zero,zero,xmm7[7],zero,zero,zero,xmm7[8],zero,zero,zero,xmm7[9],zero,zero,zero,xmm7[10],zero,zero,zero,xmm7[11],zero,zero,zero,xmm7[12],zero,zero,zero,xmm7[13],zero,zero,zero,xmm7[14],zero,zero,zero,xmm7[15],zero,zero,zero
	LONG $0x487cf162; WORD $0xe45b             // vcvtdq2ps	%zmm4, %zmm4
	QUAD $0xfe876459485cf162                   // vmulps	-128(%rdi,%rax,4), %zmm4, %zmm4
	LONG $0x487dd262; WORD $0xe831             // vpmovzxbd	%xmm8, %zmm5            # zmm5 = xmm8[0],zero,zero,zero,xmm8[1],zero,zero,zero,xmm8[2],zero,zero,zero,xmm8[3],zero,zero,zero,xmm8[4],zero,zero,zero,xmm8[5],zero,zero,zero,xmm8[6],zero,zero,zero,xmm8[7],zero,zero,zero,xmm8[8],zero,zero,zero,xmm8[9],zero,zero,zero,xmm8[10],zero,zero,zero,xmm8[11],zero,zero,zero,xmm8[12],zero,zero,zero,xmm8[13],zero,zero,zero,xmm8[14],zero,zero,zero,xmm8[15],zero,zero,zero
	LONG $0x487cf162; WORD $0xed5b             // vcvtdq2ps	%zmm5, %zmm5
	QUAD $0xff876c594854f162                   // vmulps	-64(%rdi,%rax,4), %zmm5, %zmm5
	LONG $0x486cf162; WORD $0xd458             // vaddps	%zmm4, %zmm2, %zmm2
	LONG $0x486cf162; WORD $0xd558             // vaddps	%zmm5, %zmm2, %zmm2
	LONG $0x487df262; WORD $0xdb31             // vpmovzxbd	%xmm3, %zmm3            # zmm3 = xmm3[0],zero,zero,zero,xmm3[1],zero,zero,zero,xmm3[2],zero,zero,zero,xmm3[3],zero,zero,zero,xmm3[4],zero,zero,zero,xmm3[5],zero,zero,zero,xmm3[6],zero,zero,zero,xmm3[7],zero,zero,zero,xmm3[8],zero,zero,zero,xmm3[9],zero,zero,zero,xmm3[10],zero,zero,zero,xmm3[11],zero,zero,zero,xmm3[12],zero,zero,zero,xmm3[13],zero,zero,zero,xmm3[14],zero,zero,zero,xmm3[15],zero,zero,zero
	LONG $0x487cf162; WORD $0xdb5b             // vcvtdq2ps	%zmm3, %zmm3
	LONG $0x4864f162; WORD $0x1c59; BYTE $0x87 // vmulps	(%rdi,%rax,4), %zmm3, %zmm3
	LONG $0x486cf162; WORD $0xd358             // vaddps	%zmm3, %zmm2, %zmm2
	QUAD $0x428000000c2444c7                   // movl	$1115684864, 12(%rsp)           # imm = 0x42800000
	QUAD $0x03245c18487df262                   // vbroadcastss	12(%rsp), %zmm3
	QUAD $0xfd876410c97cf162                   // vmovups	-192(%rdi,%rax,4), %zmm4 {%k1} {z}
	LONG $0x485cf162; WORD $0xe359             // vmulps	%zmm3, %zmm4, %zmm4
	LONG $0x486cf162; WORD $0xd458             // vaddps	%zmm4, %zmm2, %zmm2
	LONG $0x3179e3c4; WORD $0x10d1             // kshiftrd	$16, %k1, %k2
	QUAD $0xfe876410ca7cf162                   // vmovups	-128(%rdi,%rax,4), %zmm4 {%k2} {z}
	LONG $0x4864f162; WORD $0xe459             // vmulps	%zmm4, %zmm3, %zmm4
	LONG $0x485cf162; WORD $0xd258             // vaddps	%zmm2, %zmm4, %zmm2
	LONG $0x31f9e3c4; WORD $0x20d1             // kshiftrq	$32, %k1, %k2
	QUAD $0xff876410ca7cf162                   // vmovups	-64(%rdi,%rax,4), %zmm4 {%k2} {z}
	LONG $0x4864f162; WORD $0xe459             // vmulps	%zmm4, %zmm3, %zmm4
	LONG $0x485cf162; WORD $0xd258             // vaddps	%zmm2, %zmm4, %zmm2
	LONG $0x31f9e3c4; WORD $0x30c9             // kshiftrq	$48, %k1, %k1
	LONG $0xc97cf162; WORD $0x2410; BYTE $0x87 // vmovups	(%rdi,%rax,4), %zmm4 {%k1} {z}
	LONG $0x4864f162; WORD $0xdc59             // vmulps	%zmm4, %zmm3, %zmm3
	LONG $0x4864f162; WORD $0xd258             // vaddps	%zmm2, %zmm3, %zmm2
	LONG $0x40c08348                           // addq	$64, %rax
	LONG $0x38c68348                           // addq	$56, %rsi
	WORD $0x3948; BYTE $0xd0                   // cmpq	%rdx, %rax
	JL   LBB6_4
	JMP  LBB6_2

LBB6_1:
	LONG $0xd257e8c5 // vxorps	%xmm2, %xmm2, %xmm2

LBB6_2:
	LONG  $0x48fdf362; WORD $0xd01b; BYTE $0x01 // vextractf64x4	$1, %zmm2, %ymm0
	LONG  $0x486cf162; WORD $0xc058             // vaddps	%zmm0, %zmm2, %zmm0
	LONG  $0x197de3c4; WORD $0x01c1             // vextractf128	$1, %ymm0, %xmm1
	LONG  $0xc158f8c5                           // vaddps	%xmm1, %xmm0, %xmm0
	LONG  $0xc8c6f9c5; BYTE $0x01               // vshufpd	$1, %xmm0, %xmm0, %xmm1         # xmm1 = xmm0[1,0]
	LONG  $0xc158f8c5                           // vaddps	%xmm1, %xmm0, %xmm0
	LONG  $0xc816fac5                           // vmovshdup	%xmm0, %xmm1            # xmm1 = xmm0[1,1,3,3]
	LONG  $0xc158fac5                           // vaddss	%xmm1, %xmm0, %xmm0
	WORD  $0x8948; BYTE $0xec                   // movq	%rbp, %rsp
	BYTE  $0x5d                                 // popq	%rbp
	WORD  $0xf8c5; BYTE $0x77                   // vzeroupper
	MOVSS X0, result+24(FP)
	RET

TEXT ·ip16_fxu8_avx512(SB), $8-28
	MOVQ query+0(FP), DI
	MOVQ code+8(FP), SI
	MOVQ dim+16(FP), DX
	WORD $0x8548; BYTE $0xd2 // testq	%rdx, %rdx
	JLE  LBB7_1
	LONG $0xff428d4c         // leaq	-1(%rdx), %r8
	LONG $0x04e8c149         // shrq	$4, %r8
	WORD $0xff49; BYTE $0xc0 // incq	%r8
	WORD $0x8944; BYTE $0xc0 // movl	%r8d, %eax
	WORD $0xe083; BYTE $0x03 // andl	$3, %eax
	LONG $0x31fa8348         // cmpq	$49, %rdx
	JAE  LBB7_10
	LONG $0xc057f8c5         // vxorps	%xmm0, %xmm0, %xmm0
	WORD $0xc931             // xorl	%ecx, %ecx
	WORD $0x8548; BYTE $0xc0 // testq	%rax, %rax
	JNE  LBB7_7
	JMP  LBB7_2

LBB7_1:
	LONG $0xc057f8c5 // vxorps	%xmm0, %xmm0, %xmm0
	JMP  LBB7_2

LBB7_10:
	LONG $0xfce08349 // andq	$-4, %r8
	LONG $0xc057f8c5 // vxorps	%xmm0, %xmm0, %xmm0
	WORD $0xc931     // xorl	%ecx, %ecx

LBB7_11:
	LONG $0x487df262; WORD $0x0c31; BYTE $0x0e // vpmovzxbd	(%rsi,%rcx), %zmm1      # zmm1 = mem[0],zero,zero,zero,mem[1],zero,zero,zero,mem[2],zero,zero,zero,mem[3],zero,zero,zero,mem[4],zero,zero,zero,mem[5],zero,zero,zero,mem[6],zero,zero,zero,mem[7],zero,zero,zero,mem[8],zero,zero,zero,mem[9],zero,zero,zero,mem[10],zero,zero,zero,mem[11],zero,zero,zero,mem[12],zero,zero,zero,mem[13],zero,zero,zero,mem[14],zero,zero,zero,mem[15],zero,zero,zero
	LONG $0x487cf162; WORD $0xc95b             // vcvtdq2ps	%zmm1, %zmm1
	LONG $0x4874f162; WORD $0x0c59; BYTE $0x8f // vmulps	(%rdi,%rcx,4), %zmm1, %zmm1
	QUAD $0x010e5431487df262                   // vpmovzxbd	16(%rsi,%rcx), %zmm2    # zmm2 = mem[0],zero,zero,zero,mem[1],zero,zero,zero,mem[2],zero,zero,zero,mem[3],zero,zero,zero,mem[4],zero,zero,zero,mem[5],zero,zero,zero,mem[6],zero,zero,zero,mem[7],zero,zero,zero,mem[8],zero,zero,zero,mem[9],zero,zero,zero,mem[10],zero,zero,zero,mem[11],zero,zero,zero,mem[12],zero,zero,zero,mem[13],zero,zero,zero,mem[14],zero,zero,zero,mem[15],zero,zero,zero
	LONG $0x487cf162; WORD $0xd25b             // vcvtdq2ps	%zmm2, %zmm2
	QUAD $0x018f5459486cf162                   // vmulps	64(%rdi,%rcx,4), %zmm2, %zmm2
	LONG $0x487cf162; WORD $0xc158             // vaddps	%zmm1, %zmm0, %zmm0
	QUAD $0x020e4c31487df262                   // vpmovzxbd	32(%rsi,%rcx), %zmm1    # zmm1 = mem[0],zero,zero,zero,mem[1],zero,zero,zero,mem[2],zero,zero,zero,mem[3],zero,zero,zero,mem[4],zero,zero,zero,mem[5],zero,zero,zero,mem[6],zero,zero,zero,mem[7],zero,zero,zero,mem[8],zero,zero,zero,mem[9],zero,zero,zero,mem[10],zero,zero,zero,mem[11],zero,zero,zero,mem[12],zero,zero,zero,mem[13],zero,zero,zero,mem[14],zero,zero,zero,mem[15],zero,zero,zero
	LONG $0x487cf162; WORD $0xc95b             // vcvtdq2ps	%zmm1, %zmm1
	QUAD $0x028f4c594874f162                   // vmulps	128(%rdi,%rcx,4), %zmm1, %zmm1
	QUAD $0x030e5c31487df262                   // vpmovzxbd	48(%rsi,%rcx), %zmm3    # zmm3 = mem[0],zero,zero,zero,mem[1],zero,zero,zero,mem[2],zero,zero,zero,mem[3],zero,zero,zero,mem[4],zero,zero,zero,mem[5],zero,zero,zero,mem[6],zero,zero,zero,mem[7],zero,zero,zero,mem[8],zero,zero,zero,mem[9],zero,zero,zero,mem[10],zero,zero,zero,mem[11],zero,zero,zero,mem[12],zero,zero,zero,mem[13],zero,zero,zero,mem[14],zero,zero,zero,mem[15],zero,zero,zero
	LONG $0x487cf162; WORD $0xc258             // vaddps	%zmm2, %zmm0, %zmm0
	LONG $0x487cf162; WORD $0xd35b             // vcvtdq2ps	%zmm3, %zmm2
	QUAD $0x038f5459486cf162                   // vmulps	192(%rdi,%rcx,4), %zmm2, %zmm2
	LONG $0x487cf162; WORD $0xc158             // vaddps	%zmm1, %zmm0, %zmm0
	LONG $0x487cf162; WORD $0xc258             // vaddps	%zmm2, %zmm0, %zmm0
	LONG $0x40c18348                           // addq	$64, %rcx
	LONG $0xfcc08349                           // addq	$-4, %r8
	JNE  LBB7_11
	WORD $0x0148; BYTE $0xce                   // addq	%rcx, %rsi
	WORD $0x8548; BYTE $0xc0                   // testq	%rax, %rax
	JE   LBB7_2

LBB7_7:
	BYTE $0x55               // pushq	%rbp
	WORD $0x8948; BYTE $0xe5 // movq	%rsp, %rbp
	LONG $0xf8e48348         // andq	$-8, %rsp
	LONG $0x8f0c8d48         // leaq	(%rdi,%rcx,4), %rcx
	WORD $0xe0c1; BYTE $0x04 // shll	$4, %eax
	WORD $0xd231             // xorl	%edx, %edx

LBB7_8:
	LONG $0x487df262; WORD $0x0c31; BYTE $0x16 // vpmovzxbd	(%rsi,%rdx), %zmm1      # zmm1 = mem[0],zero,zero,zero,mem[1],zero,zero,zero,mem[2],zero,zero,zero,mem[3],zero,zero,zero,mem[4],zero,zero,zero,mem[5],zero,zero,zero,mem[6],zero,zero,zero,mem[7],zero,zero,zero,mem[8],zero,zero,zero,mem[9],zero,zero,zero,mem[10],zero,zero,zero,mem[11],zero,zero,zero,mem[12],zero,zero,zero,mem[13],zero,zero,zero,mem[14],zero,zero,zero,mem[15],zero,zero,zero
	LONG $0x487cf162; WORD $0xc95b             // vcvtdq2ps	%zmm1, %zmm1
	LONG $0x4874f162; WORD $0x0c59; BYTE $0x91 // vmulps	(%rcx,%rdx,4), %zmm1, %zmm1
	LONG $0x487cf162; WORD $0xc158             // vaddps	%zmm1, %zmm0, %zmm0
	LONG $0x10c28348                           // addq	$16, %rdx
	WORD $0x3948; BYTE $0xd0                   // cmpq	%rdx, %rax
	JNE  LBB7_8
	WORD $0x8948; BYTE $0xec                   // movq	%rbp, %rsp
	BYTE $0x5d                                 // popq	%rbp

LBB7_2:
	LONG  $0x48fdf362; WORD $0xc11b; BYTE $0x01 // vextractf64x4	$1, %zmm0, %ymm1
	LONG  $0x487cf162; WORD $0xc158             // vaddps	%zmm1, %zmm0, %zmm0
	LONG  $0x197de3c4; WORD $0x01c1             // vextractf128	$1, %ymm0, %xmm1
	LONG  $0xc158f8c5                           // vaddps	%xmm1, %xmm0, %xmm0
	LONG  $0xc8c6f9c5; BYTE $0x01               // vshufpd	$1, %xmm0, %xmm0, %xmm1         # xmm1 = xmm0[1,0]
	LONG  $0xc158f8c5                           // vaddps	%xmm1, %xmm0, %xmm0
	LONG  $0xc816fac5                           // vmovshdup	%xmm0, %xmm1            # xmm1 = xmm0[1,1,3,3]
	LONG  $0xc158fac5                           // vaddss	%xmm1, %xmm0, %xmm0
	WORD  $0xf8c5; BYTE $0x77                   // vzeroupper
	MOVSS X0, result+24(FP)
	RET
