//go:build !noasm && amd64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8 (6ubuntu1)
// 	objdump 2.46
// flags: -mavx2 -O3
// source: src/space_avx2.c

package simd

import "unsafe"

//go:noescape
func scalar_quantize_uint8_avx2(result, data unsafe.Pointer, dimension int64, lo, delta float32)

//go:noescape
func scalar_quantize_uint16_avx2(result, data unsafe.Pointer, dimension int64, lo, delta float32)

//go:noescape
func new_transpose_bin_avx2(data, result unsafe.Pointer, padded_dimension, bits int64)

//go:noescape
func new_transpose_bin_512_avx2(data, result unsafe.Pointer, padded_dimension, bits int64)

//go:noescape
func mask_ip_x0_q_avx2(query, data unsafe.Pointer, padded_dimension int64) (result float32)
