//go:build !noasm && riscv64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8 (6ubuntu1)
// 	objdump 2.46
// flags: -march=rv64imafdv -isystem /usr/lib/llvm-21/lib/clang/21/include -O3
// source: src/space_excode_rvv.c

package simd

import "unsafe"

//go:noescape
func ip16_fxu1_rvv(query, code unsafe.Pointer, dim int64) (result float32)

//go:noescape
func ip64_fxu2_rvv(query, code unsafe.Pointer, dim int64) (result float32)

//go:noescape
func ip64_fxu3_rvv(query, code unsafe.Pointer, dim int64) (result float32)

//go:noescape
func ip16_fxu4_rvv(query, code unsafe.Pointer, dim int64) (result float32)

//go:noescape
func ip64_fxu5_rvv(query, code unsafe.Pointer, dim int64) (result float32)

//go:noescape
func ip64_fxu6_rvv(query, code unsafe.Pointer, dim int64) (result float32)

//go:noescape
func ip64_fxu7_rvv(query, code unsafe.Pointer, dim int64) (result float32)

//go:noescape
func ip16_fxu8_rvv(query, code unsafe.Pointer, dim int64) (result float32)
