//go:build !noasm && loong64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8 (6ubuntu1)
// 	objdump 2.46
// flags: -mlasx -isystem /usr/lib/llvm-21/lib/clang/21/include -fno-vectorize -fno-slp-vectorize -O3
// source: src/space_excode_lasx.c

package simd

import "unsafe"

//go:noescape
func ip16_fxu1_lasx(query, compact_code unsafe.Pointer, dim int64) (result float32)

//go:noescape
func ip64_fxu2_lasx(query, compact_code unsafe.Pointer, dim int64) (result float32)

//go:noescape
func ip64_fxu3_lasx(query, compact_code unsafe.Pointer, dim int64) (result float32)

//go:noescape
func ip16_fxu4_lasx(query, compact_code unsafe.Pointer, dim int64) (result float32)

//go:noescape
func ip64_fxu5_lasx(query, compact_code unsafe.Pointer, dim int64) (result float32)

//go:noescape
func ip64_fxu6_lasx(query, compact_code unsafe.Pointer, dim int64) (result float32)

//go:noescape
func ip64_fxu7_lasx(query, compact_code unsafe.Pointer, dim int64) (result float32)

//go:noescape
func ip16_fxu8_lasx(query, code unsafe.Pointer, dim int64) (result float32)
