//go:build !noasm && riscv64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8 (6ubuntu1)
// 	objdump 2.46
// flags: -march=rv64imafdv -O3
// source: src/warmup_rvv.c

package simd

import "unsafe"

//go:noescape
func warmup_ip_x0_q_512_rvv(data, query unsafe.Pointer, delta, vl_factor float32, padded_dimension, query_bits int64) (result float32)
