coverage:
  status:
    project:
      default:
        threshold: 0.5%
    patch: off

ignore:
  - "pkg/snowball/**"
  - "internal/db/sqlengine/antlr/sql_lexer.go"
  - "internal/db/sqlengine/antlr/sql_parser.go"
  - "internal/proto/**"
