//go:build !noasm && riscv64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8 (6ubuntu1)
// 	objdump 2.46
// flags: -march=rv64imafdv -isystem /usr/lib/llvm-21/lib/clang/21/include -O3
// source: src/distance_batch_fp32_rvv.c

package mathbatch

import "unsafe"

//go:noescape
func xvec_rvv_batch_inner_products2(query, first, second unsafe.Pointer, size int64, first_output, second_output unsafe.Pointer)

//go:noescape
func xvec_rvv_batch_inner_products4(query, first, second, third, fourth unsafe.Pointer, size int64, first_output, second_output, third_output, fourth_output unsafe.Pointer)

//go:noescape
func xvec_rvv_batch_squared_euclidean_distances2(query, first, second unsafe.Pointer, size int64, first_output, second_output unsafe.Pointer)

//go:noescape
func xvec_rvv_batch_squared_euclidean_distances4(query, first, second, third, fourth unsafe.Pointer, size int64, first_output, second_output, third_output, fourth_output unsafe.Pointer)
