//go:build !noasm && arm64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8 (6ubuntu1)
// 	objdump 2.46
// flags: -O3
// source: src/distance_batch_fp32_neon.c

TEXT ·xvec_neon_batch_inner_products2(SB), $0-48
	MOVD query+0(FP), R0
	MOVD first+8(FP), R1
	MOVD second+16(FP), R2
	MOVD size+24(FP), R3
	MOVD first_output+32(FP), R4
	MOVD second_output+40(FP), R5
	WORD $0x91000c68              // add	x8, x3, #3
	WORD $0xf100007f              // cmp	x3, #0
	WORD $0x6f00e400              // movi	v0.2d, #0000000000000000
	WORD $0x9a83b109              // csel	x9, x8, x3, lt
	WORD $0xf100107f              // cmp	x3, #4
	WORD $0x927ef528              // and	x8, x9, #0xfffffffffffffffc
	WORD $0xcb080068              // sub	x8, x3, x8
	BLT  LBB0_4
	WORD $0x6f00e401              // movi	v1.2d, #0000000000000000
	WORD $0x9342fd29              // asr	x9, x9, #2
	WORD $0xaa0003eb              // mov	x11, x0
	WORD $0xaa0103ec              // mov	x12, x1
	WORD $0xaa0203ed              // mov	x13, x2
	WORD $0xaa0903ea              // mov	x10, x9

LBB0_2:
	WORD $0x3cc10562 // ldr	q2, [x11], #16
	WORD $0xf100054a // subs	x10, x10, #1
	WORD $0x3cc10583 // ldr	q3, [x12], #16
	WORD $0x3cc105a4 // ldr	q4, [x13], #16
	WORD $0x4e22cc61 // fmla	v1.4s, v3.4s, v2.4s
	WORD $0x4e22cc80 // fmla	v0.4s, v4.4s, v2.4s
	BNE  LBB0_2
	WORD $0xd37ced29 // lsl	x9, x9, #4
	WORD $0x8b090000 // add	x0, x0, x9
	WORD $0x8b090021 // add	x1, x1, x9
	WORD $0x8b090042 // add	x2, x2, x9
	B    LBB0_5

LBB0_4:
	WORD $0x6f00e401 // movi	v1.2d, #0000000000000000

LBB0_5:
	WORD $0x6e21d421 // faddp	v1.4s, v1.4s, v1.4s
	WORD $0x6e20d400 // faddp	v0.4s, v0.4s, v0.4s
	WORD $0xf100011f // cmp	x8, #0
	WORD $0x7e30d821 // faddp	s1, v1.2s
	WORD $0x7e30d800 // faddp	s0, v0.2s
	WORD $0xbd000081 // str	s1, [x4]
	WORD $0xbd0000a0 // str	s0, [x5]
	BLE  LBB0_8
	WORD $0xbd400000 // ldr	s0, [x0]
	WORD $0xbd400021 // ldr	s1, [x1]
	WORD $0xf100051f // cmp	x8, #1
	WORD $0xbd400082 // ldr	s2, [x4]
	WORD $0x1f010800 // fmadd	s0, s0, s1, s2
	WORD $0xbd000080 // str	s0, [x4]
	WORD $0xbd400000 // ldr	s0, [x0]
	WORD $0xbd400041 // ldr	s1, [x2]
	WORD $0xbd4000a2 // ldr	s2, [x5]
	WORD $0x1f010800 // fmadd	s0, s0, s1, s2
	WORD $0xbd0000a0 // str	s0, [x5]
	BEQ  LBB0_8
	WORD $0xbd400400 // ldr	s0, [x0, #4]
	WORD $0xbd400421 // ldr	s1, [x1, #4]
	WORD $0xf100091f // cmp	x8, #2
	WORD $0xbd400082 // ldr	s2, [x4]
	WORD $0x1f010800 // fmadd	s0, s0, s1, s2
	WORD $0xbd000080 // str	s0, [x4]
	WORD $0xbd400400 // ldr	s0, [x0, #4]
	WORD $0xbd400441 // ldr	s1, [x2, #4]
	WORD $0xbd4000a2 // ldr	s2, [x5]
	WORD $0x1f010800 // fmadd	s0, s0, s1, s2
	WORD $0xbd0000a0 // str	s0, [x5]
	BNE  LBB0_9

LBB0_8:
	RET

LBB0_9:
	WORD $0xbd400800 // ldr	s0, [x0, #8]
	WORD $0xbd400821 // ldr	s1, [x1, #8]
	WORD $0xbd400082 // ldr	s2, [x4]
	WORD $0x1f010800 // fmadd	s0, s0, s1, s2
	WORD $0xbd000080 // str	s0, [x4]
	WORD $0xbd400800 // ldr	s0, [x0, #8]
	WORD $0xbd400841 // ldr	s1, [x2, #8]
	WORD $0xbd4000a2 // ldr	s2, [x5]
	WORD $0x1f010800 // fmadd	s0, s0, s1, s2
	WORD $0xbd0000a0 // str	s0, [x5]
	RET

TEXT ·xvec_neon_batch_inner_products4(SB), $16-80
	MOVD query+0(FP), R0
	MOVD first+8(FP), R1
	MOVD second+16(FP), R2
	MOVD third+24(FP), R3
	MOVD fourth+32(FP), R4
	MOVD size+40(FP), R5
	MOVD first_output+48(FP), R6
	MOVD second_output+56(FP), R7
	MOVD third_output+64(FP), R8
	MOVD R8, 0(RSP)
	MOVD fourth_output+72(FP), R8
	MOVD R8, 8(RSP)
	WORD $0x91000ca8              // add	x8, x5, #3
	WORD $0xf10000bf              // cmp	x5, #0
	WORD $0x6f00e400              // movi	v0.2d, #0000000000000000
	WORD $0x9a85b10b              // csel	x11, x8, x5, lt
	WORD $0xa94023e9              // ldp	x9, x8, [sp]
	WORD $0x927ef56a              // and	x10, x11, #0xfffffffffffffffc
	WORD $0xf10010bf              // cmp	x5, #4
	WORD $0xcb0a00aa              // sub	x10, x5, x10
	BLT  LBB1_4
	WORD $0x6f00e402              // movi	v2.2d, #0000000000000000
	WORD $0x6f00e403              // movi	v3.2d, #0000000000000000
	WORD $0x9342fd6b              // asr	x11, x11, #2
	WORD $0x6f00e401              // movi	v1.2d, #0000000000000000
	WORD $0xaa0003ed              // mov	x13, x0
	WORD $0xaa0103ee              // mov	x14, x1
	WORD $0xaa0b03ec              // mov	x12, x11
	WORD $0xaa0203ef              // mov	x15, x2
	WORD $0xaa0303f0              // mov	x16, x3
	WORD $0xaa0403f1              // mov	x17, x4

LBB1_2:
	WORD $0x3cc105a4 // ldr	q4, [x13], #16
	WORD $0xf100058c // subs	x12, x12, #1
	WORD $0x3cc105c5 // ldr	q5, [x14], #16
	WORD $0x3cc105e6 // ldr	q6, [x15], #16
	WORD $0x3cc10607 // ldr	q7, [x16], #16
	WORD $0x4e24cca2 // fmla	v2.4s, v5.4s, v4.4s
	WORD $0x3cc10630 // ldr	q16, [x17], #16
	WORD $0x4e24ccc3 // fmla	v3.4s, v6.4s, v4.4s
	WORD $0x4e24cce1 // fmla	v1.4s, v7.4s, v4.4s
	WORD $0x4e24ce00 // fmla	v0.4s, v16.4s, v4.4s
	BNE  LBB1_2
	WORD $0xd37ced6b // lsl	x11, x11, #4
	WORD $0x8b0b0000 // add	x0, x0, x11
	WORD $0x8b0b0021 // add	x1, x1, x11
	WORD $0x8b0b0042 // add	x2, x2, x11
	WORD $0x8b0b0063 // add	x3, x3, x11
	WORD $0x8b0b0084 // add	x4, x4, x11
	B    LBB1_5

LBB1_4:
	WORD $0x6f00e401 // movi	v1.2d, #0000000000000000
	WORD $0x6f00e403 // movi	v3.2d, #0000000000000000
	WORD $0x6f00e402 // movi	v2.2d, #0000000000000000

LBB1_5:
	WORD $0x6e22d442 // faddp	v2.4s, v2.4s, v2.4s
	WORD $0x6e23d463 // faddp	v3.4s, v3.4s, v3.4s
	WORD $0xf100015f // cmp	x10, #0
	WORD $0x6e21d421 // faddp	v1.4s, v1.4s, v1.4s
	WORD $0x6e20d400 // faddp	v0.4s, v0.4s, v0.4s
	WORD $0x7e30d842 // faddp	s2, v2.2s
	WORD $0x7e30d863 // faddp	s3, v3.2s
	WORD $0x7e30d821 // faddp	s1, v1.2s
	WORD $0x7e30d800 // faddp	s0, v0.2s
	WORD $0xbd0000c2 // str	s2, [x6]
	WORD $0xbd0000e3 // str	s3, [x7]
	WORD $0xbd000121 // str	s1, [x9]
	WORD $0xbd000100 // str	s0, [x8]
	BLE  LBB1_8
	WORD $0xbd400000 // ldr	s0, [x0]
	WORD $0xbd400021 // ldr	s1, [x1]
	WORD $0xf100055f // cmp	x10, #1
	WORD $0xbd4000c2 // ldr	s2, [x6]
	WORD $0x1f010800 // fmadd	s0, s0, s1, s2
	WORD $0xbd0000c0 // str	s0, [x6]
	WORD $0xbd400000 // ldr	s0, [x0]
	WORD $0xbd400041 // ldr	s1, [x2]
	WORD $0xbd4000e2 // ldr	s2, [x7]
	WORD $0x1f010800 // fmadd	s0, s0, s1, s2
	WORD $0xbd0000e0 // str	s0, [x7]
	WORD $0xbd400000 // ldr	s0, [x0]
	WORD $0xbd400061 // ldr	s1, [x3]
	WORD $0xbd400122 // ldr	s2, [x9]
	WORD $0x1f010800 // fmadd	s0, s0, s1, s2
	WORD $0xbd000120 // str	s0, [x9]
	WORD $0xbd400000 // ldr	s0, [x0]
	WORD $0xbd400081 // ldr	s1, [x4]
	WORD $0xbd400102 // ldr	s2, [x8]
	WORD $0x1f010800 // fmadd	s0, s0, s1, s2
	WORD $0xbd000100 // str	s0, [x8]
	BEQ  LBB1_8
	WORD $0xbd400400 // ldr	s0, [x0, #4]
	WORD $0xbd400421 // ldr	s1, [x1, #4]
	WORD $0xf100095f // cmp	x10, #2
	WORD $0xbd4000c2 // ldr	s2, [x6]
	WORD $0x1f010800 // fmadd	s0, s0, s1, s2
	WORD $0xbd0000c0 // str	s0, [x6]
	WORD $0xbd400400 // ldr	s0, [x0, #4]
	WORD $0xbd400441 // ldr	s1, [x2, #4]
	WORD $0xbd4000e2 // ldr	s2, [x7]
	WORD $0x1f010800 // fmadd	s0, s0, s1, s2
	WORD $0xbd0000e0 // str	s0, [x7]
	WORD $0xbd400400 // ldr	s0, [x0, #4]
	WORD $0xbd400461 // ldr	s1, [x3, #4]
	WORD $0xbd400122 // ldr	s2, [x9]
	WORD $0x1f010800 // fmadd	s0, s0, s1, s2
	WORD $0xbd000120 // str	s0, [x9]
	WORD $0xbd400400 // ldr	s0, [x0, #4]
	WORD $0xbd400481 // ldr	s1, [x4, #4]
	WORD $0xbd400102 // ldr	s2, [x8]
	WORD $0x1f010800 // fmadd	s0, s0, s1, s2
	WORD $0xbd000100 // str	s0, [x8]
	BNE  LBB1_9

LBB1_8:
	RET

LBB1_9:
	WORD $0xbd400800 // ldr	s0, [x0, #8]
	WORD $0xbd400821 // ldr	s1, [x1, #8]
	WORD $0xbd4000c2 // ldr	s2, [x6]
	WORD $0x1f010800 // fmadd	s0, s0, s1, s2
	WORD $0xbd0000c0 // str	s0, [x6]
	WORD $0xbd400800 // ldr	s0, [x0, #8]
	WORD $0xbd400841 // ldr	s1, [x2, #8]
	WORD $0xbd4000e2 // ldr	s2, [x7]
	WORD $0x1f010800 // fmadd	s0, s0, s1, s2
	WORD $0xbd0000e0 // str	s0, [x7]
	WORD $0xbd400800 // ldr	s0, [x0, #8]
	WORD $0xbd400861 // ldr	s1, [x3, #8]
	WORD $0xbd400122 // ldr	s2, [x9]
	WORD $0x1f010800 // fmadd	s0, s0, s1, s2
	WORD $0xbd000120 // str	s0, [x9]
	WORD $0xbd400800 // ldr	s0, [x0, #8]
	WORD $0xbd400881 // ldr	s1, [x4, #8]
	WORD $0xbd400102 // ldr	s2, [x8]
	WORD $0x1f010800 // fmadd	s0, s0, s1, s2
	WORD $0xbd000100 // str	s0, [x8]
	RET

TEXT ·xvec_neon_batch_squared_euclidean_distances2(SB), $0-48
	MOVD query+0(FP), R0
	MOVD first+8(FP), R1
	MOVD second+16(FP), R2
	MOVD size+24(FP), R3
	MOVD first_output+32(FP), R4
	MOVD second_output+40(FP), R5
	WORD $0x91000c68              // add	x8, x3, #3
	WORD $0xf100007f              // cmp	x3, #0
	WORD $0x6f00e400              // movi	v0.2d, #0000000000000000
	WORD $0x9a83b109              // csel	x9, x8, x3, lt
	WORD $0xf100107f              // cmp	x3, #4
	WORD $0x927ef528              // and	x8, x9, #0xfffffffffffffffc
	WORD $0xcb080068              // sub	x8, x3, x8
	BLT  LBB2_4
	WORD $0x6f00e401              // movi	v1.2d, #0000000000000000
	WORD $0x9342fd29              // asr	x9, x9, #2
	WORD $0xaa0003eb              // mov	x11, x0
	WORD $0xaa0103ec              // mov	x12, x1
	WORD $0xaa0203ed              // mov	x13, x2
	WORD $0xaa0903ea              // mov	x10, x9

LBB2_2:
	WORD $0x3cc10562 // ldr	q2, [x11], #16
	WORD $0xf100054a // subs	x10, x10, #1
	WORD $0x3cc10583 // ldr	q3, [x12], #16
	WORD $0x3cc105a4 // ldr	q4, [x13], #16
	WORD $0x4ea3d443 // fsub	v3.4s, v2.4s, v3.4s
	WORD $0x4ea4d442 // fsub	v2.4s, v2.4s, v4.4s
	WORD $0x4e23cc61 // fmla	v1.4s, v3.4s, v3.4s
	WORD $0x4e22cc40 // fmla	v0.4s, v2.4s, v2.4s
	BNE  LBB2_2
	WORD $0xd37ced29 // lsl	x9, x9, #4
	WORD $0x8b090000 // add	x0, x0, x9
	WORD $0x8b090021 // add	x1, x1, x9
	WORD $0x8b090042 // add	x2, x2, x9
	B    LBB2_5

LBB2_4:
	WORD $0x6f00e401 // movi	v1.2d, #0000000000000000

LBB2_5:
	WORD $0x6e21d421 // faddp	v1.4s, v1.4s, v1.4s
	WORD $0x6e20d400 // faddp	v0.4s, v0.4s, v0.4s
	WORD $0xf100011f // cmp	x8, #0
	WORD $0x7e30d821 // faddp	s1, v1.2s
	WORD $0x7e30d800 // faddp	s0, v0.2s
	WORD $0xbd000081 // str	s1, [x4]
	WORD $0xbd0000a0 // str	s0, [x5]
	BLE  LBB2_8
	WORD $0xbd400000 // ldr	s0, [x0]
	WORD $0xbd400021 // ldr	s1, [x1]
	WORD $0xf100051f // cmp	x8, #1
	WORD $0xbd400082 // ldr	s2, [x4]
	WORD $0x1e213801 // fsub	s1, s0, s1
	WORD $0x1f010821 // fmadd	s1, s1, s1, s2
	WORD $0xbd400042 // ldr	s2, [x2]
	WORD $0x1e223800 // fsub	s0, s0, s2
	WORD $0xbd000081 // str	s1, [x4]
	WORD $0xbd4000a1 // ldr	s1, [x5]
	WORD $0x1f000400 // fmadd	s0, s0, s0, s1
	WORD $0xbd0000a0 // str	s0, [x5]
	BEQ  LBB2_8
	WORD $0xbd400400 // ldr	s0, [x0, #4]
	WORD $0xbd400421 // ldr	s1, [x1, #4]
	WORD $0xf100091f // cmp	x8, #2
	WORD $0xbd400082 // ldr	s2, [x4]
	WORD $0x1e213801 // fsub	s1, s0, s1
	WORD $0x1f010821 // fmadd	s1, s1, s1, s2
	WORD $0xbd400442 // ldr	s2, [x2, #4]
	WORD $0x1e223800 // fsub	s0, s0, s2
	WORD $0xbd000081 // str	s1, [x4]
	WORD $0xbd4000a1 // ldr	s1, [x5]
	WORD $0x1f000400 // fmadd	s0, s0, s0, s1
	WORD $0xbd0000a0 // str	s0, [x5]
	BNE  LBB2_9

LBB2_8:
	RET

LBB2_9:
	WORD $0xbd400800 // ldr	s0, [x0, #8]
	WORD $0xbd400821 // ldr	s1, [x1, #8]
	WORD $0xbd400082 // ldr	s2, [x4]
	WORD $0x1e213801 // fsub	s1, s0, s1
	WORD $0x1f010821 // fmadd	s1, s1, s1, s2
	WORD $0xbd400842 // ldr	s2, [x2, #8]
	WORD $0x1e223800 // fsub	s0, s0, s2
	WORD $0xbd000081 // str	s1, [x4]
	WORD $0xbd4000a1 // ldr	s1, [x5]
	WORD $0x1f000400 // fmadd	s0, s0, s0, s1
	WORD $0xbd0000a0 // str	s0, [x5]
	RET

TEXT ·xvec_neon_batch_squared_euclidean_distances4(SB), $16-80
	MOVD query+0(FP), R0
	MOVD first+8(FP), R1
	MOVD second+16(FP), R2
	MOVD third+24(FP), R3
	MOVD fourth+32(FP), R4
	MOVD size+40(FP), R5
	MOVD first_output+48(FP), R6
	MOVD second_output+56(FP), R7
	MOVD third_output+64(FP), R8
	MOVD R8, 0(RSP)
	MOVD fourth_output+72(FP), R8
	MOVD R8, 8(RSP)
	WORD $0x91000ca8              // add	x8, x5, #3
	WORD $0xf10000bf              // cmp	x5, #0
	WORD $0x6f00e400              // movi	v0.2d, #0000000000000000
	WORD $0x9a85b10b              // csel	x11, x8, x5, lt
	WORD $0xa94023e9              // ldp	x9, x8, [sp]
	WORD $0x927ef56a              // and	x10, x11, #0xfffffffffffffffc
	WORD $0xf10010bf              // cmp	x5, #4
	WORD $0xcb0a00aa              // sub	x10, x5, x10
	BLT  LBB3_4
	WORD $0x6f00e402              // movi	v2.2d, #0000000000000000
	WORD $0x6f00e403              // movi	v3.2d, #0000000000000000
	WORD $0x9342fd6b              // asr	x11, x11, #2
	WORD $0x6f00e401              // movi	v1.2d, #0000000000000000
	WORD $0xaa0003ed              // mov	x13, x0
	WORD $0xaa0103ee              // mov	x14, x1
	WORD $0xaa0b03ec              // mov	x12, x11
	WORD $0xaa0203ef              // mov	x15, x2
	WORD $0xaa0303f0              // mov	x16, x3
	WORD $0xaa0403f1              // mov	x17, x4

LBB3_2:
	WORD $0x3cc105a4 // ldr	q4, [x13], #16
	WORD $0xf100058c // subs	x12, x12, #1
	WORD $0x3cc105c5 // ldr	q5, [x14], #16
	WORD $0x3cc105e6 // ldr	q6, [x15], #16
	WORD $0x3cc10607 // ldr	q7, [x16], #16
	WORD $0x4ea5d485 // fsub	v5.4s, v4.4s, v5.4s
	WORD $0x3cc10630 // ldr	q16, [x17], #16
	WORD $0x4ea6d486 // fsub	v6.4s, v4.4s, v6.4s
	WORD $0x4ea7d487 // fsub	v7.4s, v4.4s, v7.4s
	WORD $0x4eb0d484 // fsub	v4.4s, v4.4s, v16.4s
	WORD $0x4e25cca2 // fmla	v2.4s, v5.4s, v5.4s
	WORD $0x4e26ccc3 // fmla	v3.4s, v6.4s, v6.4s
	WORD $0x4e27cce1 // fmla	v1.4s, v7.4s, v7.4s
	WORD $0x4e24cc80 // fmla	v0.4s, v4.4s, v4.4s
	BNE  LBB3_2
	WORD $0xd37ced6b // lsl	x11, x11, #4
	WORD $0x8b0b0000 // add	x0, x0, x11
	WORD $0x8b0b0021 // add	x1, x1, x11
	WORD $0x8b0b0042 // add	x2, x2, x11
	WORD $0x8b0b0063 // add	x3, x3, x11
	WORD $0x8b0b0084 // add	x4, x4, x11
	B    LBB3_5

LBB3_4:
	WORD $0x6f00e401 // movi	v1.2d, #0000000000000000
	WORD $0x6f00e403 // movi	v3.2d, #0000000000000000
	WORD $0x6f00e402 // movi	v2.2d, #0000000000000000

LBB3_5:
	WORD $0x6e22d442 // faddp	v2.4s, v2.4s, v2.4s
	WORD $0x6e23d463 // faddp	v3.4s, v3.4s, v3.4s
	WORD $0xf100015f // cmp	x10, #0
	WORD $0x6e21d421 // faddp	v1.4s, v1.4s, v1.4s
	WORD $0x6e20d400 // faddp	v0.4s, v0.4s, v0.4s
	WORD $0x7e30d842 // faddp	s2, v2.2s
	WORD $0x7e30d863 // faddp	s3, v3.2s
	WORD $0x7e30d821 // faddp	s1, v1.2s
	WORD $0x7e30d800 // faddp	s0, v0.2s
	WORD $0xbd0000c2 // str	s2, [x6]
	WORD $0xbd0000e3 // str	s3, [x7]
	WORD $0xbd000121 // str	s1, [x9]
	WORD $0xbd000100 // str	s0, [x8]
	BLE  LBB3_8
	WORD $0xbd400000 // ldr	s0, [x0]
	WORD $0xbd400021 // ldr	s1, [x1]
	WORD $0xf100055f // cmp	x10, #1
	WORD $0xbd4000c2 // ldr	s2, [x6]
	WORD $0xbd400063 // ldr	s3, [x3]
	WORD $0xbd400084 // ldr	s4, [x4]
	WORD $0x1e213801 // fsub	s1, s0, s1
	WORD $0x1f010821 // fmadd	s1, s1, s1, s2
	WORD $0xbd400042 // ldr	s2, [x2]
	WORD $0x1e223802 // fsub	s2, s0, s2
	WORD $0xbd0000c1 // str	s1, [x6]
	WORD $0xbd4000e1 // ldr	s1, [x7]
	WORD $0x1f020441 // fmadd	s1, s2, s2, s1
	WORD $0x1e233802 // fsub	s2, s0, s3
	WORD $0x1e243800 // fsub	s0, s0, s4
	WORD $0xbd0000e1 // str	s1, [x7]
	WORD $0xbd400121 // ldr	s1, [x9]
	WORD $0x1f020441 // fmadd	s1, s2, s2, s1
	WORD $0xbd000121 // str	s1, [x9]
	WORD $0xbd400101 // ldr	s1, [x8]
	WORD $0x1f000400 // fmadd	s0, s0, s0, s1
	WORD $0xbd000100 // str	s0, [x8]
	BEQ  LBB3_8
	WORD $0xbd400400 // ldr	s0, [x0, #4]
	WORD $0xbd400421 // ldr	s1, [x1, #4]
	WORD $0xf100095f // cmp	x10, #2
	WORD $0xbd4000c2 // ldr	s2, [x6]
	WORD $0xbd400463 // ldr	s3, [x3, #4]
	WORD $0xbd400484 // ldr	s4, [x4, #4]
	WORD $0x1e213801 // fsub	s1, s0, s1
	WORD $0x1f010821 // fmadd	s1, s1, s1, s2
	WORD $0xbd400442 // ldr	s2, [x2, #4]
	WORD $0x1e223802 // fsub	s2, s0, s2
	WORD $0xbd0000c1 // str	s1, [x6]
	WORD $0xbd4000e1 // ldr	s1, [x7]
	WORD $0x1f020441 // fmadd	s1, s2, s2, s1
	WORD $0x1e233802 // fsub	s2, s0, s3
	WORD $0x1e243800 // fsub	s0, s0, s4
	WORD $0xbd0000e1 // str	s1, [x7]
	WORD $0xbd400121 // ldr	s1, [x9]
	WORD $0x1f020441 // fmadd	s1, s2, s2, s1
	WORD $0xbd000121 // str	s1, [x9]
	WORD $0xbd400101 // ldr	s1, [x8]
	WORD $0x1f000400 // fmadd	s0, s0, s0, s1
	WORD $0xbd000100 // str	s0, [x8]
	BNE  LBB3_9

LBB3_8:
	RET

LBB3_9:
	WORD $0xbd400800 // ldr	s0, [x0, #8]
	WORD $0xbd400821 // ldr	s1, [x1, #8]
	WORD $0xbd4000c2 // ldr	s2, [x6]
	WORD $0xbd400863 // ldr	s3, [x3, #8]
	WORD $0xbd400884 // ldr	s4, [x4, #8]
	WORD $0x1e213801 // fsub	s1, s0, s1
	WORD $0x1f010821 // fmadd	s1, s1, s1, s2
	WORD $0xbd400842 // ldr	s2, [x2, #8]
	WORD $0x1e223802 // fsub	s2, s0, s2
	WORD $0xbd0000c1 // str	s1, [x6]
	WORD $0xbd4000e1 // ldr	s1, [x7]
	WORD $0x1f020441 // fmadd	s1, s2, s2, s1
	WORD $0x1e233802 // fsub	s2, s0, s3
	WORD $0x1e243800 // fsub	s0, s0, s4
	WORD $0xbd0000e1 // str	s1, [x7]
	WORD $0xbd400121 // ldr	s1, [x9]
	WORD $0x1f020441 // fmadd	s1, s2, s2, s1
	WORD $0xbd000121 // str	s1, [x9]
	WORD $0xbd400101 // ldr	s1, [x8]
	WORD $0x1f000400 // fmadd	s0, s0, s0, s1
	WORD $0xbd000100 // str	s0, [x8]
	RET
