//go:build !noasm && loong64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8 (6ubuntu1)
// 	objdump 2.46
// flags: -mlasx -O3
// source: src/distance_batch_fp32_lasx.c

TEXT ·xvec_lasx_batch_inner_products2(SB), $0-48
	MOVV query+0(FP), R4
	MOVV first+8(FP), R5
	MOVV second+16(FP), R6
	MOVV size+24(FP), R7
	MOVV first_output+32(FP), R8
	MOVV second_output+40(FP), R9
	WORD $0x02ff8063              // addi.d	$sp, $sp, -32
	WORD $0x0049fcea              // srai.d	$a6, $a3, 63
	WORD $0x0045f54a              // srli.d	$a6, $a6, 61
	WORD $0x0010a8eb              // add.d	$a7, $a3, $a6
	WORD $0x0015016a              // move	$a6, $a7
	WORD $0x0082000a              // bstrins.d	$a6, $zero, 2, 0
	WORD $0x0011a8ea              // sub.d	$a6, $a3, $a6
	WORD $0x0380200c              // ori	$t0, $zero, 8
	WORD $0x77e00000              // xvldi	$xr0, 0
	BLT  R7, R12, LBB0_3
	WORD $0x00490d67              // srai.d	$a3, $a7, 3
	WORD $0x77d40001              // xvori.b	$xr1, $xr0, 0

LBB0_2:
	WORD $0x2c800082    // xvld	$xr2, $a0, 0
	WORD $0x2c8000a3    // xvld	$xr3, $a1, 0
	WORD $0x2c8000c4    // xvld	$xr4, $a2, 0
	WORD $0x75388c43    // xvfmul.s	$xr3, $xr2, $xr3
	WORD $0x75308c21    // xvfadd.s	$xr1, $xr1, $xr3
	WORD $0x75389042    // xvfmul.s	$xr2, $xr2, $xr4
	WORD $0x75308800    // xvfadd.s	$xr0, $xr0, $xr2
	WORD $0x02c08084    // addi.d	$a0, $a0, 32
	WORD $0x02c080a5    // addi.d	$a1, $a1, 32
	WORD $0x02fffce7    // addi.d	$a3, $a3, -1
	WORD $0x02c080c6    // addi.d	$a2, $a2, 32
	BNE  R7, R0, LBB0_2
	JMP  LBB0_4

LBB0_3:
	WORD $0x77d40001 // xvori.b	$xr1, $xr0, 0

LBB0_4:
	WORD $0x02c00067     // addi.d	$a3, $sp, 0
	WORD $0x2cc000e1     // xvst	$xr1, $a3, 0
	WORD $0x2b000061     // fld.s	$fa1, $sp, 0
	WORD $0x0114a402     // movgr2fr.w	$fa2, $zero
	WORD $0x2b001063     // fld.s	$fa3, $sp, 4
	WORD $0x2b002064     // fld.s	$fa4, $sp, 8
	WORD $0x2b003065     // fld.s	$fa5, $sp, 12
	WORD $0x01008821     // fadd.s	$fa1, $fa1, $fa2
	WORD $0x01008c21     // fadd.s	$fa1, $fa1, $fa3
	WORD $0x01009021     // fadd.s	$fa1, $fa1, $fa4
	WORD $0x01009421     // fadd.s	$fa1, $fa1, $fa5
	WORD $0x2b004063     // fld.s	$fa3, $sp, 16
	WORD $0x2b005064     // fld.s	$fa4, $sp, 20
	WORD $0x2b006065     // fld.s	$fa5, $sp, 24
	WORD $0x2b007066     // fld.s	$fa6, $sp, 28
	WORD $0x01008c21     // fadd.s	$fa1, $fa1, $fa3
	WORD $0x01009021     // fadd.s	$fa1, $fa1, $fa4
	WORD $0x01009421     // fadd.s	$fa1, $fa1, $fa5
	WORD $0x01009821     // fadd.s	$fa1, $fa1, $fa6
	WORD $0x2b400101     // fst.s	$fa1, $a4, 0
	WORD $0x2cc000e0     // xvst	$xr0, $a3, 0
	WORD $0x2b000060     // fld.s	$fa0, $sp, 0
	WORD $0x2b001061     // fld.s	$fa1, $sp, 4
	WORD $0x2b002063     // fld.s	$fa3, $sp, 8
	WORD $0x2b003064     // fld.s	$fa4, $sp, 12
	WORD $0x01008800     // fadd.s	$fa0, $fa0, $fa2
	WORD $0x01008400     // fadd.s	$fa0, $fa0, $fa1
	WORD $0x01008c00     // fadd.s	$fa0, $fa0, $fa3
	WORD $0x01009000     // fadd.s	$fa0, $fa0, $fa4
	WORD $0x2b004061     // fld.s	$fa1, $sp, 16
	WORD $0x2b005062     // fld.s	$fa2, $sp, 20
	WORD $0x2b006063     // fld.s	$fa3, $sp, 24
	WORD $0x2b007064     // fld.s	$fa4, $sp, 28
	WORD $0x01008400     // fadd.s	$fa0, $fa0, $fa1
	WORD $0x01008800     // fadd.s	$fa0, $fa0, $fa2
	WORD $0x01008c00     // fadd.s	$fa0, $fa0, $fa3
	WORD $0x01009000     // fadd.s	$fa0, $fa0, $fa4
	WORD $0x03800407     // ori	$a3, $zero, 1
	WORD $0x2b400120     // fst.s	$fa0, $a5, 0
	BLT  R10, R7, LBB0_6

LBB0_5:
	WORD $0x2b000080     // fld.s	$fa0, $a0, 0
	WORD $0x2b0000a1     // fld.s	$fa1, $a1, 0
	WORD $0x2b000102     // fld.s	$fa2, $a4, 0
	WORD $0x08110400     // fmadd.s	$fa0, $fa0, $fa1, $fa2
	WORD $0x2b400100     // fst.s	$fa0, $a4, 0
	WORD $0x2b000080     // fld.s	$fa0, $a0, 0
	WORD $0x2b0000c1     // fld.s	$fa1, $a2, 0
	WORD $0x2b000122     // fld.s	$fa2, $a5, 0
	WORD $0x08110400     // fmadd.s	$fa0, $fa0, $fa1, $fa2
	WORD $0x2b400120     // fst.s	$fa0, $a5, 0
	WORD $0x02fffd4a     // addi.d	$a6, $a6, -1
	WORD $0x02c010c6     // addi.d	$a2, $a2, 4
	WORD $0x02c010a5     // addi.d	$a1, $a1, 4
	WORD $0x02c01084     // addi.d	$a0, $a0, 4
	BNE  R10, R0, LBB0_5

LBB0_6:
	WORD $0x02c08063 // addi.d	$sp, $sp, 32
	RET

TEXT ·xvec_lasx_batch_inner_products4(SB), $0-80
	MOVV query+0(FP), R4
	MOVV first+8(FP), R5
	MOVV second+16(FP), R6
	MOVV third+24(FP), R7
	MOVV fourth+32(FP), R8
	MOVV size+40(FP), R9
	MOVV first_output+48(FP), R10
	MOVV second_output+56(FP), R11
	MOVV third_output+64(FP), R12
	ADDV $-16, R3
	MOVV R12, (0)(R3)
	ADDV $16, R3
	MOVV fourth_output+72(FP), R12
	ADDV $-16, R3
	MOVV R12, (8)(R3)
	WORD $0x02ff8063               // addi.d	$sp, $sp, -32
	WORD $0x28c0a06c               // ld.d	$t0, $sp, 40
	WORD $0x0049fd2d               // srai.d	$t1, $a5, 63
	WORD $0x0045f5ad               // srli.d	$t1, $t1, 61
	WORD $0x0010b52f               // add.d	$t3, $a5, $t1
	WORD $0x28c0806d               // ld.d	$t1, $sp, 32
	WORD $0x001501ee               // move	$t2, $t3
	WORD $0x0082000e               // bstrins.d	$t2, $zero, 2, 0
	WORD $0x0011b92e               // sub.d	$t2, $a5, $t2
	WORD $0x03802010               // ori	$t4, $zero, 8
	WORD $0x77e00000               // xvldi	$xr0, 0
	BLT  R9, R16, LBB1_3
	WORD $0x00490de9               // srai.d	$a5, $t3, 3
	WORD $0x77d40001               // xvori.b	$xr1, $xr0, 0
	WORD $0x77d40002               // xvori.b	$xr2, $xr0, 0
	WORD $0x77d40003               // xvori.b	$xr3, $xr0, 0

LBB1_2:
	WORD $0x2c800084    // xvld	$xr4, $a0, 0
	WORD $0x2c8000a5    // xvld	$xr5, $a1, 0
	WORD $0x2c8000c6    // xvld	$xr6, $a2, 0
	WORD $0x75389485    // xvfmul.s	$xr5, $xr4, $xr5
	WORD $0x75309463    // xvfadd.s	$xr3, $xr3, $xr5
	WORD $0x2c8000e5    // xvld	$xr5, $a3, 0
	WORD $0x75389886    // xvfmul.s	$xr6, $xr4, $xr6
	WORD $0x2c800107    // xvld	$xr7, $a4, 0
	WORD $0x75309842    // xvfadd.s	$xr2, $xr2, $xr6
	WORD $0x75389485    // xvfmul.s	$xr5, $xr4, $xr5
	WORD $0x75309421    // xvfadd.s	$xr1, $xr1, $xr5
	WORD $0x75389c84    // xvfmul.s	$xr4, $xr4, $xr7
	WORD $0x75309000    // xvfadd.s	$xr0, $xr0, $xr4
	WORD $0x02c08084    // addi.d	$a0, $a0, 32
	WORD $0x02c080a5    // addi.d	$a1, $a1, 32
	WORD $0x02c080c6    // addi.d	$a2, $a2, 32
	WORD $0x02c080e7    // addi.d	$a3, $a3, 32
	WORD $0x02fffd29    // addi.d	$a5, $a5, -1
	WORD $0x02c08108    // addi.d	$a4, $a4, 32
	BNE  R9, R0, LBB1_2
	JMP  LBB1_4

LBB1_3:
	WORD $0x77d40003 // xvori.b	$xr3, $xr0, 0
	WORD $0x77d40002 // xvori.b	$xr2, $xr0, 0
	WORD $0x77d40001 // xvori.b	$xr1, $xr0, 0

LBB1_4:
	WORD $0x02c00069     // addi.d	$a5, $sp, 0
	WORD $0x2cc00123     // xvst	$xr3, $a5, 0
	WORD $0x2b000064     // fld.s	$fa4, $sp, 0
	WORD $0x0114a403     // movgr2fr.w	$fa3, $zero
	WORD $0x2b001065     // fld.s	$fa5, $sp, 4
	WORD $0x2b002066     // fld.s	$fa6, $sp, 8
	WORD $0x2b003067     // fld.s	$fa7, $sp, 12
	WORD $0x01008c84     // fadd.s	$fa4, $fa4, $fa3
	WORD $0x01009484     // fadd.s	$fa4, $fa4, $fa5
	WORD $0x01009884     // fadd.s	$fa4, $fa4, $fa6
	WORD $0x01009c84     // fadd.s	$fa4, $fa4, $fa7
	WORD $0x2b004065     // fld.s	$fa5, $sp, 16
	WORD $0x2b005066     // fld.s	$fa6, $sp, 20
	WORD $0x2b006067     // fld.s	$fa7, $sp, 24
	WORD $0x2b007068     // fld.s	$ft0, $sp, 28
	WORD $0x01009484     // fadd.s	$fa4, $fa4, $fa5
	WORD $0x01009884     // fadd.s	$fa4, $fa4, $fa6
	WORD $0x01009c84     // fadd.s	$fa4, $fa4, $fa7
	WORD $0x0100a084     // fadd.s	$fa4, $fa4, $ft0
	WORD $0x2b400144     // fst.s	$fa4, $a6, 0
	WORD $0x2cc00122     // xvst	$xr2, $a5, 0
	WORD $0x2b000062     // fld.s	$fa2, $sp, 0
	WORD $0x2b001064     // fld.s	$fa4, $sp, 4
	WORD $0x2b002065     // fld.s	$fa5, $sp, 8
	WORD $0x2b003066     // fld.s	$fa6, $sp, 12
	WORD $0x01008c42     // fadd.s	$fa2, $fa2, $fa3
	WORD $0x01009042     // fadd.s	$fa2, $fa2, $fa4
	WORD $0x01009442     // fadd.s	$fa2, $fa2, $fa5
	WORD $0x01009842     // fadd.s	$fa2, $fa2, $fa6
	WORD $0x2b004064     // fld.s	$fa4, $sp, 16
	WORD $0x2b005065     // fld.s	$fa5, $sp, 20
	WORD $0x2b006066     // fld.s	$fa6, $sp, 24
	WORD $0x2b007067     // fld.s	$fa7, $sp, 28
	WORD $0x01009042     // fadd.s	$fa2, $fa2, $fa4
	WORD $0x01009442     // fadd.s	$fa2, $fa2, $fa5
	WORD $0x01009842     // fadd.s	$fa2, $fa2, $fa6
	WORD $0x01009c42     // fadd.s	$fa2, $fa2, $fa7
	WORD $0x2b400162     // fst.s	$fa2, $a7, 0
	WORD $0x2cc00121     // xvst	$xr1, $a5, 0
	WORD $0x2b000061     // fld.s	$fa1, $sp, 0
	WORD $0x2b001062     // fld.s	$fa2, $sp, 4
	WORD $0x2b002064     // fld.s	$fa4, $sp, 8
	WORD $0x2b003065     // fld.s	$fa5, $sp, 12
	WORD $0x01008c21     // fadd.s	$fa1, $fa1, $fa3
	WORD $0x01008821     // fadd.s	$fa1, $fa1, $fa2
	WORD $0x01009021     // fadd.s	$fa1, $fa1, $fa4
	WORD $0x01009421     // fadd.s	$fa1, $fa1, $fa5
	WORD $0x2b004062     // fld.s	$fa2, $sp, 16
	WORD $0x2b005064     // fld.s	$fa4, $sp, 20
	WORD $0x2b006065     // fld.s	$fa5, $sp, 24
	WORD $0x2b007066     // fld.s	$fa6, $sp, 28
	WORD $0x01008821     // fadd.s	$fa1, $fa1, $fa2
	WORD $0x01009021     // fadd.s	$fa1, $fa1, $fa4
	WORD $0x01009421     // fadd.s	$fa1, $fa1, $fa5
	WORD $0x01009821     // fadd.s	$fa1, $fa1, $fa6
	WORD $0x2b4001a1     // fst.s	$fa1, $t1, 0
	WORD $0x2cc00120     // xvst	$xr0, $a5, 0
	WORD $0x2b000060     // fld.s	$fa0, $sp, 0
	WORD $0x2b001061     // fld.s	$fa1, $sp, 4
	WORD $0x2b002062     // fld.s	$fa2, $sp, 8
	WORD $0x2b003064     // fld.s	$fa4, $sp, 12
	WORD $0x01008c00     // fadd.s	$fa0, $fa0, $fa3
	WORD $0x01008400     // fadd.s	$fa0, $fa0, $fa1
	WORD $0x01008800     // fadd.s	$fa0, $fa0, $fa2
	WORD $0x01009000     // fadd.s	$fa0, $fa0, $fa4
	WORD $0x2b004061     // fld.s	$fa1, $sp, 16
	WORD $0x2b005062     // fld.s	$fa2, $sp, 20
	WORD $0x2b006063     // fld.s	$fa3, $sp, 24
	WORD $0x2b007064     // fld.s	$fa4, $sp, 28
	WORD $0x01008400     // fadd.s	$fa0, $fa0, $fa1
	WORD $0x01008800     // fadd.s	$fa0, $fa0, $fa2
	WORD $0x01008c00     // fadd.s	$fa0, $fa0, $fa3
	WORD $0x01009000     // fadd.s	$fa0, $fa0, $fa4
	WORD $0x03800409     // ori	$a5, $zero, 1
	WORD $0x2b400180     // fst.s	$fa0, $t0, 0
	BLT  R14, R9, LBB1_6

LBB1_5:
	WORD $0x2b000080     // fld.s	$fa0, $a0, 0
	WORD $0x2b0000a1     // fld.s	$fa1, $a1, 0
	WORD $0x2b000142     // fld.s	$fa2, $a6, 0
	WORD $0x08110400     // fmadd.s	$fa0, $fa0, $fa1, $fa2
	WORD $0x2b400140     // fst.s	$fa0, $a6, 0
	WORD $0x2b000080     // fld.s	$fa0, $a0, 0
	WORD $0x2b0000c1     // fld.s	$fa1, $a2, 0
	WORD $0x2b000162     // fld.s	$fa2, $a7, 0
	WORD $0x08110400     // fmadd.s	$fa0, $fa0, $fa1, $fa2
	WORD $0x2b400160     // fst.s	$fa0, $a7, 0
	WORD $0x2b000080     // fld.s	$fa0, $a0, 0
	WORD $0x2b0000e1     // fld.s	$fa1, $a3, 0
	WORD $0x2b0001a2     // fld.s	$fa2, $t1, 0
	WORD $0x08110400     // fmadd.s	$fa0, $fa0, $fa1, $fa2
	WORD $0x2b4001a0     // fst.s	$fa0, $t1, 0
	WORD $0x2b000080     // fld.s	$fa0, $a0, 0
	WORD $0x2b000101     // fld.s	$fa1, $a4, 0
	WORD $0x2b000182     // fld.s	$fa2, $t0, 0
	WORD $0x08110400     // fmadd.s	$fa0, $fa0, $fa1, $fa2
	WORD $0x2b400180     // fst.s	$fa0, $t0, 0
	WORD $0x02fffdce     // addi.d	$t2, $t2, -1
	WORD $0x02c01108     // addi.d	$a4, $a4, 4
	WORD $0x02c010e7     // addi.d	$a3, $a3, 4
	WORD $0x02c010c6     // addi.d	$a2, $a2, 4
	WORD $0x02c010a5     // addi.d	$a1, $a1, 4
	WORD $0x02c01084     // addi.d	$a0, $a0, 4
	BNE  R14, R0, LBB1_5

LBB1_6:
	WORD $0x02c08063 // addi.d	$sp, $sp, 32
	ADDV $16, R3
	RET

TEXT ·xvec_lasx_batch_squared_euclidean_distances2(SB), $0-48
	MOVV query+0(FP), R4
	MOVV first+8(FP), R5
	MOVV second+16(FP), R6
	MOVV size+24(FP), R7
	MOVV first_output+32(FP), R8
	MOVV second_output+40(FP), R9
	WORD $0x02ff8063              // addi.d	$sp, $sp, -32
	WORD $0x0049fcea              // srai.d	$a6, $a3, 63
	WORD $0x0045f54a              // srli.d	$a6, $a6, 61
	WORD $0x0010a8eb              // add.d	$a7, $a3, $a6
	WORD $0x0015016a              // move	$a6, $a7
	WORD $0x0082000a              // bstrins.d	$a6, $zero, 2, 0
	WORD $0x0011a8ea              // sub.d	$a6, $a3, $a6
	WORD $0x0380200c              // ori	$t0, $zero, 8
	WORD $0x77e00001              // xvldi	$xr1, 0
	BLT  R7, R12, LBB2_3
	WORD $0x00490d67              // srai.d	$a3, $a7, 3
	WORD $0x77d40020              // xvori.b	$xr0, $xr1, 0

LBB2_2:
	WORD $0x2c800082    // xvld	$xr2, $a0, 0
	WORD $0x2c8000a3    // xvld	$xr3, $a1, 0
	WORD $0x2c8000c4    // xvld	$xr4, $a2, 0
	WORD $0x75328c43    // xvfsub.s	$xr3, $xr2, $xr3
	WORD $0x75329042    // xvfsub.s	$xr2, $xr2, $xr4
	WORD $0x75388c63    // xvfmul.s	$xr3, $xr3, $xr3
	WORD $0x75308c21    // xvfadd.s	$xr1, $xr1, $xr3
	WORD $0x75388842    // xvfmul.s	$xr2, $xr2, $xr2
	WORD $0x75308800    // xvfadd.s	$xr0, $xr0, $xr2
	WORD $0x02c08084    // addi.d	$a0, $a0, 32
	WORD $0x02c080a5    // addi.d	$a1, $a1, 32
	WORD $0x02fffce7    // addi.d	$a3, $a3, -1
	WORD $0x02c080c6    // addi.d	$a2, $a2, 32
	BNE  R7, R0, LBB2_2
	JMP  LBB2_4

LBB2_3:
	WORD $0x77d40020 // xvori.b	$xr0, $xr1, 0

LBB2_4:
	WORD $0x02c00067     // addi.d	$a3, $sp, 0
	WORD $0x2cc000e1     // xvst	$xr1, $a3, 0
	WORD $0x2b000061     // fld.s	$fa1, $sp, 0
	WORD $0x0114a402     // movgr2fr.w	$fa2, $zero
	WORD $0x2b001063     // fld.s	$fa3, $sp, 4
	WORD $0x2b002064     // fld.s	$fa4, $sp, 8
	WORD $0x2b003065     // fld.s	$fa5, $sp, 12
	WORD $0x01008821     // fadd.s	$fa1, $fa1, $fa2
	WORD $0x01008c21     // fadd.s	$fa1, $fa1, $fa3
	WORD $0x01009021     // fadd.s	$fa1, $fa1, $fa4
	WORD $0x01009421     // fadd.s	$fa1, $fa1, $fa5
	WORD $0x2b004063     // fld.s	$fa3, $sp, 16
	WORD $0x2b005064     // fld.s	$fa4, $sp, 20
	WORD $0x2b006065     // fld.s	$fa5, $sp, 24
	WORD $0x2b007066     // fld.s	$fa6, $sp, 28
	WORD $0x01008c21     // fadd.s	$fa1, $fa1, $fa3
	WORD $0x01009021     // fadd.s	$fa1, $fa1, $fa4
	WORD $0x01009421     // fadd.s	$fa1, $fa1, $fa5
	WORD $0x01009821     // fadd.s	$fa1, $fa1, $fa6
	WORD $0x2b400101     // fst.s	$fa1, $a4, 0
	WORD $0x2cc000e0     // xvst	$xr0, $a3, 0
	WORD $0x2b000060     // fld.s	$fa0, $sp, 0
	WORD $0x2b001061     // fld.s	$fa1, $sp, 4
	WORD $0x2b002063     // fld.s	$fa3, $sp, 8
	WORD $0x2b003064     // fld.s	$fa4, $sp, 12
	WORD $0x01008800     // fadd.s	$fa0, $fa0, $fa2
	WORD $0x01008400     // fadd.s	$fa0, $fa0, $fa1
	WORD $0x01008c00     // fadd.s	$fa0, $fa0, $fa3
	WORD $0x01009000     // fadd.s	$fa0, $fa0, $fa4
	WORD $0x2b004061     // fld.s	$fa1, $sp, 16
	WORD $0x2b005062     // fld.s	$fa2, $sp, 20
	WORD $0x2b006063     // fld.s	$fa3, $sp, 24
	WORD $0x2b007064     // fld.s	$fa4, $sp, 28
	WORD $0x01008400     // fadd.s	$fa0, $fa0, $fa1
	WORD $0x01008800     // fadd.s	$fa0, $fa0, $fa2
	WORD $0x01008c00     // fadd.s	$fa0, $fa0, $fa3
	WORD $0x01009000     // fadd.s	$fa0, $fa0, $fa4
	WORD $0x03800407     // ori	$a3, $zero, 1
	WORD $0x2b400120     // fst.s	$fa0, $a5, 0
	BLT  R10, R7, LBB2_6

LBB2_5:
	WORD $0x2b000080     // fld.s	$fa0, $a0, 0
	WORD $0x2b0000a1     // fld.s	$fa1, $a1, 0
	WORD $0x2b000102     // fld.s	$fa2, $a4, 0
	WORD $0x01028401     // fsub.s	$fa1, $fa0, $fa1
	WORD $0x08110421     // fmadd.s	$fa1, $fa1, $fa1, $fa2
	WORD $0x2b0000c2     // fld.s	$fa2, $a2, 0
	WORD $0x2b400101     // fst.s	$fa1, $a4, 0
	WORD $0x2b000121     // fld.s	$fa1, $a5, 0
	WORD $0x01028800     // fsub.s	$fa0, $fa0, $fa2
	WORD $0x08108000     // fmadd.s	$fa0, $fa0, $fa0, $fa1
	WORD $0x2b400120     // fst.s	$fa0, $a5, 0
	WORD $0x02fffd4a     // addi.d	$a6, $a6, -1
	WORD $0x02c010c6     // addi.d	$a2, $a2, 4
	WORD $0x02c010a5     // addi.d	$a1, $a1, 4
	WORD $0x02c01084     // addi.d	$a0, $a0, 4
	BNE  R10, R0, LBB2_5

LBB2_6:
	WORD $0x02c08063 // addi.d	$sp, $sp, 32
	RET

TEXT ·xvec_lasx_batch_squared_euclidean_distances4(SB), $0-80
	MOVV query+0(FP), R4
	MOVV first+8(FP), R5
	MOVV second+16(FP), R6
	MOVV third+24(FP), R7
	MOVV fourth+32(FP), R8
	MOVV size+40(FP), R9
	MOVV first_output+48(FP), R10
	MOVV second_output+56(FP), R11
	MOVV third_output+64(FP), R12
	ADDV $-16, R3
	MOVV R12, (0)(R3)
	ADDV $16, R3
	MOVV fourth_output+72(FP), R12
	ADDV $-16, R3
	MOVV R12, (8)(R3)
	WORD $0x02ff8063               // addi.d	$sp, $sp, -32
	WORD $0x28c0a06c               // ld.d	$t0, $sp, 40
	WORD $0x0049fd2d               // srai.d	$t1, $a5, 63
	WORD $0x0045f5ad               // srli.d	$t1, $t1, 61
	WORD $0x0010b52f               // add.d	$t3, $a5, $t1
	WORD $0x28c0806d               // ld.d	$t1, $sp, 32
	WORD $0x001501ee               // move	$t2, $t3
	WORD $0x0082000e               // bstrins.d	$t2, $zero, 2, 0
	WORD $0x0011b92e               // sub.d	$t2, $a5, $t2
	WORD $0x03802010               // ori	$t4, $zero, 8
	WORD $0x77e00003               // xvldi	$xr3, 0
	BLT  R9, R16, LBB3_3
	WORD $0x00490de9               // srai.d	$a5, $t3, 3
	WORD $0x77d40062               // xvori.b	$xr2, $xr3, 0
	WORD $0x77d40061               // xvori.b	$xr1, $xr3, 0
	WORD $0x77d40060               // xvori.b	$xr0, $xr3, 0

LBB3_2:
	WORD $0x2c800084    // xvld	$xr4, $a0, 0
	WORD $0x2c8000a5    // xvld	$xr5, $a1, 0
	WORD $0x2c8000c6    // xvld	$xr6, $a2, 0
	WORD $0x2c8000e7    // xvld	$xr7, $a3, 0
	WORD $0x2c800108    // xvld	$xr8, $a4, 0
	WORD $0x75329485    // xvfsub.s	$xr5, $xr4, $xr5
	WORD $0x75329886    // xvfsub.s	$xr6, $xr4, $xr6
	WORD $0x75329c87    // xvfsub.s	$xr7, $xr4, $xr7
	WORD $0x7532a084    // xvfsub.s	$xr4, $xr4, $xr8
	WORD $0x753894a5    // xvfmul.s	$xr5, $xr5, $xr5
	WORD $0x75309463    // xvfadd.s	$xr3, $xr3, $xr5
	WORD $0x753898c5    // xvfmul.s	$xr5, $xr6, $xr6
	WORD $0x75309442    // xvfadd.s	$xr2, $xr2, $xr5
	WORD $0x75389ce5    // xvfmul.s	$xr5, $xr7, $xr7
	WORD $0x75309421    // xvfadd.s	$xr1, $xr1, $xr5
	WORD $0x75389084    // xvfmul.s	$xr4, $xr4, $xr4
	WORD $0x75309000    // xvfadd.s	$xr0, $xr0, $xr4
	WORD $0x02c08084    // addi.d	$a0, $a0, 32
	WORD $0x02c080a5    // addi.d	$a1, $a1, 32
	WORD $0x02c080c6    // addi.d	$a2, $a2, 32
	WORD $0x02c080e7    // addi.d	$a3, $a3, 32
	WORD $0x02fffd29    // addi.d	$a5, $a5, -1
	WORD $0x02c08108    // addi.d	$a4, $a4, 32
	BNE  R9, R0, LBB3_2
	JMP  LBB3_4

LBB3_3:
	WORD $0x77d40060 // xvori.b	$xr0, $xr3, 0
	WORD $0x77d40061 // xvori.b	$xr1, $xr3, 0
	WORD $0x77d40062 // xvori.b	$xr2, $xr3, 0

LBB3_4:
	WORD $0x02c00069     // addi.d	$a5, $sp, 0
	WORD $0x2cc00123     // xvst	$xr3, $a5, 0
	WORD $0x2b000064     // fld.s	$fa4, $sp, 0
	WORD $0x0114a403     // movgr2fr.w	$fa3, $zero
	WORD $0x2b001065     // fld.s	$fa5, $sp, 4
	WORD $0x2b002066     // fld.s	$fa6, $sp, 8
	WORD $0x2b003067     // fld.s	$fa7, $sp, 12
	WORD $0x01008c84     // fadd.s	$fa4, $fa4, $fa3
	WORD $0x01009484     // fadd.s	$fa4, $fa4, $fa5
	WORD $0x01009884     // fadd.s	$fa4, $fa4, $fa6
	WORD $0x01009c84     // fadd.s	$fa4, $fa4, $fa7
	WORD $0x2b004065     // fld.s	$fa5, $sp, 16
	WORD $0x2b005066     // fld.s	$fa6, $sp, 20
	WORD $0x2b006067     // fld.s	$fa7, $sp, 24
	WORD $0x2b007068     // fld.s	$ft0, $sp, 28
	WORD $0x01009484     // fadd.s	$fa4, $fa4, $fa5
	WORD $0x01009884     // fadd.s	$fa4, $fa4, $fa6
	WORD $0x01009c84     // fadd.s	$fa4, $fa4, $fa7
	WORD $0x0100a084     // fadd.s	$fa4, $fa4, $ft0
	WORD $0x2b400144     // fst.s	$fa4, $a6, 0
	WORD $0x2cc00122     // xvst	$xr2, $a5, 0
	WORD $0x2b000062     // fld.s	$fa2, $sp, 0
	WORD $0x2b001064     // fld.s	$fa4, $sp, 4
	WORD $0x2b002065     // fld.s	$fa5, $sp, 8
	WORD $0x2b003066     // fld.s	$fa6, $sp, 12
	WORD $0x01008c42     // fadd.s	$fa2, $fa2, $fa3
	WORD $0x01009042     // fadd.s	$fa2, $fa2, $fa4
	WORD $0x01009442     // fadd.s	$fa2, $fa2, $fa5
	WORD $0x01009842     // fadd.s	$fa2, $fa2, $fa6
	WORD $0x2b004064     // fld.s	$fa4, $sp, 16
	WORD $0x2b005065     // fld.s	$fa5, $sp, 20
	WORD $0x2b006066     // fld.s	$fa6, $sp, 24
	WORD $0x2b007067     // fld.s	$fa7, $sp, 28
	WORD $0x01009042     // fadd.s	$fa2, $fa2, $fa4
	WORD $0x01009442     // fadd.s	$fa2, $fa2, $fa5
	WORD $0x01009842     // fadd.s	$fa2, $fa2, $fa6
	WORD $0x01009c42     // fadd.s	$fa2, $fa2, $fa7
	WORD $0x2b400162     // fst.s	$fa2, $a7, 0
	WORD $0x2cc00121     // xvst	$xr1, $a5, 0
	WORD $0x2b000061     // fld.s	$fa1, $sp, 0
	WORD $0x2b001062     // fld.s	$fa2, $sp, 4
	WORD $0x2b002064     // fld.s	$fa4, $sp, 8
	WORD $0x2b003065     // fld.s	$fa5, $sp, 12
	WORD $0x01008c21     // fadd.s	$fa1, $fa1, $fa3
	WORD $0x01008821     // fadd.s	$fa1, $fa1, $fa2
	WORD $0x01009021     // fadd.s	$fa1, $fa1, $fa4
	WORD $0x01009421     // fadd.s	$fa1, $fa1, $fa5
	WORD $0x2b004062     // fld.s	$fa2, $sp, 16
	WORD $0x2b005064     // fld.s	$fa4, $sp, 20
	WORD $0x2b006065     // fld.s	$fa5, $sp, 24
	WORD $0x2b007066     // fld.s	$fa6, $sp, 28
	WORD $0x01008821     // fadd.s	$fa1, $fa1, $fa2
	WORD $0x01009021     // fadd.s	$fa1, $fa1, $fa4
	WORD $0x01009421     // fadd.s	$fa1, $fa1, $fa5
	WORD $0x01009821     // fadd.s	$fa1, $fa1, $fa6
	WORD $0x2b4001a1     // fst.s	$fa1, $t1, 0
	WORD $0x2cc00120     // xvst	$xr0, $a5, 0
	WORD $0x2b000060     // fld.s	$fa0, $sp, 0
	WORD $0x2b001061     // fld.s	$fa1, $sp, 4
	WORD $0x2b002062     // fld.s	$fa2, $sp, 8
	WORD $0x2b003064     // fld.s	$fa4, $sp, 12
	WORD $0x01008c00     // fadd.s	$fa0, $fa0, $fa3
	WORD $0x01008400     // fadd.s	$fa0, $fa0, $fa1
	WORD $0x01008800     // fadd.s	$fa0, $fa0, $fa2
	WORD $0x01009000     // fadd.s	$fa0, $fa0, $fa4
	WORD $0x2b004061     // fld.s	$fa1, $sp, 16
	WORD $0x2b005062     // fld.s	$fa2, $sp, 20
	WORD $0x2b006063     // fld.s	$fa3, $sp, 24
	WORD $0x2b007064     // fld.s	$fa4, $sp, 28
	WORD $0x01008400     // fadd.s	$fa0, $fa0, $fa1
	WORD $0x01008800     // fadd.s	$fa0, $fa0, $fa2
	WORD $0x01008c00     // fadd.s	$fa0, $fa0, $fa3
	WORD $0x01009000     // fadd.s	$fa0, $fa0, $fa4
	WORD $0x03800409     // ori	$a5, $zero, 1
	WORD $0x2b400180     // fst.s	$fa0, $t0, 0
	BLT  R14, R9, LBB3_6

LBB3_5:
	WORD $0x2b000080     // fld.s	$fa0, $a0, 0
	WORD $0x2b0000a1     // fld.s	$fa1, $a1, 0
	WORD $0x2b000142     // fld.s	$fa2, $a6, 0
	WORD $0x01028401     // fsub.s	$fa1, $fa0, $fa1
	WORD $0x2b0000c3     // fld.s	$fa3, $a2, 0
	WORD $0x2b0000e4     // fld.s	$fa4, $a3, 0
	WORD $0x08110421     // fmadd.s	$fa1, $fa1, $fa1, $fa2
	WORD $0x2b000102     // fld.s	$fa2, $a4, 0
	WORD $0x2b400141     // fst.s	$fa1, $a6, 0
	WORD $0x2b000161     // fld.s	$fa1, $a7, 0
	WORD $0x01028c03     // fsub.s	$fa3, $fa0, $fa3
	WORD $0x08108c61     // fmadd.s	$fa1, $fa3, $fa3, $fa1
	WORD $0x2b400161     // fst.s	$fa1, $a7, 0
	WORD $0x2b0001a1     // fld.s	$fa1, $t1, 0
	WORD $0x01029003     // fsub.s	$fa3, $fa0, $fa4
	WORD $0x08108c61     // fmadd.s	$fa1, $fa3, $fa3, $fa1
	WORD $0x2b4001a1     // fst.s	$fa1, $t1, 0
	WORD $0x2b000181     // fld.s	$fa1, $t0, 0
	WORD $0x01028800     // fsub.s	$fa0, $fa0, $fa2
	WORD $0x08108000     // fmadd.s	$fa0, $fa0, $fa0, $fa1
	WORD $0x2b400180     // fst.s	$fa0, $t0, 0
	WORD $0x02fffdce     // addi.d	$t2, $t2, -1
	WORD $0x02c01108     // addi.d	$a4, $a4, 4
	WORD $0x02c010e7     // addi.d	$a3, $a3, 4
	WORD $0x02c010c6     // addi.d	$a2, $a2, 4
	WORD $0x02c010a5     // addi.d	$a1, $a1, 4
	WORD $0x02c01084     // addi.d	$a0, $a0, 4
	BNE  R14, R0, LBB3_5

LBB3_6:
	WORD $0x02c08063 // addi.d	$sp, $sp, 32
	ADDV $16, R3
	RET
