//go:build !noasm && amd64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8 (6ubuntu1)
// 	objdump 2.46
// flags: -mavx -mf16c -O3
// source: src/distance_batch_fp16_avx.c

package mathbatch

import "unsafe"

//go:noescape
func fp16_l2_avx4(query, first, second, third, fourth unsafe.Pointer, size int64, output unsafe.Pointer)

//go:noescape
func fp16_dot_avx4(query, first, second, third, fourth unsafe.Pointer, size int64, output unsafe.Pointer)

//go:noescape
func fp16_products_avx4(query, first, second, third, fourth unsafe.Pointer, size int64, output unsafe.Pointer)
