//go:build !noasm && amd64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8 (6ubuntu1)
// 	objdump 2.46
// flags: -mavx -mf16c -mavx512f -mavx512dq -O3
// source: src/distance_batch_fp16_avx512.c

DATA __goat_data_2e4c435049325f30<>+0x000(SB)/8, $0x0706010003020100
DATA __goat_data_2e4c435049325f30<>+0x008(SB)/8, $0x0f0e03020b0a0100
GLOBL __goat_data_2e4c435049325f30<>(SB), 8, $16

DATA __goat_data_2e4c435049325f31<>+0x000(SB)/8, $0x0000000100000000
DATA __goat_data_2e4c435049325f31<>+0x008(SB)/8, $0x0000000100000002
DATA __goat_data_2e4c435049325f31<>+0x010(SB)/8, $0x0000000000000001
DATA __goat_data_2e4c435049325f31<>+0x018(SB)/8, $0x0000000200000003
GLOBL __goat_data_2e4c435049325f31<>(SB), 8, $32

TEXT ·fp16_l2_avx512_4(SB), $0-56
	MOVQ  query+0(FP), DI
	MOVQ  first+8(FP), SI
	MOVQ  second+16(FP), DX
	MOVQ  third+24(FP), CX
	MOVQ  fourth+32(FP), R8
	MOVQ  size+40(FP), R9
	PUSHQ output+48(FP)
	PUSHQ $0
	BYTE  $0x55               // pushq	%rbp
	WORD  $0x8948; BYTE $0xe5 // movq	%rsp, %rbp
	LONG  $0xf8e48348         // andq	$-8, %rsp
	LONG  $0x10458b48         // movq	16(%rbp), %rax
	LONG  $0x10f98349         // cmpq	$16, %r9
	JGE   LBB0_2
	LONG  $0xc057f8c5         // vxorps	%xmm0, %xmm0, %xmm0
	WORD  $0x3145; BYTE $0xd2 // xorl	%r10d, %r10d
	LONG  $0xc957f0c5         // vxorps	%xmm1, %xmm1, %xmm1
	LONG  $0xdb57e0c5         // vxorps	%xmm3, %xmm3, %xmm3
	LONG  $0xd257e8c5         // vxorps	%xmm2, %xmm2, %xmm2
	JMP   LBB0_5

LBB0_2:
	LONG $0xd257e8c5               // vxorps	%xmm2, %xmm2, %xmm2
	LONG $0x0010ba41; WORD $0x0000 // movl	$16, %r10d
	LONG $0xdb57e0c5               // vxorps	%xmm3, %xmm3, %xmm3
	LONG $0xc957f0c5               // vxorps	%xmm1, %xmm1, %xmm1
	LONG $0xc057f8c5               // vxorps	%xmm0, %xmm0, %xmm0

LBB0_3:
	QUAD $0xff576413487db262               // vcvtph2ps	-32(%rdi,%r10,2), %zmm4
	QUAD $0xff566c13487db262               // vcvtph2ps	-32(%rsi,%r10,2), %zmm5
	LONG $0x485cf162; WORD $0xed5c         // vsubps	%zmm5, %zmm4, %zmm5
	LONG $0x4854f162; WORD $0xed59         // vmulps	%zmm5, %zmm5, %zmm5
	LONG $0x486cf162; WORD $0xd558         // vaddps	%zmm5, %zmm2, %zmm2
	QUAD $0xff526c13487db262               // vcvtph2ps	-32(%rdx,%r10,2), %zmm5
	LONG $0x485cf162; WORD $0xed5c         // vsubps	%zmm5, %zmm4, %zmm5
	LONG $0x4854f162; WORD $0xed59         // vmulps	%zmm5, %zmm5, %zmm5
	QUAD $0xff517413487db262               // vcvtph2ps	-32(%rcx,%r10,2), %zmm6
	LONG $0x4864f162; WORD $0xdd58         // vaddps	%zmm5, %zmm3, %zmm3
	LONG $0x485cf162; WORD $0xee5c         // vsubps	%zmm6, %zmm4, %zmm5
	LONG $0x4854f162; WORD $0xed59         // vmulps	%zmm5, %zmm5, %zmm5
	LONG $0x4874f162; WORD $0xcd58         // vaddps	%zmm5, %zmm1, %zmm1
	QUAD $0xff506c13487d9262               // vcvtph2ps	-32(%r8,%r10,2), %zmm5
	LONG $0x485cf162; WORD $0xe55c         // vsubps	%zmm5, %zmm4, %zmm4
	LONG $0x485cf162; WORD $0xe459         // vmulps	%zmm4, %zmm4, %zmm4
	LONG $0x487cf162; WORD $0xc458         // vaddps	%zmm4, %zmm0, %zmm0
	LONG $0x10c28349                       // addq	$16, %r10
	WORD $0x394d; BYTE $0xca               // cmpq	%r9, %r10
	JLE  LBB0_3
	QUAD $0xfffffffffff0ba49; WORD $0x7fff // movabsq	$9223372036854775792, %r10      # imm = 0x7FFFFFFFFFFFFFF0
	WORD $0x214d; BYTE $0xca               // andq	%r9, %r10

LBB0_5:
	LONG $0xe37cebc5                           // vhaddps	%xmm3, %xmm2, %xmm4
	LONG $0xe4c6d8c5; BYTE $0xe8               // vshufps	$232, %xmm4, %xmm4, %xmm4       # xmm4 = xmm4[0,2,2,3]
	LONG $0xeac6e9c5; BYTE $0x01               // vshufpd	$1, %xmm2, %xmm2, %xmm5         # xmm5 = xmm2[1,0]
	LONG $0x2151e3c4; WORD $0x9ceb             // vinsertps	$156, %xmm3, %xmm5, %xmm5 # xmm5 = xmm5[0],xmm3[2],zero,zero
	LONG $0xe458d0c5                           // vaddps	%xmm4, %xmm5, %xmm4
	LONG $0xebc6e1c5; BYTE $0x01               // vshufpd	$1, %xmm3, %xmm3, %xmm5         # xmm5 = xmm3[1,0]
	LONG $0x2151e3c4; WORD $0xccea             // vinsertps	$204, %xmm2, %xmm5, %xmm5 # xmm5 = xmm2[3],xmm5[1],zero,zero
	LONG $0xe458d0c5                           // vaddps	%xmm4, %xmm5, %xmm4
	LONG $0x197de3c4; WORD $0x01dd             // vextractf128	$1, %ymm3, %xmm5
	LONG $0x197de3c4; WORD $0x01d6             // vextractf128	$1, %ymm2, %xmm6
	LONG $0x2149e3c4; WORD $0x1cfd             // vinsertps	$28, %xmm5, %xmm6, %xmm7 # xmm7 = xmm6[0],xmm5[0],zero,zero
	LONG $0xe458c0c5                           // vaddps	%xmm4, %xmm7, %xmm4
	LONG $0x2151e3c4; WORD $0x4cfe             // vinsertps	$76, %xmm6, %xmm5, %xmm7 # xmm7 = xmm6[1],xmm5[1],zero,zero
	LONG $0xe458c0c5                           // vaddps	%xmm4, %xmm7, %xmm4
	LONG $0xfec6c9c5; BYTE $0x01               // vshufpd	$1, %xmm6, %xmm6, %xmm7         # xmm7 = xmm6[1,0]
	LONG $0x2141e3c4; WORD $0x9cfd             // vinsertps	$156, %xmm5, %xmm7, %xmm7 # xmm7 = xmm7[0],xmm5[2],zero,zero
	LONG $0xe458c0c5                           // vaddps	%xmm4, %xmm7, %xmm4
	LONG $0xedc6d1c5; BYTE $0x01               // vshufpd	$1, %xmm5, %xmm5, %xmm5         # xmm5 = xmm5[1,0]
	LONG $0x2151e3c4; WORD $0xccee             // vinsertps	$204, %xmm6, %xmm5, %xmm5 # xmm5 = xmm6[3],xmm5[1],zero,zero
	LONG $0xe458d0c5                           // vaddps	%xmm4, %xmm5, %xmm4
	LONG $0x487df362; WORD $0xdd19; BYTE $0x02 // vextractf32x4	$2, %zmm3, %xmm5
	LONG $0x487df362; WORD $0xd619; BYTE $0x02 // vextractf32x4	$2, %zmm2, %xmm6
	LONG $0x2149e3c4; WORD $0x1cfd             // vinsertps	$28, %xmm5, %xmm6, %xmm7 # xmm7 = xmm6[0],xmm5[0],zero,zero
	LONG $0xe458c0c5                           // vaddps	%xmm4, %xmm7, %xmm4
	LONG $0x2151e3c4; WORD $0x4cee             // vinsertps	$76, %xmm6, %xmm5, %xmm5 # xmm5 = xmm6[1],xmm5[1],zero,zero
	LONG $0xe458d0c5                           // vaddps	%xmm4, %xmm5, %xmm4
	LONG $0x48fdf362; WORD $0xdb1b; BYTE $0x01 // vextractf64x4	$1, %zmm3, %ymm3
	LONG $0x48fdf362; WORD $0xd21b; BYTE $0x01 // vextractf64x4	$1, %zmm2, %ymm2
	LONG $0xeac6e9c5; BYTE $0x01               // vshufpd	$1, %xmm2, %xmm2, %xmm5         # xmm5 = xmm2[1,0]
	LONG $0x2151e3c4; WORD $0x9ceb             // vinsertps	$156, %xmm3, %xmm5, %xmm5 # xmm5 = xmm5[0],xmm3[2],zero,zero
	LONG $0xe458d0c5                           // vaddps	%xmm4, %xmm5, %xmm4
	LONG $0xebc6e1c5; BYTE $0x01               // vshufpd	$1, %xmm3, %xmm3, %xmm5         # xmm5 = xmm3[1,0]
	LONG $0x2151e3c4; WORD $0xccea             // vinsertps	$204, %xmm2, %xmm5, %xmm5 # xmm5 = xmm2[3],xmm5[1],zero,zero
	LONG $0xe458d0c5                           // vaddps	%xmm4, %xmm5, %xmm4
	LONG $0x197de3c4; WORD $0x01dd             // vextractf128	$1, %ymm3, %xmm5
	LONG $0x197de3c4; WORD $0x01d6             // vextractf128	$1, %ymm2, %xmm6
	LONG $0x2149e3c4; WORD $0x1cfd             // vinsertps	$28, %xmm5, %xmm6, %xmm7 # xmm7 = xmm6[0],xmm5[0],zero,zero
	LONG $0xe458c0c5                           // vaddps	%xmm4, %xmm7, %xmm4
	LONG $0x2151e3c4; WORD $0x4cee             // vinsertps	$76, %xmm6, %xmm5, %xmm5 # xmm5 = xmm6[1],xmm5[1],zero,zero
	LONG $0xe458d0c5                           // vaddps	%xmm4, %xmm5, %xmm4
	LONG $0x01fde3c4; WORD $0xffdb             // vpermpd	$255, %ymm3, %ymm3              # ymm3 = ymm3[3,3,3,3]
	LONG $0x01fde3c4; WORD $0xffd2             // vpermpd	$255, %ymm2, %ymm2              # ymm2 = ymm2[3,3,3,3]
	LONG $0x2169e3c4; WORD $0x1ceb             // vinsertps	$28, %xmm3, %xmm2, %xmm5 # xmm5 = xmm2[0],xmm3[0],zero,zero
	LONG $0xe458d0c5                           // vaddps	%xmm4, %xmm5, %xmm4
	LONG $0x2161e3c4; WORD $0x4cd2             // vinsertps	$76, %xmm2, %xmm3, %xmm2 # xmm2 = xmm2[1],xmm3[1],zero,zero
	LONG $0xd458e8c5                           // vaddps	%xmm4, %xmm2, %xmm2
	LONG $0xd87cf3c5                           // vhaddps	%xmm0, %xmm1, %xmm3
	LONG $0xdbc6e0c5; BYTE $0xe8               // vshufps	$232, %xmm3, %xmm3, %xmm3       # xmm3 = xmm3[0,2,2,3]
	LONG $0xe1c6f1c5; BYTE $0x01               // vshufpd	$1, %xmm1, %xmm1, %xmm4         # xmm4 = xmm1[1,0]
	LONG $0x2159e3c4; WORD $0x9ce0             // vinsertps	$156, %xmm0, %xmm4, %xmm4 # xmm4 = xmm4[0],xmm0[2],zero,zero
	LONG $0xdb58d8c5                           // vaddps	%xmm3, %xmm4, %xmm3
	LONG $0xe0c6f9c5; BYTE $0x01               // vshufpd	$1, %xmm0, %xmm0, %xmm4         # xmm4 = xmm0[1,0]
	LONG $0x2159e3c4; WORD $0xcce1             // vinsertps	$204, %xmm1, %xmm4, %xmm4 # xmm4 = xmm1[3],xmm4[1],zero,zero
	LONG $0xdb58d8c5                           // vaddps	%xmm3, %xmm4, %xmm3
	LONG $0x197de3c4; WORD $0x01c4             // vextractf128	$1, %ymm0, %xmm4
	LONG $0x197de3c4; WORD $0x01cd             // vextractf128	$1, %ymm1, %xmm5
	LONG $0x2151e3c4; WORD $0x1cf4             // vinsertps	$28, %xmm4, %xmm5, %xmm6 # xmm6 = xmm5[0],xmm4[0],zero,zero
	LONG $0xdb58c8c5                           // vaddps	%xmm3, %xmm6, %xmm3
	LONG $0x2159e3c4; WORD $0x4cf5             // vinsertps	$76, %xmm5, %xmm4, %xmm6 # xmm6 = xmm5[1],xmm4[1],zero,zero
	LONG $0xdb58c8c5                           // vaddps	%xmm3, %xmm6, %xmm3
	LONG $0xf5c6d1c5; BYTE $0x01               // vshufpd	$1, %xmm5, %xmm5, %xmm6         # xmm6 = xmm5[1,0]
	LONG $0x2149e3c4; WORD $0x9cf4             // vinsertps	$156, %xmm4, %xmm6, %xmm6 # xmm6 = xmm6[0],xmm4[2],zero,zero
	LONG $0xdb58c8c5                           // vaddps	%xmm3, %xmm6, %xmm3
	LONG $0xe4c6d9c5; BYTE $0x01               // vshufpd	$1, %xmm4, %xmm4, %xmm4         # xmm4 = xmm4[1,0]
	LONG $0x2159e3c4; WORD $0xcce5             // vinsertps	$204, %xmm5, %xmm4, %xmm4 # xmm4 = xmm5[3],xmm4[1],zero,zero
	LONG $0xdb58d8c5                           // vaddps	%xmm3, %xmm4, %xmm3
	LONG $0x487df362; WORD $0xc419; BYTE $0x02 // vextractf32x4	$2, %zmm0, %xmm4
	LONG $0x487df362; WORD $0xcd19; BYTE $0x02 // vextractf32x4	$2, %zmm1, %xmm5
	LONG $0x2151e3c4; WORD $0x1cf4             // vinsertps	$28, %xmm4, %xmm5, %xmm6 # xmm6 = xmm5[0],xmm4[0],zero,zero
	LONG $0xdb58c8c5                           // vaddps	%xmm3, %xmm6, %xmm3
	LONG $0x2159e3c4; WORD $0x4ce5             // vinsertps	$76, %xmm5, %xmm4, %xmm4 # xmm4 = xmm5[1],xmm4[1],zero,zero
	LONG $0xdb58d8c5                           // vaddps	%xmm3, %xmm4, %xmm3
	LONG $0x48fdf362; WORD $0xc01b; BYTE $0x01 // vextractf64x4	$1, %zmm0, %ymm0
	LONG $0x48fdf362; WORD $0xc91b; BYTE $0x01 // vextractf64x4	$1, %zmm1, %ymm1
	LONG $0xe1c6f1c5; BYTE $0x01               // vshufpd	$1, %xmm1, %xmm1, %xmm4         # xmm4 = xmm1[1,0]
	LONG $0x2159e3c4; WORD $0x9ce0             // vinsertps	$156, %xmm0, %xmm4, %xmm4 # xmm4 = xmm4[0],xmm0[2],zero,zero
	LONG $0xdb58d8c5                           // vaddps	%xmm3, %xmm4, %xmm3
	LONG $0xe0c6f9c5; BYTE $0x01               // vshufpd	$1, %xmm0, %xmm0, %xmm4         # xmm4 = xmm0[1,0]
	LONG $0x2159e3c4; WORD $0xcce1             // vinsertps	$204, %xmm1, %xmm4, %xmm4 # xmm4 = xmm1[3],xmm4[1],zero,zero
	LONG $0xdb58d8c5                           // vaddps	%xmm3, %xmm4, %xmm3
	LONG $0x197de3c4; WORD $0x01c4             // vextractf128	$1, %ymm0, %xmm4
	LONG $0x197de3c4; WORD $0x01cd             // vextractf128	$1, %ymm1, %xmm5
	LONG $0x2151e3c4; WORD $0x1cf4             // vinsertps	$28, %xmm4, %xmm5, %xmm6 # xmm6 = xmm5[0],xmm4[0],zero,zero
	LONG $0xdb58c8c5                           // vaddps	%xmm3, %xmm6, %xmm3
	LONG $0x2159e3c4; WORD $0x4ce5             // vinsertps	$76, %xmm5, %xmm4, %xmm4 # xmm4 = xmm5[1],xmm4[1],zero,zero
	LONG $0xdb58d8c5                           // vaddps	%xmm3, %xmm4, %xmm3
	LONG $0x01fde3c4; WORD $0xffc0             // vpermpd	$255, %ymm0, %ymm0              # ymm0 = ymm0[3,3,3,3]
	LONG $0x01fde3c4; WORD $0xffc9             // vpermpd	$255, %ymm1, %ymm1              # ymm1 = ymm1[3,3,3,3]
	LONG $0x2171e3c4; WORD $0x1ce0             // vinsertps	$28, %xmm0, %xmm1, %xmm4 # xmm4 = xmm1[0],xmm0[0],zero,zero
	LONG $0xdb58d8c5                           // vaddps	%xmm3, %xmm4, %xmm3
	LONG $0x2179e3c4; WORD $0x4cc1             // vinsertps	$76, %xmm1, %xmm0, %xmm0 # xmm0 = xmm1[1],xmm0[1],zero,zero
	LONG $0xc358f8c5                           // vaddps	%xmm3, %xmm0, %xmm0
	LONG $0xc816e8c5                           // vmovlhps	%xmm0, %xmm2, %xmm1             # xmm1 = xmm2[0],xmm0[0]
	LONG $0x0811f8c5                           // vmovups	%xmm1, (%rax)
	WORD $0x394d; BYTE $0xca                   // cmpq	%r9, %r10
	JGE  LBB0_9
	LONG $0x0810fac5                           // vmovss	(%rax), %xmm1                   # xmm1 = mem[0],zero,zero,zero
	LONG $0x0c69e3c4; WORD $0x01c9             // vblendps	$1, %xmm1, %xmm2, %xmm1         # xmm1 = xmm1[0],xmm2[1,2,3]
	LONG $0xc016f0c5                           // vmovlhps	%xmm0, %xmm1, %xmm0             # xmm0 = xmm1[0],xmm0[0]

LBB0_7:
	LONG $0xc479a1c4; WORD $0x570c; BYTE $0x00 // vpinsrw	$0, (%rdi,%r10,2), %xmm0, %xmm1
	LONG $0x1379e2c4; BYTE $0xc9               // vcvtph2ps	%xmm1, %xmm1
	LONG $0xc479a1c4; WORD $0x5614; BYTE $0x00 // vpinsrw	$0, (%rsi,%r10,2), %xmm0, %xmm2
	LONG $0xc479a1c4; WORD $0x521c; BYTE $0x00 // vpinsrw	$0, (%rdx,%r10,2), %xmm0, %xmm3
	LONG $0xc479a1c4; WORD $0x5124; BYTE $0x00 // vpinsrw	$0, (%rcx,%r10,2), %xmm0, %xmm4
	LONG $0xd361e9c5                           // vpunpcklwd	%xmm3, %xmm2, %xmm2     # xmm2 = xmm2[0],xmm3[0],xmm2[1],xmm3[1],xmm2[2],xmm3[2],xmm2[3],xmm3[3]
	LONG $0xc47981c4; WORD $0x501c; BYTE $0x00 // vpinsrw	$0, (%r8,%r10,2), %xmm0, %xmm3
	LONG $0xdb61d9c5                           // vpunpcklwd	%xmm3, %xmm4, %xmm3     # xmm3 = xmm4[0],xmm3[0],xmm4[1],xmm3[1],xmm4[2],xmm3[2],xmm4[3],xmm3[3]
	LONG $0xd362e9c5                           // vpunpckldq	%xmm3, %xmm2, %xmm2     # xmm2 = xmm2[0],xmm3[0],xmm2[1],xmm3[1]
	LONG $0x1379e2c4; BYTE $0xd2               // vcvtph2ps	%xmm2, %xmm2
	LONG $0x1879e2c4; BYTE $0xc9               // vbroadcastss	%xmm1, %xmm1
	LONG $0xca5cf0c5                           // vsubps	%xmm2, %xmm1, %xmm1
	LONG $0xb871e2c4; BYTE $0xc1               // vfmadd231ps	%xmm1, %xmm1, %xmm0     # xmm0 = (xmm1 * xmm1) + xmm0
	WORD $0xff49; BYTE $0xc2                   // incq	%r10
	WORD $0x394d; BYTE $0xd1                   // cmpq	%r10, %r9
	JNE  LBB0_7
	LONG $0x0011f8c5                           // vmovups	%xmm0, (%rax)

LBB0_9:
	WORD $0x8948; BYTE $0xec // movq	%rbp, %rsp
	BYTE $0x5d               // popq	%rbp
	WORD $0xf8c5; BYTE $0x77 // vzeroupper
	POPQ DI
	POPQ DI
	RET

TEXT ·fp16_dot_avx512_4(SB), $0-56
	MOVQ  query+0(FP), DI
	MOVQ  first+8(FP), SI
	MOVQ  second+16(FP), DX
	MOVQ  third+24(FP), CX
	MOVQ  fourth+32(FP), R8
	MOVQ  size+40(FP), R9
	PUSHQ output+48(FP)
	PUSHQ $0
	BYTE  $0x55               // pushq	%rbp
	WORD  $0x8948; BYTE $0xe5 // movq	%rsp, %rbp
	LONG  $0xf8e48348         // andq	$-8, %rsp
	LONG  $0x10458b48         // movq	16(%rbp), %rax
	LONG  $0x10f98349         // cmpq	$16, %r9
	JGE   LBB1_2
	LONG  $0xc057f8c5         // vxorps	%xmm0, %xmm0, %xmm0
	WORD  $0x3145; BYTE $0xd2 // xorl	%r10d, %r10d
	LONG  $0xc957f0c5         // vxorps	%xmm1, %xmm1, %xmm1
	LONG  $0xdb57e0c5         // vxorps	%xmm3, %xmm3, %xmm3
	LONG  $0xd257e8c5         // vxorps	%xmm2, %xmm2, %xmm2
	JMP   LBB1_5

LBB1_2:
	LONG $0xd257e8c5               // vxorps	%xmm2, %xmm2, %xmm2
	LONG $0x0010ba41; WORD $0x0000 // movl	$16, %r10d
	LONG $0xdb57e0c5               // vxorps	%xmm3, %xmm3, %xmm3
	LONG $0xc957f0c5               // vxorps	%xmm1, %xmm1, %xmm1
	LONG $0xc057f8c5               // vxorps	%xmm0, %xmm0, %xmm0

LBB1_3:
	QUAD $0xff576413487db262               // vcvtph2ps	-32(%rdi,%r10,2), %zmm4
	QUAD $0xff566c13487db262               // vcvtph2ps	-32(%rsi,%r10,2), %zmm5
	QUAD $0xff527413487db262               // vcvtph2ps	-32(%rdx,%r10,2), %zmm6
	LONG $0x485cf162; WORD $0xed59         // vmulps	%zmm5, %zmm4, %zmm5
	LONG $0x486cf162; WORD $0xd558         // vaddps	%zmm5, %zmm2, %zmm2
	LONG $0x485cf162; WORD $0xee59         // vmulps	%zmm6, %zmm4, %zmm5
	LONG $0x4864f162; WORD $0xdd58         // vaddps	%zmm5, %zmm3, %zmm3
	QUAD $0xff516c13487db262               // vcvtph2ps	-32(%rcx,%r10,2), %zmm5
	LONG $0x485cf162; WORD $0xed59         // vmulps	%zmm5, %zmm4, %zmm5
	LONG $0x4874f162; WORD $0xcd58         // vaddps	%zmm5, %zmm1, %zmm1
	QUAD $0xff506c13487d9262               // vcvtph2ps	-32(%r8,%r10,2), %zmm5
	LONG $0x485cf162; WORD $0xe559         // vmulps	%zmm5, %zmm4, %zmm4
	LONG $0x487cf162; WORD $0xc458         // vaddps	%zmm4, %zmm0, %zmm0
	LONG $0x10c28349                       // addq	$16, %r10
	WORD $0x394d; BYTE $0xca               // cmpq	%r9, %r10
	JLE  LBB1_3
	QUAD $0xfffffffffff0ba49; WORD $0x7fff // movabsq	$9223372036854775792, %r10      # imm = 0x7FFFFFFFFFFFFFF0
	WORD $0x214d; BYTE $0xca               // andq	%r9, %r10

LBB1_5:
	LONG $0x2169e3c4; WORD $0x1ceb             // vinsertps	$28, %xmm3, %xmm2, %xmm5 # xmm5 = xmm2[0],xmm3[0],zero,zero
	LONG $0xe457d8c5                           // vxorps	%xmm4, %xmm4, %xmm4
	LONG $0xec58d0c5                           // vaddps	%xmm4, %xmm5, %xmm5
	LONG $0x2161e3c4; WORD $0x4cf2             // vinsertps	$76, %xmm2, %xmm3, %xmm6 # xmm6 = xmm2[1],xmm3[1],zero,zero
	LONG $0xed58c8c5                           // vaddps	%xmm5, %xmm6, %xmm5
	LONG $0xf2c6e9c5; BYTE $0x01               // vshufpd	$1, %xmm2, %xmm2, %xmm6         # xmm6 = xmm2[1,0]
	LONG $0x2149e3c4; WORD $0x9cf3             // vinsertps	$156, %xmm3, %xmm6, %xmm6 # xmm6 = xmm6[0],xmm3[2],zero,zero
	LONG $0xed58c8c5                           // vaddps	%xmm5, %xmm6, %xmm5
	LONG $0xf3c6e1c5; BYTE $0x01               // vshufpd	$1, %xmm3, %xmm3, %xmm6         # xmm6 = xmm3[1,0]
	LONG $0x2149e3c4; WORD $0xccf2             // vinsertps	$204, %xmm2, %xmm6, %xmm6 # xmm6 = xmm2[3],xmm6[1],zero,zero
	LONG $0xed58c8c5                           // vaddps	%xmm5, %xmm6, %xmm5
	LONG $0x197de3c4; WORD $0x01de             // vextractf128	$1, %ymm3, %xmm6
	LONG $0x197de3c4; WORD $0x01d7             // vextractf128	$1, %ymm2, %xmm7
	LONG $0x214163c4; WORD $0x1cc6             // vinsertps	$28, %xmm6, %xmm7, %xmm8 # xmm8 = xmm7[0],xmm6[0],zero,zero
	LONG $0xed58b8c5                           // vaddps	%xmm5, %xmm8, %xmm5
	LONG $0x214963c4; WORD $0x4cc7             // vinsertps	$76, %xmm7, %xmm6, %xmm8 # xmm8 = xmm7[1],xmm6[1],zero,zero
	LONG $0xed58b8c5                           // vaddps	%xmm5, %xmm8, %xmm5
	LONG $0xc7c641c5; BYTE $0x01               // vshufpd	$1, %xmm7, %xmm7, %xmm8         # xmm8 = xmm7[1,0]
	LONG $0x213963c4; WORD $0x9cc6             // vinsertps	$156, %xmm6, %xmm8, %xmm8 # xmm8 = xmm8[0],xmm6[2],zero,zero
	LONG $0xed58b8c5                           // vaddps	%xmm5, %xmm8, %xmm5
	LONG $0xf6c6c9c5; BYTE $0x01               // vshufpd	$1, %xmm6, %xmm6, %xmm6         # xmm6 = xmm6[1,0]
	LONG $0x2149e3c4; WORD $0xccf7             // vinsertps	$204, %xmm7, %xmm6, %xmm6 # xmm6 = xmm7[3],xmm6[1],zero,zero
	LONG $0xed58c8c5                           // vaddps	%xmm5, %xmm6, %xmm5
	LONG $0x487df362; WORD $0xde19; BYTE $0x02 // vextractf32x4	$2, %zmm3, %xmm6
	LONG $0x487df362; WORD $0xd719; BYTE $0x02 // vextractf32x4	$2, %zmm2, %xmm7
	LONG $0x214163c4; WORD $0x1cc6             // vinsertps	$28, %xmm6, %xmm7, %xmm8 # xmm8 = xmm7[0],xmm6[0],zero,zero
	LONG $0xed58b8c5                           // vaddps	%xmm5, %xmm8, %xmm5
	LONG $0x2149e3c4; WORD $0x4cf7             // vinsertps	$76, %xmm7, %xmm6, %xmm6 # xmm6 = xmm7[1],xmm6[1],zero,zero
	LONG $0xed58c8c5                           // vaddps	%xmm5, %xmm6, %xmm5
	LONG $0x48fdf362; WORD $0xdb1b; BYTE $0x01 // vextractf64x4	$1, %zmm3, %ymm3
	LONG $0x48fdf362; WORD $0xd21b; BYTE $0x01 // vextractf64x4	$1, %zmm2, %ymm2
	LONG $0xf2c6e9c5; BYTE $0x01               // vshufpd	$1, %xmm2, %xmm2, %xmm6         # xmm6 = xmm2[1,0]
	LONG $0x2149e3c4; WORD $0x9cf3             // vinsertps	$156, %xmm3, %xmm6, %xmm6 # xmm6 = xmm6[0],xmm3[2],zero,zero
	LONG $0xed58c8c5                           // vaddps	%xmm5, %xmm6, %xmm5
	LONG $0xf3c6e1c5; BYTE $0x01               // vshufpd	$1, %xmm3, %xmm3, %xmm6         # xmm6 = xmm3[1,0]
	LONG $0x2149e3c4; WORD $0xccf2             // vinsertps	$204, %xmm2, %xmm6, %xmm6 # xmm6 = xmm2[3],xmm6[1],zero,zero
	LONG $0xed58c8c5                           // vaddps	%xmm5, %xmm6, %xmm5
	LONG $0x197de3c4; WORD $0x01de             // vextractf128	$1, %ymm3, %xmm6
	LONG $0x197de3c4; WORD $0x01d7             // vextractf128	$1, %ymm2, %xmm7
	LONG $0x214163c4; WORD $0x1cc6             // vinsertps	$28, %xmm6, %xmm7, %xmm8 # xmm8 = xmm7[0],xmm6[0],zero,zero
	LONG $0xed58b8c5                           // vaddps	%xmm5, %xmm8, %xmm5
	LONG $0x2149e3c4; WORD $0x4cf7             // vinsertps	$76, %xmm7, %xmm6, %xmm6 # xmm6 = xmm7[1],xmm6[1],zero,zero
	LONG $0xed58c8c5                           // vaddps	%xmm5, %xmm6, %xmm5
	LONG $0x01fde3c4; WORD $0xffdb             // vpermpd	$255, %ymm3, %ymm3              # ymm3 = ymm3[3,3,3,3]
	LONG $0x01fde3c4; WORD $0xffd2             // vpermpd	$255, %ymm2, %ymm2              # ymm2 = ymm2[3,3,3,3]
	LONG $0x2169e3c4; WORD $0x1cf3             // vinsertps	$28, %xmm3, %xmm2, %xmm6 # xmm6 = xmm2[0],xmm3[0],zero,zero
	LONG $0xed58c8c5                           // vaddps	%xmm5, %xmm6, %xmm5
	LONG $0x2161e3c4; WORD $0x4cd2             // vinsertps	$76, %xmm2, %xmm3, %xmm2 # xmm2 = xmm2[1],xmm3[1],zero,zero
	LONG $0xd558e8c5                           // vaddps	%xmm5, %xmm2, %xmm2
	LONG $0x2171e3c4; WORD $0x1cd8             // vinsertps	$28, %xmm0, %xmm1, %xmm3 # xmm3 = xmm1[0],xmm0[0],zero,zero
	LONG $0xdc58e0c5                           // vaddps	%xmm4, %xmm3, %xmm3
	LONG $0x2179e3c4; WORD $0x4ce1             // vinsertps	$76, %xmm1, %xmm0, %xmm4 # xmm4 = xmm1[1],xmm0[1],zero,zero
	LONG $0xdb58d8c5                           // vaddps	%xmm3, %xmm4, %xmm3
	LONG $0xe1c6f1c5; BYTE $0x01               // vshufpd	$1, %xmm1, %xmm1, %xmm4         # xmm4 = xmm1[1,0]
	LONG $0x2159e3c4; WORD $0x9ce0             // vinsertps	$156, %xmm0, %xmm4, %xmm4 # xmm4 = xmm4[0],xmm0[2],zero,zero
	LONG $0xdb58d8c5                           // vaddps	%xmm3, %xmm4, %xmm3
	LONG $0xe0c6f9c5; BYTE $0x01               // vshufpd	$1, %xmm0, %xmm0, %xmm4         # xmm4 = xmm0[1,0]
	LONG $0x2159e3c4; WORD $0xcce1             // vinsertps	$204, %xmm1, %xmm4, %xmm4 # xmm4 = xmm1[3],xmm4[1],zero,zero
	LONG $0xdb58d8c5                           // vaddps	%xmm3, %xmm4, %xmm3
	LONG $0x197de3c4; WORD $0x01c4             // vextractf128	$1, %ymm0, %xmm4
	LONG $0x197de3c4; WORD $0x01cd             // vextractf128	$1, %ymm1, %xmm5
	LONG $0x2151e3c4; WORD $0x1cf4             // vinsertps	$28, %xmm4, %xmm5, %xmm6 # xmm6 = xmm5[0],xmm4[0],zero,zero
	LONG $0xdb58c8c5                           // vaddps	%xmm3, %xmm6, %xmm3
	LONG $0x2159e3c4; WORD $0x4cf5             // vinsertps	$76, %xmm5, %xmm4, %xmm6 # xmm6 = xmm5[1],xmm4[1],zero,zero
	LONG $0xdb58c8c5                           // vaddps	%xmm3, %xmm6, %xmm3
	LONG $0xf5c6d1c5; BYTE $0x01               // vshufpd	$1, %xmm5, %xmm5, %xmm6         # xmm6 = xmm5[1,0]
	LONG $0x2149e3c4; WORD $0x9cf4             // vinsertps	$156, %xmm4, %xmm6, %xmm6 # xmm6 = xmm6[0],xmm4[2],zero,zero
	LONG $0xdb58c8c5                           // vaddps	%xmm3, %xmm6, %xmm3
	LONG $0xe4c6d9c5; BYTE $0x01               // vshufpd	$1, %xmm4, %xmm4, %xmm4         # xmm4 = xmm4[1,0]
	LONG $0x2159e3c4; WORD $0xcce5             // vinsertps	$204, %xmm5, %xmm4, %xmm4 # xmm4 = xmm5[3],xmm4[1],zero,zero
	LONG $0xdb58d8c5                           // vaddps	%xmm3, %xmm4, %xmm3
	LONG $0x487df362; WORD $0xc419; BYTE $0x02 // vextractf32x4	$2, %zmm0, %xmm4
	LONG $0x487df362; WORD $0xcd19; BYTE $0x02 // vextractf32x4	$2, %zmm1, %xmm5
	LONG $0x2151e3c4; WORD $0x1cf4             // vinsertps	$28, %xmm4, %xmm5, %xmm6 # xmm6 = xmm5[0],xmm4[0],zero,zero
	LONG $0xdb58c8c5                           // vaddps	%xmm3, %xmm6, %xmm3
	LONG $0x2159e3c4; WORD $0x4ce5             // vinsertps	$76, %xmm5, %xmm4, %xmm4 # xmm4 = xmm5[1],xmm4[1],zero,zero
	LONG $0xdb58d8c5                           // vaddps	%xmm3, %xmm4, %xmm3
	LONG $0x48fdf362; WORD $0xc01b; BYTE $0x01 // vextractf64x4	$1, %zmm0, %ymm0
	LONG $0x48fdf362; WORD $0xc91b; BYTE $0x01 // vextractf64x4	$1, %zmm1, %ymm1
	LONG $0xe1c6f1c5; BYTE $0x01               // vshufpd	$1, %xmm1, %xmm1, %xmm4         # xmm4 = xmm1[1,0]
	LONG $0x2159e3c4; WORD $0x9ce0             // vinsertps	$156, %xmm0, %xmm4, %xmm4 # xmm4 = xmm4[0],xmm0[2],zero,zero
	LONG $0xdb58d8c5                           // vaddps	%xmm3, %xmm4, %xmm3
	LONG $0xe0c6f9c5; BYTE $0x01               // vshufpd	$1, %xmm0, %xmm0, %xmm4         # xmm4 = xmm0[1,0]
	LONG $0x2159e3c4; WORD $0xcce1             // vinsertps	$204, %xmm1, %xmm4, %xmm4 # xmm4 = xmm1[3],xmm4[1],zero,zero
	LONG $0xdb58d8c5                           // vaddps	%xmm3, %xmm4, %xmm3
	LONG $0x197de3c4; WORD $0x01c4             // vextractf128	$1, %ymm0, %xmm4
	LONG $0x197de3c4; WORD $0x01cd             // vextractf128	$1, %ymm1, %xmm5
	LONG $0x2151e3c4; WORD $0x1cf4             // vinsertps	$28, %xmm4, %xmm5, %xmm6 # xmm6 = xmm5[0],xmm4[0],zero,zero
	LONG $0xdb58c8c5                           // vaddps	%xmm3, %xmm6, %xmm3
	LONG $0x2159e3c4; WORD $0x4ce5             // vinsertps	$76, %xmm5, %xmm4, %xmm4 # xmm4 = xmm5[1],xmm4[1],zero,zero
	LONG $0xdb58d8c5                           // vaddps	%xmm3, %xmm4, %xmm3
	LONG $0x01fde3c4; WORD $0xffc0             // vpermpd	$255, %ymm0, %ymm0              # ymm0 = ymm0[3,3,3,3]
	LONG $0x01fde3c4; WORD $0xffc9             // vpermpd	$255, %ymm1, %ymm1              # ymm1 = ymm1[3,3,3,3]
	LONG $0x2171e3c4; WORD $0x1ce0             // vinsertps	$28, %xmm0, %xmm1, %xmm4 # xmm4 = xmm1[0],xmm0[0],zero,zero
	LONG $0xdb58d8c5                           // vaddps	%xmm3, %xmm4, %xmm3
	LONG $0x2179e3c4; WORD $0x4cc1             // vinsertps	$76, %xmm1, %xmm0, %xmm0 # xmm0 = xmm1[1],xmm0[1],zero,zero
	LONG $0xc358f8c5                           // vaddps	%xmm3, %xmm0, %xmm0
	LONG $0xc816e8c5                           // vmovlhps	%xmm0, %xmm2, %xmm1             # xmm1 = xmm2[0],xmm0[0]
	LONG $0x0811f8c5                           // vmovups	%xmm1, (%rax)
	WORD $0x394d; BYTE $0xca                   // cmpq	%r9, %r10
	JGE  LBB1_9
	LONG $0x0810fac5                           // vmovss	(%rax), %xmm1                   # xmm1 = mem[0],zero,zero,zero
	LONG $0x0c69e3c4; WORD $0x01c9             // vblendps	$1, %xmm1, %xmm2, %xmm1         # xmm1 = xmm1[0],xmm2[1,2,3]
	LONG $0xc016f0c5                           // vmovlhps	%xmm0, %xmm1, %xmm0             # xmm0 = xmm1[0],xmm0[0]

LBB1_7:
	LONG $0xc479a1c4; WORD $0x570c; BYTE $0x00 // vpinsrw	$0, (%rdi,%r10,2), %xmm0, %xmm1
	LONG $0x1379e2c4; BYTE $0xc9               // vcvtph2ps	%xmm1, %xmm1
	LONG $0xc479a1c4; WORD $0x5614; BYTE $0x00 // vpinsrw	$0, (%rsi,%r10,2), %xmm0, %xmm2
	LONG $0xc479a1c4; WORD $0x521c; BYTE $0x00 // vpinsrw	$0, (%rdx,%r10,2), %xmm0, %xmm3
	LONG $0xd361e9c5                           // vpunpcklwd	%xmm3, %xmm2, %xmm2     # xmm2 = xmm2[0],xmm3[0],xmm2[1],xmm3[1],xmm2[2],xmm3[2],xmm2[3],xmm3[3]
	LONG $0xc479a1c4; WORD $0x511c; BYTE $0x00 // vpinsrw	$0, (%rcx,%r10,2), %xmm0, %xmm3
	LONG $0xc47981c4; WORD $0x5024; BYTE $0x00 // vpinsrw	$0, (%r8,%r10,2), %xmm0, %xmm4
	LONG $0xdc61e1c5                           // vpunpcklwd	%xmm4, %xmm3, %xmm3     # xmm3 = xmm3[0],xmm4[0],xmm3[1],xmm4[1],xmm3[2],xmm4[2],xmm3[3],xmm4[3]
	LONG $0xd362e9c5                           // vpunpckldq	%xmm3, %xmm2, %xmm2     # xmm2 = xmm2[0],xmm3[0],xmm2[1],xmm3[1]
	LONG $0x1379e2c4; BYTE $0xd2               // vcvtph2ps	%xmm2, %xmm2
	LONG $0x1879e2c4; BYTE $0xc9               // vbroadcastss	%xmm1, %xmm1
	LONG $0xb869e2c4; BYTE $0xc1               // vfmadd231ps	%xmm1, %xmm2, %xmm0     # xmm0 = (xmm2 * xmm1) + xmm0
	WORD $0xff49; BYTE $0xc2                   // incq	%r10
	WORD $0x394d; BYTE $0xd1                   // cmpq	%r10, %r9
	JNE  LBB1_7
	LONG $0x0011f8c5                           // vmovups	%xmm0, (%rax)

LBB1_9:
	WORD $0x8948; BYTE $0xec // movq	%rbp, %rsp
	BYTE $0x5d               // popq	%rbp
	WORD $0xf8c5; BYTE $0x77 // vzeroupper
	POPQ DI
	POPQ DI
	RET

TEXT ·fp16_products_avx512_4(SB), $0-56
	MOVQ  query+0(FP), DI
	MOVQ  first+8(FP), SI
	MOVQ  second+16(FP), DX
	MOVQ  third+24(FP), CX
	MOVQ  fourth+32(FP), R8
	MOVQ  size+40(FP), R9
	PUSHQ output+48(FP)
	PUSHQ $0
	BYTE  $0x55                   // pushq	%rbp
	WORD  $0x8948; BYTE $0xe5     // movq	%rsp, %rbp
	LONG  $0xf8e48348             // andq	$-8, %rsp
	LONG  $0x10458b48             // movq	16(%rbp), %rax
	LONG  $0x10f98349             // cmpq	$16, %r9
	JGE   LBB2_2
	LONG  $0xc057f8c5             // vxorps	%xmm0, %xmm0, %xmm0
	WORD  $0x3145; BYTE $0xd2     // xorl	%r10d, %r10d
	LONG  $0xd257e8c5             // vxorps	%xmm2, %xmm2, %xmm2
	LONG  $0xc957f0c5             // vxorps	%xmm1, %xmm1, %xmm1
	LONG  $0xe457d8c5             // vxorps	%xmm4, %xmm4, %xmm4
	LONG  $0xdb57e0c5             // vxorps	%xmm3, %xmm3, %xmm3
	LONG  $0xed57d0c5             // vxorps	%xmm5, %xmm5, %xmm5
	LONG  $0xff57c0c5             // vxorps	%xmm7, %xmm7, %xmm7
	LONG  $0x573841c4; BYTE $0xc0 // vxorps	%xmm8, %xmm8, %xmm8
	LONG  $0xf657c8c5             // vxorps	%xmm6, %xmm6, %xmm6
	JMP   LBB2_5

LBB2_2:
	LONG $0xf657c8c5               // vxorps	%xmm6, %xmm6, %xmm6
	LONG $0x0010ba41; WORD $0x0000 // movl	$16, %r10d
	LONG $0x573841c4; BYTE $0xc0   // vxorps	%xmm8, %xmm8, %xmm8
	LONG $0xff57c0c5               // vxorps	%xmm7, %xmm7, %xmm7
	LONG $0xed57d0c5               // vxorps	%xmm5, %xmm5, %xmm5
	LONG $0xdb57e0c5               // vxorps	%xmm3, %xmm3, %xmm3
	LONG $0xe457d8c5               // vxorps	%xmm4, %xmm4, %xmm4
	LONG $0xc957f0c5               // vxorps	%xmm1, %xmm1, %xmm1
	LONG $0xd257e8c5               // vxorps	%xmm2, %xmm2, %xmm2
	LONG $0xc057f8c5               // vxorps	%xmm0, %xmm0, %xmm0

LBB2_3:
	QUAD $0xff574c13487d3262               // vcvtph2ps	-32(%rdi,%r10,2), %zmm9
	LONG $0x48345162; WORD $0xd159         // vmulps	%zmm9, %zmm9, %zmm10
	QUAD $0xff565c13487d3262               // vcvtph2ps	-32(%rsi,%r10,2), %zmm11
	LONG $0x4864d162; WORD $0xda58         // vaddps	%zmm10, %zmm3, %zmm3
	LONG $0x48345162; WORD $0xd359         // vmulps	%zmm11, %zmm9, %zmm10
	LONG $0x484cd162; WORD $0xf258         // vaddps	%zmm10, %zmm6, %zmm6
	LONG $0x48245162; WORD $0xd359         // vmulps	%zmm11, %zmm11, %zmm10
	LONG $0x485cd162; WORD $0xe258         // vaddps	%zmm10, %zmm4, %zmm4
	QUAD $0xff525413487d3262               // vcvtph2ps	-32(%rdx,%r10,2), %zmm10
	LONG $0x48345162; WORD $0xda59         // vmulps	%zmm10, %zmm9, %zmm11
	LONG $0x483c5162; WORD $0xc358         // vaddps	%zmm11, %zmm8, %zmm8
	LONG $0x482c5162; WORD $0xd259         // vmulps	%zmm10, %zmm10, %zmm10
	LONG $0x4874d162; WORD $0xca58         // vaddps	%zmm10, %zmm1, %zmm1
	QUAD $0xff515413487d3262               // vcvtph2ps	-32(%rcx,%r10,2), %zmm10
	LONG $0x48345162; WORD $0xda59         // vmulps	%zmm10, %zmm9, %zmm11
	LONG $0x4844d162; WORD $0xfb58         // vaddps	%zmm11, %zmm7, %zmm7
	QUAD $0xff505c13487d1262               // vcvtph2ps	-32(%r8,%r10,2), %zmm11
	LONG $0x482c5162; WORD $0xd259         // vmulps	%zmm10, %zmm10, %zmm10
	LONG $0x486cd162; WORD $0xd258         // vaddps	%zmm10, %zmm2, %zmm2
	LONG $0x48345162; WORD $0xcb59         // vmulps	%zmm11, %zmm9, %zmm9
	LONG $0x4854d162; WORD $0xe958         // vaddps	%zmm9, %zmm5, %zmm5
	LONG $0x48245162; WORD $0xcb59         // vmulps	%zmm11, %zmm11, %zmm9
	LONG $0x487cd162; WORD $0xc158         // vaddps	%zmm9, %zmm0, %zmm0
	LONG $0x10c28349                       // addq	$16, %r10
	WORD $0x394d; BYTE $0xca               // cmpq	%r9, %r10
	JLE  LBB2_3
	QUAD $0xfffffffffff0ba49; WORD $0x7fff // movabsq	$9223372036854775792, %r10      # imm = 0x7FFFFFFFFFFFFFF0
	WORD $0x214d; BYTE $0xca               // andq	%r9, %r10

LBB2_5:
	LONG    $0x144841c4; BYTE $0xc8                // vunpcklps	%xmm8, %xmm6, %xmm9     # xmm9 = xmm6[0],xmm8[0],xmm6[1],xmm8[1]
	LONG    $0xcf1630c5                            // vmovlhps	%xmm7, %xmm9, %xmm9             # xmm9 = xmm9[0],xmm7[0]
	LONG    $0x213163c4; WORD $0x30cd              // vinsertps	$48, %xmm5, %xmm9, %xmm9 # xmm9 = xmm9[0,1,2],xmm5[0]
	LONG    $0x572841c4; BYTE $0xd2                // vxorps	%xmm10, %xmm10, %xmm10
	LONG    $0x583041c4; BYTE $0xca                // vaddps	%xmm10, %xmm9, %xmm9
	LONG    $0x213963c4; WORD $0x4cd6              // vinsertps	$76, %xmm6, %xmm8, %xmm10 # xmm10 = xmm6[1],xmm8[1],zero,zero
	LONG    $0xd7c628c5; BYTE $0xd4                // vshufps	$212, %xmm7, %xmm10, %xmm10     # xmm10 = xmm10[0,1],xmm7[1,3]
	LONG    $0x212963c4; WORD $0x70d5              // vinsertps	$112, %xmm5, %xmm10, %xmm10 # xmm10 = xmm10[0,1,2],xmm5[1]
	LONG    $0x582841c4; BYTE $0xc9                // vaddps	%xmm9, %xmm10, %xmm9
	LONG    $0x154841c4; BYTE $0xd0                // vunpckhps	%xmm8, %xmm6, %xmm10    # xmm10 = xmm6[2],xmm8[2],xmm6[3],xmm8[3]
	LONG    $0x0c4143c4; WORD $0x03d2              // vblendps	$3, %xmm10, %xmm7, %xmm10       # xmm10 = xmm10[0,1],xmm7[2,3]
	LONG    $0x212963c4; WORD $0xb0d5              // vinsertps	$176, %xmm5, %xmm10, %xmm10 # xmm10 = xmm10[0,1,2],xmm5[2]
	LONG    $0x582841c4; BYTE $0xc9                // vaddps	%xmm9, %xmm10, %xmm9
	LONG    $0xd6c638c5; BYTE $0x33                // vshufps	$51, %xmm6, %xmm8, %xmm10       # xmm10 = xmm8[3,0],xmm6[3,0]
	LONG    $0xd7c628c5; BYTE $0xf2                // vshufps	$242, %xmm7, %xmm10, %xmm10     # xmm10 = xmm10[2,0],xmm7[3,3]
	LONG    $0x0c2963c4; WORD $0x08d5              // vblendps	$8, %xmm5, %xmm10, %xmm10       # xmm10 = xmm10[0,1,2],xmm5[3]
	LONG    $0x582841c4; BYTE $0xc9                // vaddps	%xmm9, %xmm10, %xmm9
	LONG    $0x197d43c4; WORD $0x01c2              // vextractf128	$1, %ymm8, %xmm10
	LONG    $0x197dc3c4; WORD $0x01f3              // vextractf128	$1, %ymm6, %xmm11
	LONG    $0x142041c4; BYTE $0xe2                // vunpcklps	%xmm10, %xmm11, %xmm12  # xmm12 = xmm11[0],xmm10[0],xmm11[1],xmm10[1]
	LONG    $0x197dc3c4; WORD $0x01fd              // vextractf128	$1, %ymm7, %xmm13
	LONG    $0x161841c4; BYTE $0xe5                // vmovlhps	%xmm13, %xmm12, %xmm12          # xmm12 = xmm12[0],xmm13[0]
	LONG    $0x197dc3c4; WORD $0x01ee              // vextractf128	$1, %ymm5, %xmm14
	LONG    $0x211943c4; WORD $0x30e6              // vinsertps	$48, %xmm14, %xmm12, %xmm12 # xmm12 = xmm12[0,1,2],xmm14[0]
	LONG    $0x581841c4; BYTE $0xc9                // vaddps	%xmm9, %xmm12, %xmm9
	LONG    $0x212943c4; WORD $0x4ce3              // vinsertps	$76, %xmm11, %xmm10, %xmm12 # xmm12 = xmm11[1],xmm10[1],zero,zero
	LONG    $0xc61841c4; WORD $0x54e5              // vshufps	$84, %xmm13, %xmm12, %xmm12     # xmm12 = xmm12[0,1],xmm13[1,1]
	LONG    $0x211943c4; WORD $0x70e6              // vinsertps	$112, %xmm14, %xmm12, %xmm12 # xmm12 = xmm12[0,1,2],xmm14[1]
	LONG    $0x581841c4; BYTE $0xc9                // vaddps	%xmm9, %xmm12, %xmm9
	LONG    $0x152041c4; BYTE $0xe2                // vunpckhps	%xmm10, %xmm11, %xmm12  # xmm12 = xmm11[2],xmm10[2],xmm11[3],xmm10[3]
	LONG    $0x0c1143c4; WORD $0x03e4              // vblendps	$3, %xmm12, %xmm13, %xmm12      # xmm12 = xmm12[0,1],xmm13[2,3]
	LONG    $0x211943c4; WORD $0xb0e6              // vinsertps	$176, %xmm14, %xmm12, %xmm12 # xmm12 = xmm12[0,1,2],xmm14[2]
	LONG    $0x581841c4; BYTE $0xc9                // vaddps	%xmm9, %xmm12, %xmm9
	LONG    $0xc62841c4; WORD $0x33d3              // vshufps	$51, %xmm11, %xmm10, %xmm10     # xmm10 = xmm10[3,0],xmm11[3,0]
	LONG    $0xc62841c4; WORD $0xf2d5              // vshufps	$242, %xmm13, %xmm10, %xmm10    # xmm10 = xmm10[2,0],xmm13[3,3]
	LONG    $0x0c2943c4; WORD $0x08d6              // vblendps	$8, %xmm14, %xmm10, %xmm10      # xmm10 = xmm10[0,1,2],xmm14[3]
	LONG    $0x582841c4; BYTE $0xc9                // vaddps	%xmm9, %xmm10, %xmm9
	LONG    $0x487d5362; WORD $0xc219; BYTE $0x02  // vextractf32x4	$2, %zmm8, %xmm10
	LONG    $0x487dd362; WORD $0xf319; BYTE $0x02  // vextractf32x4	$2, %zmm6, %xmm11
	LONG    $0x142041c4; BYTE $0xe2                // vunpcklps	%xmm10, %xmm11, %xmm12  # xmm12 = xmm11[0],xmm10[0],xmm11[1],xmm10[1]
	LONG    $0x487dd362; WORD $0xfd19; BYTE $0x02  // vextractf32x4	$2, %zmm7, %xmm13
	LONG    $0x161841c4; BYTE $0xe5                // vmovlhps	%xmm13, %xmm12, %xmm12          # xmm12 = xmm12[0],xmm13[0]
	LONG    $0x487dd362; WORD $0xee19; BYTE $0x02  // vextractf32x4	$2, %zmm5, %xmm14
	LONG    $0x211943c4; WORD $0x30e6              // vinsertps	$48, %xmm14, %xmm12, %xmm12 # xmm12 = xmm12[0,1,2],xmm14[0]
	LONG    $0x581841c4; BYTE $0xc9                // vaddps	%xmm9, %xmm12, %xmm9
	LONG    $0x212943c4; WORD $0x4ce3              // vinsertps	$76, %xmm11, %xmm10, %xmm12 # xmm12 = xmm11[1],xmm10[1],zero,zero
	LONG    $0xc61841c4; WORD $0x54e5              // vshufps	$84, %xmm13, %xmm12, %xmm12     # xmm12 = xmm12[0,1],xmm13[1,1]
	LONG    $0x211943c4; WORD $0x70e6              // vinsertps	$112, %xmm14, %xmm12, %xmm12 # xmm12 = xmm12[0,1,2],xmm14[1]
	LONG    $0x581841c4; BYTE $0xc9                // vaddps	%xmm9, %xmm12, %xmm9
	LONG    $0x152041c4; BYTE $0xe2                // vunpckhps	%xmm10, %xmm11, %xmm12  # xmm12 = xmm11[2],xmm10[2],xmm11[3],xmm10[3]
	LONG    $0x0c1143c4; WORD $0x03e4              // vblendps	$3, %xmm12, %xmm13, %xmm12      # xmm12 = xmm12[0,1],xmm13[2,3]
	LONG    $0x211943c4; WORD $0xb0e6              // vinsertps	$176, %xmm14, %xmm12, %xmm12 # xmm12 = xmm12[0,1,2],xmm14[2]
	LONG    $0x581841c4; BYTE $0xc9                // vaddps	%xmm9, %xmm12, %xmm9
	LONG    $0xc62841c4; WORD $0x33d3              // vshufps	$51, %xmm11, %xmm10, %xmm10     # xmm10 = xmm10[3,0],xmm11[3,0]
	LONG    $0xc62841c4; WORD $0xf2d5              // vshufps	$242, %xmm13, %xmm10, %xmm10    # xmm10 = xmm10[2,0],xmm13[3,3]
	LONG    $0x0c2943c4; WORD $0x08d6              // vblendps	$8, %xmm14, %xmm10, %xmm10      # xmm10 = xmm10[0,1,2],xmm14[3]
	LONG    $0x582841c4; BYTE $0xc9                // vaddps	%xmm9, %xmm10, %xmm9
	LONG    $0x487d5362; WORD $0xc019; BYTE $0x03  // vextractf32x4	$3, %zmm8, %xmm8
	LONG    $0x487df362; WORD $0xf619; BYTE $0x03  // vextractf32x4	$3, %zmm6, %xmm6
	LONG    $0x144841c4; BYTE $0xd0                // vunpcklps	%xmm8, %xmm6, %xmm10    # xmm10 = xmm6[0],xmm8[0],xmm6[1],xmm8[1]
	LONG    $0x487df362; WORD $0xff19; BYTE $0x03  // vextractf32x4	$3, %zmm7, %xmm7
	LONG    $0xd71628c5                            // vmovlhps	%xmm7, %xmm10, %xmm10           # xmm10 = xmm10[0],xmm7[0]
	LONG    $0x487df362; WORD $0xed19; BYTE $0x03  // vextractf32x4	$3, %zmm5, %xmm5
	LONG    $0x212963c4; WORD $0x30d5              // vinsertps	$48, %xmm5, %xmm10, %xmm10 # xmm10 = xmm10[0,1,2],xmm5[0]
	LONG    $0x582841c4; BYTE $0xc9                // vaddps	%xmm9, %xmm10, %xmm9
	LONG    $0x213963c4; WORD $0x4cd6              // vinsertps	$76, %xmm6, %xmm8, %xmm10 # xmm10 = xmm6[1],xmm8[1],zero,zero
	LONG    $0xd7c628c5; BYTE $0x54                // vshufps	$84, %xmm7, %xmm10, %xmm10      # xmm10 = xmm10[0,1],xmm7[1,1]
	LONG    $0x212963c4; WORD $0x70d5              // vinsertps	$112, %xmm5, %xmm10, %xmm10 # xmm10 = xmm10[0,1,2],xmm5[1]
	LONG    $0x582841c4; BYTE $0xc9                // vaddps	%xmm9, %xmm10, %xmm9
	LONG    $0x154841c4; BYTE $0xd0                // vunpckhps	%xmm8, %xmm6, %xmm10    # xmm10 = xmm6[2],xmm8[2],xmm6[3],xmm8[3]
	LONG    $0x0c4143c4; WORD $0x03d2              // vblendps	$3, %xmm10, %xmm7, %xmm10       # xmm10 = xmm10[0,1],xmm7[2,3]
	LONG    $0x212963c4; WORD $0xb0d5              // vinsertps	$176, %xmm5, %xmm10, %xmm10 # xmm10 = xmm10[0,1,2],xmm5[2]
	LONG    $0x582841c4; BYTE $0xc9                // vaddps	%xmm9, %xmm10, %xmm9
	LONG    $0xf6c6b8c5; BYTE $0x33                // vshufps	$51, %xmm6, %xmm8, %xmm6        # xmm6 = xmm8[3,0],xmm6[3,0]
	LONG    $0xf7c6c8c5; BYTE $0xf2                // vshufps	$242, %xmm7, %xmm6, %xmm6       # xmm6 = xmm6[2,0],xmm7[3,3]
	LONG    $0x0c49e3c4; WORD $0x08ed              // vblendps	$8, %xmm5, %xmm6, %xmm5         # xmm5 = xmm6[0,1,2],xmm5[3]
	LONG    $0xed58b0c5                            // vaddps	%xmm5, %xmm9, %xmm5
	LONG    $0xf47ce3c5                            // vhaddps	%xmm4, %xmm3, %xmm6
	LONG    $0x2811f8c5                            // vmovups	%xmm5, (%rax)
	LONG    $0xeec6c8c5; BYTE $0xe8                // vshufps	$232, %xmm6, %xmm6, %xmm5       # xmm5 = xmm6[0,2,2,3]
	LONG    $0xf3c6e1c5; BYTE $0x01                // vshufpd	$1, %xmm3, %xmm3, %xmm6         # xmm6 = xmm3[1,0]
	LONG    $0x2149e3c4; WORD $0x9cf4              // vinsertps	$156, %xmm4, %xmm6, %xmm6 # xmm6 = xmm6[0],xmm4[2],zero,zero
	LONG    $0xed58c8c5                            // vaddps	%xmm5, %xmm6, %xmm5
	LONG    $0xf4c6d9c5; BYTE $0x01                // vshufpd	$1, %xmm4, %xmm4, %xmm6         # xmm6 = xmm4[1,0]
	LONG    $0x2149e3c4; WORD $0xccf3              // vinsertps	$204, %xmm3, %xmm6, %xmm6 # xmm6 = xmm3[3],xmm6[1],zero,zero
	LONG    $0xed58c8c5                            // vaddps	%xmm5, %xmm6, %xmm5
	LONG    $0x197de3c4; WORD $0x01e6              // vextractf128	$1, %ymm4, %xmm6
	LONG    $0x197de3c4; WORD $0x01df              // vextractf128	$1, %ymm3, %xmm7
	LONG    $0x214163c4; WORD $0x1cc6              // vinsertps	$28, %xmm6, %xmm7, %xmm8 # xmm8 = xmm7[0],xmm6[0],zero,zero
	LONG    $0xed58b8c5                            // vaddps	%xmm5, %xmm8, %xmm5
	LONG    $0x214963c4; WORD $0x4cc7              // vinsertps	$76, %xmm7, %xmm6, %xmm8 # xmm8 = xmm7[1],xmm6[1],zero,zero
	LONG    $0xed58b8c5                            // vaddps	%xmm5, %xmm8, %xmm5
	LONG    $0xc7c641c5; BYTE $0x01                // vshufpd	$1, %xmm7, %xmm7, %xmm8         # xmm8 = xmm7[1,0]
	LONG    $0x213963c4; WORD $0x9cc6              // vinsertps	$156, %xmm6, %xmm8, %xmm8 # xmm8 = xmm8[0],xmm6[2],zero,zero
	LONG    $0xed58b8c5                            // vaddps	%xmm5, %xmm8, %xmm5
	LONG    $0xf6c6c9c5; BYTE $0x01                // vshufpd	$1, %xmm6, %xmm6, %xmm6         # xmm6 = xmm6[1,0]
	LONG    $0x2149e3c4; WORD $0xccf7              // vinsertps	$204, %xmm7, %xmm6, %xmm6 # xmm6 = xmm7[3],xmm6[1],zero,zero
	LONG    $0xed58c8c5                            // vaddps	%xmm5, %xmm6, %xmm5
	LONG    $0x487df362; WORD $0xe619; BYTE $0x02  // vextractf32x4	$2, %zmm4, %xmm6
	LONG    $0x487df362; WORD $0xdf19; BYTE $0x02  // vextractf32x4	$2, %zmm3, %xmm7
	LONG    $0x214163c4; WORD $0x1cc6              // vinsertps	$28, %xmm6, %xmm7, %xmm8 # xmm8 = xmm7[0],xmm6[0],zero,zero
	LONG    $0xed58b8c5                            // vaddps	%xmm5, %xmm8, %xmm5
	LONG    $0x2149e3c4; WORD $0x4cf7              // vinsertps	$76, %xmm7, %xmm6, %xmm6 # xmm6 = xmm7[1],xmm6[1],zero,zero
	LONG    $0xed58c8c5                            // vaddps	%xmm5, %xmm6, %xmm5
	LONG    $0x48fdf362; WORD $0xe41b; BYTE $0x01  // vextractf64x4	$1, %zmm4, %ymm4
	LONG    $0x48fdf362; WORD $0xdb1b; BYTE $0x01  // vextractf64x4	$1, %zmm3, %ymm3
	LONG    $0xf3c6e1c5; BYTE $0x01                // vshufpd	$1, %xmm3, %xmm3, %xmm6         # xmm6 = xmm3[1,0]
	LONG    $0x2149e3c4; WORD $0x9cf4              // vinsertps	$156, %xmm4, %xmm6, %xmm6 # xmm6 = xmm6[0],xmm4[2],zero,zero
	LONG    $0xed58c8c5                            // vaddps	%xmm5, %xmm6, %xmm5
	LONG    $0xf4c6d9c5; BYTE $0x01                // vshufpd	$1, %xmm4, %xmm4, %xmm6         # xmm6 = xmm4[1,0]
	LONG    $0x2149e3c4; WORD $0xccf3              // vinsertps	$204, %xmm3, %xmm6, %xmm6 # xmm6 = xmm3[3],xmm6[1],zero,zero
	LONG    $0xed58c8c5                            // vaddps	%xmm5, %xmm6, %xmm5
	LONG    $0x197de3c4; WORD $0x01e6              // vextractf128	$1, %ymm4, %xmm6
	LONG    $0x197de3c4; WORD $0x01df              // vextractf128	$1, %ymm3, %xmm7
	LONG    $0x214163c4; WORD $0x1cc6              // vinsertps	$28, %xmm6, %xmm7, %xmm8 # xmm8 = xmm7[0],xmm6[0],zero,zero
	LONG    $0xed58b8c5                            // vaddps	%xmm5, %xmm8, %xmm5
	LONG    $0x2149e3c4; WORD $0x4cf7              // vinsertps	$76, %xmm7, %xmm6, %xmm6 # xmm6 = xmm7[1],xmm6[1],zero,zero
	LONG    $0xed58c8c5                            // vaddps	%xmm5, %xmm6, %xmm5
	LONG    $0x01fde3c4; WORD $0xffe4              // vpermpd	$255, %ymm4, %ymm4              # ymm4 = ymm4[3,3,3,3]
	LONG    $0x01fde3c4; WORD $0xffdb              // vpermpd	$255, %ymm3, %ymm3              # ymm3 = ymm3[3,3,3,3]
	LONG    $0xf414e0c5                            // vunpcklps	%xmm4, %xmm3, %xmm6     # xmm6 = xmm3[0],xmm4[0],xmm3[1],xmm4[1]
	LONG    $0xed58c8c5                            // vaddps	%xmm5, %xmm6, %xmm5
	LONG    $0x2159e3c4; WORD $0x4cdb              // vinsertps	$76, %xmm3, %xmm4, %xmm3 # xmm3 = xmm3[1],xmm4[1],zero,zero
	LONG    $0xe27cf3c5                            // vhaddps	%xmm2, %xmm1, %xmm4
	LONG    $0xdd58e0c5                            // vaddps	%xmm5, %xmm3, %xmm3
	LONG    $0xe4c6d8c5; BYTE $0xe8                // vshufps	$232, %xmm4, %xmm4, %xmm4       # xmm4 = xmm4[0,2,2,3]
	LONG    $0xe9c6f1c5; BYTE $0x01                // vshufpd	$1, %xmm1, %xmm1, %xmm5         # xmm5 = xmm1[1,0]
	LONG    $0x2151e3c4; WORD $0x9cea              // vinsertps	$156, %xmm2, %xmm5, %xmm5 # xmm5 = xmm5[0],xmm2[2],zero,zero
	LONG    $0xe458d0c5                            // vaddps	%xmm4, %xmm5, %xmm4
	LONG    $0xeac6e9c5; BYTE $0x01                // vshufpd	$1, %xmm2, %xmm2, %xmm5         # xmm5 = xmm2[1,0]
	LONG    $0x2151e3c4; WORD $0xcce9              // vinsertps	$204, %xmm1, %xmm5, %xmm5 # xmm5 = xmm1[3],xmm5[1],zero,zero
	LONG    $0xe458d0c5                            // vaddps	%xmm4, %xmm5, %xmm4
	LONG    $0x197de3c4; WORD $0x01d5              // vextractf128	$1, %ymm2, %xmm5
	LONG    $0x197de3c4; WORD $0x01ce              // vextractf128	$1, %ymm1, %xmm6
	LONG    $0x2149e3c4; WORD $0x1cfd              // vinsertps	$28, %xmm5, %xmm6, %xmm7 # xmm7 = xmm6[0],xmm5[0],zero,zero
	LONG    $0xe458c0c5                            // vaddps	%xmm4, %xmm7, %xmm4
	LONG    $0x2151e3c4; WORD $0x4cfe              // vinsertps	$76, %xmm6, %xmm5, %xmm7 # xmm7 = xmm6[1],xmm5[1],zero,zero
	LONG    $0xe458c0c5                            // vaddps	%xmm4, %xmm7, %xmm4
	LONG    $0xfec6c9c5; BYTE $0x01                // vshufpd	$1, %xmm6, %xmm6, %xmm7         # xmm7 = xmm6[1,0]
	LONG    $0x2141e3c4; WORD $0x9cfd              // vinsertps	$156, %xmm5, %xmm7, %xmm7 # xmm7 = xmm7[0],xmm5[2],zero,zero
	LONG    $0xe458c0c5                            // vaddps	%xmm4, %xmm7, %xmm4
	LONG    $0xedc6d1c5; BYTE $0x01                // vshufpd	$1, %xmm5, %xmm5, %xmm5         # xmm5 = xmm5[1,0]
	LONG    $0x2151e3c4; WORD $0xccee              // vinsertps	$204, %xmm6, %xmm5, %xmm5 # xmm5 = xmm6[3],xmm5[1],zero,zero
	LONG    $0xe458d0c5                            // vaddps	%xmm4, %xmm5, %xmm4
	LONG    $0x487df362; WORD $0xd519; BYTE $0x02  // vextractf32x4	$2, %zmm2, %xmm5
	LONG    $0x487df362; WORD $0xce19; BYTE $0x02  // vextractf32x4	$2, %zmm1, %xmm6
	LONG    $0x2149e3c4; WORD $0x1cfd              // vinsertps	$28, %xmm5, %xmm6, %xmm7 # xmm7 = xmm6[0],xmm5[0],zero,zero
	LONG    $0xe458c0c5                            // vaddps	%xmm4, %xmm7, %xmm4
	LONG    $0x2151e3c4; WORD $0x4cee              // vinsertps	$76, %xmm6, %xmm5, %xmm5 # xmm5 = xmm6[1],xmm5[1],zero,zero
	LONG    $0xe458d0c5                            // vaddps	%xmm4, %xmm5, %xmm4
	LONG    $0x48fdf362; WORD $0xd21b; BYTE $0x01  // vextractf64x4	$1, %zmm2, %ymm2
	LONG    $0x48fdf362; WORD $0xc91b; BYTE $0x01  // vextractf64x4	$1, %zmm1, %ymm1
	LONG    $0xe9c6f1c5; BYTE $0x01                // vshufpd	$1, %xmm1, %xmm1, %xmm5         # xmm5 = xmm1[1,0]
	LONG    $0x2151e3c4; WORD $0x9cea              // vinsertps	$156, %xmm2, %xmm5, %xmm5 # xmm5 = xmm5[0],xmm2[2],zero,zero
	LONG    $0xe458d0c5                            // vaddps	%xmm4, %xmm5, %xmm4
	LONG    $0xeac6e9c5; BYTE $0x01                // vshufpd	$1, %xmm2, %xmm2, %xmm5         # xmm5 = xmm2[1,0]
	LONG    $0x2151e3c4; WORD $0xcce9              // vinsertps	$204, %xmm1, %xmm5, %xmm5 # xmm5 = xmm1[3],xmm5[1],zero,zero
	LONG    $0xe458d0c5                            // vaddps	%xmm4, %xmm5, %xmm4
	LONG    $0x197de3c4; WORD $0x01d5              // vextractf128	$1, %ymm2, %xmm5
	LONG    $0x197de3c4; WORD $0x01ce              // vextractf128	$1, %ymm1, %xmm6
	LONG    $0x2149e3c4; WORD $0x1cfd              // vinsertps	$28, %xmm5, %xmm6, %xmm7 # xmm7 = xmm6[0],xmm5[0],zero,zero
	LONG    $0xe458c0c5                            // vaddps	%xmm4, %xmm7, %xmm4
	LONG    $0x2151e3c4; WORD $0x4cee              // vinsertps	$76, %xmm6, %xmm5, %xmm5 # xmm5 = xmm6[1],xmm5[1],zero,zero
	LONG    $0xe458d0c5                            // vaddps	%xmm4, %xmm5, %xmm4
	LONG    $0x01fde3c4; WORD $0xffd2              // vpermpd	$255, %ymm2, %ymm2              # ymm2 = ymm2[3,3,3,3]
	LONG    $0x01fde3c4; WORD $0xffc9              // vpermpd	$255, %ymm1, %ymm1              # ymm1 = ymm1[3,3,3,3]
	LONG    $0x2171e3c4; WORD $0x1cea              // vinsertps	$28, %xmm2, %xmm1, %xmm5 # xmm5 = xmm1[0],xmm2[0],zero,zero
	LONG    $0xe458d0c5                            // vaddps	%xmm4, %xmm5, %xmm4
	LONG    $0x2169e3c4; WORD $0x4cc9              // vinsertps	$76, %xmm1, %xmm2, %xmm1 # xmm1 = xmm1[1],xmm2[1],zero,zero
	LONG    $0xcc58f0c5                            // vaddps	%xmm4, %xmm1, %xmm1
	LONG    $0xd116e0c5                            // vmovlhps	%xmm1, %xmm3, %xmm2             # xmm2 = xmm3[0],xmm1[0]
	LONG    $0x5011f8c5; BYTE $0x10                // vmovups	%xmm2, 16(%rax)
	LONG    $0xd016fac5                            // vmovshdup	%xmm0, %xmm2            # xmm2 = xmm0[1,1,3,3]
	LONG    $0xd258fac5                            // vaddss	%xmm2, %xmm0, %xmm2
	LONG    $0xd8c6f9c5; BYTE $0x01                // vshufpd	$1, %xmm0, %xmm0, %xmm3         # xmm3 = xmm0[1,0]
	LONG    $0xd258e2c5                            // vaddss	%xmm2, %xmm3, %xmm2
	LONG    $0xd8c6f8c5; BYTE $0xff                // vshufps	$255, %xmm0, %xmm0, %xmm3       # xmm3 = xmm0[3,3,3,3]
	LONG    $0xd258e2c5                            // vaddss	%xmm2, %xmm3, %xmm2
	LONG    $0x197de3c4; WORD $0x01c3              // vextractf128	$1, %ymm0, %xmm3
	LONG    $0xd258e2c5                            // vaddss	%xmm2, %xmm3, %xmm2
	LONG    $0xe316fac5                            // vmovshdup	%xmm3, %xmm4            # xmm4 = xmm3[1,1,3,3]
	LONG    $0xd258dac5                            // vaddss	%xmm2, %xmm4, %xmm2
	LONG    $0xe3c6e1c5; BYTE $0x01                // vshufpd	$1, %xmm3, %xmm3, %xmm4         # xmm4 = xmm3[1,0]
	LONG    $0xd258dac5                            // vaddss	%xmm2, %xmm4, %xmm2
	LONG    $0xdbc6e0c5; BYTE $0xff                // vshufps	$255, %xmm3, %xmm3, %xmm3       # xmm3 = xmm3[3,3,3,3]
	LONG    $0xd258e2c5                            // vaddss	%xmm2, %xmm3, %xmm2
	LONG    $0x487df362; WORD $0xc319; BYTE $0x02  // vextractf32x4	$2, %zmm0, %xmm3
	LONG    $0xd258e2c5                            // vaddss	%xmm2, %xmm3, %xmm2
	LONG    $0xe316fac5                            // vmovshdup	%xmm3, %xmm4            # xmm4 = xmm3[1,1,3,3]
	LONG    $0xd258dac5                            // vaddss	%xmm2, %xmm4, %xmm2
	LONG    $0xe3c6e1c5; BYTE $0x01                // vshufpd	$1, %xmm3, %xmm3, %xmm4         # xmm4 = xmm3[1,0]
	LONG    $0xd258dac5                            // vaddss	%xmm2, %xmm4, %xmm2
	LONG    $0xdbc6e0c5; BYTE $0xff                // vshufps	$255, %xmm3, %xmm3, %xmm3       # xmm3 = xmm3[3,3,3,3]
	LONG    $0xd258e2c5                            // vaddss	%xmm2, %xmm3, %xmm2
	LONG    $0x487df362; WORD $0xc019; BYTE $0x03  // vextractf32x4	$3, %zmm0, %xmm0
	LONG    $0xd258fac5                            // vaddss	%xmm2, %xmm0, %xmm2
	LONG    $0xd816fac5                            // vmovshdup	%xmm0, %xmm3            # xmm3 = xmm0[1,1,3,3]
	LONG    $0xd258e2c5                            // vaddss	%xmm2, %xmm3, %xmm2
	LONG    $0xd8c6f9c5; BYTE $0x01                // vshufpd	$1, %xmm0, %xmm0, %xmm3         # xmm3 = xmm0[1,0]
	LONG    $0xd258e2c5                            // vaddss	%xmm2, %xmm3, %xmm2
	LONG    $0xc0c6f8c5; BYTE $0xff                // vshufps	$255, %xmm0, %xmm0, %xmm0       # xmm0 = xmm0[3,3,3,3]
	LONG    $0xc258fac5                            // vaddss	%xmm2, %xmm0, %xmm0
	LONG    $0x4011fac5; BYTE $0x20                // vmovss	%xmm0, 32(%rax)
	WORD    $0x394d; BYTE $0xca                    // cmpq	%r9, %r10
	JGE     LBB2_9
	LONG    $0x197de2c4; BYTE $0xc9                // vbroadcastsd	%xmm1, %ymm1
	LONG    $0x1875e3c4; WORD $0x0008              // vinsertf128	$0, (%rax), %ymm1, %ymm1
	LONG    $0x197de2c4; WORD $0x1050              // vbroadcastsd	16(%rax), %ymm2
	LONG    $0x0c75e3c4; WORD $0x30ca              // vblendps	$48, %ymm2, %ymm1, %ymm1        # ymm1 = ymm1[0,1,2,3],ymm2[4,5],ymm1[6,7]
	VMOVDQA __goat_data_2e4c435049325f30<>(SB), X2
	VMOVAPS __goat_data_2e4c435049325f31<>(SB), Y3

LBB2_7:
	LONG $0xc479a1c4; WORD $0x5724; BYTE $0x00 // vpinsrw	$0, (%rdi,%r10,2), %xmm0, %xmm4
	LONG $0xc479a1c4; WORD $0x562c; BYTE $0x00 // vpinsrw	$0, (%rsi,%r10,2), %xmm0, %xmm5
	LONG $0xc479a1c4; WORD $0x5234; BYTE $0x00 // vpinsrw	$0, (%rdx,%r10,2), %xmm0, %xmm6
	LONG $0xc479a1c4; WORD $0x513c; BYTE $0x00 // vpinsrw	$0, (%rcx,%r10,2), %xmm0, %xmm7
	LONG $0xc47901c4; WORD $0x5004; BYTE $0x00 // vpinsrw	$0, (%r8,%r10,2), %xmm0, %xmm8
	LONG $0xf772b1c5; BYTE $0x10               // vpslld	$16, %xmm7, %xmm9
	LONG $0xf572a9c5; BYTE $0x10               // vpslld	$16, %xmm5, %xmm10
	LONG $0x622941c4; BYTE $0xc9               // vpunpckldq	%xmm9, %xmm10, %xmm9    # xmm9 = xmm10[0],xmm9[0],xmm10[1],xmm9[1]
	LONG $0xd66159c5                           // vpunpcklwd	%xmm6, %xmm4, %xmm10    # xmm10 = xmm4[0],xmm6[0],xmm4[1],xmm6[1],xmm4[2],xmm6[2],xmm4[3],xmm6[3]
	LONG $0x7221c1c4; WORD $0x10f0             // vpslld	$16, %xmm8, %xmm11
	LONG $0x622941c4; BYTE $0xd3               // vpunpckldq	%xmm11, %xmm10, %xmm10  # xmm10 = xmm10[0],xmm11[0],xmm10[1],xmm11[1]
	LONG $0x6c2941c4; BYTE $0xc9               // vpunpcklqdq	%xmm9, %xmm10, %xmm9    # xmm9 = xmm10[0],xmm9[0]
	LONG $0x003162c4; BYTE $0xca               // vpshufb	%xmm2, %xmm9, %xmm9
	LONG $0x137d42c4; BYTE $0xc9               // vcvtph2ps	%xmm9, %ymm9
	LONG $0xf661c1c5                           // vpunpcklwd	%xmm6, %xmm7, %xmm6     # xmm6 = xmm7[0],xmm6[0],xmm7[1],xmm6[1],xmm7[2],xmm6[2],xmm7[3],xmm6[3]
	LONG $0xe461d1c5                           // vpunpcklwd	%xmm4, %xmm5, %xmm4     # xmm4 = xmm5[0],xmm4[0],xmm5[1],xmm4[1],xmm5[2],xmm4[2],xmm5[3],xmm4[3]
	LONG $0xe662d9c5                           // vpunpckldq	%xmm6, %xmm4, %xmm4     # xmm4 = xmm4[0],xmm6[0],xmm4[1],xmm6[1]
	LONG $0x1379e2c4; BYTE $0xe4               // vcvtph2ps	%xmm4, %xmm4
	LONG $0x1665e2c4; BYTE $0xe4               // vpermps	%ymm4, %ymm3, %ymm4
	LONG $0x1379c2c4; BYTE $0xe8               // vcvtph2ps	%xmm8, %xmm5
	LONG $0xb835e2c4; BYTE $0xcc               // vfmadd231ps	%ymm4, %ymm9, %ymm1     # ymm1 = (ymm9 * ymm4) + ymm1
	LONG $0xb951e2c4; BYTE $0xc5               // vfmadd231ss	%xmm5, %xmm5, %xmm0     # xmm0 = (xmm5 * xmm5) + xmm0
	WORD $0xff49; BYTE $0xc2                   // incq	%r10
	WORD $0x394d; BYTE $0xd1                   // cmpq	%r10, %r9
	JNE  LBB2_7
	LONG $0x0811fcc5                           // vmovups	%ymm1, (%rax)
	LONG $0x4011fac5; BYTE $0x20               // vmovss	%xmm0, 32(%rax)

LBB2_9:
	WORD $0x8948; BYTE $0xec // movq	%rbp, %rsp
	BYTE $0x5d               // popq	%rbp
	WORD $0xf8c5; BYTE $0x77 // vzeroupper
	POPQ DI
	POPQ DI
	RET
