//go:build !noasm && amd64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8 (6ubuntu1)
// 	objdump 2.46
// flags: -mavx2 -O3
// source: src/inner_product_batch_int4_avx2.c

DATA __goat_data_2e4c435049305f30<>+0x000(SB)/8, $0x0f0f0f0f0f0f0f0f
DATA __goat_data_2e4c435049305f30<>+0x008(SB)/8, $0x0f0f0f0f0f0f0f0f
DATA __goat_data_2e4c435049305f30<>+0x010(SB)/8, $0x0f0f0f0f0f0f0f0f
DATA __goat_data_2e4c435049305f30<>+0x018(SB)/8, $0x0f0f0f0f0f0f0f0f
GLOBL __goat_data_2e4c435049305f30<>(SB), 8, $32

DATA __goat_data_2e4c435049305f31<>+0x000(SB)/8, $0x0808080808080808
DATA __goat_data_2e4c435049305f31<>+0x008(SB)/8, $0x0808080808080808
DATA __goat_data_2e4c435049305f31<>+0x010(SB)/8, $0x0808080808080808
DATA __goat_data_2e4c435049305f31<>+0x018(SB)/8, $0x0808080808080808
GLOBL __goat_data_2e4c435049305f31<>(SB), 8, $32

DATA __goat_data_2e4c435049305f32<>+0x000(SB)/8, $0xf0f0f0f0f0f0f0f0
DATA __goat_data_2e4c435049305f32<>+0x008(SB)/8, $0xf0f0f0f0f0f0f0f0
DATA __goat_data_2e4c435049305f32<>+0x010(SB)/8, $0xf0f0f0f0f0f0f0f0
DATA __goat_data_2e4c435049305f32<>+0x018(SB)/8, $0xf0f0f0f0f0f0f0f0
GLOBL __goat_data_2e4c435049305f32<>(SB), 8, $32

DATA __goat_data_2e4c435049305f33<>+0x000(SB)/8, $0x0001000100010001
DATA __goat_data_2e4c435049305f33<>+0x008(SB)/8, $0x0001000100010001
DATA __goat_data_2e4c435049305f33<>+0x010(SB)/8, $0x0001000100010001
DATA __goat_data_2e4c435049305f33<>+0x018(SB)/8, $0x0001000100010001
GLOBL __goat_data_2e4c435049305f33<>(SB), 8, $32

DATA __goat_data_2e4c435049305f34<>+0x000(SB)/1, $0x0f
GLOBL __goat_data_2e4c435049305f34<>(SB), 8, $1

DATA __goat_data_2e4c435049305f35<>+0x000(SB)/1, $0x08
GLOBL __goat_data_2e4c435049305f35<>(SB), 8, $1

DATA __goat_data_2e4c435049305f36<>+0x000(SB)/2, $0x00f0
GLOBL __goat_data_2e4c435049305f36<>(SB), 8, $2

DATA __goat_data_2e4c435049305f37<>+0x000(SB)/2, $0x0001
GLOBL __goat_data_2e4c435049305f37<>(SB), 8, $2

TEXT ·xvec_avx2_batch_inner_products_int4_4(SB), $0-56
	MOVQ         query+0(FP), DI
	MOVQ         first+8(FP), SI
	MOVQ         second+16(FP), DX
	MOVQ         third+24(FP), CX
	MOVQ         fourth+32(FP), R8
	MOVQ         size+40(FP), R9
	PUSHQ        output+48(FP)
	PUSHQ        $0
	BYTE         $0x55                                  // pushq	%rbp
	WORD         $0x8948; BYTE $0xe5                    // movq	%rsp, %rbp
	LONG         $0xf8e48348                            // andq	$-8, %rsp
	LONG         $0x10458b48                            // movq	16(%rbp), %rax
	LONG         $0xc0eff9c5                            // vpxor	%xmm0, %xmm0, %xmm0
	WORD         $0x854d; BYTE $0xc9                    // testq	%r9, %r9
	JE           LBB0_6
	VPBROADCASTB __goat_data_2e4c435049305f34<>(SB), Y1
	VPBROADCASTB __goat_data_2e4c435049305f35<>(SB), Y2
	VPBROADCASTB __goat_data_2e4c435049305f36<>(SB), Y3
	VPBROADCASTW __goat_data_2e4c435049305f37<>(SB), Y4
	JMP          LBB0_2

LBB0_5:
	LONG $0x397d43c4; WORD $0x01c1 // vextracti128	$1, %ymm8, %xmm9
	LONG $0xfe3941c4; BYTE $0xc1   // vpaddd	%xmm9, %xmm8, %xmm8
	WORD $0x014c; BYTE $0xd6       // addq	%r10, %rsi
	LONG $0x397dc3c4; WORD $0x01f9 // vextracti128	$1, %ymm7, %xmm9
	LONG $0xfffeb1c5               // vpaddd	%xmm7, %xmm9, %xmm7
	LONG $0x0239e2c4; BYTE $0xff   // vphaddd	%xmm7, %xmm8, %xmm7
	WORD $0x014c; BYTE $0xd2       // addq	%r10, %rdx
	LONG $0x397dc3c4; WORD $0x01f0 // vextracti128	$1, %ymm6, %xmm8
	LONG $0xf6feb9c5               // vpaddd	%xmm6, %xmm8, %xmm6
	WORD $0x014c; BYTE $0xd1       // addq	%r10, %rcx
	LONG $0x397dc3c4; WORD $0x01e8 // vextracti128	$1, %ymm5, %xmm8
	LONG $0xedfeb9c5               // vpaddd	%xmm5, %xmm8, %xmm5
	LONG $0x0249e2c4; BYTE $0xed   // vphaddd	%xmm5, %xmm6, %xmm5
	LONG $0x0241e2c4; BYTE $0xed   // vphaddd	%xmm5, %xmm7, %xmm5
	LONG $0x257de2c4; BYTE $0xed   // vpmovsxdq	%xmm5, %ymm5
	LONG $0xc5d4fdc5               // vpaddq	%ymm5, %ymm0, %ymm0
	WORD $0x014d; BYTE $0xd0       // addq	%r10, %r8
	WORD $0x014c; BYTE $0xd7       // addq	%r10, %rdi
	WORD $0x294d; BYTE $0xd1       // subq	%r10, %r9
	JE   LBB0_6

LBB0_2:
	LONG $0x00f98149; WORD $0x1000; BYTE $0x00 // cmpq	$1048576, %r9                   # imm = 0x100000
	LONG $0x0000ba41; WORD $0x0010             // movl	$1048576, %r10d                 # imm = 0x100000
	LONG $0xd14c0f4d                           // cmovlq	%r9, %r10
	LONG $0xedefd1c5                           // vpxor	%xmm5, %xmm5, %xmm5
	LONG $0xf6efc9c5                           // vpxor	%xmm6, %xmm6, %xmm6
	LONG $0xffefc1c5                           // vpxor	%xmm7, %xmm7, %xmm7
	LONG $0xef3941c4; BYTE $0xc0               // vpxor	%xmm8, %xmm8, %xmm8
	WORD $0x854d; BYTE $0xc9                   // testq	%r9, %r9
	JLE  LBB0_5
	WORD $0x3145; BYTE $0xdb                   // xorl	%r11d, %r11d

LBB0_4:
	LONG $0x6f7e21c4; WORD $0x1f0c // vmovdqu	(%rdi,%r11), %ymm9
	LONG $0x712dc1c4; WORD $0x04f1 // vpsllw	$4, %ymm9, %ymm10
	LONG $0x712dc1c4; WORD $0x04d2 // vpsrlw	$4, %ymm10, %ymm10
	LONG $0xd1db2dc5               // vpand	%ymm1, %ymm10, %ymm10
	LONG $0xd2ef2dc5               // vpxor	%ymm2, %ymm10, %ymm10
	LONG $0xdaf82dc5               // vpsubb	%ymm2, %ymm10, %ymm11
	LONG $0xcbdb35c5               // vpand	%ymm3, %ymm9, %ymm9
	LONG $0x7135c1c4; WORD $0x04d1 // vpsrlw	$4, %ymm9, %ymm9
	LONG $0xcaef35c5               // vpxor	%ymm2, %ymm9, %ymm9
	LONG $0xcaf835c5               // vpsubb	%ymm2, %ymm9, %ymm9
	LONG $0x1c7d42c4; BYTE $0xe3   // vpabsb	%ymm11, %ymm12
	LONG $0x1c7d42c4; BYTE $0xd1   // vpabsb	%ymm9, %ymm10
	LONG $0x6f7e21c4; WORD $0x1e2c // vmovdqu	(%rsi,%r11), %ymm13
	LONG $0x710dc1c4; WORD $0x04f5 // vpsllw	$4, %ymm13, %ymm14
	LONG $0x710dc1c4; WORD $0x04d6 // vpsrlw	$4, %ymm14, %ymm14
	LONG $0xf1db0dc5               // vpand	%ymm1, %ymm14, %ymm14
	LONG $0xf2ef0dc5               // vpxor	%ymm2, %ymm14, %ymm14
	LONG $0xf2f80dc5               // vpsubb	%ymm2, %ymm14, %ymm14
	LONG $0x080d42c4; BYTE $0xf3   // vpsignb	%ymm11, %ymm14, %ymm14
	LONG $0x041d42c4; BYTE $0xf6   // vpmaddubsw	%ymm14, %ymm12, %ymm14
	LONG $0xf4f50dc5               // vpmaddwd	%ymm4, %ymm14, %ymm14
	LONG $0xebdb15c5               // vpand	%ymm3, %ymm13, %ymm13
	LONG $0x7115c1c4; WORD $0x04d5 // vpsrlw	$4, %ymm13, %ymm13
	LONG $0xeaef15c5               // vpxor	%ymm2, %ymm13, %ymm13
	LONG $0xeaf815c5               // vpsubb	%ymm2, %ymm13, %ymm13
	LONG $0x081542c4; BYTE $0xe9   // vpsignb	%ymm9, %ymm13, %ymm13
	LONG $0x042d42c4; BYTE $0xed   // vpmaddubsw	%ymm13, %ymm10, %ymm13
	LONG $0xecf515c5               // vpmaddwd	%ymm4, %ymm13, %ymm13
	LONG $0xfe3d41c4; BYTE $0xc5   // vpaddd	%ymm13, %ymm8, %ymm8
	LONG $0xfe0d41c4; BYTE $0xc0   // vpaddd	%ymm8, %ymm14, %ymm8
	LONG $0x6f7e21c4; WORD $0x1a2c // vmovdqu	(%rdx,%r11), %ymm13
	LONG $0x710dc1c4; WORD $0x04f5 // vpsllw	$4, %ymm13, %ymm14
	LONG $0x710dc1c4; WORD $0x04d6 // vpsrlw	$4, %ymm14, %ymm14
	LONG $0xf1db0dc5               // vpand	%ymm1, %ymm14, %ymm14
	LONG $0xf2ef0dc5               // vpxor	%ymm2, %ymm14, %ymm14
	LONG $0xf2f80dc5               // vpsubb	%ymm2, %ymm14, %ymm14
	LONG $0x080d42c4; BYTE $0xf3   // vpsignb	%ymm11, %ymm14, %ymm14
	LONG $0x041d42c4; BYTE $0xf6   // vpmaddubsw	%ymm14, %ymm12, %ymm14
	LONG $0xf4f50dc5               // vpmaddwd	%ymm4, %ymm14, %ymm14
	LONG $0xebdb15c5               // vpand	%ymm3, %ymm13, %ymm13
	LONG $0x7115c1c4; WORD $0x04d5 // vpsrlw	$4, %ymm13, %ymm13
	LONG $0xeaef15c5               // vpxor	%ymm2, %ymm13, %ymm13
	LONG $0xeaf815c5               // vpsubb	%ymm2, %ymm13, %ymm13
	LONG $0x081542c4; BYTE $0xe9   // vpsignb	%ymm9, %ymm13, %ymm13
	LONG $0x042d42c4; BYTE $0xed   // vpmaddubsw	%ymm13, %ymm10, %ymm13
	LONG $0xecf515c5               // vpmaddwd	%ymm4, %ymm13, %ymm13
	LONG $0xfffe95c5               // vpaddd	%ymm7, %ymm13, %ymm7
	LONG $0xfffe8dc5               // vpaddd	%ymm7, %ymm14, %ymm7
	LONG $0x6f7e21c4; WORD $0x192c // vmovdqu	(%rcx,%r11), %ymm13
	LONG $0x710dc1c4; WORD $0x04f5 // vpsllw	$4, %ymm13, %ymm14
	LONG $0x710dc1c4; WORD $0x04d6 // vpsrlw	$4, %ymm14, %ymm14
	LONG $0xf1db0dc5               // vpand	%ymm1, %ymm14, %ymm14
	LONG $0xf2ef0dc5               // vpxor	%ymm2, %ymm14, %ymm14
	LONG $0xf2f80dc5               // vpsubb	%ymm2, %ymm14, %ymm14
	LONG $0x080d42c4; BYTE $0xf3   // vpsignb	%ymm11, %ymm14, %ymm14
	LONG $0x041d42c4; BYTE $0xf6   // vpmaddubsw	%ymm14, %ymm12, %ymm14
	LONG $0xf4f50dc5               // vpmaddwd	%ymm4, %ymm14, %ymm14
	LONG $0xebdb15c5               // vpand	%ymm3, %ymm13, %ymm13
	LONG $0x7115c1c4; WORD $0x04d5 // vpsrlw	$4, %ymm13, %ymm13
	LONG $0xeaef15c5               // vpxor	%ymm2, %ymm13, %ymm13
	LONG $0xeaf815c5               // vpsubb	%ymm2, %ymm13, %ymm13
	LONG $0x081542c4; BYTE $0xe9   // vpsignb	%ymm9, %ymm13, %ymm13
	LONG $0x042d42c4; BYTE $0xed   // vpmaddubsw	%ymm13, %ymm10, %ymm13
	LONG $0xecf515c5               // vpmaddwd	%ymm4, %ymm13, %ymm13
	LONG $0xf6fe95c5               // vpaddd	%ymm6, %ymm13, %ymm6
	LONG $0xf6fe8dc5               // vpaddd	%ymm6, %ymm14, %ymm6
	LONG $0x6f7e01c4; WORD $0x182c // vmovdqu	(%r8,%r11), %ymm13
	LONG $0x710dc1c4; WORD $0x04f5 // vpsllw	$4, %ymm13, %ymm14
	LONG $0x710dc1c4; WORD $0x04d6 // vpsrlw	$4, %ymm14, %ymm14
	LONG $0xf1db0dc5               // vpand	%ymm1, %ymm14, %ymm14
	LONG $0xf2ef0dc5               // vpxor	%ymm2, %ymm14, %ymm14
	LONG $0xf2f80dc5               // vpsubb	%ymm2, %ymm14, %ymm14
	LONG $0x080d42c4; BYTE $0xdb   // vpsignb	%ymm11, %ymm14, %ymm11
	LONG $0x041d42c4; BYTE $0xdb   // vpmaddubsw	%ymm11, %ymm12, %ymm11
	LONG $0xdcf525c5               // vpmaddwd	%ymm4, %ymm11, %ymm11
	LONG $0xe3db15c5               // vpand	%ymm3, %ymm13, %ymm12
	LONG $0x711dc1c4; WORD $0x04d4 // vpsrlw	$4, %ymm12, %ymm12
	LONG $0xe2ef1dc5               // vpxor	%ymm2, %ymm12, %ymm12
	LONG $0xe2f81dc5               // vpsubb	%ymm2, %ymm12, %ymm12
	LONG $0x081d42c4; BYTE $0xc9   // vpsignb	%ymm9, %ymm12, %ymm9
	LONG $0x042d42c4; BYTE $0xc9   // vpmaddubsw	%ymm9, %ymm10, %ymm9
	LONG $0xccf535c5               // vpmaddwd	%ymm4, %ymm9, %ymm9
	LONG $0xedfeb5c5               // vpaddd	%ymm5, %ymm9, %ymm5
	LONG $0xedfea5c5               // vpaddd	%ymm5, %ymm11, %ymm5
	LONG $0x20c38349               // addq	$32, %r11
	WORD $0x394d; BYTE $0xd3       // cmpq	%r10, %r11
	JL   LBB0_4
	JMP  LBB0_5

LBB0_6:
	LONG $0x007ffec5         // vmovdqu	%ymm0, (%rax)
	WORD $0x8948; BYTE $0xec // movq	%rbp, %rsp
	BYTE $0x5d               // popq	%rbp
	WORD $0xf8c5; BYTE $0x77 // vzeroupper
	POPQ DI
	POPQ DI
	RET
