//go:build !noasm && amd64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8 (6ubuntu1)
// 	objdump 2.46
// flags: -mavx2 -O3
// source: src/inner_product_batch_int8_avx2.c

TEXT ·xvec_avx2_batch_inner_products_int8_4(SB), $0-56
	MOVQ  query+0(FP), DI
	MOVQ  first+8(FP), SI
	MOVQ  second+16(FP), DX
	MOVQ  third+24(FP), CX
	MOVQ  fourth+32(FP), R8
	MOVQ  size+40(FP), R9
	PUSHQ output+48(FP)
	PUSHQ $0
	BYTE  $0x55               // pushq	%rbp
	WORD  $0x8948; BYTE $0xe5 // movq	%rsp, %rbp
	WORD  $0x5741             // pushq	%r15
	WORD  $0x5641             // pushq	%r14
	WORD  $0x5541             // pushq	%r13
	WORD  $0x5441             // pushq	%r12
	BYTE  $0x53               // pushq	%rbx
	LONG  $0xf8e48348         // andq	$-8, %rsp
	LONG  $0xc0eff9c5         // vpxor	%xmm0, %xmm0, %xmm0
	WORD  $0xc031             // xorl	%eax, %eax
	WORD  $0x3145; BYTE $0xd2 // xorl	%r10d, %r10d
	LONG  $0x20f98349         // cmpq	$32, %r9
	JL    LBB0_1

LBB0_10:
	LONG $0x00f98149; WORD $0x0100; BYTE $0x00 // cmpq	$65536, %r9                     # imm = 0x10000
	LONG $0x0000bb41; WORD $0x0001             // movl	$65536, %r11d                   # imm = 0x10000
	LONG $0xd9420f4d                           // cmovbq	%r9, %r11
	LONG $0xe0e38141; WORD $0x01ff; BYTE $0x00 // andl	$131040, %r11d                  # imm = 0x1FFE0
	LONG $0xc9eff1c5                           // vpxor	%xmm1, %xmm1, %xmm1
	LONG $0xd2efe9c5                           // vpxor	%xmm2, %xmm2, %xmm2
	LONG $0xdbefe1c5                           // vpxor	%xmm3, %xmm3, %xmm3
	LONG $0xedefd1c5                           // vpxor	%xmm5, %xmm5, %xmm5
	LONG $0xe4efd9c5                           // vpxor	%xmm4, %xmm4, %xmm4
	LONG $0xf6efc9c5                           // vpxor	%xmm6, %xmm6, %xmm6
	LONG $0xffefc1c5                           // vpxor	%xmm7, %xmm7, %xmm7
	LONG $0xef3941c4; BYTE $0xc0               // vpxor	%xmm8, %xmm8, %xmm8
	WORD $0xdb31                               // xorl	%ebx, %ebx

LBB0_11:
	LONG $0x207d62c4; WORD $0x1f0c             // vpmovsxbw	(%rdi,%rbx), %ymm9
	LONG $0x207d62c4; WORD $0x1f54; BYTE $0x10 // vpmovsxbw	16(%rdi,%rbx), %ymm10
	LONG $0x207d62c4; WORD $0x1e1c             // vpmovsxbw	(%rsi,%rbx), %ymm11
	LONG $0x207d62c4; WORD $0x1e64; BYTE $0x10 // vpmovsxbw	16(%rsi,%rbx), %ymm12
	LONG $0xf53541c4; BYTE $0xdb               // vpmaddwd	%ymm11, %ymm9, %ymm11
	LONG $0xedfea5c5                           // vpaddd	%ymm5, %ymm11, %ymm5
	LONG $0xf52d41c4; BYTE $0xdc               // vpmaddwd	%ymm12, %ymm10, %ymm11
	LONG $0xfe2541c4; BYTE $0xc0               // vpaddd	%ymm8, %ymm11, %ymm8
	LONG $0x207d62c4; WORD $0x1a1c             // vpmovsxbw	(%rdx,%rbx), %ymm11
	LONG $0x207d62c4; WORD $0x1a64; BYTE $0x10 // vpmovsxbw	16(%rdx,%rbx), %ymm12
	LONG $0xf53541c4; BYTE $0xdb               // vpmaddwd	%ymm11, %ymm9, %ymm11
	LONG $0xdbfea5c5                           // vpaddd	%ymm3, %ymm11, %ymm3
	LONG $0xf52d41c4; BYTE $0xdc               // vpmaddwd	%ymm12, %ymm10, %ymm11
	LONG $0xfffea5c5                           // vpaddd	%ymm7, %ymm11, %ymm7
	LONG $0x207d62c4; WORD $0x191c             // vpmovsxbw	(%rcx,%rbx), %ymm11
	LONG $0x207d62c4; WORD $0x1964; BYTE $0x10 // vpmovsxbw	16(%rcx,%rbx), %ymm12
	LONG $0xf53541c4; BYTE $0xdb               // vpmaddwd	%ymm11, %ymm9, %ymm11
	LONG $0xd2fea5c5                           // vpaddd	%ymm2, %ymm11, %ymm2
	LONG $0xf52d41c4; BYTE $0xdc               // vpmaddwd	%ymm12, %ymm10, %ymm11
	LONG $0xf6fea5c5                           // vpaddd	%ymm6, %ymm11, %ymm6
	LONG $0x207d42c4; WORD $0x181c             // vpmovsxbw	(%r8,%rbx), %ymm11
	LONG $0x207d42c4; WORD $0x1864; BYTE $0x10 // vpmovsxbw	16(%r8,%rbx), %ymm12
	LONG $0xf53541c4; BYTE $0xcb               // vpmaddwd	%ymm11, %ymm9, %ymm9
	LONG $0xc9feb5c5                           // vpaddd	%ymm1, %ymm9, %ymm1
	LONG $0xf52d41c4; BYTE $0xcc               // vpmaddwd	%ymm12, %ymm10, %ymm9
	LONG $0xe4feb5c5                           // vpaddd	%ymm4, %ymm9, %ymm4
	LONG $0x20c38348                           // addq	$32, %rbx
	WORD $0x394c; BYTE $0xdb                   // cmpq	%r11, %rbx
	JB   LBB0_11
	LONG $0xedfebdc5                           // vpaddd	%ymm5, %ymm8, %ymm5
	LONG $0xdbfec5c5                           // vpaddd	%ymm3, %ymm7, %ymm3
	LONG $0xd2fecdc5                           // vpaddd	%ymm2, %ymm6, %ymm2
	LONG $0xc9feddc5                           // vpaddd	%ymm1, %ymm4, %ymm1
	LONG $0x397de3c4; WORD $0x01ec             // vextracti128	$1, %ymm5, %xmm4
	LONG $0xe4fed1c5                           // vpaddd	%xmm4, %xmm5, %xmm4
	LONG $0x0259e2c4; BYTE $0xe4               // vphaddd	%xmm4, %xmm4, %xmm4
	LONG $0x0259e2c4; BYTE $0xe4               // vphaddd	%xmm4, %xmm4, %xmm4
	LONG $0xe37ef9c5                           // vmovd	%xmm4, %ebx
	WORD $0x6348; BYTE $0xdb                   // movslq	%ebx, %rbx
	WORD $0x0148; BYTE $0xd8                   // addq	%rbx, %rax
	WORD $0x014c; BYTE $0xde                   // addq	%r11, %rsi
	LONG $0x397de3c4; WORD $0x01dc             // vextracti128	$1, %ymm3, %xmm4
	LONG $0xdcfee1c5                           // vpaddd	%xmm4, %xmm3, %xmm3
	LONG $0x0261e2c4; BYTE $0xdb               // vphaddd	%xmm3, %xmm3, %xmm3
	LONG $0x0261e2c4; BYTE $0xdb               // vphaddd	%xmm3, %xmm3, %xmm3
	LONG $0xdb7ef9c5                           // vmovd	%xmm3, %ebx
	WORD $0x6348; BYTE $0xdb                   // movslq	%ebx, %rbx
	LONG $0x397de3c4; WORD $0x01d3             // vextracti128	$1, %ymm2, %xmm3
	LONG $0xd3fee9c5                           // vpaddd	%xmm3, %xmm2, %xmm2
	LONG $0x397de3c4; WORD $0x01cb             // vextracti128	$1, %ymm1, %xmm3
	LONG $0xcbfef1c5                           // vpaddd	%xmm3, %xmm1, %xmm1
	LONG $0x0269e2c4; BYTE $0xc9               // vphaddd	%xmm1, %xmm2, %xmm1
	WORD $0x0149; BYTE $0xda                   // addq	%rbx, %r10
	LONG $0x0271e2c4; BYTE $0xc9               // vphaddd	%xmm1, %xmm1, %xmm1
	WORD $0x014c; BYTE $0xda                   // addq	%r11, %rdx
	WORD $0x014c; BYTE $0xd9                   // addq	%r11, %rcx
	LONG $0x2579e2c4; BYTE $0xc9               // vpmovsxdq	%xmm1, %xmm1
	LONG $0xc1d4f9c5                           // vpaddq	%xmm1, %xmm0, %xmm0
	WORD $0x014d; BYTE $0xd8                   // addq	%r11, %r8
	WORD $0x014c; BYTE $0xdf                   // addq	%r11, %rdi
	WORD $0x294d; BYTE $0xd9                   // subq	%r11, %r9
	LONG $0x1ff98349                           // cmpq	$31, %r9
	JG   LBB0_10

LBB0_1:
	LONG $0x105d8b4c               // movq	16(%rbp), %r11
	LONG $0x7ef9c1c4; BYTE $0xc6   // vmovq	%xmm0, %r14
	LONG $0x16f9c3c4; WORD $0x01c7 // vpextrq	$1, %xmm0, %r15
	WORD $0x854d; BYTE $0xc9       // testq	%r9, %r9
	JLE  LBB0_9
	LONG $0x08f98349               // cmpq	$8, %r9
	JAE  LBB0_5
	WORD $0xdb31                   // xorl	%ebx, %ebx
	JMP  LBB0_4

LBB0_5:
	QUAD $0xfffffffffff8bb48; WORD $0x7fff // movabsq	$9223372036854775800, %rbx      # imm = 0x7FFFFFFFFFFFFFF8
	WORD $0x214c; BYTE $0xcb               // andq	%r9, %rbx
	LONG $0x6ef9e1c4; BYTE $0xe0           // vmovq	%rax, %xmm4
	LONG $0x6ef9c1c4; BYTE $0xd2           // vmovq	%r10, %xmm2
	LONG $0xc87efac5                       // vmovq	%xmm0, %xmm1                    # xmm1 = xmm0[0],zero
	LONG $0xd873f9c5; BYTE $0x08           // vpsrldq	$8, %xmm0, %xmm0                # xmm0 = xmm0[8,9,10,11,12,13,14,15],zero,zero,zero,zero,zero,zero,zero,zero
	LONG $0xf6efc9c5                       // vpxor	%xmm6, %xmm6, %xmm6
	WORD $0xc031                           // xorl	%eax, %eax
	LONG $0xffefc1c5                       // vpxor	%xmm7, %xmm7, %xmm7
	LONG $0xedefd1c5                       // vpxor	%xmm5, %xmm5, %xmm5
	LONG $0xdbefe1c5                       // vpxor	%xmm3, %xmm3, %xmm3

LBB0_6:
	LONG $0x227d62c4; WORD $0x0704             // vpmovsxbq	(%rdi,%rax), %ymm8
	LONG $0x227d62c4; WORD $0x074c; BYTE $0x04 // vpmovsxbq	4(%rdi,%rax), %ymm9
	LONG $0x227d62c4; WORD $0x0614             // vpmovsxbq	(%rsi,%rax), %ymm10
	LONG $0x227d62c4; WORD $0x065c; BYTE $0x04 // vpmovsxbq	4(%rsi,%rax), %ymm11
	LONG $0x282d42c4; BYTE $0xd0               // vpmuldq	%ymm8, %ymm10, %ymm10
	LONG $0xe4d4adc5                           // vpaddq	%ymm4, %ymm10, %ymm4
	LONG $0x282542c4; BYTE $0xd1               // vpmuldq	%ymm9, %ymm11, %ymm10
	LONG $0xf6d4adc5                           // vpaddq	%ymm6, %ymm10, %ymm6
	LONG $0x227d62c4; WORD $0x0214             // vpmovsxbq	(%rdx,%rax), %ymm10
	LONG $0x227d62c4; WORD $0x025c; BYTE $0x04 // vpmovsxbq	4(%rdx,%rax), %ymm11
	LONG $0x282d42c4; BYTE $0xd0               // vpmuldq	%ymm8, %ymm10, %ymm10
	LONG $0xd2d4adc5                           // vpaddq	%ymm2, %ymm10, %ymm2
	LONG $0x282542c4; BYTE $0xd1               // vpmuldq	%ymm9, %ymm11, %ymm10
	LONG $0xffd4adc5                           // vpaddq	%ymm7, %ymm10, %ymm7
	LONG $0x227d62c4; WORD $0x0114             // vpmovsxbq	(%rcx,%rax), %ymm10
	LONG $0x227d62c4; WORD $0x015c; BYTE $0x04 // vpmovsxbq	4(%rcx,%rax), %ymm11
	LONG $0x282d42c4; BYTE $0xd0               // vpmuldq	%ymm8, %ymm10, %ymm10
	LONG $0xc9d4adc5                           // vpaddq	%ymm1, %ymm10, %ymm1
	LONG $0x282542c4; BYTE $0xd1               // vpmuldq	%ymm9, %ymm11, %ymm10
	LONG $0xedd4adc5                           // vpaddq	%ymm5, %ymm10, %ymm5
	LONG $0x227d42c4; WORD $0x0014             // vpmovsxbq	(%r8,%rax), %ymm10
	LONG $0x227d42c4; WORD $0x005c; BYTE $0x04 // vpmovsxbq	4(%r8,%rax), %ymm11
	LONG $0x282d42c4; BYTE $0xc0               // vpmuldq	%ymm8, %ymm10, %ymm8
	LONG $0xc0d4bdc5                           // vpaddq	%ymm0, %ymm8, %ymm0
	LONG $0x282542c4; BYTE $0xc1               // vpmuldq	%ymm9, %ymm11, %ymm8
	LONG $0xdbd4bdc5                           // vpaddq	%ymm3, %ymm8, %ymm3
	LONG $0x08c08348                           // addq	$8, %rax
	WORD $0x3948; BYTE $0xc3                   // cmpq	%rax, %rbx
	JNE  LBB0_6
	LONG $0xe4d4cdc5                           // vpaddq	%ymm4, %ymm6, %ymm4
	LONG $0x397de3c4; WORD $0x01e6             // vextracti128	$1, %ymm4, %xmm6
	LONG $0xe6d4d9c5                           // vpaddq	%xmm6, %xmm4, %xmm4
	LONG $0xf470f9c5; BYTE $0xee               // vpshufd	$238, %xmm4, %xmm6              # xmm6 = xmm4[2,3,2,3]
	LONG $0xe6d4d9c5                           // vpaddq	%xmm6, %xmm4, %xmm4
	LONG $0x7ef9e1c4; BYTE $0xe0               // vmovq	%xmm4, %rax
	LONG $0xd2d4c5c5                           // vpaddq	%ymm2, %ymm7, %ymm2
	LONG $0x397de3c4; WORD $0x01d4             // vextracti128	$1, %ymm2, %xmm4
	LONG $0xd4d4e9c5                           // vpaddq	%xmm4, %xmm2, %xmm2
	LONG $0xe270f9c5; BYTE $0xee               // vpshufd	$238, %xmm2, %xmm4              # xmm4 = xmm2[2,3,2,3]
	LONG $0xd4d4e9c5                           // vpaddq	%xmm4, %xmm2, %xmm2
	LONG $0x7ef9c1c4; BYTE $0xd2               // vmovq	%xmm2, %r10
	LONG $0xc9d4d5c5                           // vpaddq	%ymm1, %ymm5, %ymm1
	LONG $0x397de3c4; WORD $0x01ca             // vextracti128	$1, %ymm1, %xmm2
	LONG $0xcad4f1c5                           // vpaddq	%xmm2, %xmm1, %xmm1
	LONG $0xd170f9c5; BYTE $0xee               // vpshufd	$238, %xmm1, %xmm2              # xmm2 = xmm1[2,3,2,3]
	LONG $0xcad4f1c5                           // vpaddq	%xmm2, %xmm1, %xmm1
	LONG $0x7ef9c1c4; BYTE $0xce               // vmovq	%xmm1, %r14
	LONG $0xc0d4e5c5                           // vpaddq	%ymm0, %ymm3, %ymm0
	LONG $0x397de3c4; WORD $0x01c1             // vextracti128	$1, %ymm0, %xmm1
	LONG $0xc1d4f9c5                           // vpaddq	%xmm1, %xmm0, %xmm0
	LONG $0xc870f9c5; BYTE $0xee               // vpshufd	$238, %xmm0, %xmm1              # xmm1 = xmm0[2,3,2,3]
	LONG $0xc1d4f9c5                           // vpaddq	%xmm1, %xmm0, %xmm0
	LONG $0x7ef9c1c4; BYTE $0xc7               // vmovq	%xmm0, %r15
	JMP  LBB0_8

LBB0_4:
	LONG $0x24be0f4c; BYTE $0x1f // movsbq	(%rdi,%rbx), %r12
	LONG $0x2cbe0f4c; BYTE $0x1e // movsbq	(%rsi,%rbx), %r13
	LONG $0xecaf0f4d             // imulq	%r12, %r13
	WORD $0x014c; BYTE $0xe8     // addq	%r13, %rax
	LONG $0x2cbe0f4c; BYTE $0x1a // movsbq	(%rdx,%rbx), %r13
	LONG $0xecaf0f4d             // imulq	%r12, %r13
	WORD $0x014d; BYTE $0xea     // addq	%r13, %r10
	LONG $0x2cbe0f4c; BYTE $0x19 // movsbq	(%rcx,%rbx), %r13
	LONG $0xecaf0f4d             // imulq	%r12, %r13
	WORD $0x014d; BYTE $0xee     // addq	%r13, %r14
	LONG $0x2cbe0f4d; BYTE $0x18 // movsbq	(%r8,%rbx), %r13
	LONG $0xecaf0f4d             // imulq	%r12, %r13
	WORD $0x014d; BYTE $0xef     // addq	%r13, %r15
	WORD $0xff48; BYTE $0xc3     // incq	%rbx

LBB0_8:
	WORD $0x3949; BYTE $0xd9 // cmpq	%rbx, %r9
	JNE  LBB0_4

LBB0_9:
	WORD $0x8949; BYTE $0x03 // movq	%rax, (%r11)
	LONG $0x0853894d         // movq	%r10, 8(%r11)
	LONG $0x1073894d         // movq	%r14, 16(%r11)
	LONG $0x187b894d         // movq	%r15, 24(%r11)
	LONG $0xd8658d48         // leaq	-40(%rbp), %rsp
	BYTE $0x5b               // popq	%rbx
	WORD $0x5c41             // popq	%r12
	WORD $0x5d41             // popq	%r13
	WORD $0x5e41             // popq	%r14
	WORD $0x5f41             // popq	%r15
	BYTE $0x5d               // popq	%rbp
	WORD $0xf8c5; BYTE $0x77 // vzeroupper
	POPQ DI
	POPQ DI
	RET
