//go:build !noasm && riscv64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8 (6ubuntu1)
// 	objdump 2.46
// flags: -march=rv64imafdv -isystem /usr/lib/llvm-21/lib/clang/21/include -fno-vectorize -fno-slp-vectorize -O3
// source: src/inner_product_batch_int8_rvv.c

TEXT ·xvec_rvv_batch_inner_products_int8_4(SB), $0-24
	MOV  vectors+0(FP), A0
	MOV  size+8(FP), A1
	MOV  output+16(FP), A2
	WORD $0x00000693       // li	a3, 0
	WORD $0x00000713       // li	a4, 0
	WORD $0x00000793       // li	a5, 0
	WORD $0x00000813       // li	a6, 0
	BLEZ A1, LBB0_3
	WORD $0x02053883       // ld	a7, 32(a0)
	WORD $0x00053283       // ld	t0, 0(a0)
	WORD $0x00853303       // ld	t1, 8(a0)
	WORD $0x01053383       // ld	t2, 16(a0)
	WORD $0x01853503       // ld	a0, 24(a0)
	WORD $0xcd80f057       // vsetivli	zero, 1, e64, m1, ta, ma
	WORD $0x42006457       // vmv.s.x	v8, zero

LBB0_2:
	WORD $0x0c95fe57 // vsetvli	t3, a1, e16, m2, ta, ma
	WORD $0x02028487 // vle8.v	v9, (t0)
	WORD $0x02030607 // vle8.v	v12, (t1)
	WORD $0x02038907 // vle8.v	v18, (t2)
	WORD $0x02050987 // vle8.v	v19, (a0)
	WORD $0x02088a07 // vle8.v	v20, (a7)
	WORD $0x4a93a557 // vsext.vf2	v10, v9
	WORD $0x4ac3a857 // vsext.vf2	v16, v12
	WORD $0xeea82657 // vwmul.vv	v12, v10, v16
	WORD $0x0d207057 // vsetvli	zero, zero, e32, m4, ta, ma
	WORD $0xc6c404d7 // vwredsum.vs	v9, v12, v8
	WORD $0x0c907057 // vsetvli	zero, zero, e16, m2, ta, ma
	WORD $0x4b23a857 // vsext.vf2	v16, v18
	WORD $0xeea82657 // vwmul.vv	v12, v10, v16
	WORD $0x0d207057 // vsetvli	zero, zero, e32, m4, ta, ma
	WORD $0xc6c40957 // vwredsum.vs	v18, v12, v8
	WORD $0x0c907057 // vsetvli	zero, zero, e16, m2, ta, ma
	WORD $0x4b33a857 // vsext.vf2	v16, v19
	WORD $0xeea82657 // vwmul.vv	v12, v10, v16
	WORD $0x0d207057 // vsetvli	zero, zero, e32, m4, ta, ma
	WORD $0xc6c409d7 // vwredsum.vs	v19, v12, v8
	WORD $0x0c907057 // vsetvli	zero, zero, e16, m2, ta, ma
	WORD $0x4b43a857 // vsext.vf2	v16, v20
	WORD $0xeea82657 // vwmul.vv	v12, v10, v16
	WORD $0x0d207057 // vsetvli	zero, zero, e32, m4, ta, ma
	WORD $0xc6c40557 // vwredsum.vs	v10, v12, v8
	WORD $0x01c30333 // add	t1, t1, t3
	WORD $0x01c383b3 // add	t2, t2, t3
	WORD $0x01c50533 // add	a0, a0, t3
	WORD $0x01c888b3 // add	a7, a7, t3
	WORD $0x41c585b3 // sub	a1, a1, t3
	WORD $0x0db07057 // vsetvli	zero, zero, e64, m8, ta, ma
	WORD $0x42902ed7 // vmv.x.s	t4, v9
	WORD $0x01d686b3 // add	a3, a3, t4
	WORD $0x43202ed7 // vmv.x.s	t4, v18
	WORD $0x01d70733 // add	a4, a4, t4
	WORD $0x43302ed7 // vmv.x.s	t4, v19
	WORD $0x01d787b3 // add	a5, a5, t4
	WORD $0x42a02ed7 // vmv.x.s	t4, v10
	WORD $0x01d80833 // add	a6, a6, t4
	WORD $0x01c282b3 // add	t0, t0, t3
	BGTZ A1, LBB0_2

LBB0_3:
	WORD $0x00d63023 // sd	a3, 0(a2)
	WORD $0x00e63423 // sd	a4, 8(a2)
	WORD $0x00f63823 // sd	a5, 16(a2)
	WORD $0x01063c23 // sd	a6, 24(a2)
	RET
