//go:build !noasm && amd64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8 (6ubuntu1)
// 	objdump 2.46
// flags: -mavx2 -mavx512f -mavx512bw -fno-vectorize -fno-slp-vectorize -O3
// source: src/inner_product_batch_int8_avx512.c

package mathbatch

import "unsafe"

//go:noescape
func xvec_avx512_batch_inner_products_int8_4(vectors unsafe.Pointer, size int64, output unsafe.Pointer)
