//go:build !noasm && loong64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8 (6ubuntu1)
// 	objdump 2.46
// flags: -mlasx -fno-vectorize -fno-slp-vectorize -O3
// source: src/inner_product_batch_int8_lasx.c

package mathbatch

import "unsafe"

//go:noescape
func xvec_lasx_batch_inner_products_int8_4(vectors unsafe.Pointer, size int64, output unsafe.Pointer)
