//go:build !noasm && amd64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8 (6ubuntu1)
// 	objdump 2.46
// flags: -mavx2 -mavx512f -mavx512bw -fno-vectorize -fno-slp-vectorize -O3
// source: src/inner_product_batch_int4_avx512.c

DATA __goat_data_2e4c435049305f33<>+0x000(SB)/8, $0x0000001100000001
DATA __goat_data_2e4c435049305f33<>+0x008(SB)/8, $0x0000001100000001
GLOBL __goat_data_2e4c435049305f33<>(SB), 8, $16

DATA __goat_data_2e4c435049305f34<>+0x000(SB)/8, $0x0000001000000000
GLOBL __goat_data_2e4c435049305f34<>(SB), 8, $8

DATA __goat_data_2e4c435049305f35<>+0x000(SB)/1, $0x0f
GLOBL __goat_data_2e4c435049305f35<>(SB), 8, $1

DATA __goat_data_2e4c435049305f36<>+0x000(SB)/1, $0x08
GLOBL __goat_data_2e4c435049305f36<>(SB), 8, $1

DATA __goat_data_2e4c435049305f37<>+0x000(SB)/1, $0xf0
GLOBL __goat_data_2e4c435049305f37<>(SB), 8, $1

TEXT ·xvec_avx512_batch_inner_products_int4_4(SB), $0-56
	MOVQ         query+0(FP), DI
	MOVQ         first+8(FP), SI
	MOVQ         second+16(FP), DX
	MOVQ         third+24(FP), CX
	MOVQ         fourth+32(FP), R8
	MOVQ         size+40(FP), R9
	PUSHQ        output+48(FP)
	PUSHQ        $0
	BYTE         $0x55                                  // pushq	%rbp
	WORD         $0x8948; BYTE $0xe5                    // movq	%rsp, %rbp
	LONG         $0xf8e48348                            // andq	$-8, %rsp
	LONG         $0x10458b48                            // movq	16(%rbp), %rax
	LONG         $0xc0eff9c5                            // vpxor	%xmm0, %xmm0, %xmm0
	WORD         $0x854d; BYTE $0xc9                    // testq	%r9, %r9
	JE           LBB0_4
	VPBROADCASTB __goat_data_2e4c435049305f35<>(SB), Y1
	VPBROADCASTB __goat_data_2e4c435049305f36<>(SB), Y2
	VPBROADCASTB __goat_data_2e4c435049305f37<>(SB), Y3
	VMOVDQA      __goat_data_2e4c435049305f33<>(SB), X4
	VMOVDQA      __goat_data_2e4c435049305f34<>(SB), X5
	JMP          LBB0_2

LBB0_3:
	LONG $0x48fd5362; WORD $0xca3b; BYTE $0x01 // vextracti64x4	$1, %zmm9, %ymm10
	LONG $0x48355162; WORD $0xcafe             // vpaddd	%zmm10, %zmm9, %zmm9
	WORD $0x014c; BYTE $0xd6                   // addq	%r10, %rsi
	LONG $0x48fd5362; WORD $0xc23b; BYTE $0x01 // vextracti64x4	$1, %zmm8, %ymm10
	LONG $0x483d5162; WORD $0xc2fe             // vpaddd	%zmm10, %zmm8, %zmm8
	WORD $0x014c; BYTE $0xd2                   // addq	%r10, %rdx
	LONG $0x48fdd362; WORD $0xfa3b; BYTE $0x01 // vextracti64x4	$1, %zmm7, %ymm10
	LONG $0x4845d162; WORD $0xfafe             // vpaddd	%zmm10, %zmm7, %zmm7
	WORD $0x014c; BYTE $0xd1                   // addq	%r10, %rcx
	LONG $0x48fdd362; WORD $0xf23b; BYTE $0x01 // vextracti64x4	$1, %zmm6, %ymm10
	LONG $0x484dd162; WORD $0xf2fe             // vpaddd	%zmm10, %zmm6, %zmm6
	LONG $0x397d43c4; WORD $0x01c2             // vextracti128	$1, %ymm8, %xmm10
	LONG $0xfe3941c4; BYTE $0xc2               // vpaddd	%xmm10, %xmm8, %xmm8
	LONG $0x707941c4; WORD $0xeed0             // vpshufd	$238, %xmm8, %xmm10             # xmm10 = xmm8[2,3,2,3]
	LONG $0xfe3941c4; BYTE $0xc2               // vpaddd	%xmm10, %xmm8, %xmm8
	LONG $0x397d43c4; WORD $0x01ca             // vextracti128	$1, %ymm9, %xmm10
	LONG $0xfe3141c4; BYTE $0xca               // vpaddd	%xmm10, %xmm9, %xmm9
	LONG $0x707941c4; WORD $0xeed1             // vpshufd	$238, %xmm9, %xmm10             # xmm10 = xmm9[2,3,2,3]
	LONG $0xfe3141c4; BYTE $0xca               // vpaddd	%xmm10, %xmm9, %xmm9
	LONG $0x623141c4; BYTE $0xd0               // vpunpckldq	%xmm8, %xmm9, %xmm10    # xmm10 = xmm9[0],xmm8[0],xmm9[1],xmm8[1]
	LONG $0x485d5262; WORD $0xc87e             // vpermt2d	%zmm8, %zmm4, %zmm9
	LONG $0xfe2941c4; BYTE $0xc1               // vpaddd	%xmm9, %xmm10, %xmm8
	LONG $0x397dc3c4; WORD $0x01f1             // vextracti128	$1, %ymm6, %xmm9
	LONG $0xf6feb1c5                           // vpaddd	%xmm6, %xmm9, %xmm6
	LONG $0xce7079c5; BYTE $0xee               // vpshufd	$238, %xmm6, %xmm9              # xmm9 = xmm6[2,3,2,3]
	LONG $0xf6feb1c5                           // vpaddd	%xmm6, %xmm9, %xmm6
	LONG $0xce7079c5; BYTE $0x55               // vpshufd	$85, %xmm6, %xmm9               # xmm9 = xmm6[1,1,1,1]
	LONG $0xf6feb1c5                           // vpaddd	%xmm6, %xmm9, %xmm6
	LONG $0x397dc3c4; WORD $0x01f9             // vextracti128	$1, %ymm7, %xmm9
	LONG $0xfffeb1c5                           // vpaddd	%xmm7, %xmm9, %xmm7
	LONG $0xcf7079c5; BYTE $0xee               // vpshufd	$238, %xmm7, %xmm9              # xmm9 = xmm7[2,3,2,3]
	LONG $0xfffeb1c5                           // vpaddd	%xmm7, %xmm9, %xmm7
	LONG $0xcf7079c5; BYTE $0x55               // vpshufd	$85, %xmm7, %xmm9               # xmm9 = xmm7[1,1,1,1]
	LONG $0xfffeb1c5                           // vpaddd	%xmm7, %xmm9, %xmm7
	LONG $0x4855f262; WORD $0xfe7e             // vpermt2d	%zmm6, %zmm5, %zmm7
	LONG $0x0239e3c4; WORD $0x0cf7             // vpblendd	$12, %xmm7, %xmm8, %xmm6        # xmm6 = xmm8[0,1],xmm7[2,3]
	LONG $0x257de2c4; BYTE $0xf6               // vpmovsxdq	%xmm6, %ymm6
	LONG $0xc6d4fdc5                           // vpaddq	%ymm6, %ymm0, %ymm0
	WORD $0x014d; BYTE $0xd0                   // addq	%r10, %r8
	WORD $0x014c; BYTE $0xd7                   // addq	%r10, %rdi
	WORD $0x294d; BYTE $0xd1                   // subq	%r10, %r9
	JE   LBB0_4

LBB0_2:
	LONG $0x00f98149; WORD $0x1000; BYTE $0x00 // cmpq	$1048576, %r9                   # imm = 0x100000
	LONG $0x0000ba41; WORD $0x0010             // movl	$1048576, %r10d                 # imm = 0x100000
	LONG $0xd14c0f4d                           // cmovlq	%r9, %r10
	LONG $0xf6efc9c5                           // vpxor	%xmm6, %xmm6, %xmm6
	LONG $0xffefc1c5                           // vpxor	%xmm7, %xmm7, %xmm7
	LONG $0xef3941c4; BYTE $0xc0               // vpxor	%xmm8, %xmm8, %xmm8
	LONG $0xef3141c4; BYTE $0xc9               // vpxor	%xmm9, %xmm9, %xmm9
	WORD $0x854d; BYTE $0xc9                   // testq	%r9, %r9
	JLE  LBB0_3
	WORD $0x3145; BYTE $0xdb                   // xorl	%r11d, %r11d

LBB0_6:
	LONG $0x6f7e21c4; WORD $0x1f14 // vmovdqu	(%rdi,%r11), %ymm10
	LONG $0x7125c1c4; WORD $0x04f2 // vpsllw	$4, %ymm10, %ymm11
	LONG $0x7125c1c4; WORD $0x04d3 // vpsrlw	$4, %ymm11, %ymm11
	LONG $0xd9db25c5               // vpand	%ymm1, %ymm11, %ymm11
	LONG $0xdaef25c5               // vpxor	%ymm2, %ymm11, %ymm11
	LONG $0xdaf825c5               // vpsubb	%ymm2, %ymm11, %ymm11
	LONG $0xd3db2dc5               // vpand	%ymm3, %ymm10, %ymm10
	LONG $0x712dc1c4; WORD $0x04d2 // vpsrlw	$4, %ymm10, %ymm10
	LONG $0xd2ef2dc5               // vpxor	%ymm2, %ymm10, %ymm10
	LONG $0xd2f82dc5               // vpsubb	%ymm2, %ymm10, %ymm10
	LONG $0x487d5262; WORD $0xdb20 // vpmovsxbw	%ymm11, %zmm11
	LONG $0x487d5262; WORD $0xd220 // vpmovsxbw	%ymm10, %zmm10
	LONG $0x6f7e21c4; WORD $0x1e24 // vmovdqu	(%rsi,%r11), %ymm12
	LONG $0x7115c1c4; WORD $0x04f4 // vpsllw	$4, %ymm12, %ymm13
	LONG $0x7115c1c4; WORD $0x04d5 // vpsrlw	$4, %ymm13, %ymm13
	LONG $0xe9db15c5               // vpand	%ymm1, %ymm13, %ymm13
	LONG $0xeaef15c5               // vpxor	%ymm2, %ymm13, %ymm13
	LONG $0xeaf815c5               // vpsubb	%ymm2, %ymm13, %ymm13
	LONG $0x487d5262; WORD $0xed20 // vpmovsxbw	%ymm13, %zmm13
	LONG $0x48255162; WORD $0xedf5 // vpmaddwd	%zmm13, %zmm11, %zmm13
	LONG $0xe3db1dc5               // vpand	%ymm3, %ymm12, %ymm12
	LONG $0x711dc1c4; WORD $0x04d4 // vpsrlw	$4, %ymm12, %ymm12
	LONG $0xe2ef1dc5               // vpxor	%ymm2, %ymm12, %ymm12
	LONG $0xe2f81dc5               // vpsubb	%ymm2, %ymm12, %ymm12
	LONG $0x487d5262; WORD $0xe420 // vpmovsxbw	%ymm12, %zmm12
	LONG $0x482d5162; WORD $0xe4f5 // vpmaddwd	%zmm12, %zmm10, %zmm12
	LONG $0x48355162; WORD $0xccfe // vpaddd	%zmm12, %zmm9, %zmm9
	LONG $0x48155162; WORD $0xc9fe // vpaddd	%zmm9, %zmm13, %zmm9
	LONG $0x6f7e21c4; WORD $0x1a24 // vmovdqu	(%rdx,%r11), %ymm12
	LONG $0x7115c1c4; WORD $0x04f4 // vpsllw	$4, %ymm12, %ymm13
	LONG $0x7115c1c4; WORD $0x04d5 // vpsrlw	$4, %ymm13, %ymm13
	LONG $0xe9db15c5               // vpand	%ymm1, %ymm13, %ymm13
	LONG $0xeaef15c5               // vpxor	%ymm2, %ymm13, %ymm13
	LONG $0xeaf815c5               // vpsubb	%ymm2, %ymm13, %ymm13
	LONG $0x487d5262; WORD $0xed20 // vpmovsxbw	%ymm13, %zmm13
	LONG $0x48255162; WORD $0xedf5 // vpmaddwd	%zmm13, %zmm11, %zmm13
	LONG $0xe3db1dc5               // vpand	%ymm3, %ymm12, %ymm12
	LONG $0x711dc1c4; WORD $0x04d4 // vpsrlw	$4, %ymm12, %ymm12
	LONG $0xe2ef1dc5               // vpxor	%ymm2, %ymm12, %ymm12
	LONG $0xe2f81dc5               // vpsubb	%ymm2, %ymm12, %ymm12
	LONG $0x487d5262; WORD $0xe420 // vpmovsxbw	%ymm12, %zmm12
	LONG $0x482d5162; WORD $0xe4f5 // vpmaddwd	%zmm12, %zmm10, %zmm12
	LONG $0x483d5162; WORD $0xc4fe // vpaddd	%zmm12, %zmm8, %zmm8
	LONG $0x48155162; WORD $0xc0fe // vpaddd	%zmm8, %zmm13, %zmm8
	LONG $0x6f7e21c4; WORD $0x1924 // vmovdqu	(%rcx,%r11), %ymm12
	LONG $0x7115c1c4; WORD $0x04f4 // vpsllw	$4, %ymm12, %ymm13
	LONG $0x7115c1c4; WORD $0x04d5 // vpsrlw	$4, %ymm13, %ymm13
	LONG $0xe9db15c5               // vpand	%ymm1, %ymm13, %ymm13
	LONG $0xeaef15c5               // vpxor	%ymm2, %ymm13, %ymm13
	LONG $0xeaf815c5               // vpsubb	%ymm2, %ymm13, %ymm13
	LONG $0x487d5262; WORD $0xed20 // vpmovsxbw	%ymm13, %zmm13
	LONG $0x48255162; WORD $0xedf5 // vpmaddwd	%zmm13, %zmm11, %zmm13
	LONG $0xe3db1dc5               // vpand	%ymm3, %ymm12, %ymm12
	LONG $0x711dc1c4; WORD $0x04d4 // vpsrlw	$4, %ymm12, %ymm12
	LONG $0xe2ef1dc5               // vpxor	%ymm2, %ymm12, %ymm12
	LONG $0xe2f81dc5               // vpsubb	%ymm2, %ymm12, %ymm12
	LONG $0x487d5262; WORD $0xe420 // vpmovsxbw	%ymm12, %zmm12
	LONG $0x482d5162; WORD $0xe4f5 // vpmaddwd	%zmm12, %zmm10, %zmm12
	LONG $0x4845d162; WORD $0xfcfe // vpaddd	%zmm12, %zmm7, %zmm7
	LONG $0x4815f162; WORD $0xfffe // vpaddd	%zmm7, %zmm13, %zmm7
	LONG $0x6f7e01c4; WORD $0x1824 // vmovdqu	(%r8,%r11), %ymm12
	LONG $0x7115c1c4; WORD $0x04f4 // vpsllw	$4, %ymm12, %ymm13
	LONG $0x7115c1c4; WORD $0x04d5 // vpsrlw	$4, %ymm13, %ymm13
	LONG $0xe9db15c5               // vpand	%ymm1, %ymm13, %ymm13
	LONG $0xeaef15c5               // vpxor	%ymm2, %ymm13, %ymm13
	LONG $0xeaf815c5               // vpsubb	%ymm2, %ymm13, %ymm13
	LONG $0x487d5262; WORD $0xed20 // vpmovsxbw	%ymm13, %zmm13
	LONG $0x48255162; WORD $0xddf5 // vpmaddwd	%zmm13, %zmm11, %zmm11
	LONG $0xe3db1dc5               // vpand	%ymm3, %ymm12, %ymm12
	LONG $0x711dc1c4; WORD $0x04d4 // vpsrlw	$4, %ymm12, %ymm12
	LONG $0xe2ef1dc5               // vpxor	%ymm2, %ymm12, %ymm12
	LONG $0xe2f81dc5               // vpsubb	%ymm2, %ymm12, %ymm12
	LONG $0x487d5262; WORD $0xe420 // vpmovsxbw	%ymm12, %zmm12
	LONG $0x482d5162; WORD $0xd4f5 // vpmaddwd	%zmm12, %zmm10, %zmm10
	LONG $0x484dd162; WORD $0xf2fe // vpaddd	%zmm10, %zmm6, %zmm6
	LONG $0x4825f162; WORD $0xf6fe // vpaddd	%zmm6, %zmm11, %zmm6
	LONG $0x20c38349               // addq	$32, %r11
	WORD $0x394d; BYTE $0xd3       // cmpq	%r10, %r11
	JL   LBB0_6
	JMP  LBB0_3

LBB0_4:
	LONG $0x007ffec5         // vmovdqu	%ymm0, (%rax)
	WORD $0x8948; BYTE $0xec // movq	%rbp, %rsp
	BYTE $0x5d               // popq	%rbp
	WORD $0xf8c5; BYTE $0x77 // vzeroupper
	POPQ DI
	POPQ DI
	RET
