//go:build !noasm && riscv64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8 (6ubuntu1)
// 	objdump 2.46
// flags: -march=rv64imafdv -isystem /usr/lib/llvm-21/lib/clang/21/include -fno-vectorize -fno-slp-vectorize -O3
// source: src/inner_product_batch_int8_rvv.c

package mathbatch

import "unsafe"

//go:noescape
func xvec_rvv_batch_inner_products_int8_4(vectors unsafe.Pointer, size int64, output unsafe.Pointer)
