//go:build !noasm && loong64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8 (6ubuntu1)
// 	objdump 2.46
// flags: -mlasx -fno-vectorize -fno-slp-vectorize -O3
// source: src/distance_matrix_fp16_lasx.c

TEXT ·squared_euclidean_distance_fp16_lasx(SB), $8-28
	MOVV left+0(FP), R4
	MOVV right+8(FP), R5
	MOVV size+16(FP), R6
	WORD $0x02ff8063     // addi.d	$sp, $sp, -32
	WORD $0x03800407     // ori	$a3, $zero, 1
	WORD $0x77e00000     // xvldi	$xr0, 0
	BLT  R6, R7, LBB0_3
	WORD $0x00150007     // move	$a3, $zero

LBB0_2:
	WORD $0x2c800081    // xvld	$xr1, $a0, 0
	WORD $0x2c8000a2    // xvld	$xr2, $a1, 0
	WORD $0x769de823    // xvfcvtl.s.h	$xr3, $xr1
	WORD $0x769dec21    // xvfcvth.s.h	$xr1, $xr1
	WORD $0x769de844    // xvfcvtl.s.h	$xr4, $xr2
	WORD $0x769dec42    // xvfcvth.s.h	$xr2, $xr2
	WORD $0x75329063    // xvfsub.s	$xr3, $xr3, $xr4
	WORD $0x75388c63    // xvfmul.s	$xr3, $xr3, $xr3
	WORD $0x75308c00    // xvfadd.s	$xr0, $xr0, $xr3
	WORD $0x75328821    // xvfsub.s	$xr1, $xr1, $xr2
	WORD $0x75388421    // xvfmul.s	$xr1, $xr1, $xr1
	WORD $0x75308400    // xvfadd.s	$xr0, $xr0, $xr1
	WORD $0x02c040e7    // addi.d	$a3, $a3, 16
	WORD $0x02c080a5    // addi.d	$a1, $a1, 32
	WORD $0x02c08084    // addi.d	$a0, $a0, 32
	BLT  R7, R6, LBB0_2

LBB0_3:
	WORD $0x02c00064       // addi.d	$a0, $sp, 0
	WORD $0x2cc00080       // xvst	$xr0, $a0, 0
	WORD $0x2b000060       // fld.s	$fa0, $sp, 0
	WORD $0x0114a401       // movgr2fr.w	$fa1, $zero
	WORD $0x2b001062       // fld.s	$fa2, $sp, 4
	WORD $0x2b002063       // fld.s	$fa3, $sp, 8
	WORD $0x2b003064       // fld.s	$fa4, $sp, 12
	WORD $0x01008400       // fadd.s	$fa0, $fa0, $fa1
	WORD $0x01008800       // fadd.s	$fa0, $fa0, $fa2
	WORD $0x01008c00       // fadd.s	$fa0, $fa0, $fa3
	WORD $0x01009000       // fadd.s	$fa0, $fa0, $fa4
	WORD $0x2b004061       // fld.s	$fa1, $sp, 16
	WORD $0x2b005062       // fld.s	$fa2, $sp, 20
	WORD $0x2b006063       // fld.s	$fa3, $sp, 24
	WORD $0x2b007064       // fld.s	$fa4, $sp, 28
	WORD $0x01008400       // fadd.s	$fa0, $fa0, $fa1
	WORD $0x01008800       // fadd.s	$fa0, $fa0, $fa2
	WORD $0x01008c00       // fadd.s	$fa0, $fa0, $fa3
	WORD $0x01009000       // fadd.s	$fa0, $fa0, $fa4
	WORD $0x02c08063       // addi.d	$sp, $sp, 32
	MOVF F0, result+24(FP)
	RET

TEXT ·inner_product_fp16_lasx(SB), $8-28
	MOVV left+0(FP), R4
	MOVV right+8(FP), R5
	MOVV size+16(FP), R6
	WORD $0x02ff8063     // addi.d	$sp, $sp, -32
	WORD $0x03800407     // ori	$a3, $zero, 1
	WORD $0x77e00000     // xvldi	$xr0, 0
	BLT  R6, R7, LBB1_3
	WORD $0x00150007     // move	$a3, $zero

LBB1_2:
	WORD $0x2c800081    // xvld	$xr1, $a0, 0
	WORD $0x2c8000a2    // xvld	$xr2, $a1, 0
	WORD $0x769de823    // xvfcvtl.s.h	$xr3, $xr1
	WORD $0x769dec21    // xvfcvth.s.h	$xr1, $xr1
	WORD $0x769de844    // xvfcvtl.s.h	$xr4, $xr2
	WORD $0x769dec42    // xvfcvth.s.h	$xr2, $xr2
	WORD $0x75389063    // xvfmul.s	$xr3, $xr3, $xr4
	WORD $0x75308c00    // xvfadd.s	$xr0, $xr0, $xr3
	WORD $0x75388821    // xvfmul.s	$xr1, $xr1, $xr2
	WORD $0x75308400    // xvfadd.s	$xr0, $xr0, $xr1
	WORD $0x02c040e7    // addi.d	$a3, $a3, 16
	WORD $0x02c080a5    // addi.d	$a1, $a1, 32
	WORD $0x02c08084    // addi.d	$a0, $a0, 32
	BLT  R7, R6, LBB1_2

LBB1_3:
	WORD $0x02c00064       // addi.d	$a0, $sp, 0
	WORD $0x2cc00080       // xvst	$xr0, $a0, 0
	WORD $0x2b000060       // fld.s	$fa0, $sp, 0
	WORD $0x0114a401       // movgr2fr.w	$fa1, $zero
	WORD $0x2b001062       // fld.s	$fa2, $sp, 4
	WORD $0x2b002063       // fld.s	$fa3, $sp, 8
	WORD $0x2b003064       // fld.s	$fa4, $sp, 12
	WORD $0x01008400       // fadd.s	$fa0, $fa0, $fa1
	WORD $0x01008800       // fadd.s	$fa0, $fa0, $fa2
	WORD $0x01008c00       // fadd.s	$fa0, $fa0, $fa3
	WORD $0x01009000       // fadd.s	$fa0, $fa0, $fa4
	WORD $0x2b004061       // fld.s	$fa1, $sp, 16
	WORD $0x2b005062       // fld.s	$fa2, $sp, 20
	WORD $0x2b006063       // fld.s	$fa3, $sp, 24
	WORD $0x2b007064       // fld.s	$fa4, $sp, 28
	WORD $0x01008400       // fadd.s	$fa0, $fa0, $fa1
	WORD $0x01008800       // fadd.s	$fa0, $fa0, $fa2
	WORD $0x01008c00       // fadd.s	$fa0, $fa0, $fa3
	WORD $0x01009000       // fadd.s	$fa0, $fa0, $fa4
	WORD $0x02c08063       // addi.d	$sp, $sp, 32
	MOVF F0, result+24(FP)
	RET

TEXT ·inner_product_and_squared_norm_fp16_lasx(SB), $8-44
	MOVV left+0(FP), R4
	MOVV right+8(FP), R5
	MOVV size+16(FP), R6
	MOVV left_norm+24(FP), R7
	MOVV right_norm+32(FP), R8
	WORD $0x02ff8063           // addi.d	$sp, $sp, -32
	WORD $0x03800409           // ori	$a5, $zero, 1
	WORD $0x77e00001           // xvldi	$xr1, 0
	BLT  R6, R9, LBB2_3
	WORD $0x00150009           // move	$a5, $zero
	WORD $0x77d40022           // xvori.b	$xr2, $xr1, 0
	WORD $0x77d40020           // xvori.b	$xr0, $xr1, 0

LBB2_2:
	WORD $0x2c800083    // xvld	$xr3, $a0, 0
	WORD $0x2c8000a4    // xvld	$xr4, $a1, 0
	WORD $0x769de865    // xvfcvtl.s.h	$xr5, $xr3
	WORD $0x769dec63    // xvfcvth.s.h	$xr3, $xr3
	WORD $0x769de886    // xvfcvtl.s.h	$xr6, $xr4
	WORD $0x769dec84    // xvfcvth.s.h	$xr4, $xr4
	WORD $0x753898a7    // xvfmul.s	$xr7, $xr5, $xr6
	WORD $0x75309c00    // xvfadd.s	$xr0, $xr0, $xr7
	WORD $0x75389067    // xvfmul.s	$xr7, $xr3, $xr4
	WORD $0x75309c00    // xvfadd.s	$xr0, $xr0, $xr7
	WORD $0x753894a5    // xvfmul.s	$xr5, $xr5, $xr5
	WORD $0x75309442    // xvfadd.s	$xr2, $xr2, $xr5
	WORD $0x75388c63    // xvfmul.s	$xr3, $xr3, $xr3
	WORD $0x75308c42    // xvfadd.s	$xr2, $xr2, $xr3
	WORD $0x753898c3    // xvfmul.s	$xr3, $xr6, $xr6
	WORD $0x75308c21    // xvfadd.s	$xr1, $xr1, $xr3
	WORD $0x75389083    // xvfmul.s	$xr3, $xr4, $xr4
	WORD $0x75308c21    // xvfadd.s	$xr1, $xr1, $xr3
	WORD $0x02c04129    // addi.d	$a5, $a5, 16
	WORD $0x02c080a5    // addi.d	$a1, $a1, 32
	WORD $0x02c08084    // addi.d	$a0, $a0, 32
	BLT  R9, R6, LBB2_2
	JMP  LBB2_4

LBB2_3:
	WORD $0x77d40020 // xvori.b	$xr0, $xr1, 0
	WORD $0x77d40022 // xvori.b	$xr2, $xr1, 0

LBB2_4:
	WORD $0x02c00064       // addi.d	$a0, $sp, 0
	WORD $0x2cc00082       // xvst	$xr2, $a0, 0
	WORD $0x2b000062       // fld.s	$fa2, $sp, 0
	WORD $0x0114a403       // movgr2fr.w	$fa3, $zero
	WORD $0x2b001064       // fld.s	$fa4, $sp, 4
	WORD $0x2b002065       // fld.s	$fa5, $sp, 8
	WORD $0x2b003066       // fld.s	$fa6, $sp, 12
	WORD $0x01008c42       // fadd.s	$fa2, $fa2, $fa3
	WORD $0x01009042       // fadd.s	$fa2, $fa2, $fa4
	WORD $0x01009442       // fadd.s	$fa2, $fa2, $fa5
	WORD $0x01009842       // fadd.s	$fa2, $fa2, $fa6
	WORD $0x2b004064       // fld.s	$fa4, $sp, 16
	WORD $0x2b005065       // fld.s	$fa5, $sp, 20
	WORD $0x2b006066       // fld.s	$fa6, $sp, 24
	WORD $0x2b007067       // fld.s	$fa7, $sp, 28
	WORD $0x01009042       // fadd.s	$fa2, $fa2, $fa4
	WORD $0x01009442       // fadd.s	$fa2, $fa2, $fa5
	WORD $0x01009842       // fadd.s	$fa2, $fa2, $fa6
	WORD $0x01009c42       // fadd.s	$fa2, $fa2, $fa7
	WORD $0x2b4000e2       // fst.s	$fa2, $a3, 0
	WORD $0x2cc00081       // xvst	$xr1, $a0, 0
	WORD $0x2b000061       // fld.s	$fa1, $sp, 0
	WORD $0x2b001062       // fld.s	$fa2, $sp, 4
	WORD $0x2b002064       // fld.s	$fa4, $sp, 8
	WORD $0x2b003065       // fld.s	$fa5, $sp, 12
	WORD $0x01008c21       // fadd.s	$fa1, $fa1, $fa3
	WORD $0x01008821       // fadd.s	$fa1, $fa1, $fa2
	WORD $0x01009021       // fadd.s	$fa1, $fa1, $fa4
	WORD $0x01009421       // fadd.s	$fa1, $fa1, $fa5
	WORD $0x2b004062       // fld.s	$fa2, $sp, 16
	WORD $0x2b005064       // fld.s	$fa4, $sp, 20
	WORD $0x2b006065       // fld.s	$fa5, $sp, 24
	WORD $0x2b007066       // fld.s	$fa6, $sp, 28
	WORD $0x01008821       // fadd.s	$fa1, $fa1, $fa2
	WORD $0x01009021       // fadd.s	$fa1, $fa1, $fa4
	WORD $0x01009421       // fadd.s	$fa1, $fa1, $fa5
	WORD $0x01009821       // fadd.s	$fa1, $fa1, $fa6
	WORD $0x2b400101       // fst.s	$fa1, $a4, 0
	WORD $0x2cc00080       // xvst	$xr0, $a0, 0
	WORD $0x2b000060       // fld.s	$fa0, $sp, 0
	WORD $0x2b001061       // fld.s	$fa1, $sp, 4
	WORD $0x2b002062       // fld.s	$fa2, $sp, 8
	WORD $0x2b003064       // fld.s	$fa4, $sp, 12
	WORD $0x01008c00       // fadd.s	$fa0, $fa0, $fa3
	WORD $0x01008400       // fadd.s	$fa0, $fa0, $fa1
	WORD $0x01008800       // fadd.s	$fa0, $fa0, $fa2
	WORD $0x01009000       // fadd.s	$fa0, $fa0, $fa4
	WORD $0x2b004061       // fld.s	$fa1, $sp, 16
	WORD $0x2b005062       // fld.s	$fa2, $sp, 20
	WORD $0x2b006063       // fld.s	$fa3, $sp, 24
	WORD $0x2b007064       // fld.s	$fa4, $sp, 28
	WORD $0x01008400       // fadd.s	$fa0, $fa0, $fa1
	WORD $0x01008800       // fadd.s	$fa0, $fa0, $fa2
	WORD $0x01008c00       // fadd.s	$fa0, $fa0, $fa3
	WORD $0x01009000       // fadd.s	$fa0, $fa0, $fa4
	WORD $0x02c08063       // addi.d	$sp, $sp, 32
	MOVF F0, result+40(FP)
	RET
