//go:build !noasm && riscv64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8 (6ubuntu1)
// 	objdump 2.46
// flags: -march=rv64imafdv -isystem /usr/lib/llvm-21/lib/clang/21/include -O3
// source: src/distance_utility_rvv.c

package mathutil

import "unsafe"

//go:noescape
func xvec_rvv_l2_squared(left, right unsafe.Pointer, size int64, output unsafe.Pointer)

//go:noescape
func xvec_rvv_inner_product(left, right unsafe.Pointer, size int64, output unsafe.Pointer)

//go:noescape
func xvec_rvv_dot_norms(left, right unsafe.Pointer, size int64, dot, left_norm, right_norm unsafe.Pointer)
