//go:build !noasm && arm64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8 (6ubuntu1)
// 	objdump 2.46
// flags: -O3
// source: src/distance_utility_neon.c

TEXT ·xvec_neon_l2_squared(SB), $0-32
	MOVD left+0(FP), R0
	MOVD right+8(FP), R1
	MOVD size+16(FP), R2
	MOVD output+24(FP), R3
	WORD $0x91000c48       // add	x8, x2, #3
	WORD $0xf100005f       // cmp	x2, #0
	WORD $0x6f00e400       // movi	v0.2d, #0000000000000000
	WORD $0x9a82b109       // csel	x9, x8, x2, lt
	WORD $0xf100105f       // cmp	x2, #4
	WORD $0x927ef528       // and	x8, x9, #0xfffffffffffffffc
	WORD $0xcb080048       // sub	x8, x2, x8
	BLT  LBB0_4
	WORD $0x9342fd29       // asr	x9, x9, #2
	WORD $0xaa0003eb       // mov	x11, x0
	WORD $0xaa0103ec       // mov	x12, x1
	WORD $0xaa0903ea       // mov	x10, x9

LBB0_2:
	WORD $0x3cc10561 // ldr	q1, [x11], #16
	WORD $0xf100054a // subs	x10, x10, #1
	WORD $0x3cc10582 // ldr	q2, [x12], #16
	WORD $0x4ea2d421 // fsub	v1.4s, v1.4s, v2.4s
	WORD $0x4e21cc20 // fmla	v0.4s, v1.4s, v1.4s
	BNE  LBB0_2
	WORD $0xd37ced29 // lsl	x9, x9, #4
	WORD $0x8b090000 // add	x0, x0, x9
	WORD $0x8b090021 // add	x1, x1, x9

LBB0_4:
	WORD $0x4e0c0401 // dup	v1.4s, v0.s[1]
	WORD $0x4e140402 // dup	v2.4s, v0.s[2]
	WORD $0xf100011f // cmp	x8, #0
	WORD $0x4e21d401 // fadd	v1.4s, v0.4s, v1.4s
	WORD $0x4e1c0400 // dup	v0.4s, v0.s[3]
	WORD $0x4e21d441 // fadd	v1.4s, v2.4s, v1.4s
	WORD $0x4e21d400 // fadd	v0.4s, v0.4s, v1.4s
	BLE  LBB0_8
	WORD $0xbd400001 // ldr	s1, [x0]
	WORD $0xbd400022 // ldr	s2, [x1]
	WORD $0xf100051f // cmp	x8, #1
	WORD $0x1e223821 // fsub	s1, s1, s2
	WORD $0x1f010020 // fmadd	s0, s1, s1, s0
	BEQ  LBB0_8
	WORD $0xbd400401 // ldr	s1, [x0, #4]
	WORD $0xbd400422 // ldr	s2, [x1, #4]
	WORD $0xf100091f // cmp	x8, #2
	WORD $0x1e223821 // fsub	s1, s1, s2
	WORD $0x1f010020 // fmadd	s0, s1, s1, s0
	BEQ  LBB0_8
	WORD $0xbd400801 // ldr	s1, [x0, #8]
	WORD $0xbd400822 // ldr	s2, [x1, #8]
	WORD $0x1e223821 // fsub	s1, s1, s2
	WORD $0x1f010020 // fmadd	s0, s1, s1, s0

LBB0_8:
	WORD $0xbd000060 // str	s0, [x3]
	RET

TEXT ·xvec_neon_inner_product(SB), $0-32
	MOVD left+0(FP), R0
	MOVD right+8(FP), R1
	MOVD size+16(FP), R2
	MOVD output+24(FP), R3
	WORD $0x91000c48       // add	x8, x2, #3
	WORD $0xf100005f       // cmp	x2, #0
	WORD $0x6f00e400       // movi	v0.2d, #0000000000000000
	WORD $0x9a82b109       // csel	x9, x8, x2, lt
	WORD $0xf100105f       // cmp	x2, #4
	WORD $0x927ef528       // and	x8, x9, #0xfffffffffffffffc
	WORD $0xcb080048       // sub	x8, x2, x8
	BLT  LBB1_4
	WORD $0x9342fd29       // asr	x9, x9, #2
	WORD $0xaa0003eb       // mov	x11, x0
	WORD $0xaa0103ec       // mov	x12, x1
	WORD $0xaa0903ea       // mov	x10, x9

LBB1_2:
	WORD $0x3cc10561 // ldr	q1, [x11], #16
	WORD $0xf100054a // subs	x10, x10, #1
	WORD $0x3cc10582 // ldr	q2, [x12], #16
	WORD $0x4e21cc40 // fmla	v0.4s, v2.4s, v1.4s
	BNE  LBB1_2
	WORD $0xd37ced29 // lsl	x9, x9, #4
	WORD $0x8b090000 // add	x0, x0, x9
	WORD $0x8b090021 // add	x1, x1, x9

LBB1_4:
	WORD $0x4e0c0401 // dup	v1.4s, v0.s[1]
	WORD $0x4e140402 // dup	v2.4s, v0.s[2]
	WORD $0xf100011f // cmp	x8, #0
	WORD $0x4e21d401 // fadd	v1.4s, v0.4s, v1.4s
	WORD $0x4e1c0400 // dup	v0.4s, v0.s[3]
	WORD $0x4e21d441 // fadd	v1.4s, v2.4s, v1.4s
	WORD $0x4e21d400 // fadd	v0.4s, v0.4s, v1.4s
	BLE  LBB1_8
	WORD $0xbd400001 // ldr	s1, [x0]
	WORD $0xbd400022 // ldr	s2, [x1]
	WORD $0xf100051f // cmp	x8, #1
	WORD $0x1f020020 // fmadd	s0, s1, s2, s0
	BEQ  LBB1_8
	WORD $0xbd400401 // ldr	s1, [x0, #4]
	WORD $0xbd400422 // ldr	s2, [x1, #4]
	WORD $0xf100091f // cmp	x8, #2
	WORD $0x1f020020 // fmadd	s0, s1, s2, s0
	BEQ  LBB1_8
	WORD $0xbd400801 // ldr	s1, [x0, #8]
	WORD $0xbd400822 // ldr	s2, [x1, #8]
	WORD $0x1f020020 // fmadd	s0, s1, s2, s0

LBB1_8:
	WORD $0xbd000060 // str	s0, [x3]
	RET

TEXT ·xvec_neon_dot_norms(SB), $0-48
	MOVD left+0(FP), R0
	MOVD right+8(FP), R1
	MOVD size+16(FP), R2
	MOVD dot+24(FP), R3
	MOVD left_norm+32(FP), R4
	MOVD right_norm+40(FP), R5
	WORD $0x91000c48           // add	x8, x2, #3
	WORD $0xf100005f           // cmp	x2, #0
	WORD $0x6f00e400           // movi	v0.2d, #0000000000000000
	WORD $0x9a82b109           // csel	x9, x8, x2, lt
	WORD $0xf100105f           // cmp	x2, #4
	WORD $0x927ef528           // and	x8, x9, #0xfffffffffffffffc
	WORD $0xcb080048           // sub	x8, x2, x8
	BLT  LBB2_4
	WORD $0x6f00e401           // movi	v1.2d, #0000000000000000
	WORD $0x6f00e402           // movi	v2.2d, #0000000000000000
	WORD $0x9342fd29           // asr	x9, x9, #2
	WORD $0xaa0003eb           // mov	x11, x0
	WORD $0xaa0103ec           // mov	x12, x1
	WORD $0xaa0903ea           // mov	x10, x9

LBB2_2:
	WORD $0x3cc10563 // ldr	q3, [x11], #16
	WORD $0xf100054a // subs	x10, x10, #1
	WORD $0x3cc10584 // ldr	q4, [x12], #16
	WORD $0x4e23cc62 // fmla	v2.4s, v3.4s, v3.4s
	WORD $0x4e23cc81 // fmla	v1.4s, v4.4s, v3.4s
	WORD $0x4e24cc80 // fmla	v0.4s, v4.4s, v4.4s
	BNE  LBB2_2
	WORD $0xd37ced29 // lsl	x9, x9, #4
	WORD $0x8b090000 // add	x0, x0, x9
	WORD $0x8b090021 // add	x1, x1, x9
	B    LBB2_5

LBB2_4:
	WORD $0x6f00e402 // movi	v2.2d, #0000000000000000
	WORD $0x6f00e401 // movi	v1.2d, #0000000000000000

LBB2_5:
	WORD $0x4e0c0423 // dup	v3.4s, v1.s[1]
	WORD $0x4e0c0444 // dup	v4.4s, v2.s[1]
	WORD $0xf100011f // cmp	x8, #0
	WORD $0x4e0c0405 // dup	v5.4s, v0.s[1]
	WORD $0x4e140426 // dup	v6.4s, v1.s[2]
	WORD $0x4e140447 // dup	v7.4s, v2.s[2]
	WORD $0x4e140410 // dup	v16.4s, v0.s[2]
	WORD $0x4e23d423 // fadd	v3.4s, v1.4s, v3.4s
	WORD $0x4e24d444 // fadd	v4.4s, v2.4s, v4.4s
	WORD $0x4e1c0421 // dup	v1.4s, v1.s[3]
	WORD $0x4e25d405 // fadd	v5.4s, v0.4s, v5.4s
	WORD $0x4e1c0442 // dup	v2.4s, v2.s[3]
	WORD $0x4e1c0400 // dup	v0.4s, v0.s[3]
	WORD $0x4e23d4c3 // fadd	v3.4s, v6.4s, v3.4s
	WORD $0x4e24d4e4 // fadd	v4.4s, v7.4s, v4.4s
	WORD $0x4e25d605 // fadd	v5.4s, v16.4s, v5.4s
	WORD $0x4e23d421 // fadd	v1.4s, v1.4s, v3.4s
	WORD $0x4e24d442 // fadd	v2.4s, v2.4s, v4.4s
	WORD $0x4e25d400 // fadd	v0.4s, v0.4s, v5.4s
	WORD $0xbd000061 // str	s1, [x3]
	WORD $0xbd000082 // str	s2, [x4]
	WORD $0xbd0000a0 // str	s0, [x5]
	BLE  LBB2_8
	WORD $0xbd400000 // ldr	s0, [x0]
	WORD $0xbd400021 // ldr	s1, [x1]
	WORD $0xf100051f // cmp	x8, #1
	WORD $0xbd400062 // ldr	s2, [x3]
	WORD $0x1f010800 // fmadd	s0, s0, s1, s2
	WORD $0xbd000060 // str	s0, [x3]
	WORD $0xbd400000 // ldr	s0, [x0]
	WORD $0xbd400081 // ldr	s1, [x4]
	WORD $0x1f000400 // fmadd	s0, s0, s0, s1
	WORD $0xbd000080 // str	s0, [x4]
	WORD $0xbd400020 // ldr	s0, [x1]
	WORD $0xbd4000a1 // ldr	s1, [x5]
	WORD $0x1f000400 // fmadd	s0, s0, s0, s1
	WORD $0xbd0000a0 // str	s0, [x5]
	BEQ  LBB2_8
	WORD $0xbd400400 // ldr	s0, [x0, #4]
	WORD $0xbd400421 // ldr	s1, [x1, #4]
	WORD $0xf100091f // cmp	x8, #2
	WORD $0xbd400062 // ldr	s2, [x3]
	WORD $0x1f010800 // fmadd	s0, s0, s1, s2
	WORD $0xbd000060 // str	s0, [x3]
	WORD $0xbd400400 // ldr	s0, [x0, #4]
	WORD $0xbd400081 // ldr	s1, [x4]
	WORD $0x1f000400 // fmadd	s0, s0, s0, s1
	WORD $0xbd000080 // str	s0, [x4]
	WORD $0xbd400420 // ldr	s0, [x1, #4]
	WORD $0xbd4000a1 // ldr	s1, [x5]
	WORD $0x1f000400 // fmadd	s0, s0, s0, s1
	WORD $0xbd0000a0 // str	s0, [x5]
	BNE  LBB2_9

LBB2_8:
	RET

LBB2_9:
	WORD $0xbd400800 // ldr	s0, [x0, #8]
	WORD $0xbd400821 // ldr	s1, [x1, #8]
	WORD $0xbd400062 // ldr	s2, [x3]
	WORD $0x1f010800 // fmadd	s0, s0, s1, s2
	WORD $0xbd000060 // str	s0, [x3]
	WORD $0xbd400800 // ldr	s0, [x0, #8]
	WORD $0xbd400081 // ldr	s1, [x4]
	WORD $0x1f000400 // fmadd	s0, s0, s0, s1
	WORD $0xbd000080 // str	s0, [x4]
	WORD $0xbd400820 // ldr	s0, [x1, #8]
	WORD $0xbd4000a1 // ldr	s1, [x5]
	WORD $0x1f000400 // fmadd	s0, s0, s0, s1
	WORD $0xbd0000a0 // str	s0, [x5]
	RET
