//go:build !noasm && riscv64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8 (6ubuntu1)
// 	objdump 2.46
// flags: -march=rv64imafdv -isystem /usr/lib/llvm-21/lib/clang/21/include -O3
// source: src/euclidean_distance_matrix_fp32_rvv.c

TEXT ·squared_euclidean_distance_fp32_rvv(SB), $8-28
	MOV  lhs+0(FP), A0
	MOV  rhs+8(FP), A1
	MOV  size+16(FP), A2
	WORD $0x0d0077d7     // vsetvli	a5, zero, e32, m1, ta, ma
	WORD $0x02f656b3     // divu	a3, a2, a5
	WORD $0x02f68733     // mul	a4, a3, a5
	WORD $0x40e60633     // sub	a2, a2, a4
	WORD $0x5e003457     // vmv.v.i	v8, 0
	BLEZ A3, LBB0_6
	WORD $0x00000713     // li	a4, 0
	WORD $0x00279793     // slli	a5, a5, 2
	WORD $0x9e8034d7     // vmv1r.v	v9, v8

LBB0_2:
	WORD $0x02056507    // vle32.v	v10, (a0)
	WORD $0x0205e587    // vle32.v	v11, (a1)
	WORD $0x00170713    // addi	a4, a4, 1
	WORD $0x00f50533    // add	a0, a0, a5
	WORD $0x0aa59557    // vfsub.vv	v10, v10, v11
	WORD $0xb2a514d7    // vfmacc.vv	v9, v10, v10
	WORD $0x00f585b3    // add	a1, a1, a5
	BLT  A4, A3, LBB0_2
	WORD $0x0e941457    // vfredosum.vs	v8, v9, v8
	WORD $0x42801557    // vfmv.f.s	fa0, v8
	BEQZ A2, LBB0_5

LBB0_4:
	WORD $0x0d067057 // vsetvli	zero, a2, e32, m1, ta, ma
	WORD $0x02056407 // vle32.v	v8, (a0)
	WORD $0x0205e487 // vle32.v	v9, (a1)
	WORD $0x0a849457 // vfsub.vv	v8, v8, v9
	WORD $0x92841457 // vfmul.vv	v8, v8, v8
	WORD $0x5e0034d7 // vmv.v.i	v9, 0
	WORD $0x0e849457 // vfredosum.vs	v8, v8, v9
	WORD $0x428017d7 // vfmv.f.s	fa5, v8
	WORD $0x00f57553 // fadd.s	fa0, fa0, fa5

LBB0_5:
	MOVF FA0, result+24(FP)
	RET

LBB0_6:
	WORD $0x0e841457 // vfredosum.vs	v8, v8, v8
	WORD $0x42801557 // vfmv.f.s	fa0, v8
	BNEZ A2, LBB0_4
	JMP  LBB0_5
