//go:build !noasm && arm64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8 (6ubuntu1)
// 	objdump 2.46
// flags: -O3
// source: src/euclidean_distance_matrix_fp32_neon.c

TEXT ·squared_euclidean_distance_fp32_neon(SB), $0-28
	MOVD lhs+0(FP), R0
	MOVD rhs+8(FP), R1
	MOVD size+16(FP), R2
	WORD $0xd37ef448     // lsl	x8, x2, #2
	WORD $0xf27be909     // ands	x9, x8, #0xffffffffffffffe0
	WORD $0x8b080008     // add	x8, x0, x8
	WORD $0x8b090009     // add	x9, x0, x9
	BEQ  LBB0_12
	WORD $0x6f00e400     // movi	v0.2d, #0000000000000000
	WORD $0x6f00e401     // movi	v1.2d, #0000000000000000

LBB0_2:
	WORD $0xacc10c02 // ldp	q2, q3, [x0], #32
	WORD $0xacc11424 // ldp	q4, q5, [x1], #32
	WORD $0xeb09001f // cmp	x0, x9
	WORD $0x4ea4d442 // fsub	v2.4s, v2.4s, v4.4s
	WORD $0x4ea5d463 // fsub	v3.4s, v3.4s, v5.4s
	WORD $0x4e22cc40 // fmla	v0.4s, v2.4s, v2.4s
	WORD $0x4e23cc61 // fmla	v1.4s, v3.4s, v3.4s
	BNE  LBB0_2
	WORD $0xaa0903e0 // mov	x0, x9
	WORD $0x91004129 // add	x9, x9, #16
	WORD $0xeb09011f // cmp	x8, x9
	BLO  LBB0_5

LBB0_4:
	WORD $0x3cc10402 // ldr	q2, [x0], #16
	WORD $0x3cc10423 // ldr	q3, [x1], #16
	WORD $0x4ea3d442 // fsub	v2.4s, v2.4s, v3.4s
	WORD $0x4e22cc40 // fmla	v0.4s, v2.4s, v2.4s

LBB0_5:
	WORD $0x4e20d420 // fadd	v0.4s, v1.4s, v0.4s
	WORD $0xcb000108 // sub	x8, x8, x0
	WORD $0x9342fd08 // asr	x8, x8, #2
	WORD $0xf100051f // cmp	x8, #1
	WORD $0x6e20d400 // faddp	v0.4s, v0.4s, v0.4s
	WORD $0x7e30d800 // faddp	s0, v0.2s
	BEQ  LBB0_10
	WORD $0xf100091f // cmp	x8, #2
	BEQ  LBB0_9
	WORD $0xf1000d1f // cmp	x8, #3
	BNE  LBB0_11
	WORD $0xbd400801 // ldr	s1, [x0, #8]
	WORD $0xbd400822 // ldr	s2, [x1, #8]
	WORD $0x1e223821 // fsub	s1, s1, s2
	WORD $0x1f010020 // fmadd	s0, s1, s1, s0

LBB0_9:
	WORD $0xbd400401 // ldr	s1, [x0, #4]
	WORD $0xbd400422 // ldr	s2, [x1, #4]
	WORD $0x1e223821 // fsub	s1, s1, s2
	WORD $0x1f010020 // fmadd	s0, s1, s1, s0

LBB0_10:
	WORD $0xbd400001 // ldr	s1, [x0]
	WORD $0xbd400022 // ldr	s2, [x1]
	WORD $0x1e223821 // fsub	s1, s1, s2
	WORD $0x1f010020 // fmadd	s0, s1, s1, s0

LBB0_11:
	FMOVS F0, result+24(FP)
	RET

LBB0_12:
	WORD $0x6f00e401 // movi	v1.2d, #0000000000000000
	WORD $0x6f00e400 // movi	v0.2d, #0000000000000000
	WORD $0x91004129 // add	x9, x9, #16
	WORD $0xeb09011f // cmp	x8, x9
	BHS  LBB0_4
	B    LBB0_5
