//go:build !noasm && loong64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8 (6ubuntu1)
// 	objdump 2.46
// flags: -mlasx -O3
// source: src/euclidean_distance_matrix_fp32_lasx.c

package mathutil

import "unsafe"

//go:noescape
func squared_euclidean_distance_fp32_lasx(lhs, rhs unsafe.Pointer, size int64) (result float32)
