//go:build !noasm && loong64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8 (6ubuntu1)
// 	objdump 2.46
// flags: -mlasx -O3
// source: src/euclidean_distance_matrix_fp32_lasx.c

TEXT ·squared_euclidean_distance_fp32_lasx(SB), $8-28
	MOVV lhs+0(FP), R4
	MOVV rhs+8(FP), R5
	MOVV size+16(FP), R6
	WORD $0x02ff8063     // addi.d	$sp, $sp, -32
	WORD $0x0049fcc7     // srai.d	$a3, $a2, 63
	WORD $0x0045f4e7     // srli.d	$a3, $a3, 61
	WORD $0x00109cc8     // add.d	$a4, $a2, $a3
	WORD $0x00150107     // move	$a3, $a4
	WORD $0x00820007     // bstrins.d	$a3, $zero, 2, 0
	WORD $0x00119cc7     // sub.d	$a3, $a2, $a3
	WORD $0x03802009     // ori	$a5, $zero, 8
	WORD $0x77e00000     // xvldi	$xr0, 0
	BLT  R6, R9, LBB0_3
	WORD $0x00490d06     // srai.d	$a2, $a4, 3

LBB0_2:
	WORD $0x2c800081    // xvld	$xr1, $a0, 0
	WORD $0x2c8000a2    // xvld	$xr2, $a1, 0
	WORD $0x75328821    // xvfsub.s	$xr1, $xr1, $xr2
	WORD $0x75388421    // xvfmul.s	$xr1, $xr1, $xr1
	WORD $0x75308400    // xvfadd.s	$xr0, $xr0, $xr1
	WORD $0x02c08084    // addi.d	$a0, $a0, 32
	WORD $0x02fffcc6    // addi.d	$a2, $a2, -1
	WORD $0x02c080a5    // addi.d	$a1, $a1, 32
	BNE  R6, R0, LBB0_2

LBB0_3:
	WORD $0x02c00066    // addi.d	$a2, $sp, 0
	WORD $0x2cc000c0    // xvst	$xr0, $a2, 0
	WORD $0x2b000060    // fld.s	$fa0, $sp, 0
	WORD $0x0114a401    // movgr2fr.w	$fa1, $zero
	WORD $0x2b001062    // fld.s	$fa2, $sp, 4
	WORD $0x2b002063    // fld.s	$fa3, $sp, 8
	WORD $0x01008400    // fadd.s	$fa0, $fa0, $fa1
	WORD $0x2b003061    // fld.s	$fa1, $sp, 12
	WORD $0x01008800    // fadd.s	$fa0, $fa0, $fa2
	WORD $0x01008c00    // fadd.s	$fa0, $fa0, $fa3
	WORD $0x2b004062    // fld.s	$fa2, $sp, 16
	WORD $0x01008400    // fadd.s	$fa0, $fa0, $fa1
	WORD $0x2b005061    // fld.s	$fa1, $sp, 20
	WORD $0x2b006063    // fld.s	$fa3, $sp, 24
	WORD $0x01008800    // fadd.s	$fa0, $fa0, $fa2
	WORD $0x2b007062    // fld.s	$fa2, $sp, 28
	WORD $0x01008400    // fadd.s	$fa0, $fa0, $fa1
	WORD $0x01008c00    // fadd.s	$fa0, $fa0, $fa3
	WORD $0x03800406    // ori	$a2, $zero, 1
	WORD $0x01008800    // fadd.s	$fa0, $fa0, $fa2
	BLT  R7, R6, LBB0_5

LBB0_4:
	WORD $0x2b000081    // fld.s	$fa1, $a0, 0
	WORD $0x2b0000a2    // fld.s	$fa2, $a1, 0
	WORD $0x01028821    // fsub.s	$fa1, $fa1, $fa2
	WORD $0x08100420    // fmadd.s	$fa0, $fa1, $fa1, $fa0
	WORD $0x02fffce7    // addi.d	$a3, $a3, -1
	WORD $0x02c010a5    // addi.d	$a1, $a1, 4
	WORD $0x02c01084    // addi.d	$a0, $a0, 4
	BNE  R7, R0, LBB0_4

LBB0_5:
	WORD $0x02c08063       // addi.d	$sp, $sp, 32
	MOVF F0, result+24(FP)
	RET
