//go:build !noasm && riscv64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8 (6ubuntu1)
// 	objdump 2.46
// flags: -march=rv64imafdv -isystem /usr/lib/llvm-21/lib/clang/21/include -O3
// source: src/fht_rvv.c

package mathutil

import "unsafe"

//go:noescape
func fht_flip_sign_rvv(signs, data unsafe.Pointer, size int64)

//go:noescape
func fht_kacs_walk_rvv(data unsafe.Pointer, size int64)

//go:noescape
func fht_inv_kacs_walk_rvv(data unsafe.Pointer, size int64)

//go:noescape
func fht_inplace_rvv(data unsafe.Pointer, size int64)
