//go:build !noasm && arm64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8 (6ubuntu1)
// 	objdump 2.46
// flags: -O3
// source: src/fht_neon.c

TEXT ·fht_flip_sign_neon(SB), $0-24
	MOVD signs+0(FP), R0
	MOVD data+8(FP), R1
	MOVD size+16(FP), R2
	WORD $0xd10043ff     // sub	sp, sp, #16
	WORD $0xf100105f     // cmp	x2, #4
	WORD $0x927ef448     // and	x8, x2, #0xfffffffffffffffc
	BLT  LBB0_5
	WORD $0x91001c4a     // add	x10, x2, #7
	WORD $0xaa1f03e9     // mov	x9, xzr
	WORD $0x910003eb     // mov	x11, sp
	WORD $0xd343fd4a     // lsr	x10, x10, #3
	WORD $0xaa0103ec     // mov	x12, x1
	B    LBB0_3

LBB0_2:
	WORD $0x12003dad // and	w13, w13, #0xffff
	WORD $0x927e012e // and	x14, x9, #0x4
	WORD $0x91001129 // add	x9, x9, #4
	WORD $0x1ace25ad // lsr	w13, w13, w14
	WORD $0xeb08013f // cmp	x9, x8
	WORD $0x121f01af // and	w15, w13, #0x2
	WORD $0x530101ae // lsl	w14, w13, #31
	WORD $0x530309b0 // lsl	w16, w13, #29
	WORD $0x121d01ad // and	w13, w13, #0x8
	WORD $0xd341fdef // lsr	x15, x15, #1
	WORD $0xd343fdad // lsr	x13, x13, #3
	WORD $0xb34101ee // bfi	x14, x15, #63, #1
	WORD $0x1201020f // and	w15, w16, #0x80000000
	WORD $0xb34101af // bfi	x15, x13, #63, #1
	WORD $0xf90007ee // str	x14, [sp, #8]
	WORD $0xf90003ef // str	x15, [sp]
	WORD $0xfd4007e0 // ldr	d0, [sp, #8]
	WORD $0x4d408560 // ld1	{ v0.d }[1], [x11]
	WORD $0x3dc00181 // ldr	q1, [x12]
	WORD $0x6e201c20 // eor	v0.16b, v1.16b, v0.16b
	WORD $0x3c810580 // str	q0, [x12], #16
	BGE  LBB0_5

LBB0_3:
	WORD $0xd343fd2d // lsr	x13, x9, #3
	WORD $0x910005ae // add	x14, x13, #1
	WORD $0x386d680d // ldrb	w13, [x0, x13]
	WORD $0xeb0a01df // cmp	x14, x10
	BHS  LBB0_2
	WORD $0x386e680e // ldrb	w14, [x0, x14]
	WORD $0x2a0e21ad // orr	w13, w13, w14, lsl #8
	B    LBB0_2

LBB0_5:
	WORD $0xeb02011f // cmp	x8, x2
	BNE  LBB0_8

LBB0_6:
	WORD $0x910043ff // add	sp, sp, #16
	RET

LBB0_7:
	WORD $0x91000508 // add	x8, x8, #1
	WORD $0xeb02011f // cmp	x8, x2
	BGE  LBB0_6

LBB0_8:
	WORD $0x91001d09 // add	x9, x8, #7
	WORD $0xf100011f // cmp	x8, #0
	WORD $0x9a88b129 // csel	x9, x9, x8, lt
	WORD $0x9343fd29 // asr	x9, x9, #3
	WORD $0x3869680a // ldrb	w10, [x0, x9]
	WORD $0x4b090d09 // sub	w9, w8, w9, lsl #3
	WORD $0x1ac92549 // lsr	w9, w10, w9
	WORD $0x3607fec9 // tbz	w9, #0, .LBB0_7
	WORD $0xbc687820 // ldr	s0, [x1, x8, lsl #2]
	WORD $0x1e214000 // fneg	s0, s0
	WORD $0xbc287820 // str	s0, [x1, x8, lsl #2]
	B    LBB0_7

TEXT ·fht_kacs_walk_neon(SB), $0-16
	MOVD data+0(FP), R0
	MOVD size+8(FP), R1
	WORD $0x8b41fc28    // add	x8, x1, x1, lsr #63
	WORD $0xf100203f    // cmp	x1, #8
	WORD $0x9341fd08    // asr	x8, x8, #1
	WORD $0x927ef509    // and	x9, x8, #0xfffffffffffffffc
	BLT  LBB1_3
	WORD $0xd37ef42b    // lsl	x11, x1, #2
	WORD $0xaa1f03ea    // mov	x10, xzr
	WORD $0xaa0003ec    // mov	x12, x0
	WORD $0xcb08096b    // sub	x11, x11, x8, lsl #2

LBB1_2:
	WORD $0x3dc00180 // ldr	q0, [x12]
	WORD $0x3ceb6981 // ldr	q1, [x12, x11]
	WORD $0x9100114a // add	x10, x10, #4
	WORD $0xeb09015f // cmp	x10, x9
	WORD $0x4e21d402 // fadd	v2.4s, v0.4s, v1.4s
	WORD $0x4ea1d400 // fsub	v0.4s, v0.4s, v1.4s
	WORD $0x3d800182 // str	q2, [x12]
	WORD $0x3cab6980 // str	q0, [x12, x11]
	WORD $0x9100418c // add	x12, x12, #16
	BLT  LBB1_2

LBB1_3:
	WORD $0xeb08013f // cmp	x9, x8
	BEQ  LBB1_11
	WORD $0xb240012b // orr	x11, x9, #0x1
	WORD $0xeb0b011f // cmp	x8, x11
	WORD $0x9a89c50a // csinc	x10, x8, x9, gt
	WORD $0xcb09014a // sub	x10, x10, x9
	WORD $0xf100415f // cmp	x10, #16
	BLO  LBB1_9
	WORD $0xeb0b011f // cmp	x8, x11
	WORD $0xd342fd0c // lsr	x12, x8, #2
	WORD $0x927eed0d // and	x13, x8, #0x3ffffffffffffffc
	WORD $0x9a89c50b // csinc	x11, x8, x9, gt
	WORD $0x8b0d002d // add	x13, x1, x13
	WORD $0x8b0b002e // add	x14, x1, x11
	WORD $0x8b0c100c // add	x12, x0, x12, lsl #4
	WORD $0xcb0801ad // sub	x13, x13, x8
	WORD $0xcb0801ce // sub	x14, x14, x8
	WORD $0x8b0b080b // add	x11, x0, x11, lsl #2
	WORD $0x8b0d080d // add	x13, x0, x13, lsl #2
	WORD $0x8b0e080e // add	x14, x0, x14, lsl #2
	WORD $0xeb0e019f // cmp	x12, x14
	WORD $0xfa4b31a2 // ccmp	x13, x11, #2, lo
	BLO  LBB1_9
	WORD $0xd37ef50d // lsl	x13, x8, #2
	WORD $0xd37ef42e // lsl	x14, x1, #2
	WORD $0x927df14b // and	x11, x10, #0xfffffffffffffff8
	WORD $0x8b0b0129 // add	x9, x9, x11
	WORD $0x927cedac // and	x12, x13, #0xfffffffffffffff0
	WORD $0xcb0d01cd // sub	x13, x14, x13
	WORD $0xaa0b03ee // mov	x14, x11
	WORD $0x8b00018c // add	x12, x12, x0
	WORD $0x9100418c // add	x12, x12, #16

LBB1_7:
	WORD $0x8b0d018f // add	x15, x12, x13
	WORD $0xad7f8981 // ldp	q1, q2, [x12, #-16]
	WORD $0xad7f8de0 // ldp	q0, q3, [x15, #-16]
	WORD $0xf10021ce // subs	x14, x14, #8
	WORD $0x4e20d424 // fadd	v4.4s, v1.4s, v0.4s
	WORD $0x4e23d445 // fadd	v5.4s, v2.4s, v3.4s
	WORD $0x4ea0d420 // fsub	v0.4s, v1.4s, v0.4s
	WORD $0x4ea3d441 // fsub	v1.4s, v2.4s, v3.4s
	WORD $0xad3f9584 // stp	q4, q5, [x12, #-16]
	WORD $0x9100818c // add	x12, x12, #32
	WORD $0xad3f85e0 // stp	q0, q1, [x15, #-16]
	BNE  LBB1_7
	WORD $0xeb0b015f // cmp	x10, x11
	BEQ  LBB1_11

LBB1_9:
	WORD $0xcb08080a // sub	x10, x0, x8, lsl #2
	WORD $0x8b01094a // add	x10, x10, x1, lsl #2

LBB1_10:
	WORD $0xbc697800 // ldr	s0, [x0, x9, lsl #2]
	WORD $0xbc697941 // ldr	s1, [x10, x9, lsl #2]
	WORD $0x1e212802 // fadd	s2, s0, s1
	WORD $0x1e213800 // fsub	s0, s0, s1
	WORD $0xbc297802 // str	s2, [x0, x9, lsl #2]
	WORD $0xbc297940 // str	s0, [x10, x9, lsl #2]
	WORD $0x91000529 // add	x9, x9, #1
	WORD $0xeb08013f // cmp	x9, x8
	BLT  LBB1_10

LBB1_11:
	RET

TEXT ·fht_inv_kacs_walk_neon(SB), $0-16
	MOVD data+0(FP), R0
	MOVD size+8(FP), R1
	WORD $0x8b41fc28    // add	x8, x1, x1, lsr #63
	WORD $0xf100203f    // cmp	x1, #8
	WORD $0x9341fd08    // asr	x8, x8, #1
	WORD $0x927ef509    // and	x9, x8, #0xfffffffffffffffc
	BLT  LBB2_3
	WORD $0xd37ef42b    // lsl	x11, x1, #2
	WORD $0x4f0167e0    // movi	v0.4s, #63, lsl #24
	WORD $0xaa1f03ea    // mov	x10, xzr
	WORD $0xaa0003ec    // mov	x12, x0
	WORD $0xcb08096b    // sub	x11, x11, x8, lsl #2

LBB2_2:
	WORD $0x3dc00181 // ldr	q1, [x12]
	WORD $0x3ceb6982 // ldr	q2, [x12, x11]
	WORD $0x9100114a // add	x10, x10, #4
	WORD $0xeb09015f // cmp	x10, x9
	WORD $0x4e22d423 // fadd	v3.4s, v1.4s, v2.4s
	WORD $0x4ea2d421 // fsub	v1.4s, v1.4s, v2.4s
	WORD $0x6e20dc62 // fmul	v2.4s, v3.4s, v0.4s
	WORD $0x6e20dc21 // fmul	v1.4s, v1.4s, v0.4s
	WORD $0x3d800182 // str	q2, [x12]
	WORD $0x3cab6981 // str	q1, [x12, x11]
	WORD $0x9100418c // add	x12, x12, #16
	BLT  LBB2_2

LBB2_3:
	WORD $0xeb08013f // cmp	x9, x8
	BEQ  LBB2_11
	WORD $0xb240012c // orr	x12, x9, #0x1
	WORD $0xeb0c011f // cmp	x8, x12
	WORD $0x9a89c50a // csinc	x10, x8, x9, gt
	WORD $0xcb09014b // sub	x11, x10, x9
	WORD $0xf100317f // cmp	x11, #12
	BLO  LBB2_9
	WORD $0xeb0c011f // cmp	x8, x12
	WORD $0xd342fd0d // lsr	x13, x8, #2
	WORD $0x927eed0e // and	x14, x8, #0x3ffffffffffffffc
	WORD $0x9a89c50c // csinc	x12, x8, x9, gt
	WORD $0x8b0e002e // add	x14, x1, x14
	WORD $0x8b0c002f // add	x15, x1, x12
	WORD $0x8b0d100d // add	x13, x0, x13, lsl #4
	WORD $0xcb0801ce // sub	x14, x14, x8
	WORD $0xcb0801ef // sub	x15, x15, x8
	WORD $0x8b0c080c // add	x12, x0, x12, lsl #2
	WORD $0x8b0e080e // add	x14, x0, x14, lsl #2
	WORD $0x8b0f080f // add	x15, x0, x15, lsl #2
	WORD $0xeb0f01bf // cmp	x13, x15
	WORD $0xfa4c31c2 // ccmp	x14, x12, #2, lo
	BLO  LBB2_9
	WORD $0xd37ef42d // lsl	x13, x1, #2
	WORD $0x4f0167e0 // movi	v0.4s, #63, lsl #24
	WORD $0x9240054a // and	x10, x10, #0x3
	WORD $0xcb0a016b // sub	x11, x11, x10
	WORD $0x8b09080c // add	x12, x0, x9, lsl #2
	WORD $0xcb0809ad // sub	x13, x13, x8, lsl #2
	WORD $0x8b0b0129 // add	x9, x9, x11

LBB2_7:
	WORD $0x3dc00181 // ldr	q1, [x12]
	WORD $0x3ced6982 // ldr	q2, [x12, x13]
	WORD $0xf100116b // subs	x11, x11, #4
	WORD $0x4e22d423 // fadd	v3.4s, v1.4s, v2.4s
	WORD $0x4ea2d421 // fsub	v1.4s, v1.4s, v2.4s
	WORD $0x6e20dc62 // fmul	v2.4s, v3.4s, v0.4s
	WORD $0x6e20dc21 // fmul	v1.4s, v1.4s, v0.4s
	WORD $0x3cad6981 // str	q1, [x12, x13]
	WORD $0x3c810582 // str	q2, [x12], #16
	BNE  LBB2_7
	WORD $0xb40001ea // cbz	x10, .LBB2_11

LBB2_9:
	WORD $0xcb08080a // sub	x10, x0, x8, lsl #2
	WORD $0x1e2c1000 // fmov	s0, #0.50000000
	WORD $0x8b01094a // add	x10, x10, x1, lsl #2

LBB2_10:
	WORD $0xbc697801 // ldr	s1, [x0, x9, lsl #2]
	WORD $0xbc697942 // ldr	s2, [x10, x9, lsl #2]
	WORD $0x1e222823 // fadd	s3, s1, s2
	WORD $0x1e223821 // fsub	s1, s1, s2
	WORD $0x1e200862 // fmul	s2, s3, s0
	WORD $0x1e200821 // fmul	s1, s1, s0
	WORD $0xbc297802 // str	s2, [x0, x9, lsl #2]
	WORD $0xbc297941 // str	s1, [x10, x9, lsl #2]
	WORD $0x91000529 // add	x9, x9, #1
	WORD $0xeb08013f // cmp	x9, x8
	BLT  LBB2_10

LBB2_11:
	RET

TEXT ·fht_inplace_neon(SB), $0-16
	MOVD data+0(FP), R0
	MOVD size+8(FP), R1
	WORD $0xf100083f    // cmp	x1, #2
	BLT  LBB3_29
	WORD $0xf81e0ff5    // str	x21, [sp, #-32]!
	WORD $0x91004008    // add	x8, x0, #16
	WORD $0x52800029    // mov	w9, #1
	WORD $0xa9014ff4    // stp	x20, x19, [sp, #16]
	B    LBB3_3

LBB3_2:
	WORD $0xeb01015f // cmp	x10, x1
	WORD $0xaa0a03e9 // mov	x9, x10
	BGE  LBB3_28

LBB3_3:
	WORD $0xd37ff92a // lsl	x10, x9, #1
	WORD $0xf1000d3f // cmp	x9, #3
	WORD $0x927ef52b // and	x11, x9, #0xfffffffffffffffc
	BLE  LBB3_9
	WORD $0xeb09017f // cmp	x11, x9
	BNE  LBB3_18
	WORD $0xd37df12c // lsl	x12, x9, #3
	WORD $0xd37ef52d // lsl	x13, x9, #2
	WORD $0xaa1f03eb // mov	x11, xzr
	WORD $0xaa0003ee // mov	x14, x0

LBB3_6:
	WORD $0xaa1f03ef // mov	x15, xzr
	WORD $0xaa0e03f0 // mov	x16, x14

LBB3_7:
	WORD $0x3dc00200 // ldr	q0, [x16]
	WORD $0x3ced6a01 // ldr	q1, [x16, x13]
	WORD $0x910011ef // add	x15, x15, #4
	WORD $0xeb0901ff // cmp	x15, x9
	WORD $0x4e21d402 // fadd	v2.4s, v0.4s, v1.4s
	WORD $0x4ea1d400 // fsub	v0.4s, v0.4s, v1.4s
	WORD $0x3d800202 // str	q2, [x16]
	WORD $0x3cad6a00 // str	q0, [x16, x13]
	WORD $0x91004210 // add	x16, x16, #16
	BLT  LBB3_7
	WORD $0x8b0a016b // add	x11, x11, x10
	WORD $0x8b0c01ce // add	x14, x14, x12
	WORD $0xeb01017f // cmp	x11, x1
	BLT  LBB3_6
	B    LBB3_2

LBB3_9:
	WORD $0xeb09017f // cmp	x11, x9
	BEQ  LBB3_2
	WORD $0xeb0a003f // cmp	x1, x10
	WORD $0xdac0014d // rbit	x13, x10
	WORD $0x927eed31 // and	x17, x9, #0x3ffffffffffffffc
	WORD $0x9a8ac02e // csel	x14, x1, x10, gt
	WORD $0x8b110131 // add	x17, x9, x17
	WORD $0xaa1f03ec // mov	x12, xzr
	WORD $0xd10005ce // sub	x14, x14, #1
	WORD $0xdac011af // clz	x15, x13
	WORD $0xd37df12d // lsl	x13, x9, #3
	WORD $0x9acf25ce // lsr	x14, x14, x15
	WORD $0x8b110811 // add	x17, x0, x17, lsl #2
	WORD $0x9b0e01af // madd	x15, x13, x14, x0
	WORD $0xb240016e // orr	x14, x11, #0x1
	WORD $0xeb0e013f // cmp	x9, x14
	WORD $0xd37ef52e // lsl	x14, x9, #2
	WORD $0x9a8bc530 // csinc	x16, x9, x11, gt
	WORD $0x8b100122 // add	x2, x9, x16
	WORD $0x927cedc3 // and	x3, x14, #0xfffffffffffffff0
	WORD $0x8b030004 // add	x4, x0, x3
	WORD $0x8b030103 // add	x3, x8, x3
	WORD $0x8b0209e2 // add	x2, x15, x2, lsl #2
	WORD $0x8b1009ef // add	x15, x15, x16, lsl #2
	WORD $0xeb02009f // cmp	x4, x2
	WORD $0xaa0003e4 // mov	x4, x0
	WORD $0xfa4f3222 // ccmp	x17, x15, #2, lo
	WORD $0xcb0b020f // sub	x15, x16, x11
	WORD $0xfa4029a8 // ccmp	x13, #0, #8, hs
	WORD $0x927df1f0 // and	x16, x15, #0xfffffffffffffff8
	WORD $0x1a9fa7f1 // cset	w17, lt
	WORD $0x8b100162 // add	x2, x11, x16
	B    LBB3_12

LBB3_11:
	WORD $0x8b0a018c // add	x12, x12, x10
	WORD $0x8b0d0063 // add	x3, x3, x13
	WORD $0x8b0d0084 // add	x4, x4, x13
	WORD $0xeb01019f // cmp	x12, x1
	BGE  LBB3_2

LBB3_12:
	WORD $0xf10021ff // cmp	x15, #8
	WORD $0x1a9f27e5 // cset	w5, lo
	WORD $0x2a1100a6 // orr	w6, w5, w17
	WORD $0xaa0b03e5 // mov	x5, x11
	WORD $0x37000246 // tbnz	w6, #0, .LBB3_16
	WORD $0xaa0303e5 // mov	x5, x3
	WORD $0xaa1003e6 // mov	x6, x16

LBB3_14:
	WORD $0x8b0e00a7 // add	x7, x5, x14
	WORD $0xad7f88a1 // ldp	q1, q2, [x5, #-16]
	WORD $0xad7f8ce0 // ldp	q0, q3, [x7, #-16]
	WORD $0xf10020c6 // subs	x6, x6, #8
	WORD $0x4e20d424 // fadd	v4.4s, v1.4s, v0.4s
	WORD $0x4e23d445 // fadd	v5.4s, v2.4s, v3.4s
	WORD $0x4ea0d420 // fsub	v0.4s, v1.4s, v0.4s
	WORD $0x4ea3d441 // fsub	v1.4s, v2.4s, v3.4s
	WORD $0xad3f94a4 // stp	q4, q5, [x5, #-16]
	WORD $0x910080a5 // add	x5, x5, #32
	WORD $0xad3f84e0 // stp	q0, q1, [x7, #-16]
	BNE  LBB3_14
	WORD $0xeb1001ff // cmp	x15, x16
	WORD $0xaa0203e5 // mov	x5, x2
	BEQ  LBB3_11

LBB3_16:
	WORD $0x8b050887 // add	x7, x4, x5, lsl #2
	WORD $0xaa1f03e6 // mov	x6, xzr
	WORD $0x8b0e00f3 // add	x19, x7, x14

LBB3_17:
	WORD $0xbc6678e0 // ldr	s0, [x7, x6, lsl #2]
	WORD $0xbc667a61 // ldr	s1, [x19, x6, lsl #2]
	WORD $0x1e212802 // fadd	s2, s0, s1
	WORD $0x1e213800 // fsub	s0, s0, s1
	WORD $0xbc2678e2 // str	s2, [x7, x6, lsl #2]
	WORD $0xbc267a60 // str	s0, [x19, x6, lsl #2]
	WORD $0x910004c6 // add	x6, x6, #1
	WORD $0x8b0600b4 // add	x20, x5, x6
	WORD $0xeb09029f // cmp	x20, x9
	BLT  LBB3_17
	B    LBB3_11

LBB3_18:
	WORD $0xeb0a003f // cmp	x1, x10
	WORD $0xdac0014d // rbit	x13, x10
	WORD $0x927eed31 // and	x17, x9, #0x3ffffffffffffffc
	WORD $0x9a8ac02e // csel	x14, x1, x10, gt
	WORD $0x8b110131 // add	x17, x9, x17
	WORD $0xaa1f03ec // mov	x12, xzr
	WORD $0xd10005ce // sub	x14, x14, #1
	WORD $0xdac011af // clz	x15, x13
	WORD $0xd37df12d // lsl	x13, x9, #3
	WORD $0x9acf25ce // lsr	x14, x14, x15
	WORD $0x8b110811 // add	x17, x0, x17, lsl #2
	WORD $0xaa0003e5 // mov	x5, x0
	WORD $0x9b0e01af // madd	x15, x13, x14, x0
	WORD $0xb240016e // orr	x14, x11, #0x1
	WORD $0xeb0e013f // cmp	x9, x14
	WORD $0xd37ef52e // lsl	x14, x9, #2
	WORD $0x9a8bc530 // csinc	x16, x9, x11, gt
	WORD $0x8b100122 // add	x2, x9, x16
	WORD $0x927cedc4 // and	x4, x14, #0xfffffffffffffff0
	WORD $0x8b040003 // add	x3, x0, x4
	WORD $0x8b040104 // add	x4, x8, x4
	WORD $0x8b0209e2 // add	x2, x15, x2, lsl #2
	WORD $0x8b1009ef // add	x15, x15, x16, lsl #2
	WORD $0xeb02007f // cmp	x3, x2
	WORD $0xfa4f3222 // ccmp	x17, x15, #2, lo
	WORD $0x91000571 // add	x17, x11, #1
	WORD $0xcb0b020f // sub	x15, x16, x11
	WORD $0xfa4029a8 // ccmp	x13, #0, #8, hs
	WORD $0x1a9fa7f0 // cset	w16, lt
	WORD $0xeb11013f // cmp	x9, x17
	WORD $0x927df1f1 // and	x17, x15, #0xfffffffffffffff8
	WORD $0x9a8bc523 // csinc	x3, x9, x11, gt
	WORD $0x8b110162 // add	x2, x11, x17
	WORD $0xcb0b0063 // sub	x3, x3, x11
	WORD $0x927df063 // and	x3, x3, #0xfffffffffffffff8
	B    LBB3_20

LBB3_19:
	WORD $0x8b0a018c // add	x12, x12, x10
	WORD $0x8b0d00a5 // add	x5, x5, x13
	WORD $0x8b0d0084 // add	x4, x4, x13
	WORD $0xeb01019f // cmp	x12, x1
	BGE  LBB3_2

LBB3_20:
	WORD $0xaa1f03e6 // mov	x6, xzr
	WORD $0xaa0503e7 // mov	x7, x5

LBB3_21:
	WORD $0x3dc000e0 // ldr	q0, [x7]
	WORD $0x3cee68e1 // ldr	q1, [x7, x14]
	WORD $0x910010c6 // add	x6, x6, #4
	WORD $0xeb0b00df // cmp	x6, x11
	WORD $0x4e21d402 // fadd	v2.4s, v0.4s, v1.4s
	WORD $0x4ea1d400 // fsub	v0.4s, v0.4s, v1.4s
	WORD $0x3d8000e2 // str	q2, [x7]
	WORD $0x3cae68e0 // str	q0, [x7, x14]
	WORD $0x910040e7 // add	x7, x7, #16
	BLT  LBB3_21
	WORD $0xf10021ff // cmp	x15, #8
	WORD $0x1a9f27e6 // cset	w6, lo
	WORD $0x2a1000c7 // orr	w7, w6, w16
	WORD $0xaa0b03e6 // mov	x6, x11
	WORD $0x37000247 // tbnz	w7, #0, .LBB3_26
	WORD $0xaa0403e6 // mov	x6, x4
	WORD $0xaa0303e7 // mov	x7, x3

LBB3_24:
	WORD $0x8b0e00d3 // add	x19, x6, x14
	WORD $0xad7f88c1 // ldp	q1, q2, [x6, #-16]
	WORD $0xad7f8e60 // ldp	q0, q3, [x19, #-16]
	WORD $0xf10020e7 // subs	x7, x7, #8
	WORD $0x4e20d424 // fadd	v4.4s, v1.4s, v0.4s
	WORD $0x4e23d445 // fadd	v5.4s, v2.4s, v3.4s
	WORD $0x4ea0d420 // fsub	v0.4s, v1.4s, v0.4s
	WORD $0x4ea3d441 // fsub	v1.4s, v2.4s, v3.4s
	WORD $0xad3f94c4 // stp	q4, q5, [x6, #-16]
	WORD $0x910080c6 // add	x6, x6, #32
	WORD $0xad3f8660 // stp	q0, q1, [x19, #-16]
	BNE  LBB3_24
	WORD $0xeb1101ff // cmp	x15, x17
	WORD $0xaa0203e6 // mov	x6, x2
	BEQ  LBB3_19

LBB3_26:
	WORD $0x8b0608b3 // add	x19, x5, x6, lsl #2
	WORD $0xaa1f03e7 // mov	x7, xzr
	WORD $0x8b0e0274 // add	x20, x19, x14

LBB3_27:
	WORD $0xbc677a60 // ldr	s0, [x19, x7, lsl #2]
	WORD $0xbc677a81 // ldr	s1, [x20, x7, lsl #2]
	WORD $0x1e212802 // fadd	s2, s0, s1
	WORD $0x1e213800 // fsub	s0, s0, s1
	WORD $0xbc277a62 // str	s2, [x19, x7, lsl #2]
	WORD $0xbc277a80 // str	s0, [x20, x7, lsl #2]
	WORD $0x910004e7 // add	x7, x7, #1
	WORD $0x8b0700d5 // add	x21, x6, x7
	WORD $0xeb0902bf // cmp	x21, x9
	BLT  LBB3_27
	B    LBB3_19

LBB3_28:
	WORD $0xa9414ff4 // ldp	x20, x19, [sp, #16]
	WORD $0xf84207f5 // ldr	x21, [sp], #32

LBB3_29:
	RET
