//go:build !noasm && amd64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8 (6ubuntu1)
// 	objdump 2.46
// flags: -mavx512f -mavx512dq -O3
// source: src/fht_avx512.c

TEXT ·xvec_avx512_fht_flip_signs(SB), $0-24
	MOVQ signs+0(FP), DI
	MOVQ data+8(FP), SI
	MOVQ size+16(FP), DX
	BYTE $0x55                     // pushq	%rbp
	WORD $0x8948; BYTE $0xe5       // movq	%rsp, %rbp
	LONG $0xf8e48348               // andq	$-8, %rsp
	LONG $0x10ec8348               // subq	$16, %rsp
	WORD $0x8948; BYTE $0xd0       // movq	%rdx, %rax
	LONG $0xc0e08348               // andq	$-64, %rax
	QUAD $0x800000000c2444c7       // movl	$-2147483648, 12(%rsp)          # imm = 0x80000000
	LONG $0x0c244c8b               // movl	12(%rsp), %ecx
	LONG $0x40fa8348               // cmpq	$64, %rdx
	JL   LBB0_3
	LONG $0x487df262; WORD $0xc17c // vpbroadcastd	%ecx, %zmm0
	WORD $0xc931                   // xorl	%ecx, %ecx
	WORD $0x8949; BYTE $0xf8       // movq	%rdi, %r8

LBB0_2:
	WORD $0x8b4d; BYTE $0x08                   // movq	(%r8), %r9
	LONG $0x9278c1c4; BYTE $0xc9               // kmovw	%r9d, %k1
	LONG $0x48fef162; WORD $0x0c6f; BYTE $0x8e // vmovdqu64	(%rsi,%rcx,4), %zmm1
	QUAD $0x018e546f48fef162                   // vmovdqu64	64(%rsi,%rcx,4), %zmm2
	QUAD $0x028e5c6f48fef162                   // vmovdqu64	128(%rsi,%rcx,4), %zmm3
	QUAD $0x038e646f48fef162                   // vmovdqu64	192(%rsi,%rcx,4), %zmm4
	LONG $0x497df162; WORD $0xc9ef             // vpxord	%zmm1, %zmm0, %zmm1 {%k1}
	LONG $0x48fef162; WORD $0x0c7f; BYTE $0x8e // vmovdqu64	%zmm1, (%rsi,%rcx,4)
	WORD $0x8945; BYTE $0xca                   // movl	%r9d, %r10d
	LONG $0x10eac141                           // shrl	$16, %r10d
	LONG $0x9278c1c4; BYTE $0xca               // kmovw	%r10d, %k1
	LONG $0x497df162; WORD $0xd2ef             // vpxord	%zmm2, %zmm0, %zmm2 {%k1}
	QUAD $0x018e547f48fef162                   // vmovdqu64	%zmm2, 64(%rsi,%rcx,4)
	WORD $0x894d; BYTE $0xca                   // movq	%r9, %r10
	LONG $0x20eac149                           // shrq	$32, %r10
	LONG $0x9278c1c4; BYTE $0xca               // kmovw	%r10d, %k1
	LONG $0x497df162; WORD $0xdbef             // vpxord	%zmm3, %zmm0, %zmm3 {%k1}
	QUAD $0x028e5c7f48fef162                   // vmovdqu64	%zmm3, 128(%rsi,%rcx,4)
	LONG $0x30e9c149                           // shrq	$48, %r9
	LONG $0x9278c1c4; BYTE $0xc9               // kmovw	%r9d, %k1
	LONG $0x497df162; WORD $0xe4ef             // vpxord	%zmm4, %zmm0, %zmm4 {%k1}
	QUAD $0x038e647f48fef162                   // vmovdqu64	%zmm4, 192(%rsi,%rcx,4)
	LONG $0x40c18348                           // addq	$64, %rcx
	LONG $0x08c08349                           // addq	$8, %r8
	WORD $0x3948; BYTE $0xc1                   // cmpq	%rax, %rcx
	JL   LBB0_2

LBB0_3:
	WORD $0x3948; BYTE $0xd0 // cmpq	%rdx, %rax
	JNE  LBB0_4

LBB0_7:
	WORD $0x8948; BYTE $0xec // movq	%rbp, %rsp
	BYTE $0x5d               // popq	%rbp
	WORD $0xf8c5; BYTE $0x77 // vzeroupper
	RET

LBB0_6:
	WORD $0xff48; BYTE $0xc0 // incq	%rax
	WORD $0x3948; BYTE $0xd0 // cmpq	%rdx, %rax
	JGE  LBB0_7

LBB0_4:
	LONG $0x07488d48             // leaq	7(%rax), %rcx
	WORD $0x8548; BYTE $0xc0     // testq	%rax, %rax
	LONG $0xc8490f48             // cmovnsq	%rax, %rcx
	LONG $0x03f9c148             // sarq	$3, %rcx
	LONG $0x04b60f44; BYTE $0x0f // movzbl	(%rdi,%rcx), %r8d
	WORD $0xe1c1; BYTE $0x03     // shll	$3, %ecx
	WORD $0x8941; BYTE $0xc1     // movl	%eax, %r9d
	WORD $0x2941; BYTE $0xc9     // subl	%ecx, %r9d
	LONG $0xc8a30f45             // btl	%r9d, %r8d
	JAE  LBB0_6
	LONG $0x03867480; BYTE $0x80 // xorb	$-128, 3(%rsi,%rax,4)
	JMP  LBB0_6

TEXT ·xvec_avx512_fht_kac_walk(SB), $0-16
	MOVQ data+0(FP), DI
	MOVQ size+8(FP), SI
	WORD $0x8948; BYTE $0xf0 // movq	%rsi, %rax
	LONG $0x3fe8c148         // shrq	$63, %rax
	WORD $0x0148; BYTE $0xf0 // addq	%rsi, %rax
	WORD $0xd148; BYTE $0xf8 // sarq	%rax
	WORD $0x8948; BYTE $0xc2 // movq	%rax, %rdx
	LONG $0xf0e28348         // andq	$-16, %rdx
	LONG $0x20fe8348         // cmpq	$32, %rsi
	JL   LBB1_3
	QUAD $0x0000000085048d4c // leaq	(,%rax,4), %r8
	LONG $0xb70c8d48         // leaq	(%rdi,%rsi,4), %rcx
	WORD $0x294c; BYTE $0xc1 // subq	%r8, %rcx
	WORD $0x3145; BYTE $0xc0 // xorl	%r8d, %r8d

LBB1_2:
	LONG $0x487cb162; WORD $0x0410; BYTE $0x87 // vmovups	(%rdi,%r8,4), %zmm0
	LONG $0x487cb162; WORD $0x0c10; BYTE $0x81 // vmovups	(%rcx,%r8,4), %zmm1
	LONG $0x487cf162; WORD $0xd158             // vaddps	%zmm1, %zmm0, %zmm2
	LONG $0x487cb162; WORD $0x1411; BYTE $0x87 // vmovups	%zmm2, (%rdi,%r8,4)
	LONG $0x487cf162; WORD $0xc15c             // vsubps	%zmm1, %zmm0, %zmm0
	LONG $0x487cb162; WORD $0x0411; BYTE $0x81 // vmovups	%zmm0, (%rcx,%r8,4)
	LONG $0x10c08349                           // addq	$16, %r8
	WORD $0x3949; BYTE $0xd0                   // cmpq	%rdx, %r8
	JL   LBB1_2

LBB1_3:
	WORD $0x3948; BYTE $0xc2               // cmpq	%rax, %rdx
	JE   LBB1_16
	BYTE $0x55                             // pushq	%rbp
	WORD $0x8948; BYTE $0xe5               // movq	%rsp, %rbp
	BYTE $0x53                             // pushq	%rbx
	LONG $0xf8e48348                       // andq	$-8, %rsp
	WORD $0x8949; BYTE $0xd1               // movq	%rdx, %r9
	LONG $0x01c98349                       // orq	$1, %r9
	WORD $0x394c; BYTE $0xc8               // cmpq	%r9, %rax
	WORD $0x894d; BYTE $0xc8               // movq	%r9, %r8
	LONG $0xc04f0f4c                       // cmovgq	%rax, %r8
	WORD $0x894c; BYTE $0xc1               // movq	%r8, %rcx
	WORD $0x2948; BYTE $0xd1               // subq	%rdx, %rcx
	LONG $0x03f98348                       // cmpq	$3, %rcx
	JBE  LBB1_5
	LONG $0x97148d4c                       // leaq	(%rdi,%rdx,4), %r10
	WORD $0x394c; BYTE $0xc8               // cmpq	%r9, %rax
	LONG $0xc84f0f4c                       // cmovgq	%rax, %r9
	LONG $0x0e1c8d4e                       // leaq	(%rsi,%r9), %r11
	WORD $0x2949; BYTE $0xc3               // subq	%rax, %r11
	LONG $0x9f1c8d4e                       // leaq	(%rdi,%r11,4), %r11
	WORD $0x394d; BYTE $0xda               // cmpq	%r11, %r10
	JAE  LBB1_10
	LONG $0x8f0c8d4e                       // leaq	(%rdi,%r9,4), %r9
	QUAD $0xfffffffffff0ba49; WORD $0x3fff // movabsq	$4611686018427387888, %r10      # imm = 0x3FFFFFFFFFFFFFF0
	WORD $0x2149; BYTE $0xc2               // andq	%rax, %r10
	WORD $0x0149; BYTE $0xf2               // addq	%rsi, %r10
	WORD $0x2949; BYTE $0xc2               // subq	%rax, %r10
	LONG $0x97148d4e                       // leaq	(%rdi,%r10,4), %r10
	WORD $0x394d; BYTE $0xca               // cmpq	%r9, %r10
	JAE  LBB1_10

LBB1_5:
	WORD $0x8948; BYTE $0xd1 // movq	%rdx, %rcx

LBB1_6:
	QUAD $0x0000000085048d4c // leaq	(,%rax,4), %r8
	LONG $0xb7148d48         // leaq	(%rdi,%rsi,4), %rdx
	WORD $0x294c; BYTE $0xc2 // subq	%r8, %rdx

LBB1_7:
	LONG $0x0410fac5; BYTE $0x8f // vmovss	(%rdi,%rcx,4), %xmm0            # xmm0 = mem[0],zero,zero,zero
	LONG $0x0c10fac5; BYTE $0x8a // vmovss	(%rdx,%rcx,4), %xmm1            # xmm1 = mem[0],zero,zero,zero
	LONG $0xd158fac5             // vaddss	%xmm1, %xmm0, %xmm2
	LONG $0x1411fac5; BYTE $0x8f // vmovss	%xmm2, (%rdi,%rcx,4)
	LONG $0xc15cfac5             // vsubss	%xmm1, %xmm0, %xmm0
	LONG $0x0411fac5; BYTE $0x8a // vmovss	%xmm0, (%rdx,%rcx,4)
	WORD $0xff48; BYTE $0xc1     // incq	%rcx
	WORD $0x3948; BYTE $0xc1     // cmpq	%rax, %rcx
	JL   LBB1_7

LBB1_15:
	LONG $0xf8658d48 // leaq	-8(%rbp), %rsp
	BYTE $0x5b       // popq	%rbx
	BYTE $0x5d       // popq	%rbp

LBB1_16:
	WORD $0xf8c5; BYTE $0x77 // vzeroupper
	RET

LBB1_10:
	LONG $0x20f98348         // cmpq	$32, %rcx
	JAE  LBB1_17
	WORD $0x3145; BYTE $0xc9 // xorl	%r9d, %r9d
	JMP  LBB1_12

LBB1_17:
	WORD $0x8949; BYTE $0xc9 // movq	%rcx, %r9
	LONG $0xe0e18349         // andq	$-32, %r9
	QUAD $0x00000000851c8d4c // leaq	(,%rax,4), %r11
	QUAD $0x00000000b5148d4c // leaq	(,%rsi,4), %r10
	WORD $0x294d; BYTE $0xda // subq	%r11, %r10
	LONG $0xc0e38349         // andq	$-64, %r11
	WORD $0x0149; BYTE $0xfb // addq	%rdi, %r11
	LONG $0x40c38349         // addq	$64, %r11
	WORD $0x894c; BYTE $0xcb // movq	%r9, %rbx

LBB1_18:
	LONG $0x487cd162; WORD $0x4310; BYTE $0xff // vmovups	-64(%r11), %zmm0
	LONG $0x487cd162; WORD $0x0b10             // vmovups	(%r11), %zmm1
	QUAD $0xff135410487c9162                   // vmovups	-64(%r11,%r10), %zmm2
	LONG $0x487c9162; WORD $0x1c10; BYTE $0x13 // vmovups	(%r11,%r10), %zmm3
	LONG $0x487cf162; WORD $0xe258             // vaddps	%zmm2, %zmm0, %zmm4
	LONG $0x4874f162; WORD $0xeb58             // vaddps	%zmm3, %zmm1, %zmm5
	LONG $0x487cd162; WORD $0x6311; BYTE $0xff // vmovups	%zmm4, -64(%r11)
	LONG $0x487cd162; WORD $0x2b11             // vmovups	%zmm5, (%r11)
	LONG $0x487cf162; WORD $0xc25c             // vsubps	%zmm2, %zmm0, %zmm0
	LONG $0x4874f162; WORD $0xcb5c             // vsubps	%zmm3, %zmm1, %zmm1
	QUAD $0xff134411487c9162                   // vmovups	%zmm0, -64(%r11,%r10)
	LONG $0x487c9162; WORD $0x0c11; BYTE $0x13 // vmovups	%zmm1, (%r11,%r10)
	LONG $0x80eb8349                           // subq	$-128, %r11
	LONG $0xe0c38348                           // addq	$-32, %rbx
	JNE  LBB1_18
	WORD $0x394c; BYTE $0xc9                   // cmpq	%r9, %rcx
	JE   LBB1_15
	WORD $0xc1f6; BYTE $0x1c                   // testb	$28, %cl
	JE   LBB1_21

LBB1_12:
	WORD $0x8945; BYTE $0xc2 // movl	%r8d, %r10d
	LONG $0x03e28341         // andl	$3, %r10d
	WORD $0x294c; BYTE $0xd1 // subq	%r10, %rcx
	WORD $0x0148; BYTE $0xd1 // addq	%rdx, %rcx
	QUAD $0x00000000851c8d48 // leaq	(,%rax,4), %rbx
	QUAD $0x00000000b51c8d4c // leaq	(,%rsi,4), %r11
	WORD $0x2949; BYTE $0xdb // subq	%rbx, %r11
	LONG $0xc0e38348         // andq	$-64, %rbx
	LONG $0x8b1c8d4a         // leaq	(%rbx,%r9,4), %rbx
	WORD $0x0148; BYTE $0xfb // addq	%rdi, %rbx
	WORD $0x294d; BYTE $0xc8 // subq	%r9, %r8
	WORD $0x294d; BYTE $0xd0 // subq	%r10, %r8
	WORD $0x2949; BYTE $0xd0 // subq	%rdx, %r8

LBB1_13:
	LONG $0x0310f8c5               // vmovups	(%rbx), %xmm0
	LONG $0x1078a1c4; WORD $0x1b0c // vmovups	(%rbx,%r11), %xmm1
	LONG $0xd158f8c5               // vaddps	%xmm1, %xmm0, %xmm2
	LONG $0x1311f8c5               // vmovups	%xmm2, (%rbx)
	LONG $0xc15cf8c5               // vsubps	%xmm1, %xmm0, %xmm0
	LONG $0x1178a1c4; WORD $0x1b04 // vmovups	%xmm0, (%rbx,%r11)
	LONG $0x10c38348               // addq	$16, %rbx
	LONG $0xfcc08349               // addq	$-4, %r8
	JNE  LBB1_13
	WORD $0x854d; BYTE $0xd2       // testq	%r10, %r10
	JNE  LBB1_6
	JMP  LBB1_15

LBB1_21:
	WORD $0x014c; BYTE $0xca // addq	%r9, %rdx
	JMP  LBB1_5

TEXT ·xvec_avx512_fht_inverse_kac_walk(SB), $0-16
	MOVQ data+0(FP), DI
	MOVQ size+8(FP), SI
	BYTE $0x55               // pushq	%rbp
	WORD $0x8948; BYTE $0xe5 // movq	%rsp, %rbp
	LONG $0xf8e48348         // andq	$-8, %rsp
	LONG $0x10ec8348         // subq	$16, %rsp
	WORD $0x8948; BYTE $0xf0 // movq	%rsi, %rax
	LONG $0x3fe8c148         // shrq	$63, %rax
	WORD $0x0148; BYTE $0xf0 // addq	%rsi, %rax
	WORD $0xd148; BYTE $0xf8 // sarq	%rax
	WORD $0x8948; BYTE $0xc1 // movq	%rax, %rcx
	LONG $0xf0e18348         // andq	$-16, %rcx
	QUAD $0x3f0000000c2444c7 // movl	$1056964608, 12(%rsp)           # imm = 0x3F000000
	QUAD $0x03244418487df262 // vbroadcastss	12(%rsp), %zmm0
	LONG $0xb7148d48         // leaq	(%rdi,%rsi,4), %rdx
	LONG $0x20fe8348         // cmpq	$32, %rsi
	JL   LBB2_3
	QUAD $0x0000000085048d4c // leaq	(,%rax,4), %r8
	WORD $0x8948; BYTE $0xd6 // movq	%rdx, %rsi
	WORD $0x294c; BYTE $0xc6 // subq	%r8, %rsi
	WORD $0x3145; BYTE $0xc0 // xorl	%r8d, %r8d

LBB2_2:
	LONG $0x487cb162; WORD $0x0c10; BYTE $0x87 // vmovups	(%rdi,%r8,4), %zmm1
	LONG $0x487cb162; WORD $0x1410; BYTE $0x86 // vmovups	(%rsi,%r8,4), %zmm2
	LONG $0x4874f162; WORD $0xda58             // vaddps	%zmm2, %zmm1, %zmm3
	LONG $0x487cf162; WORD $0xdb59             // vmulps	%zmm3, %zmm0, %zmm3
	LONG $0x487cb162; WORD $0x1c11; BYTE $0x87 // vmovups	%zmm3, (%rdi,%r8,4)
	LONG $0x4874f162; WORD $0xca5c             // vsubps	%zmm2, %zmm1, %zmm1
	LONG $0x487cf162; WORD $0xc959             // vmulps	%zmm1, %zmm0, %zmm1
	LONG $0x487cb162; WORD $0x0c11; BYTE $0x86 // vmovups	%zmm1, (%rsi,%r8,4)
	LONG $0x10c08349                           // addq	$16, %r8
	WORD $0x3949; BYTE $0xc8                   // cmpq	%rcx, %r8
	JL   LBB2_2

LBB2_3:
	WORD $0x3948; BYTE $0xc1 // cmpq	%rax, %rcx
	JE   LBB2_6
	QUAD $0x0000000085348d48 // leaq	(,%rax,4), %rsi
	WORD $0x2948; BYTE $0xf2 // subq	%rsi, %rdx

LBB2_5:
	LONG $0x0410fac5; BYTE $0x8f   // vmovss	(%rdi,%rcx,4), %xmm0            # xmm0 = mem[0],zero,zero,zero
	LONG $0x0c10fac5; BYTE $0x8a   // vmovss	(%rdx,%rcx,4), %xmm1            # xmm1 = mem[0],zero,zero,zero
	LONG $0xd158fac5               // vaddss	%xmm1, %xmm0, %xmm2
	LONG $0x5459eac5; WORD $0x0c24 // vmulss	12(%rsp), %xmm2, %xmm2
	LONG $0x1411fac5; BYTE $0x8f   // vmovss	%xmm2, (%rdi,%rcx,4)
	LONG $0xc15cfac5               // vsubss	%xmm1, %xmm0, %xmm0
	LONG $0x4459fac5; WORD $0x0c24 // vmulss	12(%rsp), %xmm0, %xmm0
	LONG $0x0411fac5; BYTE $0x8a   // vmovss	%xmm0, (%rdx,%rcx,4)
	WORD $0xff48; BYTE $0xc1       // incq	%rcx
	WORD $0x3948; BYTE $0xc1       // cmpq	%rax, %rcx
	JL   LBB2_5

LBB2_6:
	WORD $0x8948; BYTE $0xec // movq	%rbp, %rsp
	BYTE $0x5d               // popq	%rbp
	WORD $0xf8c5; BYTE $0x77 // vzeroupper
	RET

TEXT ·xvec_avx512_fht_in_place(SB), $0-16
	MOVQ data+0(FP), DI
	MOVQ size+8(FP), SI
	BYTE $0x55                     // pushq	%rbp
	WORD $0x8948; BYTE $0xe5       // movq	%rsp, %rbp
	WORD $0x5741                   // pushq	%r15
	WORD $0x5641                   // pushq	%r14
	WORD $0x5541                   // pushq	%r13
	WORD $0x5441                   // pushq	%r12
	BYTE $0x53                     // pushq	%rbx
	LONG $0xf8e48348               // andq	$-8, %rsp
	LONG $0x78ec8348               // subq	$120, %rsp
	LONG $0x247c8948; BYTE $0x20   // movq	%rdi, 32(%rsp)                  # 8-byte Spill
	LONG $0x24748948; BYTE $0x18   // movq	%rsi, 24(%rsp)                  # 8-byte Spill
	LONG $0x02fe8348               // cmpq	$2, %rsi
	JL   LBB3_28
	LONG $0x24448b48; BYTE $0x20   // movq	32(%rsp), %rax                  # 8-byte Reload
	LONG $0x40c08348               // addq	$64, %rax
	LONG $0x24448948; BYTE $0x30   // movq	%rax, 48(%rsp)                  # 8-byte Spill
	LONG $0x0001b941; WORD $0x0000 // movl	$1, %r9d
	JMP  LBB3_2

LBB3_27:
	LONG $0x244c3b4c; BYTE $0x18 // cmpq	24(%rsp), %r9                   # 8-byte Folded Reload
	JGE  LBB3_28

LBB3_2:
	WORD $0x894d; BYTE $0xca               // movq	%r9, %r10
	WORD $0x014d; BYTE $0xc9               // addq	%r9, %r9
	WORD $0x894d; BYTE $0xd3               // movq	%r10, %r11
	LONG $0xf0e38349                       // andq	$-16, %r11
	LONG $0x0ffa8349                       // cmpq	$15, %r10
	LONG $0x244c894c; BYTE $0x50           // movq	%r9, 80(%rsp)                   # 8-byte Spill
	JLE  LBB3_3
	WORD $0x394d; BYTE $0xd3               // cmpq	%r10, %r11
	JNE  LBB3_29
	LONG $0xff428d49                       // leaq	-1(%r10), %rax
	WORD $0x8948; BYTE $0xc1               // movq	%rax, %rcx
	LONG $0x04e9c148                       // shrq	$4, %rcx
	WORD $0xff48; BYTE $0xc1               // incq	%rcx
	QUAD $0xfffffffffffeba48; WORD $0x1fff // movabsq	$2305843009213693950, %rdx      # imm = 0x1FFFFFFFFFFFFFFE
	WORD $0x2148; BYTE $0xd1               // andq	%rdx, %rcx
	QUAD $0x00000000d5148d4a               // leaq	(,%r10,8), %rdx
	QUAD $0x00000000953c8d4a               // leaq	(,%r10,4), %rdi
	LONG $0x24448b4c; BYTE $0x30           // movq	48(%rsp), %r8                   # 8-byte Reload
	WORD $0x3145; BYTE $0xdb               // xorl	%r11d, %r11d
	JMP  LBB3_10

LBB3_16:
	WORD $0x014d; BYTE $0xcb     // addq	%r9, %r11
	WORD $0x0149; BYTE $0xd0     // addq	%rdx, %r8
	LONG $0x245c3b4c; BYTE $0x18 // cmpq	24(%rsp), %r11                  # 8-byte Folded Reload
	JGE  LBB3_27

LBB3_10:
	LONG $0x10f88348 // cmpq	$16, %rax
	JAE  LBB3_12
	WORD $0xdb31     // xorl	%ebx, %ebx
	JMP  LBB3_14

LBB3_12:
	LONG $0x38348d49         // leaq	(%r8,%rdi), %rsi
	WORD $0x8949; BYTE $0xce // movq	%rcx, %r14
	WORD $0xdb31             // xorl	%ebx, %ebx

LBB3_13:
	QUAD $0xff984410487cd162                   // vmovups	-64(%r8,%rbx,4), %zmm0
	QUAD $0xff9e4c10487cf162                   // vmovups	-64(%rsi,%rbx,4), %zmm1
	LONG $0x487cf162; WORD $0xd158             // vaddps	%zmm1, %zmm0, %zmm2
	QUAD $0xff985411487cd162                   // vmovups	%zmm2, -64(%r8,%rbx,4)
	LONG $0x487cf162; WORD $0xc15c             // vsubps	%zmm1, %zmm0, %zmm0
	QUAD $0xff9e4411487cf162                   // vmovups	%zmm0, -64(%rsi,%rbx,4)
	LONG $0x487cd162; WORD $0x0410; BYTE $0x98 // vmovups	(%r8,%rbx,4), %zmm0
	LONG $0x487cf162; WORD $0x0c10; BYTE $0x9e // vmovups	(%rsi,%rbx,4), %zmm1
	LONG $0x487cf162; WORD $0xd158             // vaddps	%zmm1, %zmm0, %zmm2
	LONG $0x487cd162; WORD $0x1411; BYTE $0x98 // vmovups	%zmm2, (%r8,%rbx,4)
	LONG $0x487cf162; WORD $0xc15c             // vsubps	%zmm1, %zmm0, %zmm0
	LONG $0x487cf162; WORD $0x0411; BYTE $0x9e // vmovups	%zmm0, (%rsi,%rbx,4)
	LONG $0x20c38348                           // addq	$32, %rbx
	LONG $0xfec68349                           // addq	$-2, %r14
	JNE  LBB3_13

LBB3_14:
	WORD $0x10a8                               // testb	$16, %al
	JNE  LBB3_16
	LONG $0x24748b48; BYTE $0x20               // movq	32(%rsp), %rsi                  # 8-byte Reload
	LONG $0x9e348d4a                           // leaq	(%rsi,%r11,4), %rsi
	LONG $0x9e348d4c                           // leaq	(%rsi,%rbx,4), %r14
	LONG $0x487cf162; WORD $0x0410; BYTE $0x9e // vmovups	(%rsi,%rbx,4), %zmm0
	LONG $0x487c9162; WORD $0x0c10; BYTE $0x96 // vmovups	(%r14,%r10,4), %zmm1
	LONG $0x487cf162; WORD $0xd158             // vaddps	%zmm1, %zmm0, %zmm2
	LONG $0x487cf162; WORD $0x1411; BYTE $0x9e // vmovups	%zmm2, (%rsi,%rbx,4)
	LONG $0x487cf162; WORD $0xc15c             // vsubps	%zmm1, %zmm0, %zmm0
	LONG $0x487c9162; WORD $0x0411; BYTE $0x96 // vmovups	%zmm0, (%r14,%r10,4)
	JMP  LBB3_16

LBB3_3:
	LONG $0x245c894c; BYTE $0x10           // movq	%r11, 16(%rsp)                  # 8-byte Spill
	WORD $0x394d; BYTE $0xd3               // cmpq	%r10, %r11
	JE   LBB3_27
	QUAD $0x0000000095048d4a               // leaq	(,%r10,4), %rax
	WORD $0x8949; BYTE $0xc4               // movq	%rax, %r12
	LONG $0xc0e48349                       // andq	$-64, %r12
	LONG $0x246c8b4c; BYTE $0x20           // movq	32(%rsp), %r13                  # 8-byte Reload
	LONG $0x2c3c8d4b                       // leaq	(%r12,%r13), %rdi
	LONG $0x244c8b48; BYTE $0x18           // movq	24(%rsp), %rcx                  # 8-byte Reload
	WORD $0x394c; BYTE $0xc9               // cmpq	%r9, %rcx
	WORD $0x894d; BYTE $0xc8               // movq	%r9, %r8
	LONG $0xc14f0f4c                       // cmovgq	%rcx, %r8
	WORD $0xff49; BYTE $0xc8               // decq	%r8
	LONG $0x245c8b4c; BYTE $0x10           // movq	16(%rsp), %r11                  # 8-byte Reload
	WORD $0x894d; BYTE $0xdf               // movq	%r11, %r15
	LONG $0x01cf8349                       // orq	$1, %r15
	WORD $0x394d; BYTE $0xfa               // cmpq	%r15, %r10
	LONG $0xfa4f0f4d                       // cmovgq	%r10, %r15
	QUAD $0x00000000d51c8d4a               // leaq	(,%r10,8), %rbx
	WORD $0x894c; BYTE $0xd1               // movq	%r10, %rcx
	QUAD $0xfffffffffff0ba48; WORD $0x3fff // movabsq	$4611686018427387888, %rdx      # imm = 0x3FFFFFFFFFFFFFF0
	WORD $0x2148; BYTE $0xd1               // andq	%rdx, %rcx
	WORD $0x014c; BYTE $0xd1               // addq	%r10, %rcx
	QUAD $0x000000008d148d48               // leaq	(,%rcx,4), %rdx
	WORD $0x014c; BYTE $0xea               // addq	%r13, %rdx
	LONG $0x3a348d4b                       // leaq	(%r10,%r15), %rsi
	WORD $0x894d; BYTE $0xfe               // movq	%r15, %r14
	LONG $0xbc0f49f3; BYTE $0xc9           // rep		bsfq	%r9, %rcx
	WORD $0xd349; BYTE $0xe8               // shrq	%cl, %r8
	WORD $0x294d; BYTE $0xde               // subq	%r11, %r14
	LONG $0xc3af0f4c                       // imulq	%rbx, %r8
	WORD $0x014d; BYTE $0xe8               // addq	%r13, %r8
	LONG $0xb80c8d4b                       // leaq	(%r8,%r15,4), %rcx
	LONG $0xb0348d49                       // leaq	(%r8,%rsi,4), %rsi
	WORD $0x3948; BYTE $0xf7               // cmpq	%rsi, %rdi
	LONG $0xc6920f40                       // setb	%sil
	WORD $0x3948; BYTE $0xca               // cmpq	%rcx, %rdx
	WORD $0x920f; BYTE $0xc2               // setb	%dl
	WORD $0x2040; BYTE $0xf2               // andb	%sil, %dl
	WORD $0x8548; BYTE $0xdb               // testq	%rbx, %rbx
	WORD $0x980f; BYTE $0xc1               // sets	%cl
	WORD $0xd108                           // orb	%dl, %cl
	WORD $0x894c; BYTE $0xf2               // movq	%r14, %rdx
	LONG $0xe0e28348                       // andq	$-32, %rdx
	LONG $0x24548948; BYTE $0x08           // movq	%rdx, 8(%rsp)                   # 8-byte Spill
	WORD $0x014c; BYTE $0xda               // addq	%r11, %rdx
	LONG $0x24548948; BYTE $0x38           // movq	%rdx, 56(%rsp)                  # 8-byte Spill
	WORD $0x8944; BYTE $0xfa               // movl	%r15d, %edx
	WORD $0xe283; BYTE $0x03               // andl	$3, %edx
	LONG $0x24548948; BYTE $0x40           // movq	%rdx, 64(%rsp)                  # 8-byte Spill
	LONG $0xfce78349                       // andq	$-4, %r15
	LONG $0x247c894c; BYTE $0x48           // movq	%r15, 72(%rsp)                  # 8-byte Spill
	LONG $0x2464034c; BYTE $0x30           // addq	48(%rsp), %r12                  # 8-byte Folded Reload
	LONG $0x01538d49                       // leaq	1(%r11), %rdx
	WORD $0x3949; BYTE $0xd2               // cmpq	%rdx, %r10
	LONG $0xd24f0f49                       // cmovgq	%r10, %rdx
	LONG $0xfce28348                       // andq	$-4, %rdx
	WORD $0x294c; BYTE $0xda               // subq	%r11, %rdx
	LONG $0x24548948; BYTE $0x28           // movq	%rdx, 40(%rsp)                  # 8-byte Spill
	WORD $0x3145; BYTE $0xc0               // xorl	%r8d, %r8d
	JMP  LBB3_5

LBB3_26:
	LONG $0x244c8b4c; BYTE $0x50 // movq	80(%rsp), %r9                   # 8-byte Reload
	WORD $0x014d; BYTE $0xc8     // addq	%r9, %r8
	WORD $0x0149; BYTE $0xdc     // addq	%rbx, %r12
	WORD $0x0148; BYTE $0xdf     // addq	%rbx, %rdi
	WORD $0x0149; BYTE $0xdd     // addq	%rbx, %r13
	LONG $0x24443b4c; BYTE $0x18 // cmpq	24(%rsp), %r8                   # 8-byte Folded Reload
	JGE  LBB3_27

LBB3_5:
	LONG $0x04fe8349             // cmpq	$4, %r14
	WORD $0x920f; BYTE $0xc2     // setb	%dl
	WORD $0xca08                 // orb	%cl, %dl
	LONG $0x245c8b4c; BYTE $0x10 // movq	16(%rsp), %r11                  # 8-byte Reload
	WORD $0xc2f6; BYTE $0x01     // testb	$1, %dl
	JNE  LBB3_24
	LONG $0x20fe8349             // cmpq	$32, %r14
	JAE  LBB3_17
	WORD $0xf631                 // xorl	%esi, %esi
	JMP  LBB3_21

LBB3_17:
	LONG $0x245c8b4c; BYTE $0x08 // movq	8(%rsp), %r11                   # 8-byte Reload
	WORD $0x894c; BYTE $0xe2     // movq	%r12, %rdx

LBB3_18:
	LONG $0x487cf162; WORD $0x4210; BYTE $0xff // vmovups	-64(%rdx), %zmm0
	LONG $0x487cf162; WORD $0x0a10             // vmovups	(%rdx), %zmm1
	QUAD $0xff025410487cf162                   // vmovups	-64(%rdx,%rax), %zmm2
	LONG $0x487cf162; WORD $0x1c10; BYTE $0x02 // vmovups	(%rdx,%rax), %zmm3
	LONG $0x487cf162; WORD $0xe258             // vaddps	%zmm2, %zmm0, %zmm4
	LONG $0x4874f162; WORD $0xeb58             // vaddps	%zmm3, %zmm1, %zmm5
	LONG $0x487cf162; WORD $0x6211; BYTE $0xff // vmovups	%zmm4, -64(%rdx)
	LONG $0x487cf162; WORD $0x2a11             // vmovups	%zmm5, (%rdx)
	LONG $0x487cf162; WORD $0xc25c             // vsubps	%zmm2, %zmm0, %zmm0
	LONG $0x4874f162; WORD $0xcb5c             // vsubps	%zmm3, %zmm1, %zmm1
	QUAD $0xff024411487cf162                   // vmovups	%zmm0, -64(%rdx,%rax)
	LONG $0x487cf162; WORD $0x0c11; BYTE $0x02 // vmovups	%zmm1, (%rdx,%rax)
	LONG $0x80ea8348                           // subq	$-128, %rdx
	LONG $0xe0c38349                           // addq	$-32, %r11
	JNE  LBB3_18
	LONG $0x24743b4c; BYTE $0x08               // cmpq	8(%rsp), %r14                   # 8-byte Folded Reload
	JE   LBB3_26
	LONG $0x24748b48; BYTE $0x08               // movq	8(%rsp), %rsi                   # 8-byte Reload
	LONG $0x245c8b4c; BYTE $0x38               // movq	56(%rsp), %r11                  # 8-byte Reload
	LONG $0x1cc6f641                           // testb	$28, %r14b
	JE   LBB3_24

LBB3_21:
	LONG $0xb7148d48             // leaq	(%rdi,%rsi,4), %rdx
	LONG $0x021c8d4c             // leaq	(%rdx,%rax), %r11
	LONG $0x247c8b4c; BYTE $0x28 // movq	40(%rsp), %r15                  # 8-byte Reload
	WORD $0x2949; BYTE $0xf7     // subq	%rsi, %r15
	WORD $0xf631                 // xorl	%esi, %esi

LBB3_22:
	LONG $0x0410f8c5; BYTE $0xb2   // vmovups	(%rdx,%rsi,4), %xmm0
	LONG $0x1078c1c4; WORD $0xb30c // vmovups	(%r11,%rsi,4), %xmm1
	LONG $0xd158f8c5               // vaddps	%xmm1, %xmm0, %xmm2
	LONG $0x1411f8c5; BYTE $0xb2   // vmovups	%xmm2, (%rdx,%rsi,4)
	LONG $0xc15cf8c5               // vsubps	%xmm1, %xmm0, %xmm0
	LONG $0x1178c1c4; WORD $0xb304 // vmovups	%xmm0, (%r11,%rsi,4)
	LONG $0x04c68348               // addq	$4, %rsi
	WORD $0x3949; BYTE $0xf7       // cmpq	%rsi, %r15
	JNE  LBB3_22
	LONG $0x245c8b4c; BYTE $0x48   // movq	72(%rsp), %r11                  # 8-byte Reload
	LONG $0x247c8348; WORD $0x0040 // cmpq	$0, 64(%rsp)                    # 8-byte Folded Reload
	JE   LBB3_26

LBB3_24:
	QUAD $0x000000009d148d4a // leaq	(,%r11,4), %rdx
	WORD $0x014c; BYTE $0xea // addq	%r13, %rdx
	LONG $0x023c8d4c         // leaq	(%rdx,%rax), %r15
	WORD $0xf631             // xorl	%esi, %esi

LBB3_25:
	LONG $0x0410fac5; BYTE $0xb2   // vmovss	(%rdx,%rsi,4), %xmm0            # xmm0 = mem[0],zero,zero,zero
	LONG $0x107ac1c4; WORD $0xb70c // vmovss	(%r15,%rsi,4), %xmm1            # xmm1 = mem[0],zero,zero,zero
	LONG $0xd158fac5               // vaddss	%xmm1, %xmm0, %xmm2
	LONG $0x1411fac5; BYTE $0xb2   // vmovss	%xmm2, (%rdx,%rsi,4)
	LONG $0xc15cfac5               // vsubss	%xmm1, %xmm0, %xmm0
	LONG $0x117ac1c4; WORD $0xb704 // vmovss	%xmm0, (%r15,%rsi,4)
	LONG $0x330c8d4d               // leaq	(%r11,%rsi), %r9
	WORD $0xff49; BYTE $0xc1       // incq	%r9
	WORD $0xff48; BYTE $0xc6       // incq	%rsi
	WORD $0x394d; BYTE $0xd1       // cmpq	%r10, %r9
	JL   LBB3_25
	JMP  LBB3_26

LBB3_29:
	QUAD $0x0000000095348d4e               // leaq	(,%r10,4), %r14
	LONG $0x2474894c; BYTE $0x08           // movq	%r14, 8(%rsp)                   # 8-byte Spill
	LONG $0xc0e68349                       // andq	$-64, %r14
	LONG $0x24448b4c; BYTE $0x20           // movq	32(%rsp), %r8                   # 8-byte Reload
	LONG $0x303c8d4f                       // leaq	(%r8,%r14), %r15
	QUAD $0x00000000d5248d4e               // leaq	(,%r10,8), %r12
	LONG $0x244c8b48; BYTE $0x18           // movq	24(%rsp), %rcx                  # 8-byte Reload
	WORD $0x394c; BYTE $0xc9               // cmpq	%r9, %rcx
	WORD $0x894c; BYTE $0xce               // movq	%r9, %rsi
	LONG $0xf14f0f48                       // cmovgq	%rcx, %rsi
	WORD $0xff48; BYTE $0xce               // decq	%rsi
	WORD $0x894c; BYTE $0xdb               // movq	%r11, %rbx
	LONG $0x01cb8348                       // orq	$1, %rbx
	WORD $0x3949; BYTE $0xda               // cmpq	%rbx, %r10
	LONG $0xda4f0f49                       // cmovgq	%r10, %rbx
	WORD $0x894c; BYTE $0xd1               // movq	%r10, %rcx
	QUAD $0xfffffffffff0ba48; WORD $0x3fff // movabsq	$4611686018427387888, %rdx      # imm = 0x3FFFFFFFFFFFFFF0
	WORD $0x2148; BYTE $0xd1               // andq	%rdx, %rcx
	WORD $0x014c; BYTE $0xd1               // addq	%r10, %rcx
	LONG $0x88048d49                       // leaq	(%r8,%rcx,4), %rax
	LONG $0x24448948; BYTE $0x10           // movq	%rax, 16(%rsp)                  # 8-byte Spill
	LONG $0x1a3c8d49                       // leaq	(%r10,%rbx), %rdi
	WORD $0x8949; BYTE $0xdd               // movq	%rbx, %r13
	WORD $0x294d; BYTE $0xdd               // subq	%r11, %r13
	LONG $0xff538d49                       // leaq	-1(%r11), %rdx
	WORD $0x8948; BYTE $0xd0               // movq	%rdx, %rax
	LONG $0x04e8c148                       // shrq	$4, %rax
	WORD $0xff48; BYTE $0xc0               // incq	%rax
	LONG $0xbc0f49f3; BYTE $0xc9           // rep		bsfq	%r9, %rcx
	WORD $0xd348; BYTE $0xee               // shrq	%cl, %rsi
	QUAD $0xfffffffffffeb948; WORD $0x1fff // movabsq	$2305843009213693950, %rcx      # imm = 0x1FFFFFFFFFFFFFFE
	WORD $0x2148; BYTE $0xc8               // andq	%rcx, %rax
	LONG $0x24448948; BYTE $0x40           // movq	%rax, 64(%rsp)                  # 8-byte Spill
	LONG $0xf4af0f49                       // imulq	%r12, %rsi
	WORD $0x014c; BYTE $0xc6               // addq	%r8, %rsi
	LONG $0x9e0c8d48                       // leaq	(%rsi,%rbx,4), %rcx
	LONG $0xbe048d48                       // leaq	(%rsi,%rdi,4), %rax
	WORD $0x3949; BYTE $0xc7               // cmpq	%rax, %r15
	WORD $0x920f; BYTE $0xc0               // setb	%al
	LONG $0x244c3948; BYTE $0x10           // cmpq	%rcx, 16(%rsp)                  # 8-byte Folded Reload
	WORD $0x920f; BYTE $0xc1               // setb	%cl
	WORD $0xc120                           // andb	%al, %cl
	WORD $0x854d; BYTE $0xe4               // testq	%r12, %r12
	WORD $0x980f; BYTE $0xc0               // sets	%al
	WORD $0xc808                           // orb	%cl, %al
	LONG $0x48244488                       // movb	%al, 72(%rsp)                   # 1-byte Spill
	WORD $0x894c; BYTE $0xe9               // movq	%r13, %rcx
	LONG $0xe0e18348                       // andq	$-32, %rcx
	WORD $0xd889                           // movl	%ebx, %eax
	WORD $0xe083; BYTE $0x03               // andl	$3, %eax
	LONG $0x24448948; BYTE $0x70           // movq	%rax, 112(%rsp)                 # 8-byte Spill
	LONG $0xfce38348                       // andq	$-4, %rbx
	LONG $0x245c8948; BYTE $0x38           // movq	%rbx, 56(%rsp)                  # 8-byte Spill
	LONG $0x24448b48; BYTE $0x30           // movq	48(%rsp), %rax                  # 8-byte Reload
	WORD $0x0149; BYTE $0xc6               // addq	%rax, %r14
	LONG $0x01738d49                       // leaq	1(%r11), %rsi
	WORD $0x3949; BYTE $0xf2               // cmpq	%rsi, %r10
	LONG $0xf24f0f49                       // cmovgq	%r10, %rsi
	WORD $0x8948; BYTE $0xf7               // movq	%rsi, %rdi
	WORD $0x294c; BYTE $0xdf               // subq	%r11, %rdi
	LONG $0xe0e78348                       // andq	$-32, %rdi
	LONG $0x247c8948; BYTE $0x60           // movq	%rdi, 96(%rsp)                  # 8-byte Spill
	LONG $0xfce68348                       // andq	$-4, %rsi
	WORD $0x294c; BYTE $0xde               // subq	%r11, %rsi
	LONG $0x24748948; BYTE $0x68           // movq	%rsi, 104(%rsp)                 # 8-byte Spill
	LONG $0x245c894c; BYTE $0x10           // movq	%r11, 16(%rsp)                  # 8-byte Spill
	LONG $0x244c8948; BYTE $0x28           // movq	%rcx, 40(%rsp)                  # 8-byte Spill
	WORD $0x014c; BYTE $0xd9               // addq	%r11, %rcx
	LONG $0x244c8948; BYTE $0x58           // movq	%rcx, 88(%rsp)                  # 8-byte Spill
	WORD $0x894c; BYTE $0xc7               // movq	%r8, %rdi
	WORD $0x3145; BYTE $0xc0               // xorl	%r8d, %r8d
	JMP  LBB3_30

LBB3_48:
	LONG $0x244c8b4c; BYTE $0x50 // movq	80(%rsp), %r9                   # 8-byte Reload
	WORD $0x014d; BYTE $0xc8     // addq	%r9, %r8
	WORD $0x014c; BYTE $0xe0     // addq	%r12, %rax
	WORD $0x014d; BYTE $0xe6     // addq	%r12, %r14
	WORD $0x014d; BYTE $0xe7     // addq	%r12, %r15
	WORD $0x014c; BYTE $0xe7     // addq	%r12, %rdi
	LONG $0x24443b4c; BYTE $0x18 // cmpq	24(%rsp), %r8                   # 8-byte Folded Reload
	JGE  LBB3_27

LBB3_30:
	LONG $0x0ffa8348 // cmpq	$15, %rdx
	JNE  LBB3_32
	WORD $0xc931     // xorl	%ecx, %ecx
	JMP  LBB3_34

LBB3_32:
	LONG $0x244c8b48; BYTE $0x08 // movq	8(%rsp), %rcx                   # 8-byte Reload
	LONG $0x081c8d4c             // leaq	(%rax,%rcx), %r11
	LONG $0x245c8b48; BYTE $0x40 // movq	64(%rsp), %rbx                  # 8-byte Reload
	WORD $0xc931                 // xorl	%ecx, %ecx

LBB3_33:
	QUAD $0xff884410487cf162                   // vmovups	-64(%rax,%rcx,4), %zmm0
	QUAD $0xff8b4c10487cd162                   // vmovups	-64(%r11,%rcx,4), %zmm1
	LONG $0x487cf162; WORD $0xd158             // vaddps	%zmm1, %zmm0, %zmm2
	QUAD $0xff885411487cf162                   // vmovups	%zmm2, -64(%rax,%rcx,4)
	LONG $0x487cf162; WORD $0xc15c             // vsubps	%zmm1, %zmm0, %zmm0
	QUAD $0xff8b4411487cd162                   // vmovups	%zmm0, -64(%r11,%rcx,4)
	LONG $0x487cf162; WORD $0x0410; BYTE $0x88 // vmovups	(%rax,%rcx,4), %zmm0
	LONG $0x487cd162; WORD $0x0c10; BYTE $0x8b // vmovups	(%r11,%rcx,4), %zmm1
	LONG $0x487cf162; WORD $0xd158             // vaddps	%zmm1, %zmm0, %zmm2
	LONG $0x487cf162; WORD $0x1411; BYTE $0x88 // vmovups	%zmm2, (%rax,%rcx,4)
	LONG $0x487cf162; WORD $0xc15c             // vsubps	%zmm1, %zmm0, %zmm0
	LONG $0x487cd162; WORD $0x0411; BYTE $0x8b // vmovups	%zmm0, (%r11,%rcx,4)
	LONG $0x20c18348                           // addq	$32, %rcx
	LONG $0xfec38348                           // addq	$-2, %rbx
	JNE  LBB3_33

LBB3_34:
	WORD $0xc2f6; BYTE $0x10                   // testb	$16, %dl
	JNE  LBB3_36
	LONG $0x24748b48; BYTE $0x20               // movq	32(%rsp), %rsi                  # 8-byte Reload
	LONG $0x86348d4a                           // leaq	(%rsi,%r8,4), %rsi
	LONG $0x8e0c8d4c                           // leaq	(%rsi,%rcx,4), %r9
	LONG $0x487cf162; WORD $0x0410; BYTE $0x8e // vmovups	(%rsi,%rcx,4), %zmm0
	LONG $0x487c9162; WORD $0x0c10; BYTE $0x91 // vmovups	(%r9,%r10,4), %zmm1
	LONG $0x487cf162; WORD $0xd158             // vaddps	%zmm1, %zmm0, %zmm2
	LONG $0x487cf162; WORD $0x1411; BYTE $0x8e // vmovups	%zmm2, (%rsi,%rcx,4)
	LONG $0x487cf162; WORD $0xc15c             // vsubps	%zmm1, %zmm0, %zmm0
	LONG $0x487c9162; WORD $0x0411; BYTE $0x91 // vmovups	%zmm0, (%r9,%r10,4)

LBB3_36:
	LONG $0x04fd8349             // cmpq	$4, %r13
	LONG $0xc6920f40             // setb	%sil
	LONG $0x24740a40; BYTE $0x48 // orb	72(%rsp), %sil                  # 1-byte Folded Reload
	LONG $0x244c8b48; BYTE $0x10 // movq	16(%rsp), %rcx                  # 8-byte Reload
	LONG $0x01c6f640             // testb	$1, %sil
	JNE  LBB3_37
	LONG $0x20fd8349             // cmpq	$32, %r13
	JAE  LBB3_41
	WORD $0xf631                 // xorl	%esi, %esi
	JMP  LBB3_45

LBB3_41:
	LONG $0x244c8b48; BYTE $0x60 // movq	96(%rsp), %rcx                  # 8-byte Reload
	WORD $0x894d; BYTE $0xf3     // movq	%r14, %r11

LBB3_42:
	LONG $0x487cd162; WORD $0x4310; BYTE $0xff // vmovups	-64(%r11), %zmm0
	LONG $0x487cd162; WORD $0x0b10             // vmovups	(%r11), %zmm1
	QUAD $0xff935410487c9162                   // vmovups	-64(%r11,%r10,4), %zmm2
	LONG $0x487c9162; WORD $0x1c10; BYTE $0x93 // vmovups	(%r11,%r10,4), %zmm3
	LONG $0x487cf162; WORD $0xe258             // vaddps	%zmm2, %zmm0, %zmm4
	LONG $0x4874f162; WORD $0xeb58             // vaddps	%zmm3, %zmm1, %zmm5
	LONG $0x487cd162; WORD $0x6311; BYTE $0xff // vmovups	%zmm4, -64(%r11)
	LONG $0x487cd162; WORD $0x2b11             // vmovups	%zmm5, (%r11)
	LONG $0x487cf162; WORD $0xc25c             // vsubps	%zmm2, %zmm0, %zmm0
	LONG $0x4874f162; WORD $0xcb5c             // vsubps	%zmm3, %zmm1, %zmm1
	QUAD $0xff934411487c9162                   // vmovups	%zmm0, -64(%r11,%r10,4)
	LONG $0x487c9162; WORD $0x0c11; BYTE $0x93 // vmovups	%zmm1, (%r11,%r10,4)
	LONG $0x80eb8349                           // subq	$-128, %r11
	LONG $0xe0c18348                           // addq	$-32, %rcx
	JNE  LBB3_42
	LONG $0x246c3b4c; BYTE $0x28               // cmpq	40(%rsp), %r13                  # 8-byte Folded Reload
	JE   LBB3_48
	LONG $0x244c8b48; BYTE $0x58               // movq	88(%rsp), %rcx                  # 8-byte Reload
	LONG $0x24748b48; BYTE $0x28               // movq	40(%rsp), %rsi                  # 8-byte Reload
	LONG $0x1cc5f641                           // testb	$28, %r13b
	JE   LBB3_37

LBB3_45:
	LONG $0xb70c8d49             // leaq	(%r15,%rsi,4), %rcx
	LONG $0x244c8b4c; BYTE $0x08 // movq	8(%rsp), %r9                    # 8-byte Reload
	LONG $0x091c8d4e             // leaq	(%rcx,%r9), %r11
	LONG $0x245c8b48; BYTE $0x68 // movq	104(%rsp), %rbx                 # 8-byte Reload
	WORD $0x2948; BYTE $0xf3     // subq	%rsi, %rbx
	WORD $0xf631                 // xorl	%esi, %esi

LBB3_46:
	LONG $0x0410f8c5; BYTE $0xb1   // vmovups	(%rcx,%rsi,4), %xmm0
	LONG $0x1078c1c4; WORD $0xb30c // vmovups	(%r11,%rsi,4), %xmm1
	LONG $0xd158f8c5               // vaddps	%xmm1, %xmm0, %xmm2
	LONG $0x1411f8c5; BYTE $0xb1   // vmovups	%xmm2, (%rcx,%rsi,4)
	LONG $0xc15cf8c5               // vsubps	%xmm1, %xmm0, %xmm0
	LONG $0x1178c1c4; WORD $0xb304 // vmovups	%xmm0, (%r11,%rsi,4)
	LONG $0x04c68348               // addq	$4, %rsi
	WORD $0x3948; BYTE $0xf3       // cmpq	%rsi, %rbx
	JNE  LBB3_46
	LONG $0x244c8b48; BYTE $0x38   // movq	56(%rsp), %rcx                  # 8-byte Reload
	LONG $0x247c8348; WORD $0x0070 // cmpq	$0, 112(%rsp)                   # 8-byte Folded Reload
	JE   LBB3_48

LBB3_37:
	LONG $0x8f1c8d4c             // leaq	(%rdi,%rcx,4), %r11
	LONG $0x24748b48; BYTE $0x08 // movq	8(%rsp), %rsi                   # 8-byte Reload
	LONG $0x331c8d49             // leaq	(%r11,%rsi), %rbx
	WORD $0xf631                 // xorl	%esi, %esi

LBB3_38:
	LONG $0x107ac1c4; WORD $0xb304 // vmovss	(%r11,%rsi,4), %xmm0            # xmm0 = mem[0],zero,zero,zero
	LONG $0x0c10fac5; BYTE $0xb3   // vmovss	(%rbx,%rsi,4), %xmm1            # xmm1 = mem[0],zero,zero,zero
	LONG $0xd158fac5               // vaddss	%xmm1, %xmm0, %xmm2
	LONG $0x117ac1c4; WORD $0xb314 // vmovss	%xmm2, (%r11,%rsi,4)
	LONG $0xc15cfac5               // vsubss	%xmm1, %xmm0, %xmm0
	LONG $0x0411fac5; BYTE $0xb3   // vmovss	%xmm0, (%rbx,%rsi,4)
	LONG $0x310c8d4c               // leaq	(%rcx,%rsi), %r9
	WORD $0xff49; BYTE $0xc1       // incq	%r9
	WORD $0xff48; BYTE $0xc6       // incq	%rsi
	WORD $0x394d; BYTE $0xd1       // cmpq	%r10, %r9
	JL   LBB3_38
	JMP  LBB3_48

LBB3_28:
	LONG $0xd8658d48         // leaq	-40(%rbp), %rsp
	BYTE $0x5b               // popq	%rbx
	WORD $0x5c41             // popq	%r12
	WORD $0x5d41             // popq	%r13
	WORD $0x5e41             // popq	%r14
	WORD $0x5f41             // popq	%r15
	BYTE $0x5d               // popq	%rbp
	WORD $0xf8c5; BYTE $0x77 // vzeroupper
	RET
