//go:build !noasm && riscv64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8 (6ubuntu1)
// 	objdump 2.46
// flags: -march=rv64imafdv -isystem /usr/lib/llvm-21/lib/clang/21/include -O3
// source: src/fht_rvv.c

TEXT ·fht_flip_sign_rvv(SB), $0-24
	MOV  signs+0(FP), A0
	MOV  data+8(FP), A1
	MOV  size+16(FP), A2
	BLEZ A2, LBB0_14
	WORD $0xfc010113     // addi	sp, sp, -64
	WORD $0x02813c23     // sd	s0, 56(sp)                      # 8-byte Folded Spill
	WORD $0x02913823     // sd	s1, 48(sp)                      # 8-byte Folded Spill
	WORD $0x03213423     // sd	s2, 40(sp)                      # 8-byte Folded Spill
	WORD $0x00000693     // li	a3, 0
	WORD $0xc22022f3     // csrr	t0, vlenb
	WORD $0x00810713     // addi	a4, sp, 8
	WORD $0x0da077d7     // vsetvli	a5, zero, e64, m4, ta, ma
	WORD $0x5208a457     // vid.v	v8
	WORD $0x03f00793     // li	a5, 63
	WORD $0x80000337     // lui	t1, 524288
	WORD $0x0032d813     // srli	a6, t0, 3
	WORD $0x0012d893     // srli	a7, t0, 1
	WORD $0x00129293     // slli	t0, t0, 1
	WORD $0x0d107057     // vsetvli	zero, zero, e32, m2, ta, ma
	WORD $0x5e034857     // vmv.v.x	v16, t1
	WORD $0x41100333     // neg	t1, a7
	WORD $0x03d00393     // li	t2, 61
	JMP  LBB0_3

LBB0_2:
	WORD $0x00269f13     // slli	t5, a3, 2
	WORD $0x0d0ef057     // vsetvli	zero, t4, e32, m1, ta, ma
	WORD $0x02076607     // vle32.v	v12, (a4)
	WORD $0x01e58f33     // add	t5, a1, t5
	WORD $0x020f6687     // vle32.v	v13, (t5)
	WORD $0x2ed60657     // vxor.vv	v12, v13, v12
	WORD $0x00de06b3     // add	a3, t3, a3
	WORD $0x020f6627     // vse32.v	v12, (t5)
	BGE  A3, A2, LBB0_13

LBB0_3:
	WORD $0x40d60e33    // sub	t3, a2, a3
	WORD $0x00800e93    // li	t4, 8
	BLT  T3, T4, LBB0_5
	WORD $0x00800e13    // li	t3, 8

LBB0_5:
	WORD $0x000e0e93    // mv	t4, t3
	WORD $0x0d0e7e57    // vsetvli	t3, t3, e32, m1, ta, ma
	BEQZ T3, LBB0_2
	BGEU T3, A7, LBB0_8
	WORD $0x00000f13    // li	t5, 0
	JMP  LBB0_11

LBB0_8:
	WORD $0x006e7f33 // and	t5, t3, t1
	WORD $0x01e30fb3 // add	t6, t1, t5
	WORD $0x031fdfb3 // divu	t6, t6, a7
	WORD $0x004f9f93 // slli	t6, t6, 4
	WORD $0x010f8f93 // addi	t6, t6, 16
	WORD $0x03f80433 // mul	s0, a6, t6
	WORD $0x00810f93 // addi	t6, sp, 8
	WORD $0x008f8433 // add	s0, t6, s0
	WORD $0x9e81b657 // vmv4r.v	v12, v8

LBB0_9:
	WORD $0x0da074d7    // vsetvli	s1, zero, e64, m4, ta, ma
	WORD $0x02c6ca57    // vadd.vx	v20, v12, a3
	WORD $0xa747cc57    // vsra.vx	v24, v20, a5
	WORD $0xa383cc57    // vsrl.vx	v24, v24, t2
	WORD $0x034c0c57    // vadd.vv	v24, v20, v24
	WORD $0xa781be57    // vsra.vi	v28, v24, 3
	WORD $0x0c707057    // vsetvli	zero, zero, e8, mf2, ta, ma
	WORD $0x07c57387    // vluxei64.v	v7, (a0), v28
	WORD $0x0da07057    // vsetvli	zero, zero, e64, m4, ta, ma
	WORD $0x278c3c57    // vand.vi	v24, v24, -8
	WORD $0x0b4c0a57    // vsub.vv	v20, v20, v24
	WORD $0x0d107057    // vsetvli	zero, zero, e32, m2, ta, ma
	WORD $0xb3403957    // vnsrl.wi	v18, v20, 0
	WORD $0x4a722a57    // vzext.vf4	v20, v7
	WORD $0xa3490957    // vsrl.vv	v18, v20, v18
	WORD $0x2720b957    // vand.vi	v18, v18, 1
	WORD $0x63203057    // vmseq.vi	v0, v18, 0
	WORD $0x5d003957    // vmerge.vim	v18, v16, 0, v0
	WORD $0x228f8927    // vs2r.v	v18, (t6)
	WORD $0x005f8fb3    // add	t6, t6, t0
	WORD $0x0da07057    // vsetvli	zero, zero, e64, m4, ta, ma
	WORD $0x02c8c657    // vadd.vx	v12, v12, a7
	BNE  T6, S0, LBB0_9
	BEQ  T3, T5, LBB0_2

LBB0_11:
	WORD $0x002f1f93 // slli	t6, t5, 2
	WORD $0x01e68f33 // add	t5, a3, t5
	WORD $0x002e1413 // slli	s0, t3, 2
	WORD $0x01f70fb3 // add	t6, a4, t6
	WORD $0x00870433 // add	s0, a4, s0

LBB0_12:
	WORD $0x43ff5493     // srai	s1, t5, 63
	WORD $0x03d4d493     // srli	s1, s1, 61
	WORD $0x009f04b3     // add	s1, t5, s1
	WORD $0x4034d913     // srai	s2, s1, 3
	WORD $0x01250933     // add	s2, a0, s2
	WORD $0x00094903     // lbu	s2, 0(s2)
	WORD $0x0184f493     // andi	s1, s1, 24
	WORD $0x409f04bb     // subw	s1, t5, s1
	WORD $0x009954bb     // srlw	s1, s2, s1
	WORD $0x01f49493     // slli	s1, s1, 31
	WORD $0x009fa023     // sw	s1, 0(t6)
	WORD $0x004f8f93     // addi	t6, t6, 4
	WORD $0x001f0f13     // addi	t5, t5, 1
	BNE  T6, S0, LBB0_12
	JMP  LBB0_2

LBB0_13:
	WORD $0x03813403 // ld	s0, 56(sp)                      # 8-byte Folded Reload
	WORD $0x03013483 // ld	s1, 48(sp)                      # 8-byte Folded Reload
	WORD $0x02813903 // ld	s2, 40(sp)                      # 8-byte Folded Reload
	WORD $0x04010113 // addi	sp, sp, 64

LBB0_14:
	RET

TEXT ·fht_kacs_walk_rvv(SB), $0-16
	MOV  data+0(FP), A0
	MOV  size+8(FP), A1
	WORD $0x00200613    // li	a2, 2
	BLT  A1, A2, LBB1_3
	WORD $0x00000613    // li	a2, 0
	WORD $0x03f5d693    // srli	a3, a1, 63
	WORD $0x00d586b3    // add	a3, a1, a3
	WORD $0x4016d693    // srai	a3, a3, 1
	WORD $0x40d585b3    // sub	a1, a1, a3
	WORD $0x00259593    // slli	a1, a1, 2

LBB1_2:
	WORD $0x40c68733    // sub	a4, a3, a2
	WORD $0x00261793    // slli	a5, a2, 2
	WORD $0x0d077757    // vsetvli	a4, a4, e32, m1, ta, ma
	WORD $0x00f507b3    // add	a5, a0, a5
	WORD $0x0207e407    // vle32.v	v8, (a5)
	WORD $0x00b78833    // add	a6, a5, a1
	WORD $0x02086487    // vle32.v	v9, (a6)
	WORD $0x00c70633    // add	a2, a4, a2
	WORD $0x02849557    // vfadd.vv	v10, v8, v9
	WORD $0x0a849457    // vfsub.vv	v8, v8, v9
	WORD $0x0207e527    // vse32.v	v10, (a5)
	WORD $0x02086427    // vse32.v	v8, (a6)
	BLT  A2, A3, LBB1_2

LBB1_3:
	RET

TEXT ·fht_inv_kacs_walk_rvv(SB), $0-16
	MOV  data+0(FP), A0
	MOV  size+8(FP), A1
	WORD $0x00200613    // li	a2, 2
	BLT  A1, A2, LBB2_3
	WORD $0x00000613    // li	a2, 0
	WORD $0x3f0006b7    // lui	a3, 258048
	WORD $0xf00687d3    // fmv.w.x	fa5, a3
	WORD $0x03f5d693    // srli	a3, a1, 63
	WORD $0x00d586b3    // add	a3, a1, a3
	WORD $0x4016d693    // srai	a3, a3, 1
	WORD $0x40d585b3    // sub	a1, a1, a3
	WORD $0x00259593    // slli	a1, a1, 2

LBB2_2:
	WORD $0x40c68733    // sub	a4, a3, a2
	WORD $0x00261793    // slli	a5, a2, 2
	WORD $0x0d077757    // vsetvli	a4, a4, e32, m1, ta, ma
	WORD $0x00f507b3    // add	a5, a0, a5
	WORD $0x0207e407    // vle32.v	v8, (a5)
	WORD $0x00b78833    // add	a6, a5, a1
	WORD $0x02086487    // vle32.v	v9, (a6)
	WORD $0x00c70633    // add	a2, a4, a2
	WORD $0x02849557    // vfadd.vv	v10, v8, v9
	WORD $0x0a849457    // vfsub.vv	v8, v8, v9
	WORD $0x92a7d4d7    // vfmul.vf	v9, v10, fa5
	WORD $0x9287d457    // vfmul.vf	v8, v8, fa5
	WORD $0x0207e4a7    // vse32.v	v9, (a5)
	WORD $0x02086427    // vse32.v	v8, (a6)
	BLT  A2, A3, LBB2_2

LBB2_3:
	RET

TEXT ·fht_inplace_rvv(SB), $0-16
	MOV  data+0(FP), A0
	MOV  size+8(FP), A1
	WORD $0x00200613    // li	a2, 2
	BLT  A1, A2, LBB3_8
	WORD $0x00100613    // li	a2, 1
	JMP  LBB3_3

LBB3_2:
	WORD $0x00068613    // mv	a2, a3
	BGE  A3, A1, LBB3_8

LBB3_3:
	WORD $0x00161693 // slli	a3, a2, 1
	BLEZ A2, LBB3_2
	WORD $0x00000713 // li	a4, 0
	WORD $0x00261793 // slli	a5, a2, 2

LBB3_5:
	WORD $0x00000813 // li	a6, 0
	WORD $0x00271893 // slli	a7, a4, 2
	WORD $0x011508b3 // add	a7, a0, a7

LBB3_6:
	WORD $0x410602b3    // sub	t0, a2, a6
	WORD $0x00281313    // slli	t1, a6, 2
	WORD $0x0d02f2d7    // vsetvli	t0, t0, e32, m1, ta, ma
	WORD $0x00688333    // add	t1, a7, t1
	WORD $0x02036407    // vle32.v	v8, (t1)
	WORD $0x00f303b3    // add	t2, t1, a5
	WORD $0x0203e487    // vle32.v	v9, (t2)
	WORD $0x01028833    // add	a6, t0, a6
	WORD $0x02849557    // vfadd.vv	v10, v8, v9
	WORD $0x0a849457    // vfsub.vv	v8, v8, v9
	WORD $0x02036527    // vse32.v	v10, (t1)
	WORD $0x0203e427    // vse32.v	v8, (t2)
	BLT  A6, A2, LBB3_6
	WORD $0x00d70733    // add	a4, a4, a3
	BLT  A4, A1, LBB3_5
	JMP  LBB3_2

LBB3_8:
	RET
