//go:build !noasm && amd64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8 (6ubuntu1)
// 	objdump 2.46
// flags: -mavx512f -mavx512dq -O3
// source: src/fht_avx512.c

package mathutil

import "unsafe"

//go:noescape
func fht_flip_sign_avx512(signs, data unsafe.Pointer, size int64)

//go:noescape
func fht_kacs_walk_avx512(data unsafe.Pointer, size int64)

//go:noescape
func fht_inv_kacs_walk_avx512(data unsafe.Pointer, size int64)

//go:noescape
func fht_inplace_avx512(data unsafe.Pointer, size int64)
