//go:build !noasm && loong64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8 (6ubuntu1)
// 	objdump 2.46
// flags: -mlasx -O3
// source: src/fht_lasx.c

package mathutil

import "unsafe"

//go:noescape
func fht_flip_sign_lasx(signs, data unsafe.Pointer, size int64)

//go:noescape
func fht_kacs_walk_lasx(data unsafe.Pointer, size int64)

//go:noescape
func fht_inv_kacs_walk_lasx(data unsafe.Pointer, size int64)

//go:noescape
func fht_inplace_lasx(data unsafe.Pointer, size int64)
