//go:build !noasm && amd64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8 (6ubuntu1)
// 	objdump 2.46
// flags: -mavx2 -O3
// source: src/inner_product_matrix_int8_avx2.c

TEXT ·inner_product_int8_avx2(SB), $8-32
	MOVQ lhs+0(FP), DI
	MOVQ rhs+8(FP), SI
	MOVQ size+16(FP), DX
	BYTE $0x55               // pushq	%rbp
	WORD $0x8948; BYTE $0xe5 // movq	%rsp, %rbp
	LONG $0xf8e48348         // andq	$-8, %rsp
	WORD $0xc031             // xorl	%eax, %eax
	LONG $0x20fa8348         // cmpq	$32, %rdx
	JL   LBB0_1

LBB0_16:
	LONG $0x00fa8148; WORD $0x0100; BYTE $0x00 // cmpq	$65536, %rdx                    # imm = 0x10000
	LONG $0x010000b9; BYTE $0x00               // movl	$65536, %ecx                    # imm = 0x10000
	LONG $0xca420f48                           // cmovbq	%rdx, %rcx
	LONG $0xffe0e181; WORD $0x0001             // andl	$131040, %ecx                   # imm = 0x1FFE0
	LONG $0xc0eff9c5                           // vpxor	%xmm0, %xmm0, %xmm0
	LONG $0xc9eff1c5                           // vpxor	%xmm1, %xmm1, %xmm1
	WORD $0x3145; BYTE $0xc0                   // xorl	%r8d, %r8d

LBB0_17:
	LONG $0x207da2c4; WORD $0x0714             // vpmovsxbw	(%rdi,%r8), %ymm2
	LONG $0x207da2c4; WORD $0x075c; BYTE $0x10 // vpmovsxbw	16(%rdi,%r8), %ymm3
	LONG $0x207da2c4; WORD $0x0624             // vpmovsxbw	(%rsi,%r8), %ymm4
	LONG $0xd4f5edc5                           // vpmaddwd	%ymm4, %ymm2, %ymm2
	LONG $0xc0feedc5                           // vpaddd	%ymm0, %ymm2, %ymm0
	LONG $0x207da2c4; WORD $0x0654; BYTE $0x10 // vpmovsxbw	16(%rsi,%r8), %ymm2
	LONG $0xd2f5e5c5                           // vpmaddwd	%ymm2, %ymm3, %ymm2
	LONG $0xc9feedc5                           // vpaddd	%ymm1, %ymm2, %ymm1
	LONG $0x20c08349                           // addq	$32, %r8
	WORD $0x3949; BYTE $0xc8                   // cmpq	%rcx, %r8
	JB   LBB0_17
	LONG $0xc1fefdc5                           // vpaddd	%ymm1, %ymm0, %ymm0
	LONG $0x397de3c4; WORD $0x01c1             // vextracti128	$1, %ymm0, %xmm1
	LONG $0xc1fef9c5                           // vpaddd	%xmm1, %xmm0, %xmm0
	LONG $0x0279e2c4; BYTE $0xc0               // vphaddd	%xmm0, %xmm0, %xmm0
	LONG $0x0279e2c4; BYTE $0xc0               // vphaddd	%xmm0, %xmm0, %xmm0
	LONG $0x7e79c1c4; BYTE $0xc0               // vmovd	%xmm0, %r8d
	WORD $0x634d; BYTE $0xc0                   // movslq	%r8d, %r8
	WORD $0x014c; BYTE $0xc0                   // addq	%r8, %rax
	WORD $0x0148; BYTE $0xcf                   // addq	%rcx, %rdi
	WORD $0x0148; BYTE $0xce                   // addq	%rcx, %rsi
	WORD $0x2948; BYTE $0xca                   // subq	%rcx, %rdx
	LONG $0x1ffa8348                           // cmpq	$31, %rdx
	JG   LBB0_16

LBB0_1:
	WORD $0x8548; BYTE $0xd2 // testq	%rdx, %rdx
	JLE  LBB0_15
	LONG $0x03fa8348         // cmpq	$3, %rdx
	JA   LBB0_5
	WORD $0xc931             // xorl	%ecx, %ecx
	JMP  LBB0_4

LBB0_5:
	QUAD $0xfffffffffff0b849; WORD $0x7fff // movabsq	$9223372036854775792, %r8       # imm = 0x7FFFFFFFFFFFFFF0
	LONG $0x10fa8348                       // cmpq	$16, %rdx
	JAE  LBB0_7
	WORD $0xc931                           // xorl	%ecx, %ecx
	JMP  LBB0_11

LBB0_7:
	WORD $0x8948; BYTE $0xd1     // movq	%rdx, %rcx
	WORD $0x214c; BYTE $0xc1     // andq	%r8, %rcx
	LONG $0x6ef9e1c4; BYTE $0xc0 // vmovq	%rax, %xmm0
	LONG $0xc9eff1c5             // vpxor	%xmm1, %xmm1, %xmm1
	WORD $0xc031                 // xorl	%eax, %eax
	LONG $0xd2efe9c5             // vpxor	%xmm2, %xmm2, %xmm2
	LONG $0xdbefe1c5             // vpxor	%xmm3, %xmm3, %xmm3

LBB0_8:
	LONG $0x227de2c4; WORD $0x0724             // vpmovsxbq	(%rdi,%rax), %ymm4
	LONG $0x227de2c4; WORD $0x076c; BYTE $0x04 // vpmovsxbq	4(%rdi,%rax), %ymm5
	LONG $0x227de2c4; WORD $0x0774; BYTE $0x08 // vpmovsxbq	8(%rdi,%rax), %ymm6
	LONG $0x227de2c4; WORD $0x077c; BYTE $0x0c // vpmovsxbq	12(%rdi,%rax), %ymm7
	LONG $0x227d62c4; WORD $0x0604             // vpmovsxbq	(%rsi,%rax), %ymm8
	LONG $0x283de2c4; BYTE $0xe4               // vpmuldq	%ymm4, %ymm8, %ymm4
	LONG $0xc0d4ddc5                           // vpaddq	%ymm0, %ymm4, %ymm0
	LONG $0x227de2c4; WORD $0x0664; BYTE $0x04 // vpmovsxbq	4(%rsi,%rax), %ymm4
	LONG $0x285de2c4; BYTE $0xe5               // vpmuldq	%ymm5, %ymm4, %ymm4
	LONG $0xc9d4ddc5                           // vpaddq	%ymm1, %ymm4, %ymm1
	LONG $0x227de2c4; WORD $0x0664; BYTE $0x08 // vpmovsxbq	8(%rsi,%rax), %ymm4
	LONG $0x285de2c4; BYTE $0xe6               // vpmuldq	%ymm6, %ymm4, %ymm4
	LONG $0xd2d4ddc5                           // vpaddq	%ymm2, %ymm4, %ymm2
	LONG $0x227de2c4; WORD $0x0664; BYTE $0x0c // vpmovsxbq	12(%rsi,%rax), %ymm4
	LONG $0x285de2c4; BYTE $0xe7               // vpmuldq	%ymm7, %ymm4, %ymm4
	LONG $0xdbd4ddc5                           // vpaddq	%ymm3, %ymm4, %ymm3
	LONG $0x10c08348                           // addq	$16, %rax
	WORD $0x3948; BYTE $0xc1                   // cmpq	%rax, %rcx
	JNE  LBB0_8
	LONG $0xc0d4f5c5                           // vpaddq	%ymm0, %ymm1, %ymm0
	LONG $0xc0d4edc5                           // vpaddq	%ymm0, %ymm2, %ymm0
	LONG $0xc0d4e5c5                           // vpaddq	%ymm0, %ymm3, %ymm0
	LONG $0x397de3c4; WORD $0x01c1             // vextracti128	$1, %ymm0, %xmm1
	LONG $0xc1d4f9c5                           // vpaddq	%xmm1, %xmm0, %xmm0
	LONG $0xc870f9c5; BYTE $0xee               // vpshufd	$238, %xmm0, %xmm1              # xmm1 = xmm0[2,3,2,3]
	LONG $0xc1d4f9c5                           // vpaddq	%xmm1, %xmm0, %xmm0
	LONG $0x7ef9e1c4; BYTE $0xc0               // vmovq	%xmm0, %rax
	WORD $0x3948; BYTE $0xca                   // cmpq	%rcx, %rdx
	JE   LBB0_15
	WORD $0xc2f6; BYTE $0x0c                   // testb	$12, %dl
	JE   LBB0_4

LBB0_11:
	WORD $0x8949; BYTE $0xc9     // movq	%rcx, %r9
	LONG $0x0cc08349             // addq	$12, %r8
	WORD $0x894c; BYTE $0xc1     // movq	%r8, %rcx
	WORD $0x2148; BYTE $0xd1     // andq	%rdx, %rcx
	LONG $0x6ef9e1c4; BYTE $0xc0 // vmovq	%rax, %xmm0

LBB0_12:
	LONG $0x227da2c4; WORD $0x0f0c // vpmovsxbq	(%rdi,%r9), %ymm1
	LONG $0x227da2c4; WORD $0x0e14 // vpmovsxbq	(%rsi,%r9), %ymm2
	LONG $0x286de2c4; BYTE $0xc9   // vpmuldq	%ymm1, %ymm2, %ymm1
	LONG $0xc0d4f5c5               // vpaddq	%ymm0, %ymm1, %ymm0
	LONG $0x04c18349               // addq	$4, %r9
	WORD $0x394c; BYTE $0xc9       // cmpq	%r9, %rcx
	JNE  LBB0_12
	LONG $0x397de3c4; WORD $0x01c1 // vextracti128	$1, %ymm0, %xmm1
	LONG $0xc1d4f9c5               // vpaddq	%xmm1, %xmm0, %xmm0
	LONG $0xc870f9c5; BYTE $0xee   // vpshufd	$238, %xmm0, %xmm1              # xmm1 = xmm0[2,3,2,3]
	LONG $0xc1d4f9c5               // vpaddq	%xmm1, %xmm0, %xmm0
	LONG $0x7ef9e1c4; BYTE $0xc0   // vmovq	%xmm0, %rax
	JMP  LBB0_14

LBB0_4:
	LONG $0x04be0f4c; BYTE $0x0f // movsbq	(%rdi,%rcx), %r8
	LONG $0x0cbe0f4c; BYTE $0x0e // movsbq	(%rsi,%rcx), %r9
	LONG $0xc8af0f4d             // imulq	%r8, %r9
	WORD $0x014c; BYTE $0xc8     // addq	%r9, %rax
	WORD $0xff48; BYTE $0xc1     // incq	%rcx

LBB0_14:
	WORD $0x3948; BYTE $0xca // cmpq	%rcx, %rdx
	JNE  LBB0_4

LBB0_15:
	WORD $0x8948; BYTE $0xec // movq	%rbp, %rsp
	BYTE $0x5d               // popq	%rbp
	WORD $0xf8c5; BYTE $0x77 // vzeroupper
	MOVQ AX, result+24(FP)
	RET
