//go:build !noasm && amd64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8 (6ubuntu1)
// 	objdump 2.46
// flags: -mavx2 -mavx512f -mavx512bw -O3
// source: src/inner_product_matrix_int8_avx512.c

package mathutil

import "unsafe"

//go:noescape
func inner_product_int8_avx512(lhs, rhs unsafe.Pointer, size int64) (result int64)
