//go:build !noasm && arm64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8 (6ubuntu1)
// 	objdump 2.46
// flags: -O3
// source: src/inner_product_matrix_int8_neon.c

TEXT ·inner_product_int8_neon(SB), $0-32
	MOVD lhs+0(FP), R0
	MOVD rhs+8(FP), R1
	MOVD size+16(FP), R2
	WORD $0xf100405f     // cmp	x2, #16
	WORD $0xaa0003e8     // mov	x8, x0
	WORD $0xaa1f03e0     // mov	x0, xzr
	BLT  LBB0_5
	WORD $0x52a00029     // mov	w9, #65536

LBB0_2:
	WORD $0x6f00e400 // movi	v0.2d, #0000000000000000
	WORD $0x6f00e401 // movi	v1.2d, #0000000000000000
	WORD $0xf140405f // cmp	x2, #16, lsl #12
	WORD $0x9a89304a // csel	x10, x2, x9, lo
	WORD $0xaa1f03eb // mov	x11, xzr
	WORD $0x927c314a // and	x10, x10, #0x1fff0

LBB0_3:
	WORD $0x3ceb6902 // ldr	q2, [x8, x11]
	WORD $0x3ceb6823 // ldr	q3, [x1, x11]
	WORD $0x9100416b // add	x11, x11, #16
	WORD $0xeb0a017f // cmp	x11, x10
	WORD $0x0f08a444 // sshll	v4.8h, v2.8b, #0
	WORD $0x0f08a465 // sshll	v5.8h, v3.8b, #0
	WORD $0x4f08a442 // sshll2	v2.8h, v2.16b, #0
	WORD $0x4f08a463 // sshll2	v3.8h, v3.16b, #0
	WORD $0x0e658080 // smlal	v0.4s, v4.4h, v5.4h
	WORD $0x4e658081 // smlal2	v1.4s, v4.8h, v5.8h
	WORD $0x0e638040 // smlal	v0.4s, v2.4h, v3.4h
	WORD $0x4e638041 // smlal2	v1.4s, v2.8h, v3.8h
	BLO  LBB0_3
	WORD $0x4ea18400 // add	v0.4s, v0.4s, v1.4s
	WORD $0xcb0a0042 // sub	x2, x2, x10
	WORD $0x8b0a0108 // add	x8, x8, x10
	WORD $0xf1003c5f // cmp	x2, #15
	WORD $0x8b0a0021 // add	x1, x1, x10
	WORD $0x4ea02800 // saddlp	v0.2d, v0.4s
	WORD $0x4e183c0b // mov	x11, v0.d[1]
	WORD $0x9e66000c // fmov	x12, d0
	WORD $0x8b0c000c // add	x12, x0, x12
	WORD $0x8b0c0160 // add	x0, x11, x12
	BGT  LBB0_2

LBB0_5:
	WORD $0xf100045f // cmp	x2, #1
	BLT  LBB0_13
	BNE  LBB0_8
	WORD $0xaa1f03e9 // mov	x9, xzr
	B    LBB0_11

LBB0_8:
	WORD $0x927ff449 // and	x9, x2, #0x7ffffffffffffffe
	WORD $0xaa1f03ea // mov	x10, xzr
	WORD $0x9100050b // add	x11, x8, #1
	WORD $0x9100042c // add	x12, x1, #1
	WORD $0xaa0903ed // mov	x13, x9

LBB0_9:
	WORD $0x389ff16e // ldursb	x14, [x11, #-1]
	WORD $0x389ff18f // ldursb	x15, [x12, #-1]
	WORD $0xf10009ad // subs	x13, x13, #2
	WORD $0x39800170 // ldrsb	x16, [x11]
	WORD $0x39800191 // ldrsb	x17, [x12]
	WORD $0x9100096b // add	x11, x11, #2
	WORD $0x9b2e01e0 // smaddl	x0, w15, w14, x0
	WORD $0x9100098c // add	x12, x12, #2
	WORD $0x9b302a2a // smaddl	x10, w17, w16, x10
	BNE  LBB0_9
	WORD $0xeb09005f // cmp	x2, x9
	WORD $0x8b000140 // add	x0, x10, x0
	BEQ  LBB0_13

LBB0_11:
	WORD $0xcb09004a // sub	x10, x2, x9
	WORD $0x8b09002b // add	x11, x1, x9
	WORD $0x8b090108 // add	x8, x8, x9

LBB0_12:
	WORD $0x38801509 // ldrsb	x9, [x8], #1
	WORD $0xf100054a // subs	x10, x10, #1
	WORD $0x3880156c // ldrsb	x12, [x11], #1
	WORD $0x9b290180 // smaddl	x0, w12, w9, x0
	BNE  LBB0_12

LBB0_13:
	MOVD R0, result+24(FP)
	RET
