//go:build !noasm && amd64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8 (6ubuntu1)
// 	objdump 2.46
// flags: -msse2 -fno-jump-tables -O3
// source: src/inner_product_matrix_fp32_sse.c

package mathutil

import "unsafe"

//go:noescape
func inner_product_fp32_sse(lhs, rhs unsafe.Pointer, size int64) (result float32)
