//go:build !noasm && arm64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8 (6ubuntu1)
// 	objdump 2.46
// flags: -O3
// source: src/mips_euclidean_distance_matrix_fp32_neon.c

package mathutil

import "unsafe"

//go:noescape
func inner_product_and_squared_norm_fp32_neon(lhs, rhs unsafe.Pointer, size int64, dot, lhs_norm, rhs_norm unsafe.Pointer)
