//go:build !noasm && loong64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8 (6ubuntu1)
// 	objdump 2.46
// flags: -mlasx -O3
// source: src/mips_euclidean_distance_matrix_fp32_lasx.c

package mathutil

import "unsafe"

//go:noescape
func inner_product_and_squared_norm_fp32_lasx(lhs, rhs unsafe.Pointer, size int64, dot, lhs_norm, rhs_norm unsafe.Pointer)
