//go:build !noasm && riscv64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8 (6ubuntu1)
// 	objdump 2.46
// flags: -march=rv64imafdv -isystem /usr/lib/llvm-21/lib/clang/21/include -O3
// source: src/mips_euclidean_distance_matrix_fp32_rvv.c

TEXT ·inner_product_and_squared_norm_fp32_rvv(SB), $0-48
	MOV  lhs+0(FP), A0
	MOV  rhs+8(FP), A1
	MOV  size+16(FP), A2
	MOV  dot+24(FP), A3
	MOV  lhs_norm+32(FP), A4
	MOV  rhs_norm+40(FP), A5
	WORD $0x0d0072d7         // vsetvli	t0, zero, e32, m1, ta, ma
	WORD $0x02565833         // divu	a6, a2, t0
	WORD $0x025808b3         // mul	a7, a6, t0
	WORD $0x41160633         // sub	a2, a2, a7
	WORD $0x5e003457         // vmv.v.i	v8, 0
	BLEZ A6, LBB0_3
	WORD $0x00000893         // li	a7, 0
	WORD $0x00229293         // slli	t0, t0, 2
	WORD $0x9e8035d7         // vmv1r.v	v11, v8
	WORD $0x9e803557         // vmv1r.v	v10, v8
	WORD $0x9e8034d7         // vmv1r.v	v9, v8

LBB0_2:
	WORD $0x02056607    // vle32.v	v12, (a0)
	WORD $0x0205e687    // vle32.v	v13, (a1)
	WORD $0x00188893    // addi	a7, a7, 1
	WORD $0x00550533    // add	a0, a0, t0
	WORD $0xb2c695d7    // vfmacc.vv	v11, v13, v12
	WORD $0xb2c61557    // vfmacc.vv	v10, v12, v12
	WORD $0xb2d694d7    // vfmacc.vv	v9, v13, v13
	WORD $0x005585b3    // add	a1, a1, t0
	BLT  A7, A6, LBB0_2
	JMP  LBB0_4

LBB0_3:
	WORD $0x9e8034d7 // vmv1r.v	v9, v8
	WORD $0x9e803557 // vmv1r.v	v10, v8
	WORD $0x9e8035d7 // vmv1r.v	v11, v8

LBB0_4:
	WORD $0x0eb415d7 // vfredosum.vs	v11, v11, v8
	WORD $0x0ea41557 // vfredosum.vs	v10, v10, v8
	WORD $0x0e941457 // vfredosum.vs	v8, v9, v8
	WORD $0xcd00f057 // vsetivli	zero, 1, e32, m1, ta, ma
	WORD $0x0206e5a7 // vse32.v	v11, (a3)
	WORD $0x02076527 // vse32.v	v10, (a4)
	WORD $0x0207e427 // vse32.v	v8, (a5)
	BEQZ A2, LBB0_6
	WORD $0x0d067057 // vsetvli	zero, a2, e32, m1, ta, ma
	WORD $0x02056407 // vle32.v	v8, (a0)
	WORD $0x0205e487 // vle32.v	v9, (a1)
	WORD $0x0006a787 // flw	fa5, 0(a3)
	WORD $0x92849557 // vfmul.vv	v10, v8, v9
	WORD $0x5e0035d7 // vmv.v.i	v11, 0
	WORD $0x0ea59557 // vfredosum.vs	v10, v10, v11
	WORD $0x42a01757 // vfmv.f.s	fa4, v10
	WORD $0x00f777d3 // fadd.s	fa5, fa4, fa5
	WORD $0x00f6a027 // fsw	fa5, 0(a3)
	WORD $0x00072787 // flw	fa5, 0(a4)
	WORD $0x92841457 // vfmul.vv	v8, v8, v8
	WORD $0x0e859457 // vfredosum.vs	v8, v8, v11
	WORD $0x42801757 // vfmv.f.s	fa4, v8
	WORD $0x00f777d3 // fadd.s	fa5, fa4, fa5
	WORD $0x00f72027 // fsw	fa5, 0(a4)
	WORD $0x0007a787 // flw	fa5, 0(a5)
	WORD $0x92949457 // vfmul.vv	v8, v9, v9
	WORD $0x0e859457 // vfredosum.vs	v8, v8, v11
	WORD $0x42801757 // vfmv.f.s	fa4, v8
	WORD $0x00f777d3 // fadd.s	fa5, fa4, fa5
	WORD $0x00f7a027 // fsw	fa5, 0(a5)

LBB0_6:
	RET
