//go:build !noasm && amd64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8 (6ubuntu1)
// 	objdump 2.46
// flags: -msse2 -O3
// source: src/mips_euclidean_distance_matrix_fp32_sse.c

TEXT ·inner_product_and_squared_norm_fp32_sse(SB), $8-44
	MOVQ lhs+0(FP), DI
	MOVQ rhs+8(FP), SI
	MOVQ size+16(FP), DX
	MOVQ lhs_norm+24(FP), CX
	MOVQ rhs_norm+32(FP), R8
	BYTE $0x55               // pushq	%rbp
	WORD $0x8948; BYTE $0xe5 // movq	%rsp, %rbp
	LONG $0xf8e48348         // andq	$-8, %rsp
	LONG $0x97048d48         // leaq	(%rdi,%rdx,4), %rax
	LONG $0x02e2c148         // shlq	$2, %rdx
	LONG $0xe0e28348         // andq	$-32, %rdx
	LONG $0x170c8d4c         // leaq	(%rdi,%rdx), %r9
	WORD $0x8941; BYTE $0xf2 // movl	%esi, %r10d
	WORD $0x0941; BYTE $0xfa // orl	%edi, %r10d
	LONG $0x0fc2f641         // testb	$15, %r10b
	JE   LBB0_3
	WORD $0x8548; BYTE $0xd2 // testq	%rdx, %rdx
	JE   LBB0_2
	WORD $0x570f; BYTE $0xc0 // xorps	%xmm0, %xmm0
	WORD $0x570f; BYTE $0xd2 // xorps	%xmm2, %xmm2
	WORD $0x570f; BYTE $0xc9 // xorps	%xmm1, %xmm1

LBB0_11:
	WORD $0x100f; BYTE $0x1f // movups	(%rdi), %xmm3
	WORD $0x280f; BYTE $0xe3 // movaps	%xmm3, %xmm4
	WORD $0x590f; BYTE $0xdb // mulps	%xmm3, %xmm3
	WORD $0x580f; BYTE $0xda // addps	%xmm2, %xmm3
	LONG $0x1057100f         // movups	16(%rdi), %xmm2
	WORD $0x100f; BYTE $0x2e // movups	(%rsi), %xmm5
	WORD $0x590f; BYTE $0xe5 // mulps	%xmm5, %xmm4
	WORD $0x590f; BYTE $0xed // mulps	%xmm5, %xmm5
	WORD $0x580f; BYTE $0xe9 // addps	%xmm1, %xmm5
	LONG $0x104e100f         // movups	16(%rsi), %xmm1
	WORD $0x580f; BYTE $0xe0 // addps	%xmm0, %xmm4
	WORD $0x280f; BYTE $0xc2 // movaps	%xmm2, %xmm0
	WORD $0x590f; BYTE $0xc1 // mulps	%xmm1, %xmm0
	WORD $0x580f; BYTE $0xc4 // addps	%xmm4, %xmm0
	WORD $0x590f; BYTE $0xd2 // mulps	%xmm2, %xmm2
	WORD $0x580f; BYTE $0xd3 // addps	%xmm3, %xmm2
	WORD $0x590f; BYTE $0xc9 // mulps	%xmm1, %xmm1
	WORD $0x580f; BYTE $0xcd // addps	%xmm5, %xmm1
	LONG $0x20c78348         // addq	$32, %rdi
	LONG $0x20c68348         // addq	$32, %rsi
	WORD $0x394c; BYTE $0xcf // cmpq	%r9, %rdi
	JNE  LBB0_11
	WORD $0x894c; BYTE $0xcf // movq	%r9, %rdi
	LONG $0x10c18349         // addq	$16, %r9
	WORD $0x394c; BYTE $0xc8 // cmpq	%r9, %rax
	JAE  LBB0_14
	JMP  LBB0_16

LBB0_3:
	WORD $0x8548; BYTE $0xd2 // testq	%rdx, %rdx
	JE   LBB0_4
	WORD $0x570f; BYTE $0xc0 // xorps	%xmm0, %xmm0
	WORD $0x570f; BYTE $0xd2 // xorps	%xmm2, %xmm2
	WORD $0x570f; BYTE $0xc9 // xorps	%xmm1, %xmm1

LBB0_6:
	WORD $0x280f; BYTE $0x1f // movaps	(%rdi), %xmm3
	WORD $0x280f; BYTE $0xe3 // movaps	%xmm3, %xmm4
	WORD $0x590f; BYTE $0xdb // mulps	%xmm3, %xmm3
	WORD $0x580f; BYTE $0xda // addps	%xmm2, %xmm3
	LONG $0x1057280f         // movaps	16(%rdi), %xmm2
	WORD $0x280f; BYTE $0x2e // movaps	(%rsi), %xmm5
	WORD $0x590f; BYTE $0xe5 // mulps	%xmm5, %xmm4
	WORD $0x590f; BYTE $0xed // mulps	%xmm5, %xmm5
	WORD $0x580f; BYTE $0xe9 // addps	%xmm1, %xmm5
	LONG $0x104e280f         // movaps	16(%rsi), %xmm1
	WORD $0x580f; BYTE $0xe0 // addps	%xmm0, %xmm4
	WORD $0x280f; BYTE $0xc2 // movaps	%xmm2, %xmm0
	WORD $0x590f; BYTE $0xc1 // mulps	%xmm1, %xmm0
	WORD $0x580f; BYTE $0xc4 // addps	%xmm4, %xmm0
	WORD $0x590f; BYTE $0xd2 // mulps	%xmm2, %xmm2
	WORD $0x580f; BYTE $0xd3 // addps	%xmm3, %xmm2
	WORD $0x590f; BYTE $0xc9 // mulps	%xmm1, %xmm1
	WORD $0x580f; BYTE $0xcd // addps	%xmm5, %xmm1
	LONG $0x20c78348         // addq	$32, %rdi
	LONG $0x20c68348         // addq	$32, %rsi
	WORD $0x394c; BYTE $0xcf // cmpq	%r9, %rdi
	JNE  LBB0_6
	WORD $0x894c; BYTE $0xcf // movq	%r9, %rdi
	LONG $0x10c18349         // addq	$16, %r9
	WORD $0x394c; BYTE $0xc8 // cmpq	%r9, %rax
	JAE  LBB0_9
	JMP  LBB0_16

LBB0_2:
	WORD $0x570f; BYTE $0xc9 // xorps	%xmm1, %xmm1
	WORD $0x570f; BYTE $0xd2 // xorps	%xmm2, %xmm2
	WORD $0x570f; BYTE $0xc0 // xorps	%xmm0, %xmm0
	LONG $0x10c18349         // addq	$16, %r9
	WORD $0x394c; BYTE $0xc8 // cmpq	%r9, %rax
	JB   LBB0_16

LBB0_14:
	WORD $0x100f; BYTE $0x1f // movups	(%rdi), %xmm3
	WORD $0x100f; BYTE $0x26 // movups	(%rsi), %xmm4
	JMP  LBB0_15

LBB0_4:
	WORD $0x570f; BYTE $0xc9 // xorps	%xmm1, %xmm1
	WORD $0x570f; BYTE $0xd2 // xorps	%xmm2, %xmm2
	WORD $0x570f; BYTE $0xc0 // xorps	%xmm0, %xmm0
	LONG $0x10c18349         // addq	$16, %r9
	WORD $0x394c; BYTE $0xc8 // cmpq	%r9, %rax
	JB   LBB0_16

LBB0_9:
	WORD $0x280f; BYTE $0x1f // movaps	(%rdi), %xmm3
	WORD $0x280f; BYTE $0x26 // movaps	(%rsi), %xmm4

LBB0_15:
	WORD $0x280f; BYTE $0xeb // movaps	%xmm3, %xmm5
	WORD $0x590f; BYTE $0xec // mulps	%xmm4, %xmm5
	WORD $0x580f; BYTE $0xc5 // addps	%xmm5, %xmm0
	WORD $0x590f; BYTE $0xdb // mulps	%xmm3, %xmm3
	WORD $0x580f; BYTE $0xd3 // addps	%xmm3, %xmm2
	WORD $0x590f; BYTE $0xe4 // mulps	%xmm4, %xmm4
	WORD $0x580f; BYTE $0xcc // addps	%xmm4, %xmm1
	LONG $0x10c78348         // addq	$16, %rdi
	LONG $0x10c68348         // addq	$16, %rsi

LBB0_16:
	WORD $0x280f; BYTE $0xd8     // movaps	%xmm0, %xmm3
	LONG $0xd8150f66             // unpckhpd	%xmm0, %xmm3                    # xmm3 = xmm3[1],xmm0[1]
	WORD $0x580f; BYTE $0xd8     // addps	%xmm0, %xmm3
	WORD $0x280f; BYTE $0xc3     // movaps	%xmm3, %xmm0
	LONG $0x55c3c60f             // shufps	$85, %xmm3, %xmm0               # xmm0 = xmm0[1,1],xmm3[1,1]
	LONG $0xc3580ff3             // addss	%xmm3, %xmm0
	WORD $0x280f; BYTE $0xda     // movaps	%xmm2, %xmm3
	LONG $0xda150f66             // unpckhpd	%xmm2, %xmm3                    # xmm3 = xmm3[1],xmm2[1]
	WORD $0x580f; BYTE $0xda     // addps	%xmm2, %xmm3
	WORD $0x280f; BYTE $0xd1     // movaps	%xmm1, %xmm2
	LONG $0xd1150f66             // unpckhpd	%xmm1, %xmm2                    # xmm2 = xmm2[1],xmm1[1]
	WORD $0x580f; BYTE $0xd1     // addps	%xmm1, %xmm2
	WORD $0x280f; BYTE $0xcb     // movaps	%xmm3, %xmm1
	WORD $0x140f; BYTE $0xca     // unpcklps	%xmm2, %xmm1                    # xmm1 = xmm1[0],xmm2[0],xmm1[1],xmm2[1]
	LONG $0x11d3c60f             // shufps	$17, %xmm3, %xmm2               # xmm2 = xmm2[1,0],xmm3[1,0]
	LONG $0xe2d3c60f             // shufps	$226, %xmm3, %xmm2              # xmm2 = xmm2[2,0],xmm3[2,3]
	WORD $0x580f; BYTE $0xd1     // addps	%xmm1, %xmm2
	WORD $0x2948; BYTE $0xf8     // subq	%rdi, %rax
	LONG $0x02f8c148             // sarq	$2, %rax
	LONG $0x01f88348             // cmpq	$1, %rax
	JE   LBB0_21
	LONG $0x02f88348             // cmpq	$2, %rax
	JE   LBB0_20
	LONG $0x03f88348             // cmpq	$3, %rax
	JNE  LBB0_22
	LONG $0x4f100ff3; BYTE $0x08 // movss	8(%rdi), %xmm1                  # xmm1 = mem[0],zero,zero,zero
	LONG $0x5e100ff3; BYTE $0x08 // movss	8(%rsi), %xmm3                  # xmm3 = mem[0],zero,zero,zero
	WORD $0x280f; BYTE $0xe1     // movaps	%xmm1, %xmm4
	LONG $0xe3590ff3             // mulss	%xmm3, %xmm4
	LONG $0xc4580ff3             // addss	%xmm4, %xmm0
	WORD $0x140f; BYTE $0xcb     // unpcklps	%xmm3, %xmm1                    # xmm1 = xmm1[0],xmm3[0],xmm1[1],xmm3[1]
	WORD $0x590f; BYTE $0xc9     // mulps	%xmm1, %xmm1
	WORD $0x580f; BYTE $0xd1     // addps	%xmm1, %xmm2

LBB0_20:
	LONG $0x4f100ff3; BYTE $0x04 // movss	4(%rdi), %xmm1                  # xmm1 = mem[0],zero,zero,zero
	LONG $0x5e100ff3; BYTE $0x04 // movss	4(%rsi), %xmm3                  # xmm3 = mem[0],zero,zero,zero
	WORD $0x280f; BYTE $0xe1     // movaps	%xmm1, %xmm4
	LONG $0xe3590ff3             // mulss	%xmm3, %xmm4
	LONG $0xc4580ff3             // addss	%xmm4, %xmm0
	WORD $0x140f; BYTE $0xcb     // unpcklps	%xmm3, %xmm1                    # xmm1 = xmm1[0],xmm3[0],xmm1[1],xmm3[1]
	WORD $0x590f; BYTE $0xc9     // mulps	%xmm1, %xmm1
	WORD $0x580f; BYTE $0xd1     // addps	%xmm1, %xmm2

LBB0_21:
	LONG $0x0f100ff3         // movss	(%rdi), %xmm1                   # xmm1 = mem[0],zero,zero,zero
	LONG $0x1e100ff3         // movss	(%rsi), %xmm3                   # xmm3 = mem[0],zero,zero,zero
	WORD $0x280f; BYTE $0xe1 // movaps	%xmm1, %xmm4
	LONG $0xe3590ff3         // mulss	%xmm3, %xmm4
	LONG $0xc4580ff3         // addss	%xmm4, %xmm0
	WORD $0x140f; BYTE $0xcb // unpcklps	%xmm3, %xmm1                    # xmm1 = xmm1[0],xmm3[0],xmm1[1],xmm3[1]
	WORD $0x590f; BYTE $0xc9 // mulps	%xmm1, %xmm1
	WORD $0x580f; BYTE $0xd1 // addps	%xmm1, %xmm2

LBB0_22:
	LONG  $0x11110ff3             // movss	%xmm2, (%rcx)
	LONG  $0x55d2c60f             // shufps	$85, %xmm2, %xmm2               # xmm2 = xmm2[1,1,1,1]
	LONG  $0x110f41f3; BYTE $0x10 // movss	%xmm2, (%r8)
	WORD  $0x8948; BYTE $0xec     // movq	%rbp, %rsp
	BYTE  $0x5d                   // popq	%rbp
	MOVSS X0, result+40(FP)
	RET
